-- ============================================================
-- JLPT Vocabulary Seed: JLPT N3
-- Records: 821
-- Generated: 2026-07-04T05:53:39.994Z
-- ============================================================

USE JapaneseAI;
GO

SET NOCOUNT ON;

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'男性', N'だんせい', N'Nam tính', N'Nam giới', N'N3', NULL, NULL, 1, GETDATE()),
  (N'女性', N'じょせい', N'Nữ tính', N'Nữ giới', N'N3', NULL, NULL, 2, GETDATE()),
  (N'理想', N'りそう', N'Lý tưởng', N'Lý tưởng', N'N3', NULL, NULL, 3, GETDATE()),
  (N'高齢', N'こうれい', N'Cao linh', N'Cao tuổi', N'N3', NULL, NULL, 4, GETDATE()),
  (N'年上', N'としうえ', N'Niên thượng', N'Hơn tuổi', N'N3', NULL, NULL, 5, GETDATE()),
  (N'目上', N'めうえ', N'Mục thượng', N'Người trên', N'N3', NULL, NULL, 6, GETDATE()),
  (N'敬語', N'けいご', N'Kính ngữ', N'Kính ngữ', N'N3', NULL, NULL, 7, GETDATE()),
  (N'先輩', N'せんぱい', N'Tiền bối', N'Tiền bối', N'N3', NULL, NULL, 8, GETDATE()),
  (N'後輩', N'こうはい', N'Hậu bối', N'Hậu bối', N'N3', NULL, NULL, 9, GETDATE()),
  (N'職場', N'しょくば', N'Chức trường', N'Nơi làm việc', N'N3', NULL, NULL, 10, GETDATE()),
  (N'上司', N'じょうし', N'Thượng ty', N'Cấp trên', N'N3', NULL, NULL, 11, GETDATE()),
  (N'決定', N'けってい', N'Quyết định', N'Quyết định', N'N3', NULL, NULL, 12, GETDATE()),
  (N'相手', N'あいて', N'Tương thủ', N'Đối tác', N'N3', NULL, NULL, 13, GETDATE()),
  (N'就職', N'しゅうしょく', N'Tựu chức', N'Có việc làm', N'N3', NULL, NULL, 14, GETDATE()),
  (N'友人', N'ゆうじん', N'Hữu nhân', N'Bạn thân', N'N3', NULL, NULL, 15, GETDATE()),
  (N'時代', N'じだい', N'Thời đại', N'Thời đại', N'N3', NULL, NULL, 16, GETDATE()),
  (N'仲', N'なか', N'Trọng', N'Quan hệ', N'N3', NULL, NULL, 17, GETDATE()),
  (N'生年月日', N'せいねんがっぴ', N'Sinh Niên Nguyệt Nhật', N'Ngày tháng năm sinh', N'N3', NULL, NULL, 18, GETDATE()),
  (N'誕生', N'たんじょう', N'Đản sinh', N'Ra đời', N'N3', NULL, NULL, 19, GETDATE()),
  (N'出身', N'しゅっしん', N'Xuất thân', N'Xuất thân', N'N3', NULL, NULL, 20, GETDATE()),
  (N'命', N'いのち', N'Mệnh', N'Số mệnh, cuộc sống', N'N3', NULL, NULL, 21, GETDATE()),
  (N'計画', N'けいかく', N'Kế hoạch', N'Kế hoạch', N'N3', NULL, NULL, 22, GETDATE()),
  (N'故郷', N'こきょう', N'Cố hương', N'Quê hương', N'N3', NULL, NULL, 23, GETDATE()),
  (N'事業', N'じぎょう', N'Sự nghiệp', N'Sự nghiệp', N'N3', NULL, NULL, 24, GETDATE()),
  (N'喜ぶ', N'よろこぶ', N'Hỉ', N'Hạnh phúc', N'N3', NULL, NULL, 25, GETDATE()),
  (N'記入する', N'きにゅうする', N'Kí nhập', N'Nhập vào', N'N3', NULL, NULL, 26, GETDATE()),
  (N'立てる', N'たてる', N'Lập', N'Lập ( kế hoạch)', N'N3', NULL, NULL, 27, GETDATE()),
  (N'頼む', N'たのむ', N'Lại', N'Nhờ vả', N'N3', NULL, NULL, 28, GETDATE()),
  (N'成長する', N'せいちょうする', N'Thành trường', N'Trưởng thành', N'N3', NULL, NULL, 29, GETDATE()),
  (N'成人する', N'せいじんする', N'Thành nhân', N'Người lớn', N'N3', NULL, NULL, 30, GETDATE()),
  (N'合格する', N'ごうかくする', N'Hợp cách', N'Đỗ (kỳ thi)', N'N3', NULL, NULL, 31, GETDATE()),
  (N'進学する', N'しんがくする', N'Tiến học', N'Đi học', N'N3', NULL, NULL, 32, GETDATE()),
  (N'退学する', N'たいがくする', N'Thoái học', N'Bỏ học', N'N3', NULL, NULL, 33, GETDATE()),
  (N'就職する', N'しゅうしょくする', N'Tựu chức', N'Có việc làm', N'N3', NULL, NULL, 34, GETDATE()),
  (N'介護', N'かいご', N'Giới hộ', N'Chăm sóc', N'N3', NULL, NULL, 35, GETDATE()),
  (N'決める', N'きめる', N'Quyết', N'Quyết định', N'N3', NULL, NULL, 36, GETDATE()),
  (N'退職する', N'たいしょくする', N'Thoái chức', N'Nghỉ việc', N'N3', NULL, NULL, 37, GETDATE()),
  (N'倒産する', N'とうさんする', N'Đảo sản', N'Phá sản', N'N3', NULL, NULL, 38, GETDATE()),
  (N'失業する', N'しつぎょうする', N'Thất nghiệp', N'Thất nghiệp', N'N3', NULL, NULL, 39, GETDATE()),
  (N'残業する', N'ざんぎょうする', N'Tàn nghiệp', N'Làm thêm giờ', N'N3', NULL, NULL, 40, GETDATE()),
  (N'疲れる', N'つかれる', N'Bì', N'Mệt', N'N3', NULL, NULL, 41, GETDATE()),
  (N'生活する', N'せいかつする', N'Sinh hoạt', N'Cuộc sống', N'N3', NULL, NULL, 42, GETDATE()),
  (N'通勤する', N'つうきんする', N'Thông cần', N'Đi làm', N'N3', NULL, NULL, 43, GETDATE()),
  (N'学歴', N'がくれき', N'Học lịch', N'Bằng cấp', N'N3', NULL, NULL, 44, GETDATE()),
  (N'実力', N'じつりょく', N'Thực lực', N'Thực lực', N'N3', NULL, NULL, 45, GETDATE()),
  (N'給料', N'きゅうりょう', N'Cấp liệu', N'Lương', N'N3', NULL, NULL, 46, GETDATE()),
  (N'面接する', N'めんせつする', N'Diện tiếp', N'Phỏng vấn', N'N3', NULL, NULL, 47, GETDATE()),
  (N'休憩する', N'きゅうけいする', N'Hưu khế', N'Nghỉ giải lao', N'N3', NULL, NULL, 48, GETDATE()),
  (N'観光する', N'かんこうする', N'Quan quang', N'Thăm quan', N'N3', NULL, NULL, 49, GETDATE()),
  (N'帰国する', N'きこくする', N'Quy quốc', N'Về nước', N'N3', NULL, NULL, 50, GETDATE()),
  (N'帰省する', N'きせいする', N'Quy tỉnh', N'Về quê', N'N3', NULL, NULL, 51, GETDATE()),
  (N'帰宅する', N'きたくする', N'Quy trạch', N'Về nhà', N'N3', NULL, NULL, 52, GETDATE()),
  (N'参加する', N'さんかする', N'Tham gia', N'Tham gia', N'N3', NULL, NULL, 53, GETDATE()),
  (N'活動', N'かつどう', N'Hoạt động', N'Hoạt động', N'N3', NULL, NULL, 54, GETDATE()),
  (N'出席する', N'しゅっせきする', N'Xuất tịch', N'Tham gia', N'N3', NULL, NULL, 55, GETDATE()),
  (N'欠席する', N'けっせきする', N'Khuyết tịch', N'Không tham gia', N'N3', NULL, NULL, 56, GETDATE()),
  (N'寝坊', N'ねぼう', N'Tẩm phường', N'Ngủ quên', N'N3', NULL, NULL, 57, GETDATE()),
  (N'遅刻する', N'ちこくする', N'Trì khắc', N'Đến muộn', N'N3', NULL, NULL, 58, GETDATE()),
  (N'化粧する', N'けしょうする', N'Hóa trang', N'Trang điểm', N'N3', NULL, NULL, 59, GETDATE()),
  (N'苦手', N'にがて', N'Khổ thủ', N'Kém', N'N3', NULL, NULL, 60, GETDATE()),
  (N'計算する', N'けいさんする', N'Kế toán', N'Tính toán', N'N3', NULL, NULL, 61, GETDATE()),
  (N'計画する', N'けいかくする', N'Kế hoạch', N'Kế hoạch', N'N3', NULL, NULL, 62, GETDATE()),
  (N'成功する', N'せいこうする', N'Thành công', N'Thành công', N'N3', NULL, NULL, 63, GETDATE()),
  (N'失敗する', N'しっぱいする', N'Thất bại', N'Thất bại', N'N3', NULL, NULL, 64, GETDATE()),
  (N'実験', N'じっけん', N'Thực nghiệm', N'Thực nghiệm', N'N3', NULL, NULL, 65, GETDATE()),
  (N'準備する', N'じゅんびする', N'Chuẩn bị', N'Chuẩn bị', N'N3', NULL, NULL, 66, GETDATE()),
  (N'整理する', N'せいりする', N'Chỉnh lý', N'Sắp xếp', N'N3', NULL, NULL, 67, GETDATE()),
  (N'書類', N'しょるい', N'Thư loại', N'Giấy tờ', N'N3', NULL, NULL, 68, GETDATE()),
  (N'品', N'しな', N'Phẩm', N'Hàng hóa', N'N3', NULL, NULL, 69, GETDATE()),
  (N'届く', N'とどく', N'Giới', N'Đến nơi', N'N3', NULL, NULL, 70, GETDATE()),
  (N'注文する', N'ちゅうもんする', N'Chú văn', N'Đặt hàng', N'N3', NULL, NULL, 71, GETDATE()),
  (N'貯金する', N'ちょきんする', N'Trữ kim', N'Tiết kiệm', N'N3', NULL, NULL, 72, GETDATE()),
  (N'増える', N'ふえる', N'Tăng', N'Tăng', N'N3', NULL, NULL, 73, GETDATE()),
  (N'徹夜する', N'てつやする', N'Triệt dạ', N'Thức xuyên đêm', N'N3', NULL, NULL, 74, GETDATE()),
  (N'身長', N'しんちょう', N'Thân trường', N'Chiều cao', N'N3', NULL, NULL, 75, GETDATE()),
  (N'体重', N'たいじゅう', N'Thể trọng', N'Cân nặng', N'N3', NULL, NULL, 76, GETDATE()),
  (N'怪我', N'けが', N'Quái ngã', N'Bị thương', N'N3', NULL, NULL, 77, GETDATE()),
  (N'趣味', N'しゅみ', N'Thú vị', N'Sở thích', N'N3', NULL, NULL, 78, GETDATE()),
  (N'読書', N'どくしょ', N'Độc thư', N'Đọc sách', N'N3', NULL, NULL, 79, GETDATE()),
  (N'興味', N'きょうみ', N'Hưng vị', N'Hứng thú', N'N3', NULL, NULL, 80, GETDATE()),
  (N'歴史', N'れきし', N'Lịch sử', N'Lịch sử', N'N3', NULL, NULL, 81, GETDATE()),
  (N'思い出', N'おもいで', N'Tư xuất', N'Hồi ức', N'N3', NULL, NULL, 82, GETDATE()),
  (N'冗談', N'じょうだん', N'Nhũng đàm', N'Đùa cợt', N'N3', NULL, NULL, 83, GETDATE()),
  (N'本気', N'ほんき', N'Bản khí', N'Sự thật', N'N3', NULL, NULL, 84, GETDATE()),
  (N'目的', N'もくてき', N'Mục đích', N'Mục đích', N'N3', NULL, NULL, 85, GETDATE()),
  (N'約束する', N'やくそくする', N'Ước thúc', N'Lời hứa', N'N3', NULL, NULL, 86, GETDATE()),
  (N'おしゃべりする', N'おしゃべりする', NULL, N'Nói chuyện', N'N3', NULL, NULL, 87, GETDATE()),
  (N'怒る', N'おこる', N'Nộ', N'Tức giận', N'N3', NULL, NULL, 88, GETDATE()),
  (N'遠慮する', N'えんりょ', N'Viễn lự', N'Ngại ngần', N'N3', NULL, NULL, 89, GETDATE()),
  (N'我慢する', N'がまんする', N'Ngã mạn', N'Chịu đựng', N'N3', NULL, NULL, 90, GETDATE()),
  (N'迷惑する', N'めいわくする', N'Mê hoặc', N'Làm phiền', N'N3', NULL, NULL, 91, GETDATE()),
  (N'捨てる', N'すてる', N'Vứt', N'Vứt', N'N3', NULL, NULL, 92, GETDATE()),
  (N'希望', N'きぼう', N'Hi vọng', N'Hi vọng', N'N3', NULL, NULL, 93, GETDATE()),
  (N'夢', N'ゆめ', N'Mộng', N'Giấc mơ, ước mơ', N'N3', NULL, NULL, 94, GETDATE()),
  (N'怖い', N'こわい', N'Bố', N'Đáng sợ', N'N3', NULL, NULL, 95, GETDATE()),
  (N'賛成する', N'さんせいする', N'Tán thành', N'Tán thành', N'N3', NULL, NULL, 96, GETDATE()),
  (N'挙げる', N'あげる', N'Cử', N'Giơ tay', N'N3', NULL, NULL, 97, GETDATE()),
  (N'反対する', N'はんたいする', N'Phản đối', N'Phản đối', N'N3', NULL, NULL, 98, GETDATE()),
  (N'想像する', N'そうぞう', N'Tưởng tượng', N'Tưởng tượng', N'N3', NULL, NULL, 99, GETDATE()),
  (N'現実', N'げんじつ', N'Hiện thực', N'Hiện thực, sự thật', N'N3', NULL, NULL, 100, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'努力する', N'どりょくする', N'Nỗ lực', N'Nỗ lực', N'N3', NULL, NULL, 101, GETDATE()),
  (N'太陽', N'たいよう', N'Thái dương', N'Mặt trời', N'N3', NULL, NULL, 102, GETDATE()),
  (N'昇る', N'のぼる', N'Thăng', N'Lên cao, tăng lên', N'N3', NULL, NULL, 103, GETDATE()),
  (N'地球', N'ちきゅう', N'Địa cầu', N'Trái đất', N'N3', NULL, NULL, 104, GETDATE()),
  (N'環境', N'かんきょう', N'Hoàn cảnh', N'Môi trường', N'N3', NULL, NULL, 105, GETDATE()),
  (N'温度', N'おんど', N'Ôn độ', N'Nhiệt độ', N'N3', NULL, NULL, 106, GETDATE()),
  (N'湿度', N'しつど', N'Thấp độ', N'Độ ẩm', N'N3', NULL, NULL, 107, GETDATE()),
  (N'湿気', N'しっけ', N'Thấp khí', N'Hơi ẩm', N'N3', NULL, NULL, 108, GETDATE()),
  (N'梅雨', N'つゆ', N'Mai vũ', N'Mùa mưa', N'N3', NULL, NULL, 109, GETDATE()),
  (N'かび', N'かび', NULL, N'Nấm mốc', N'N3', NULL, NULL, 110, GETDATE()),
  (N'時期', N'じき', N'Thời kì', N'Thời kì', N'N3', NULL, NULL, 111, GETDATE()),
  (N'暖房', N'だんぼう', N'Noãn phòng', N'Thiết bị làm ấm', N'N3', NULL, NULL, 112, GETDATE()),
  (N'皮', N'かわ', N'Bì', N'Vỏ, da', N'N3', NULL, NULL, 113, GETDATE()),
  (N'画面', N'がめん', N'Họa diện', N'Màn hình', N'N3', NULL, NULL, 114, GETDATE()),
  (N'番組', N'ばんぐみ', N'Phiên tổ', N'Chương trình', N'N3', NULL, NULL, 115, GETDATE()),
  (N'記事', N'きじ', N'Kí sự', N'Kí sự', N'N3', NULL, NULL, 116, GETDATE()),
  (N'近所', N'きんじょ', N'Cận sở', N'Hàng xóm, xung quanh', N'N3', NULL, NULL, 117, GETDATE()),
  (N'盗む', N'ぬすむ', N'Đạo', N'Ăn trộm', N'N3', NULL, NULL, 118, GETDATE()),
  (N'警官', N'けいかん', N'Cảnh quan', N'Cảnh sát', N'N3', NULL, NULL, 119, GETDATE()),
  (N'犯人', N'はんにん', N'Phạm nhân', N'Tội phạm', N'N3', NULL, NULL, 120, GETDATE()),
  (N'小銭', N'こぜに', N'Tiểu tiền', N'Tiền lẻ', N'N3', NULL, NULL, 121, GETDATE()),
  (N'お祝う', N'おいわう', N'Chúc', N'Chúc mừng', N'N3', NULL, NULL, 122, GETDATE()),
  (N'ごちそう', N'ごちそう', NULL, N'Chiêu đãi', N'N3', NULL, NULL, 123, GETDATE()),
  (N'作者', N'さくしゃ', N'Tác giả', N'Tác giả', N'N3', NULL, NULL, 124, GETDATE()),
  (N'作品', N'さくひん', N'Tác phẩm', N'Tác phẩm', N'N3', NULL, NULL, 125, GETDATE()),
  (N'展示', N'てんじ', N'Triển thị', N'Trưng bày', N'N3', NULL, NULL, 126, GETDATE()),
  (N'制服', N'せいふく', N'Chế phục', N'Đồng phục', N'N3', NULL, NULL, 127, GETDATE()),
  (N'食器', N'しょっき', N'Thực khí', N'Bát đĩa', N'N3', NULL, NULL, 128, GETDATE()),
  (N'洗剤', N'せんざい', N'Tẩy tễ', N'Chất tẩy rửa', N'N3', NULL, NULL, 129, GETDATE()),
  (N'底', N'そこ', N'Để', N'Đáy', N'N3', NULL, NULL, 130, GETDATE()),
  (N'進む', N'すすむ', N'Tiến', N'Tiến lên/triển/bộ', N'N3', NULL, NULL, 131, GETDATE()),
  (N'開発', N'かいはつ', N'Khai phát', N'Phát triển', N'N3', NULL, NULL, 132, GETDATE()),
  (N'都市', N'とし', N'Đô thị', N'Thành phố', N'N3', NULL, NULL, 133, GETDATE()),
  (N'寺', N'てら', N'Tự', N'Chùa', N'N3', NULL, NULL, 134, GETDATE()),
  (N'道路', N'どうろ', N'Đạo lộ', N'Con đường', N'N3', NULL, NULL, 135, GETDATE()),
  (N'坂', N'さか', N'Phản', N'Dốc', N'N3', NULL, NULL, 136, GETDATE()),
  (N'煙', N'けむり', N'Yên', N'Khói', N'N3', NULL, NULL, 137, GETDATE()),
  (N'逃げる', N'にげる', N'Đào', N'Bỏ chạy, tẩu thoát', N'N3', NULL, NULL, 138, GETDATE()),
  (N'火事', N'かじ', N'Hỏa sự', N'Hỏa hoạn', N'N3', NULL, NULL, 139, GETDATE()),
  (N'灰', N'はい', N'Hôi', N'Tro tàn', N'N3', NULL, NULL, 140, GETDATE()),
  (N'判', N'はん', N'Phán', N'Con dấu', N'N3', NULL, NULL, 141, GETDATE()),
  (N'名刺', N'めいし', N'Danh thích', N'Danh thiếp', N'N3', NULL, NULL, 142, GETDATE()),
  (N'交換', N'こうかん', N'Giao hoán', N'Trao đổi', N'N3', NULL, NULL, 143, GETDATE()),
  (N'免許', N'めんきょ', N'Miễn hứa', N'Giấy phép', N'N3', NULL, NULL, 144, GETDATE()),
  (N'必要（な）', N'ひつよう', N'Tất yếu', N'Cần thiết', N'N3', NULL, NULL, 145, GETDATE()),
  (N'調理師', N'ちょうりし', N'Điều lý sư', N'Đầu bếp', N'N3', NULL, NULL, 146, GETDATE()),
  (N'多く', N'おおく', N'Đa', N'Nhiều', N'N3', NULL, NULL, 147, GETDATE()),
  (N'前半', N'ぜんはん', N'Tiền bán', N'Phần đầu', N'N3', NULL, NULL, 148, GETDATE()),
  (N'後半', N'こうはん', N'Hậu bán', N'Phần sau', N'N3', NULL, NULL, 149, GETDATE()),
  (N'退屈', N'たいくつ', N'Thoái khuất', N'Buồn tẻ, chán ngắt', N'N3', NULL, NULL, 150, GETDATE()),
  (N'最高', N'さいこう', N'Tối cao', N'Cao nhất', N'N3', NULL, NULL, 151, GETDATE()),
  (N'最低', N'さいてい', N'Tối đê', N'Thấp nhất', N'N3', NULL, NULL, 152, GETDATE()),
  (N'最初', N'さいしょ', N'Tối sơ', N'Đầu tiên', N'N3', NULL, NULL, 153, GETDATE()),
  (N'最後', N'さいご', N'Tối hậu', N'Cuối cùng', N'N3', NULL, NULL, 154, GETDATE()),
  (N'花束', N'はなたば', N'Hoa thúc', N'Bó hoa', N'N3', NULL, NULL, 155, GETDATE()),
  (N'自動', N'じどう', N'Tự động', N'Tự động', N'N3', NULL, NULL, 156, GETDATE()),
  (N'種類', N'しゅるい', N'Chủng loại', N'Chủng loại', N'N3', NULL, NULL, 157, GETDATE()),
  (N'性格', N'せいかく', N'Tính cách', N'Tính cách', N'N3', NULL, NULL, 158, GETDATE()),
  (N'性質', N'せいしつ', N'Tính chất', N'Tính chất', N'N3', NULL, NULL, 159, GETDATE()),
  (N'布', N'ぬの', N'Bố', N'Vải', N'N3', NULL, NULL, 160, GETDATE()),
  (N'順番', N'じゅんばん', N'Thuận phiên', N'Thứ tự', N'N3', NULL, NULL, 161, GETDATE()),
  (N'発表', N'はっぴょう', N'Phát biểu', N'Phát biểu', N'N3', NULL, NULL, 162, GETDATE()),
  (N'商品', N'しょうひん', N'Thương phẩm', N'Phần thưởng', N'N3', NULL, NULL, 163, GETDATE()),
  (N'番', N'ばん', N'Phiên', N'Lượt', N'N3', NULL, NULL, 164, GETDATE()),
  (N'方法', N'ほうほう', N'Phương pháp', N'Phương pháp', N'N3', NULL, NULL, 165, GETDATE()),
  (N'検査', N'ちょうさ', N'Kiểm tra', N'Kiểm tra', N'N3', NULL, NULL, 166, GETDATE()),
  (N'完成', N'かんせい', N'Hoàn thành', N'Hoàn thành', N'N3', NULL, NULL, 167, GETDATE()),
  (N'製品', N'せいひん', N'Chế phẩm', N'Sản phẩm, thành phẩm', N'N3', NULL, NULL, 168, GETDATE()),
  (N'値上がり', N'ねあがり', N'Trị thượng', N'Tăng giá', N'N3', NULL, NULL, 169, GETDATE()),
  (N'生', N'なま', N'Sinh', N'Tươi, mới (chưa chế biến)', N'N3', NULL, NULL, 170, GETDATE()),
  (N'渇く', N'かわく', N'Khát', N'Khát', N'N3', NULL, NULL, 171, GETDATE()),
  (N'嗅ぐ', N'かぐ', N'Khứu', N'Ngửi', N'N3', NULL, NULL, 172, GETDATE()),
  (N'叩く', N'たたく', N'Khấu', N'Vỗ, đánh, gõ', N'N3', NULL, NULL, 173, GETDATE()),
  (N'お尻', N'おしり', N'Khào', N'Mông', N'N3', NULL, NULL, 174, GETDATE()),
  (N'殴る', N'なぐる', N'Ẩu', N'Đánh', N'N3', NULL, NULL, 175, GETDATE()),
  (N'蹴る', N'ける', N'Xúc', N'Đá', N'N3', NULL, NULL, 176, GETDATE()),
  (N'抱く', N'だく', N'Bão', N'Ôm', N'N3', NULL, NULL, 177, GETDATE()),
  (N'両手', N'りょうて', N'Lưỡng thủ', N'Hai tay', N'N3', NULL, NULL, 178, GETDATE()),
  (N'台風', N'たいふう', N'Đài phong', N'Bão', N'N3', NULL, NULL, 179, GETDATE()),
  (N'倒れる', N'たおれる', N'Đảo', N'Bị gãy/đổ/rơi', N'N3', NULL, NULL, 180, GETDATE()),
  (N'倒す', N'たおす', N'Đảo', N'Chặt đổ, quật ngã', N'N3', NULL, NULL, 181, GETDATE()),
  (N'起きる', N'おきる', N'Khởi', N'Thức dậy', N'N3', NULL, NULL, 182, GETDATE()),
  (N'起こす', N'おこす', N'Khởi', N'Đánh thức', N'N3', NULL, NULL, 183, GETDATE()),
  (N'尋ねる', N'たずねる', N'Tầm', N'Hỏi, thăm hỏi', N'N3', NULL, NULL, 184, GETDATE()),
  (N'呼ぶ', N'よぶ', N'Hô', N'Gọi', N'N3', NULL, NULL, 185, GETDATE()),
  (N'叫ぶ', N'さけぶ', N'Khiếu', N'Gào, hét, rú lên', N'N3', NULL, NULL, 186, GETDATE()),
  (N'黙る', N'だまる', N'Mặc', N'Im lặng', N'N3', NULL, NULL, 187, GETDATE()),
  (N'飼う', N'かう', N'Tự', N'Nuôi', N'N3', NULL, NULL, 188, GETDATE()),
  (N'数える', N'かぞえる', N'Số', N'Đếm', N'N3', NULL, NULL, 189, GETDATE()),
  (N'数', N'かず', N'Số', N'Số', N'N3', NULL, NULL, 190, GETDATE()),
  (N'乾く', N'かわく', N'Can', N'Khô', N'N3', NULL, NULL, 191, GETDATE()),
  (N'乾かす', N'かわかす', N'Can', N'Làm khô', N'N3', NULL, NULL, 192, GETDATE()),
  (N'濡れる', N'ぬれる', N'Nhu', N'Ướt', N'N3', NULL, NULL, 193, GETDATE()),
  (N'畳む', N'たたむ', N'Điệp', N'Gấp, gập, xếp', N'N3', NULL, NULL, 194, GETDATE()),
  (N'畳', N'じょう', N'Điệp', N'Cái chiếu', N'N3', NULL, NULL, 195, GETDATE()),
  (N'誘う', N'さそう', N'Dụ', N'Mời , rủ', N'N3', NULL, NULL, 196, GETDATE()),
  (N'奢る', N'おごる', N'Xa', N'Chiêu đãi, khao', N'N3', NULL, NULL, 197, GETDATE()),
  (N'預かる', N'あずかる', N'Dự', N'Chăm sóc, trông nom', N'N3', NULL, NULL, 198, GETDATE()),
  (N'預ける', N'あずける', N'Dự', N'Giao cho, gửi', N'N3', NULL, NULL, 199, GETDATE()),
  (N'決まる', N'きまる', N'Quyết', N'Bị quyết định', N'N3', NULL, NULL, 200, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'決める', N'きめる', N'Quyết', N'Quyết định', N'N3', NULL, NULL, 201, GETDATE()),
  (N'が　写る', N'うつる', N'Tả', N'Được chụp', N'N3', NULL, NULL, 202, GETDATE()),
  (N'写す', N'うつす', N'Tả', N'Chụp lại', N'N3', NULL, NULL, 203, GETDATE()),
  (N'思い出す', N'おもいだす', N'Tư xuất', N'Nhớ nhung', N'N3', NULL, NULL, 204, GETDATE()),
  (N'教わる', N'おそわる', N'Giáo', N'Được dạy', N'N3', NULL, NULL, 205, GETDATE()),
  (N'申し込む', N'もうしこむ', N'Thân nhập', N'Đăng kí', N'N3', NULL, NULL, 206, GETDATE()),
  (N'断る', N'ことわる', N'Đoạn', N'Từ chối', N'N3', NULL, NULL, 207, GETDATE()),
  (N'指輪', N'ゆびわ', N'Chỉ luân', N'Nhẫn', N'N3', NULL, NULL, 208, GETDATE()),
  (N'見つかる', N'みつかる', N'Kiến', N'Được tìm thấy', N'N3', NULL, NULL, 209, GETDATE()),
  (N'見つける', N'みつける', N'Kiến', N'Tìm thấy', N'N3', NULL, NULL, 210, GETDATE()),
  (N'捕まる', N'つかまる', N'Bộ', N'Bị bắt, bị tóm', N'N3', NULL, NULL, 211, GETDATE()),
  (N'捕まえる', N'つかまえる', N'Bộ', N'Đi bắt', N'N3', NULL, NULL, 212, GETDATE()),
  (N'乗る', N'のる', N'Thừa', N'Lên', N'N3', NULL, NULL, 213, GETDATE()),
  (N'乗せる', N'のせる', N'Thừa', N'Cho lên, xếp lên', N'N3', NULL, NULL, 214, GETDATE()),
  (N'下りる/降りる', N'おりる', N'Hạ/ Giáng', N'Xuống', N'N3', NULL, NULL, 215, GETDATE()),
  (N'下ろす、降ろす', N'おろす', N'Hạ/ Giáng', N'Cho xuống', N'N3', NULL, NULL, 216, GETDATE()),
  (N'直る', N'なおる', N'Trực', N'Được sửa, sửa chữa', N'N3', NULL, NULL, 217, GETDATE()),
  (N'直す', N'なおす', N'Trực', N'Sửa xong', N'N3', NULL, NULL, 218, GETDATE()),
  (N'治る', N'なおる', N'Trị', N'Khôi phục', N'N3', NULL, NULL, 219, GETDATE()),
  (N'治す', N'なおす', N'Trị', N'Chữa trị', N'N3', NULL, NULL, 220, GETDATE()),
  (N'亡くなる', N'なくなる', N'Vong', N'Chết', N'N3', NULL, NULL, 221, GETDATE()),
  (N'亡くす', N'なくす', N'Vong', N'Mất', N'N3', NULL, NULL, 222, GETDATE()),
  (N'父親', N'ちちおや', N'Phụ thân', N'Cha mẹ', N'N3', NULL, NULL, 223, GETDATE()),
  (N'生まれる', N'うまれる', N'Sinh', N'Được sinh ra', N'N3', NULL, NULL, 224, GETDATE()),
  (N'産む', N'うむ', N'Sản', N'Sinh, đẻ', N'N3', NULL, NULL, 225, GETDATE()),
  (N'先日', N'せんじつ', N'Tiên nhật', N'Mấy ngày trước', N'N3', NULL, NULL, 226, GETDATE()),
  (N'出会う', N'であう', N'Xuất hội', N'Gặp gỡ ngẫu nhiên', N'N3', NULL, NULL, 227, GETDATE()),
  (N'訪ねる', N'たずねる', N'Phỏng', N'Thăm, ghé thăm', N'N3', NULL, NULL, 228, GETDATE()),
  (N'付き合う', N'つきあう', N'Phó hợp', N'Hẹn hò', N'N3', NULL, NULL, 229, GETDATE()),
  (N'効く', N'きく', N'Hiệu', N'Hiệu quả', N'N3', NULL, NULL, 230, GETDATE()),
  (N'頭痛', N'ずつう', N'Đầu thống', N'Đau đầu', N'N3', NULL, NULL, 231, GETDATE()),
  (N'流行する', N'りゅうこうする', N'Lưu hành', N'Lưu hành', N'N3', NULL, NULL, 232, GETDATE()),
  (N'経つ', N'たつ', N'Kinh', N'Trải qua', N'N3', NULL, NULL, 233, GETDATE()),
  (N'間に合う', N'まにあう', N'Gian hợp', N'Kịp giờ', N'N3', NULL, NULL, 234, GETDATE()),
  (N'間に合わせる', N'まにあわせる', N'Gian hợp', N'Đúng giờ', N'N3', NULL, NULL, 235, GETDATE()),
  (N'通う', N'かよう', N'Thống', N'Đi đi về về', N'N3', NULL, NULL, 236, GETDATE()),
  (N'込む', N'こむ', N'Nhập', N'Đông, tắc', N'N3', NULL, NULL, 237, GETDATE()),
  (N'すれ違う', N'すれちがう', N'Vi', N'Vượt qua, lướt qua', N'N3', NULL, NULL, 238, GETDATE()),
  (N'動く', N'うごく', N'Động', N'Bị chuyển động', N'N3', NULL, NULL, 239, GETDATE()),
  (N'動かす', N'うごかす', N'Động', N'Di chuyển', N'N3', NULL, NULL, 240, GETDATE()),
  (N'離れる', N'はなれる', N'Ly', N'Tách rời', N'N3', NULL, NULL, 241, GETDATE()),
  (N'離す', N'はなす', N'Ly', N'Để xa ra, làm tránh ra', N'N3', NULL, NULL, 242, GETDATE()),
  (N'ぶつかる', N'ぶつかる', NULL, N'Bị đâm', N'N3', NULL, NULL, 243, GETDATE()),
  (N'ぶつける', N'ぶつける', NULL, N'Đâm vào', N'N3', NULL, NULL, 244, GETDATE()),
  (N'涙', N'なみだ', N'Lệ', N'Nước mắt', N'N3', NULL, NULL, 245, GETDATE()),
  (N'溢れる', N'こぼれる', N'Dật', N'Tràn ra', N'N3', NULL, NULL, 246, GETDATE()),
  (N'溢す', N'こぼす', N'Dật', N'Làm tràn ra', N'N3', NULL, NULL, 247, GETDATE()),
  (N'拭く', N'ふく', N'Thức', N'Lau, chùi, gạt', N'N3', NULL, NULL, 248, GETDATE()),
  (N'片付く', N'かたづく', N'Phiến phó', N'Ngăn nắp', N'N3', NULL, NULL, 249, GETDATE()),
  (N'片付ける', N'かたづける', N'Phiến phó', N'Dọn dẹp', N'N3', NULL, NULL, 250, GETDATE()),
  (N'包む', N'つつむ', N'Bao', N'Bọc', N'N3', NULL, NULL, 251, GETDATE()),
  (N'貼る', N'はる', N'Thiếp', N'Dán', N'N3', NULL, NULL, 252, GETDATE()),
  (N'無くなる', N'なくなる', N'Vô', N'Bị mất', N'N3', NULL, NULL, 253, GETDATE()),
  (N'無くす', N'なくす', N'Vô', N'Làm mất', N'N3', NULL, NULL, 254, GETDATE()),
  (N'足りる', N'たりる', N'Túc', N'Đủ', N'N3', NULL, NULL, 255, GETDATE()),
  (N'収入', N'しゅうにゅう', N'Thu nhập', N'Thu nhập', N'N3', NULL, NULL, 256, GETDATE()),
  (N'残る', N'のこる', N'Tàn', N'Còn lại, sót lại', N'N3', NULL, NULL, 257, GETDATE()),
  (N'残す', N'のこす', N'Tàn', N'Thừa lại, sót lại', N'N3', NULL, NULL, 258, GETDATE()),
  (N'腐る', N'くさる', N'Hủ', N'Ôi, thiu', N'N3', NULL, NULL, 259, GETDATE()),
  (N'剥ける', N'むける', N'Bác', N'Bóc, gọt', N'N3', NULL, NULL, 260, GETDATE()),
  (N'剥く', N'むく', N'Bác', N'Bóc, gọt', N'N3', NULL, NULL, 261, GETDATE()),
  (N'滑る', N'すべる', N'Hoạt', N'Trượt', N'N3', NULL, NULL, 262, GETDATE()),
  (N'雪', N'ゆき', N'Tuyết', N'Tuyết', N'N3', NULL, NULL, 263, GETDATE()),
  (N'積もる', N'つもる', N'Tích', N'Chất đống', N'N3', NULL, NULL, 264, GETDATE()),
  (N'積む', N'つむ', N'Tích', N'Để lên, chất lên', N'N3', NULL, NULL, 265, GETDATE()),
  (N'空く', N'あく', N'Không', N'Trống rỗng, vắng vẻ', N'N3', NULL, NULL, 266, GETDATE()),
  (N'空ける', N'あける', N'Không', N'Giữ chỗ', N'N3', NULL, NULL, 267, GETDATE()),
  (N'下がる', N'さがる', N'Hạ', N'Giảm', N'N3', NULL, NULL, 268, GETDATE()),
  (N'下げる', N'さげる', N'Hạ', N'Hạ xuống', N'N3', NULL, NULL, 269, GETDATE()),
  (N'冷える', N'ひえる', N'Lãnh', N'Lạnh, cóng', N'N3', NULL, NULL, 270, GETDATE()),
  (N'冷やす', N'ひやす', N'Lãnh', N'Làm lạnh', N'N3', NULL, NULL, 271, GETDATE()),
  (N'冷める', N'さめる', N'Lãnh', N'Nguội', N'N3', NULL, NULL, 272, GETDATE()),
  (N'冷ます', N'さます', N'Lãnh', N'Làm nguội', N'N3', NULL, NULL, 273, GETDATE()),
  (N'燃える', N'もえる', N'Nhiên', N'Cháy', N'N3', NULL, NULL, 274, GETDATE()),
  (N'燃やす', N'もやす', N'Nhiên', N'Đốt cháy', N'N3', NULL, NULL, 275, GETDATE()),
  (N'沸く', N'わく', N'Phất', N'Nước sôi', N'N3', NULL, NULL, 276, GETDATE()),
  (N'沸かす', N'わかす', N'Phất', N'Đun sôi', N'N3', NULL, NULL, 277, GETDATE()),
  (N'お湯', N'おゆ', N'Thang', N'Nước nóng/sôi', N'N3', NULL, NULL, 278, GETDATE()),
  (N'鳴る', N'なる', N'Minh', N'Kêu', N'N3', NULL, NULL, 279, GETDATE()),
  (N'鳴らす', N'ならす', N'Minh', N'Làm cho kêu', N'N3', NULL, NULL, 280, GETDATE()),
  (N'役に立つ', N'やくにたつ', N'Dịch lập', N'Có tác dụng', N'N3', NULL, NULL, 281, GETDATE()),
  (N'役に立てる', N'やくにたてる', N'Dịch lập', N'Có tác dụng, có ích', N'N3', NULL, NULL, 282, GETDATE()),
  (N'飾る', N'かざる', N'Sức', N'Trang trí', N'N3', NULL, NULL, 283, GETDATE()),
  (N'遊ぶ', N'あそぶ', N'Du', N'Chơi', N'N3', NULL, NULL, 284, GETDATE()),
  (N'集まる', N'あつまる', N'Tập', N'Sưu tập', N'N3', NULL, NULL, 285, GETDATE()),
  (N'踊る', N'おどる', N'Dũng', N'Nhảy', N'N3', NULL, NULL, 286, GETDATE()),
  (N'思う', N'おもう', N'Tư', N'Suy nghĩ', N'N3', NULL, NULL, 287, GETDATE()),
  (N'考える', N'かんがえる', N'Khảo', N'Nghĩ', N'N3', NULL, NULL, 288, GETDATE()),
  (N'手伝う', N'てつだう', N'Thủ truyền', N'Giúp đỡ', N'N3', NULL, NULL, 289, GETDATE()),
  (N'働く', N'はたらく', N'Động', N'Hoạt động', N'N3', NULL, NULL, 290, GETDATE()),
  (N'決まる', N'きまる', N'Quyết', N'Luật lệ, quy định', N'N3', NULL, NULL, 291, GETDATE()),
  (N'騒ぐ', N'さわぐ', N'Tao', N'Làm ồn/rùng beng', N'N3', NULL, NULL, 292, GETDATE()),
  (N'知らせる', N'しらせる', N'Tri', N'Thông báo', N'N3', NULL, NULL, 293, GETDATE()),
  (N'頼む', N'たのむ', N'Lại', N'Nhờ vả', N'N3', NULL, NULL, 294, GETDATE()),
  (N'疲れる', N'つかれる', N'Bì', N'Mệt', N'N3', NULL, NULL, 295, GETDATE()),
  (N'違う', N'ちがう', N'Vi', N'Khác', N'N3', NULL, NULL, 296, GETDATE()),
  (N'始める', N'はじめる', N'Thủy', N'Bắt đầu', N'N3', NULL, NULL, 297, GETDATE()),
  (N'続く', N'つづく', N'Tục', N'Tiếp tục', N'N3', NULL, NULL, 298, GETDATE()),
  (N'暮れる', N'くれる', N'Mộ', N'Lặn(mặt trời), hết(ngày)', N'N3', NULL, NULL, 299, GETDATE()),
  (N'別れる', N'わかれる', N'Biệt', N'Chia tay, ly biệt', N'N3', NULL, NULL, 300, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'喜ぶ', N'よろこぶ', N'Hỉ', N'Hạnh phúc', N'N3', NULL, NULL, 301, GETDATE()),
  (N'優勝する', N'ゆうしょうする', N'Ưu thắng', N'Vô địch', N'N3', NULL, NULL, 302, GETDATE()),
  (N'笑う', N'わらう', N'Tiếu', N'Cười', N'N3', NULL, NULL, 303, GETDATE()),
  (N'驚く', N'おどろく', N'Kinh', N'Kinh ngạc', N'N3', NULL, NULL, 304, GETDATE()),
  (N'怒る', N'いかる', N'Nộ', N'Nổi giận', N'N3', NULL, NULL, 305, GETDATE()),
  (N'殺人', N'さつじん', N'Sát nhân', N'Sát nhân', N'N3', NULL, NULL, 306, GETDATE()),
  (N'幸せ（な）', N'しあわせ', N'Hạnh', N'Hạnh phúc', N'N3', NULL, NULL, 307, GETDATE()),
  (N'得意（な）', N'とくい', N'Đắc ý', N'Giỏi', N'N3', NULL, NULL, 308, GETDATE()),
  (N'苦手（な）', N'にがて', N'Khổ thủ', N'Kém', N'N3', NULL, NULL, 309, GETDATE()),
  (N'熱心（な）', N'ねっしん', N'Nhiệt tâm', N'Nhiệt tình', N'N3', NULL, NULL, 310, GETDATE()),
  (N'認め', N'みとめ', N'Nhận', N'Thừa nhận', N'N3', NULL, NULL, 311, GETDATE()),
  (N'昇進', N'しょうしん', N'Thăng tiến', N'Thăng tiến', N'N3', NULL, NULL, 312, GETDATE()),
  (N'夢中（な）', N'むちゅう', N'Mộng trung', N'Say mê', N'N3', NULL, NULL, 313, GETDATE()),
  (N'観客', N'かんきゃく', N'Quan khách', N'Khánh hàng', N'N3', NULL, NULL, 314, GETDATE()),
  (N'退屈（な）', N'たいくつ', N'Thoái khuất', N'Chán, tẻ nhạt', N'N3', NULL, NULL, 315, GETDATE()),
  (N'健康（な）', N'けんこう', N'Kiện khang', N'Khỏe khoắn', N'N3', NULL, NULL, 316, GETDATE()),
  (N'育てる', N'そだてる', N'Dục', N'Nuôi dạy', N'N3', NULL, NULL, 317, GETDATE()),
  (N'苦しい', N'くるしい', N'Khổ', N'Cực khổ', N'N3', NULL, NULL, 318, GETDATE()),
  (N'悪口', N'わるぐち', N'Ác khẩu', N'Nói xấu', N'N3', NULL, NULL, 319, GETDATE()),
  (N'平気（な）', N'へいき', N'Bình khí', N'Bình thản', N'N3', NULL, NULL, 320, GETDATE()),
  (N'悔しい', N'くやしい', N'Hối', N'Đáng tiếc, đáng ân hận', N'N3', NULL, NULL, 321, GETDATE()),
  (N'羨ましい', N'うらやましい', N'Tiện', N'Ghen tị', N'N3', NULL, NULL, 322, GETDATE()),
  (N'才能', N'さいのう', N'Tài năng', N'Tài năng', N'N3', NULL, NULL, 323, GETDATE()),
  (N'豊か', N'ゆたか', N'Phong', N'Phong phú', N'N3', NULL, NULL, 324, GETDATE()),
  (N'蚊', N'か', N'Văn', N'Muỗi', N'N3', NULL, NULL, 325, GETDATE()),
  (N'首', N'くび', N'Thủ', N'Cái cổ', N'N3', NULL, NULL, 326, GETDATE()),
  (N'痒い', N'かゆい', N'Dưỡng', N'Ngứa', N'N3', NULL, NULL, 327, GETDATE()),
  (N'大人しい', N'おとなしい', N'Đại nhân', N'Hiền lành', N'N3', NULL, NULL, 328, GETDATE()),
  (N'我慢強い', N'がまんづよい', N'Ngã mạn cường', N'Chịu đựng giỏi', N'N3', NULL, NULL, 329, GETDATE()),
  (N'正直（な）', N'しょうじき', N'Chính trực', N'Trung thực', N'N3', NULL, NULL, 330, GETDATE()),
  (N'けち（な）', N'けち（な）', NULL, N'Kiệt xỉ', N'N3', NULL, NULL, 331, GETDATE()),
  (N'我儘（な）', N'わがまま', N'Ngã tận', N'Ích kỉ', N'N3', NULL, NULL, 332, GETDATE()),
  (N'積極的（な）', N'せっきょくてき', N'Tích cực tính', N'Tính tích cực', N'N3', NULL, NULL, 333, GETDATE()),
  (N'消極的（な）', N'しょうきょくてき', N'Tiêu cực tính', N'Tính tiêu cực', N'N3', NULL, NULL, 334, GETDATE()),
  (N'満足（な）', N'まんぞく', N'Mãn túc', N'Mãn nguyện', N'N3', NULL, NULL, 335, GETDATE()),
  (N'不満（な）', N'ふまん', N'Bất mãn', N'Bất mãn', N'N3', NULL, NULL, 336, GETDATE()),
  (N'不安（な）', N'ふあん', N'Bất an', N'Bất an', N'N3', NULL, NULL, 337, GETDATE()),
  (N'大変（な）', N'たいへん', N'Đại biến', N'Vất vả', N'N3', NULL, NULL, 338, GETDATE()),
  (N'無理（な）', N'むり', N'Vô lý', N'Vô lý', N'N3', NULL, NULL, 339, GETDATE()),
  (N'不注意（な）', N'ふちゅうい', N'Bất chú ý', N'Không chú ý', N'N3', NULL, NULL, 340, GETDATE()),
  (N'楽（な）', N'らく', N'Lạc', N'Thoải mái, nhàn hạ', N'N3', NULL, NULL, 341, GETDATE()),
  (N'面倒（な）', N'めんどう', N'Diện đảo', N'Phiền hà, quấy rầy', N'N3', NULL, NULL, 342, GETDATE()),
  (N'手続き', N'てつづき', N'Thủ tục', N'Thủ tục', N'N3', NULL, NULL, 343, GETDATE()),
  (N'失礼（な）', N'しつれい', N'Thất lễ', N'Mất lịch sự', N'N3', NULL, NULL, 344, GETDATE()),
  (N'当然（な）', N'とうぜん', N'Đương nhiên', N'Đương nhiên', N'N3', NULL, NULL, 345, GETDATE()),
  (N'意外（な）', N'いがい', N'Ý ngoại', N'Ngoài ý muốn', N'N3', NULL, NULL, 346, GETDATE()),
  (N'調査', N'ちょうさ', N'Điều tra', N'Điều tra', N'N3', NULL, NULL, 347, GETDATE()),
  (N'事故', N'じこ', N'Sự cố', N'Tai nạn, sự cố', N'N3', NULL, NULL, 348, GETDATE()),
  (N'結構（な）', N'けっこう', N'Kết cấu', N'Tốt, cũng được', N'N3', NULL, NULL, 349, GETDATE()),
  (N'派手（な）', N'はで', N'Phái thủ', N'Lòe loẹt, màu mè', N'N3', NULL, NULL, 350, GETDATE()),
  (N'地味（な）', N'じみ', N'Địa vị', N'Giản dị, đơn giản', N'N3', NULL, NULL, 351, GETDATE()),
  (N'お洒落（な）', N'おしゃれ', N'Sái lạc', N'Thời trang thịnh hành', N'N3', NULL, NULL, 352, GETDATE()),
  (N'変（な）', N'へん', N'Biến', N'Lạ, kỳ quặc', N'N3', NULL, NULL, 353, GETDATE()),
  (N'不思議（な）', N'ふしぎ', N'Bất tư nghĩa', N'Bí hiểm, kỳ quái', N'N3', NULL, NULL, 354, GETDATE()),
  (N'増し（な）', N'まし', N'Tăng', N'Tốt lên', N'N3', NULL, NULL, 355, GETDATE()),
  (N'無駄（な）', N'むだ', N'Vô đả', N'Lãng phí', N'N3', NULL, NULL, 356, GETDATE()),
  (N'自由（な）', N'じゆう', N'Tự do', N'Tự do', N'N3', NULL, NULL, 357, GETDATE()),
  (N'不自由（な）', N'ふじゆう', N'Bất tự do', N'Không tự do, tàn phế', N'N3', NULL, NULL, 358, GETDATE()),
  (N'暖まる', N'あたたまる', N'Noãn', N'Ấm lên', N'N3', NULL, NULL, 359, GETDATE()),
  (N'暖める', N'あたためる', N'Noãn', N'Làm ấm', N'N3', NULL, NULL, 360, GETDATE()),
  (N'高まる', N'たかまる', N'Cao', N'Bốc lên, nâng lên', N'N3', NULL, NULL, 361, GETDATE()),
  (N'高める', N'たかめる', N'Cao', N'Làm cho lên, dựng lên', N'N3', NULL, NULL, 362, GETDATE()),
  (N'強まる', N'つよまる', N'Cường', N'Khỏe,mạnh lên', N'N3', NULL, NULL, 363, GETDATE()),
  (N'強める', N'つよめる', N'Cường', N'Làm khỏe lên', N'N3', NULL, NULL, 364, GETDATE()),
  (N'弱まる', N'よわまる', N'Nhược', N'Yếu đi', N'N3', NULL, NULL, 365, GETDATE()),
  (N'弱める', N'よわめる', N'Nhược', N'Làm yếu đi', N'N3', NULL, NULL, 366, GETDATE()),
  (N'広まる', N'ひろまる', N'Quảng', N'Được lan truyền', N'N3', NULL, NULL, 367, GETDATE()),
  (N'広める', N'ひろめる', N'Quảng', N'Loan tin, tuyên truyền', N'N3', NULL, NULL, 368, GETDATE()),
  (N'深まる', N'ふかまる', N'Thâm', N'Sâu sắc thêm', N'N3', NULL, NULL, 369, GETDATE()),
  (N'深める', N'ふかめる', N'Thâm', N'Làm sâu sắc thêm', N'N3', NULL, NULL, 370, GETDATE()),
  (N'世話', N'せわ', N'Thế thoại', N'Giúp đỡ', N'N3', NULL, NULL, 371, GETDATE()),
  (N'家庭', N'かてい', N'Gia đình', N'Gia đình', N'N3', NULL, NULL, 372, GETDATE()),
  (N'厳しい', N'きびしい', N'Nghiêm', N'Nghiêm khắc', N'N3', NULL, NULL, 373, GETDATE()),
  (N'易しい', N'やさしい', N'Dị', N'Dễ', N'N3', NULL, NULL, 374, GETDATE()),
  (N'協力する', N'きょうりょくする', N'Hiệp lực', N'Hiệp lực', N'N3', NULL, NULL, 375, GETDATE()),
  (N'介護', N'かいご', N'Giới hộ', N'Chăm sóc', N'N3', NULL, NULL, 376, GETDATE()),
  (N'感謝する', N'かんしゃする', N'Cảm tạ', N'Cảm ơn, biết ơn', N'N3', NULL, NULL, 377, GETDATE()),
  (N'お詫び', N'おわび', N'Sá', N'Xin lỗi', N'N3', NULL, NULL, 378, GETDATE()),
  (N'迷惑をかける', N'めいわくをかける', N'Mê hoặc', N'Làm phiền', N'N3', NULL, NULL, 379, GETDATE()),
  (N'お辞儀', N'おじぎ', N'Từ nghi', N'Cúi chào', N'N3', NULL, NULL, 380, GETDATE()),
  (N'丁寧（な）', N'ていねい', N'Đinh ninh', N'Lịch sự', N'N3', NULL, NULL, 381, GETDATE()),
  (N'握手', N'あくしゅ', N'Ác thủ', N'Bắt tay', N'N3', NULL, NULL, 382, GETDATE()),
  (N'意地悪する', N'いじわるする', N'Ý địa ác', N'Tâm địa xấu, xấu bụng', N'N3', NULL, NULL, 383, GETDATE()),
  (N'悪戯する', N'いたずらする', N'Ác hí', N'Nghịch ngợm', N'N3', NULL, NULL, 384, GETDATE()),
  (N'節約する', N'せつやくする', N'Tiết ước', N'Tiết kiệm, dành dụm', N'N3', NULL, NULL, 385, GETDATE()),
  (N'生活費', N'せいかつひ', N'Sinh hoạt phí', N'Phí sinh hoạt', N'N3', NULL, NULL, 386, GETDATE()),
  (N'経営する', N'けいえいする', N'Kinh doanh', N'Quản lý kinh doanh', N'N3', NULL, NULL, 387, GETDATE()),
  (N'反省する', N'はんせいする', N'Phản tỉnh', N'Kiểm điểm', N'N3', NULL, NULL, 388, GETDATE()),
  (N'実行する', N'じっこうする', N'Thực hành', N'Thực hành', N'N3', NULL, NULL, 389, GETDATE()),
  (N'進歩する', N'しんぽする', N'Tiến bộ', N'Tiến bộ', N'N3', NULL, NULL, 390, GETDATE()),
  (N'変化する', N'へんかする', N'Biến hóa', N'Thay đổi', N'N3', NULL, NULL, 391, GETDATE()),
  (N'発達する', N'はったつする', N'Phát đạt', N'Phát triển, phát đạt', N'N3', NULL, NULL, 392, GETDATE()),
  (N'体力', N'たいりょく', N'Thể lực', N'Thể lực', N'N3', NULL, NULL, 393, GETDATE()),
  (N'低下', N'ていか', N'Đê hạ', N'Suy giảm', N'N3', NULL, NULL, 394, GETDATE()),
  (N'若者', N'わかもの', N'Nhã giả', N'Giới trẻ', N'N3', NULL, NULL, 395, GETDATE()),
  (N'出場する', N'しゅつじょうする', N'Xuất trường', N'Ra mặt, ra mắt(trình diễn)', N'N3', NULL, NULL, 396, GETDATE()),
  (N'活躍する', N'かつやくする', N'Hoạt dược', N'Hoạt động', N'N3', NULL, NULL, 397, GETDATE()),
  (N'競争する', N'きょうそうする', N'Cạnh tranh', N'Cạnh tranh', N'N3', NULL, NULL, 398, GETDATE()),
  (N'成績', N'せいせき', N'Thành tích', N'Thành tích', N'N3', NULL, NULL, 399, GETDATE()),
  (N'応援する', N'おうえんする', N'Ứng viên', N'Cổ vũ, hỗ trợ', N'N3', NULL, NULL, 400, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'拍手する', N'はくしゅする', N'Phách thủ', N'Vỗ tay', N'N3', NULL, NULL, 401, GETDATE()),
  (N'噂する', N'うわさする', N'Đồn', N'Lời đồn, bàn tán', N'N3', NULL, NULL, 402, GETDATE()),
  (N'情報', N'じょうほう', N'Tình báo', N'Thông tin', N'N3', NULL, NULL, 403, GETDATE()),
  (N'流行する', N'りゅうこうする', N'Lưu hành', N'Lưu hành', N'N3', NULL, NULL, 404, GETDATE()),
  (N'交換する', N'こうかんする', N'Giao hoán', N'Trao đổi', N'N3', NULL, NULL, 405, GETDATE()),
  (N'宣伝する', N'せんでんする', N'Tuyên truyền', N'Tuyền truyền', N'N3', NULL, NULL, 406, GETDATE()),
  (N'広告', N'こうこく', N'Quảng cáo', N'Quảng cáo', N'N3', NULL, NULL, 407, GETDATE()),
  (N'注目する', N'ちゅうもくする', N'Chú mục', N'Tập trung sự chú ý', N'N3', NULL, NULL, 408, GETDATE()),
  (N'通訳する', N'つうやくする', N'Thông dịch', N'Thông dịch', N'N3', NULL, NULL, 409, GETDATE()),
  (N'翻訳する', N'ほんやくする', N'Phiên dịch', N'Phiên dịch', N'N3', NULL, NULL, 410, GETDATE()),
  (N'伝言する', N'でんごんする', N'Truyền ngôn', N'Nhắn tin', N'N3', NULL, NULL, 411, GETDATE()),
  (N'報告する', N'ほうこくする', N'Báo cáo', N'Báo cáo', N'N3', NULL, NULL, 412, GETDATE()),
  (N'録画', N'ろくが', N'Lục họa', N'Ghi hình', N'N3', NULL, NULL, 413, GETDATE()),
  (N'混雑する', N'こんざつする', N'Hỗn tạp', N'Hỗn tạp, đông đúc', N'N3', NULL, NULL, 414, GETDATE()),
  (N'渋滞する', N'じゅうたいする', N'Sáp trệ', N'Tắc đường, tắc nghẽn', N'N3', NULL, NULL, 415, GETDATE()),
  (N'衝突する', N'しょうとつする', N'Xung đột', N'Xung đột, va chạm', N'N3', NULL, NULL, 416, GETDATE()),
  (N'場面', N'ばめん', N'Trường diện', N'Hiện trường', N'N3', NULL, NULL, 417, GETDATE()),
  (N'被害', N'ひがい', N'Bị hại', N'Thiệt hại', N'N3', NULL, NULL, 418, GETDATE()),
  (N'事故', N'じこ', N'Sự cố', N'Tại nạn, sự cố', N'N3', NULL, NULL, 419, GETDATE()),
  (N'事件', N'じけん', N'Sự kiện', N'Sự kiện', N'N3', NULL, NULL, 420, GETDATE()),
  (N'故障する', N'こしょうする', N'Cố chướng', N'Hỏng hóc, trục trặc', N'N3', NULL, NULL, 421, GETDATE()),
  (N'修理する', N'しゅうりする', N'Tu lý', N'Sửa chữa', N'N3', NULL, NULL, 422, GETDATE()),
  (N'停電', N'ていでん', N'Đình điện', N'Mất điện', N'N3', NULL, NULL, 423, GETDATE()),
  (N'雷', N'かみなり', N'Lôi', N'Sấm sét', N'N3', NULL, NULL, 424, GETDATE()),
  (N'調子', N'ちょうし', N'Điều tử', N'Tình trạng', N'N3', NULL, NULL, 425, GETDATE()),
  (N'自信', N'じしん', N'Tự tín', N'Tự tin', N'N3', NULL, NULL, 426, GETDATE()),
  (N'自慢', N'じまん', N'Tự mãn', N'Tự mãn', N'N3', NULL, NULL, 427, GETDATE()),
  (N'関心', N'かんしん', N'Quan tâm', N'Quan tâm', N'N3', NULL, NULL, 428, GETDATE()),
  (N'感動する', N'かんどうする', N'Cảm động', N'Cảm động', N'N3', NULL, NULL, 429, GETDATE()),
  (N'興奮する', N'こうふんする', N'Hưng phấn', N'Hưng phấn', N'N3', NULL, NULL, 430, GETDATE()),
  (N'感想', N'かんそう', N'Cảm tưởng', N'Cảm tưởng', N'N3', NULL, NULL, 431, GETDATE()),
  (N'予想する', N'よそうする', N'Dự tưởng', N'Đoán trước, trù liệu', N'N3', NULL, NULL, 432, GETDATE()),
  (N'専門', N'せんもん', N'Chuyên môn', N'Chuyên môn', N'N3', NULL, NULL, 433, GETDATE()),
  (N'研究する', N'けんきゅうする', N'Nghiên cứu', N'Nghiên cứu', N'N3', NULL, NULL, 434, GETDATE()),
  (N'調査する', N'ちょうさする', N'Điều tra', N'Điều tra', N'N3', NULL, NULL, 435, GETDATE()),
  (N'原因', N'げんいん', N'Nguyên nhân', N'Nguyên nhân', N'N3', NULL, NULL, 436, GETDATE()),
  (N'結果', N'けっか', N'Kết quả', N'Kết quả', N'N3', NULL, NULL, 437, GETDATE()),
  (N'解決', N'かいけつ', N'Giải quyết', N'Quải quyết', N'N3', NULL, NULL, 438, GETDATE()),
  (N'確かめる', N'たしかめる', N'Xác', N'Xác nhận, kiểm tra', N'N3', NULL, NULL, 439, GETDATE()),
  (N'間違う', N'まちがう', N'Gian vi', N'Sai', N'N3', NULL, NULL, 440, GETDATE()),
  (N'利用する', N'りようする', N'Lợi dụng', N'Sử dụng', N'N3', NULL, NULL, 441, GETDATE()),
  (N'減る', N'へる', N'Giảm', N'Giảm', N'N3', NULL, NULL, 442, GETDATE()),
  (N'理解する', N'りかいする', N'Lý giải', N'Lý giải', N'N3', NULL, NULL, 443, GETDATE()),
  (N'発見する', N'はっけんする', N'Phát kiến', N'Phát hiện', N'N3', NULL, NULL, 444, GETDATE()),
  (N'発明する', N'はつめいする', N'Phát minh', N'Phát minh', N'N3', NULL, NULL, 445, GETDATE()),
  (N'関係する', N'かんけいする', N'Quan hệ', N'Quan hệ', N'N3', NULL, NULL, 446, GETDATE()),
  (N'団体', N'だんたい', N'Đoàn thể', N'Đoàn thể, nhóm', N'N3', NULL, NULL, 447, GETDATE()),
  (N'博物館', N'はくぶつかん', N'Bác học quán', N'Viện bảo tàng', N'N3', NULL, NULL, 448, GETDATE()),
  (N'選挙', N'せんきょ', N'Tuyển cử', N'Bầu cử', N'N3', NULL, NULL, 449, GETDATE()),
  (N'行う', N'おこなう', N'Hành', N'Tổ chức', N'N3', NULL, NULL, 450, GETDATE()),
  (N'税金', N'ぜいきん', N'Thuế kim', N'Tiền thuế', N'N3', NULL, NULL, 451, GETDATE()),
  (N'責任', N'せきにん', N'Trách nhiệm', N'Trách nhiệm', N'N3', NULL, NULL, 452, GETDATE()),
  (N'書類', N'しょるい', N'Thư loại', N'Giấy tờ', N'N3', NULL, NULL, 453, GETDATE()),
  (N'題名', N'だいめい', N'Đề danh', N'Nhan đề', N'N3', NULL, NULL, 454, GETDATE()),
  (N'条件', N'じょうけん', N'Điều kiện', N'Điều kiện', N'N3', NULL, NULL, 455, GETDATE()),
  (N'採用', N'さいよう', N'Thải dụng', N'Tuyển dụng', N'N3', NULL, NULL, 456, GETDATE()),
  (N'締め切り', N'しめきり', N'Đế thiết', N'Hạn cuối', N'N3', NULL, NULL, 457, GETDATE()),
  (N'倍', N'ばい', N'Bối', N'Gấp đôi', N'N3', NULL, NULL, 459, GETDATE()),
  (N'近道', N'ちかみち', N'Cận đạo', N'Đường tắt', N'N3', NULL, NULL, 460, GETDATE()),
  (N'中心', N'ちゅうしん', N'Trung tâm', N'Trung tâm', N'N3', NULL, NULL, 461, GETDATE()),
  (N'辺り', N'あたり', N'Biên', N'Xung quanh', N'N3', NULL, NULL, 462, GETDATE()),
  (N'周り', N'まわり', N'Chu', N'Xung quanh', N'N3', NULL, NULL, 463, GETDATE()),
  (N'穴', N'あな', N'Huyệt', N'Lỗ', N'N3', NULL, NULL, 464, GETDATE()),
  (N'地面', N'じめん', N'Địa diện', N'Mặt đất', N'N3', NULL, NULL, 465, GETDATE()),
  (N'掘る', N'ほる', N'Quật', N'Đào', N'N3', NULL, NULL, 466, GETDATE()),
  (N'列', N'れつ', N'Liệt', N'Hàng ( xếp hàng)', N'N3', NULL, NULL, 467, GETDATE()),
  (N'幅', N'はば', N'Phúc', N'Chiều rộng', N'N3', NULL, NULL, 468, GETDATE()),
  (N'範囲', N'はんい', N'Phạm vi', N'Phạm vi', N'N3', NULL, NULL, 469, GETDATE()),
  (N'内容', N'ないよう', N'Nội dung', N'Nội dung', N'N3', NULL, NULL, 470, GETDATE()),
  (N'中身', N'なかみ', N'Trung thân', N'Nội dung bên trong', N'N3', NULL, NULL, 471, GETDATE()),
  (N'特徴', N'とくちょう', N'Đặc trưng', N'Đặc trưng', N'N3', NULL, NULL, 472, GETDATE()),
  (N'普通', N'ふつう', N'Phổ thông', N'Phổ thông, thông thường', N'N3', NULL, NULL, 473, GETDATE()),
  (N'当たり前', N'あたりまえ', N'Đương tiền', N'Dĩ nhiên', N'N3', NULL, NULL, 474, GETDATE()),
  (N'偽', N'にせ', N'Ngụy', N'Giả (giả dối)', N'N3', NULL, NULL, 475, GETDATE()),
  (N'別れる', N'わかれる', N'Biệt', N'Chia tay, ly biệt', N'N3', NULL, NULL, 476, GETDATE()),
  (N'国籍', N'こくせき', N'Quốc tịch', N'Quốc tịch', N'N3', NULL, NULL, 477, GETDATE()),
  (N'東洋', N'とうよう', N'Đông dương', N'Phương Đông', N'N3', NULL, NULL, 478, GETDATE()),
  (N'西洋', N'せいよう', N'Tây dương', N'Phương Tây', N'N3', NULL, NULL, 479, GETDATE()),
  (N'比べる', N'くらべる', N'Tỷ', N'So sánh', N'N3', NULL, NULL, 480, GETDATE()),
  (N'文化', N'ぶんか', N'Văn hóa', N'Văn hóa', N'N3', NULL, NULL, 481, GETDATE()),
  (N'国際', N'こくさい', N'Quốc tế', N'Quốc tế', N'N3', NULL, NULL, 482, GETDATE()),
  (N'支社', N'ししゃ', N'Chi xã', N'Chi nhánh', N'N3', NULL, NULL, 483, GETDATE()),
  (N'企業', N'きぎょう', N'Xí nghiệp', N'Công ty, xí nghiệp', N'N3', NULL, NULL, 484, GETDATE()),
  (N'発展', N'はってん', N'Phát triển', N'Phát triển', N'N3', NULL, NULL, 485, GETDATE()),
  (N'自然', N'しぜん', N'Tự nhiên', N'Tự nhiên', N'N3', NULL, NULL, 486, GETDATE()),
  (N'景色', N'けしき', N'Cảnh sắc', N'Phong cảnh', N'N3', NULL, NULL, 487, GETDATE()),
  (N'宗教', N'しゅうきょう', N'Tôn giáo', N'Tôn giáo', N'N3', NULL, NULL, 488, GETDATE()),
  (N'愛', N'あい', N'Ái', N'Yêu', N'N3', NULL, NULL, 489, GETDATE()),
  (N'が　届く', N'とどく', N'Giới', N'Được gửi đến', N'N3', NULL, NULL, 490, GETDATE()),
  (N'届ける', N'とどける', N'Giới', N'Chuyển đến', N'N3', NULL, NULL, 491, GETDATE()),
  (N'掻く', N'かく', N'Tao', N'Gãi, cào, bới', N'N3', NULL, NULL, 492, GETDATE()),
  (N'掴む', N'つかむ', N'Quặc', N'Tóm, chộp', N'N3', NULL, NULL, 493, GETDATE()),
  (N'びっくりする', N'びっくりする', NULL, N'Ngạc nhiên, giật mình', N'N3', NULL, NULL, 494, GETDATE()),
  (N'握る', N'にぎる', N'Ác', N'Bắt, bíu, nắm', N'N3', NULL, NULL, 495, GETDATE()),
  (N'押さえる', N'おさえる', N'Áp', N'Giữ, ôm(bụng)', N'N3', NULL, NULL, 496, GETDATE()),
  (N'が　近づく', N'ちかづく', N'Cận', N'Đến gần, tới gần', N'N3', NULL, NULL, 497, GETDATE()),
  (N'近づける', N'ちかづける', N'Cận', N'Kết thân, mang lại gần', N'N3', NULL, NULL, 498, GETDATE()),
  (N'が　合う', N'あう', N'Hợp', N'Chạm mặt', N'N3', NULL, NULL, 499, GETDATE()),
  (N'不図', N'ふと', N'Bất đồ', N'Đột nhiên', N'N3', NULL, NULL, 500, GETDATE()),
  (N'合わせる', N'あわせる', N'Hợp', N'Hiệp sức', N'N3', NULL, NULL, 501, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'が　当たる', N'あたる', N'Đương', N'Bị đánh', N'N3', NULL, NULL, 502, GETDATE()),
  (N'当てる', N'あてる', N'Đương', N'Đánh trúng', N'N3', NULL, NULL, 503, GETDATE()),
  (N'比べる', N'くらべる', N'Tỷ', N'So sánh', N'N3', NULL, NULL, 504, GETDATE()),
  (N'似合う', N'にあう', N'Tự hợp', N'Hợp', N'N3', NULL, NULL, 505, GETDATE()),
  (N'似る', N'にる', N'Tự', N'Giống', N'N3', NULL, NULL, 506, GETDATE()),
  (N'似せる', N'にせる', N'Tự', N'Bắt chước', N'N3', NULL, NULL, 507, GETDATE()),
  (N'が　分かれる', N'わかれる', N'Phân', N'Phân chia', N'N3', NULL, NULL, 508, GETDATE()),
  (N'分ける', N'わける', N'Phân', N'Chia', N'N3', NULL, NULL, 509, GETDATE()),
  (N'財産', N'ざいさん', N'Tài sản', N'Tài sản', N'N3', NULL, NULL, 510, GETDATE()),
  (N'足す', N'たす', N'Túc', N'Cộng vào, thêm vào', N'N3', NULL, NULL, 511, GETDATE()),
  (N'薄い', N'うすい', N'Bạc', N'Nhạt, mỏng', N'N3', NULL, NULL, 512, GETDATE()),
  (N'塩', N'しお', N'Diêm', N'Muối', N'N3', NULL, NULL, 513, GETDATE()),
  (N'引く', N'ひく', N'Dẫn', N'Trừ', N'N3', NULL, NULL, 514, GETDATE()),
  (N'が　増える', N'ふえる', N'Tăng', N'Tăng lên', N'N3', NULL, NULL, 515, GETDATE()),
  (N'増やす', N'ふやす', N'Tăng', N'Làm tăng lên', N'N3', NULL, NULL, 516, GETDATE()),
  (N'が　減る', N'へる', N'Giảm', N'Giảm', N'N3', NULL, NULL, 517, GETDATE()),
  (N'減らす', N'へらす', N'Giảm', N'Làm giảm', N'N3', NULL, NULL, 518, GETDATE()),
  (N'店長', N'てんちょう', N'Điếm trường', N'Chủ tiệm', N'N3', NULL, NULL, 519, GETDATE()),
  (N'が　返る', N'かえる', N'Phản', N'Được trả lại', N'N3', NULL, NULL, 520, GETDATE()),
  (N'返す', N'かえす', N'Phản', N'Trả lại', N'N3', NULL, NULL, 521, GETDATE()),
  (N'譲る', N'ゆずる', N'Nhượng', N'Nhường nhin, nhượng bộ', N'N3', NULL, NULL, 522, GETDATE()),
  (N'が　助かる', N'たすかる', N'Trợ', N'Được giúp', N'N3', NULL, NULL, 523, GETDATE()),
  (N'助ける', N'たすける', N'Trợ', N'Giúp đỡ', N'N3', NULL, NULL, 524, GETDATE()),
  (N'虐める', N'いじめる', N'Ngược', N'Bị bắt nạt', N'N3', NULL, NULL, 525, GETDATE()),
  (N'騙す', N'だます', N'Phiến', N'Lừa đảo, lạm dụng', N'N3', NULL, NULL, 526, GETDATE()),
  (N'独身', N'どくしん', N'Độc thân', N'Độc thân', N'N3', NULL, NULL, 527, GETDATE()),
  (N'女性', N'じょせい', N'Nữ giới', N'Nữ giới', N'N3', NULL, NULL, 528, GETDATE()),
  (N'付き合う', N'つきあう', N'Phó hợp', N'Hẹn hò', N'N3', NULL, NULL, 529, GETDATE()),
  (N'盗む', N'ぬすむ', N'Đạo', N'Ăn trộm', N'N3', NULL, NULL, 530, GETDATE()),
  (N'留守中', N'るすちゅう', N'Lưu thủ trung', N'Trong khi vắng nhà', N'N3', NULL, NULL, 531, GETDATE()),
  (N'が　刺さる', N'ささる', N'Thích', N'Mắc, hóc', N'N3', NULL, NULL, 532, GETDATE()),
  (N'刺す', N'さす', N'Thích', N'Đâm, chọc', N'N3', NULL, NULL, 533, GETDATE()),
  (N'殺す', N'ころす', N'Sát', N'Giết', N'N3', NULL, NULL, 534, GETDATE()),
  (N'が　隠れる', N'かくれる', N'Ẩn', N'Ẩn nấp, núp', N'N3', NULL, NULL, 535, GETDATE()),
  (N'隠す', N'かくす', N'Ẩn', N'Che giấu', N'N3', NULL, NULL, 536, GETDATE()),
  (N'が　埋まる', N'うまる', N'Mai', N'Bị lấp/chôn', N'N3', NULL, NULL, 537, GETDATE()),
  (N'埋める', N'うめる', N'Mai', N'Chôn lấp', N'N3', NULL, NULL, 538, GETDATE()),
  (N'囲む', N'かこむ', N'Vi', N'Bao quanh, vây hãm', N'N3', NULL, NULL, 539, GETDATE()),
  (N'が　詰まる', N'つまる', N'Cật', N'Chặt, đầy', N'N3', NULL, NULL, 540, GETDATE()),
  (N'詰める', N'つめる', N'Cật', N'Nhét vào, tống vào', N'N3', NULL, NULL, 541, GETDATE()),
  (N'開く', N'ひらく', N'Khai', N'Mở', N'N3', NULL, NULL, 542, GETDATE()),
  (N'閉じる', N'とじる', N'Bế', N'Đóng', N'N3', NULL, NULL, 543, GETDATE()),
  (N'が　飛ぶ', N'とぶ', N'Phi', N'Bay', N'N3', NULL, NULL, 544, GETDATE()),
  (N'飛ばす', N'とばす', N'Phi', N'Làm cho bay', N'N3', NULL, NULL, 545, GETDATE()),
  (N'振る', N'ふる', N'Chấn', N'Vẫy (tay)', N'N3', NULL, NULL, 546, GETDATE()),
  (N'捲る', N'めくる', N'Quyển', N'Xắn, quấn', N'N3', NULL, NULL, 547, GETDATE()),
  (N'見かける', N'みかける', N'Kiến', N'Tình cờ gặp', N'N3', NULL, NULL, 548, GETDATE()),
  (N'確かめる', N'たしかめる', N'Xác', N'Xác nhận, kiểm tra', N'N3', NULL, NULL, 549, GETDATE()),
  (N'試す', N'ためす', N'Thí', N'Mặc thử', N'N3', NULL, NULL, 550, GETDATE()),
  (N'洋服', N'ようふく', N'Dương phục', N'Quần áo kiểu Tây Âu', N'N3', NULL, NULL, 551, GETDATE()),
  (N'繰り返す', N'くりかえす', N'Sào phản', N'Lặp lại', N'N3', NULL, NULL, 552, GETDATE()),
  (N'体操する', N'たいそうする', N'Thể thao', N'Tập thể dục', N'N3', NULL, NULL, 553, GETDATE()),
  (N'訳す', N'やくす', N'Dịch', N'Dịch', N'N3', NULL, NULL, 554, GETDATE()),
  (N'行う', N'おこなう', N'Hành', N'Tổ chức', N'N3', NULL, NULL, 555, GETDATE()),
  (N'が　間違う', N'まちがう', N'Gian vi', N'Bị sai', N'N3', NULL, NULL, 556, GETDATE()),
  (N'間違える', N'まちがえる', N'Gian vi', N'Làm sai', N'N3', NULL, NULL, 557, GETDATE()),
  (N'許す', N'ゆるす', N'Hứa', N'Tha thứ, tha lỗi', N'N3', NULL, NULL, 558, GETDATE()),
  (N'謝る', N'あやまる', N'Tạ', N'Xin lỗi', N'N3', NULL, NULL, 559, GETDATE()),
  (N'が　慣れる', N'なれる', N'Quán', N'Quen', N'N3', NULL, NULL, 560, GETDATE()),
  (N'慣らす', N'ならす', N'Quán', N'Làm quen, khởi động', N'N3', NULL, NULL, 561, GETDATE()),
  (N'が　立つ', N'たつ', N'Lập', N'Bị đứng', N'N3', NULL, NULL, 562, GETDATE()),
  (N'立てる', N'たてる', N'Lập', N'Đứng lên', N'N3', NULL, NULL, 563, GETDATE()),
  (N'が　建つ', N'たつ', N'Kiến', N'Được xây', N'N3', NULL, NULL, 564, GETDATE()),
  (N'建てる', N'たてる', N'Kiến', N'Xây lên', N'N3', NULL, NULL, 565, GETDATE()),
  (N'が　育つ', N'そだつ', N'Dục', N'Lớn lên, khôn lớn', N'N3', NULL, NULL, 566, GETDATE()),
  (N'育てる', N'そだてる', N'Dục', N'Nuôi, dạy', N'N3', NULL, NULL, 567, GETDATE()),
  (N'が　生える', N'はえる', N'Sinh', N'Mọc, phát triển', N'N3', NULL, NULL, 568, GETDATE()),
  (N'生やす', N'はやす', N'Sinh', N'Để dài (râu)', N'N3', NULL, NULL, 569, GETDATE()),
  (N'が　汚れる', N'よごれる', N'Ô', N'Bị bẩn', N'N3', NULL, NULL, 570, GETDATE()),
  (N'汚す', N'よごす', N'Ô', N'Làm bẩn', N'N3', NULL, NULL, 571, GETDATE()),
  (N'が　壊れる', N'こわれる', N'Hoại', N'Bị hỏng', N'N3', NULL, NULL, 572, GETDATE()),
  (N'壊す', N'こわす', N'Hoại', N'Làm hỏng', N'N3', NULL, NULL, 573, GETDATE()),
  (N'が　割れる', N'われる', N'Cát', N'Bị vỡ', N'N3', NULL, NULL, 574, GETDATE()),
  (N'割る', N'わる', N'Cát', N'Làm vỡ', N'N3', NULL, NULL, 575, GETDATE()),
  (N'が　折れる', N'おれる', N'Triết', N'Gãy', N'N3', NULL, NULL, 576, GETDATE()),
  (N'折る', N'おる', N'Triết', N'Làm gãy', N'N3', NULL, NULL, 577, GETDATE()),
  (N'が　破れる', N'やぶれる', N'Phá', N'Rách', N'N3', NULL, NULL, 578, GETDATE()),
  (N'破る', N'やぶる', N'Phá', N'Xé rách', N'N3', NULL, NULL, 579, GETDATE()),
  (N'が　曲がる', N'まがる', N'Khúc', N'Bị gập, cong', N'N3', NULL, NULL, 580, GETDATE()),
  (N'曲げる', N'まげる', N'Khúc', N'Gập, bẻ cong', N'N3', NULL, NULL, 581, GETDATE()),
  (N'が　外れる', N'はずれる', N'Ngoại', N'Rời ra, tách ra', N'N3', NULL, NULL, 582, GETDATE()),
  (N'外す', N'はずす', N'Ngoại', N'Làm rời ra, tách ra', N'N3', NULL, NULL, 583, GETDATE()),
  (N'が　揺れる', N'ゆれる', N'Dao', N'Bi rung', N'N3', NULL, NULL, 584, GETDATE()),
  (N'揺らす', N'ゆらす', N'Dao', N'Rung, đung đưa', N'N3', NULL, NULL, 585, GETDATE()),
  (N'が　流れる', N'ながれる', N'Lưu', N'Chảy, trôi đi', N'N3', NULL, NULL, 586, GETDATE()),
  (N'流す', N'ながす', N'Lưu', N'Cho chảy', N'N3', NULL, NULL, 587, GETDATE()),
  (N'都心', N'としん', N'Đô tâm', N'Trung tâm', N'N3', NULL, NULL, 588, GETDATE()),
  (N'が　濡れる', N'ぬれる', N'Nhu', N'Bị ướt', N'N3', NULL, NULL, 589, GETDATE()),
  (N'濡らす', N'ぬらす', N'Nhu', N'Làm ướt', N'N3', NULL, NULL, 590, GETDATE()),
  (N'が　迷う', N'まよう', N'Mê', N'Lạc đường', N'N3', NULL, NULL, 591, GETDATE()),
  (N'悩む', N'なやむ', N'Não', N'Phiền muội, lo lắng', N'N3', NULL, NULL, 592, GETDATE()),
  (N'が　慌てる', N'あわてる', N'Hoảng', N'Luống cuống, vội vàng', N'N3', NULL, NULL, 593, GETDATE()),
  (N'が　覚める', N'さめる', N'Giác', N'Tỉnh giấc, tỉnh dậy', N'N3', NULL, NULL, 594, GETDATE()),
  (N'覚ます', N'さます', N'Giác', N'Làm cho tỉnh lại', N'N3', NULL, NULL, 595, GETDATE()),
  (N'夜中', N'よなか', N'Dạ trung', N'Giữa đêm', N'N3', NULL, NULL, 596, GETDATE()),
  (N'が　眠る', N'ねむる', N'Miên', N'Ngủ', N'N3', NULL, NULL, 597, GETDATE()),
  (N'緊張する', N'きんちょうする', N'Khẩn trương', N'Căng thẳng, lo lắng', N'N3', NULL, NULL, 598, GETDATE()),
  (N'祈る', N'いのる', N'Kì', N'Cầu nguyện', N'N3', NULL, NULL, 599, GETDATE()),
  (N'祝う', N'いわう', N'Chúc', N'Chúc mừng', N'N3', NULL, NULL, 600, GETDATE()),
  (N'感じる', N'かんじる', N'Cảm', N'Cảm thấy', N'N3', NULL, NULL, 601, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'濃い', N'こい', N'Nùng', N'Nồng, đậm', N'N3', NULL, NULL, 602, GETDATE()),
  (N'薄い', N'うすい', N'Bạc', N'Nhạt', N'N3', NULL, NULL, 603, GETDATE()),
  (N'酸っぱい', N'すっぱい', N'Toan', N'Chua', N'N3', NULL, NULL, 604, GETDATE()),
  (N'臭い', N'くさい', N'Xú', N'Thối, tanh', N'N3', NULL, NULL, 605, GETDATE()),
  (N'可笑しい', N'かわいい', N'Khả tiếu', N'Buồn cười', N'N3', NULL, NULL, 606, GETDATE()),
  (N'格好いい', N'かっこいい', N'Cách hảo', N'Đẹp trai, bảnh bao', N'N3', NULL, NULL, 607, GETDATE()),
  (N'うまい', N'うまい', NULL, N'Ngon', N'N3', NULL, NULL, 608, GETDATE()),
  (N'親しい', N'したしい', N'Thân', N'Thân thiện, gần gũi', N'N3', NULL, NULL, 609, GETDATE()),
  (N'詳しい', N'くわしい', N'Tường', N'Tường tận, tỉ mỉ', N'N3', NULL, NULL, 610, GETDATE()),
  (N'細かい', N'こまかい', N'Tế', N'Chi tiết, chi li', N'N3', NULL, NULL, 611, GETDATE()),
  (N'浅い', N'あさい', N'Thiển', N'Nông, cạn', N'N3', NULL, NULL, 612, GETDATE()),
  (N'硬い/固い', N'かたい', N'Ngạch/Cố', N'Cứng, dai', N'N3', NULL, NULL, 613, GETDATE()),
  (N'温い', N'ぬるい', N'Ôn', N'Nguội', N'N3', NULL, NULL, 614, GETDATE()),
  (N'眩しい', N'まぶしい', N'Huyễn', N'Chói mắt, sáng chói', N'N3', NULL, NULL, 615, GETDATE()),
  (N'蒸し暑い', N'むしあつい', N'Chưng thử', N'Nóng ẩm', N'N3', NULL, NULL, 616, GETDATE()),
  (N'清潔（な）', N'せいけつ', N'Thanh khiết', N'Thanh khiết, sạch sẽ', N'N3', NULL, NULL, 617, GETDATE()),
  (N'新鮮（な）', N'しんせん', N'Tân tiến', N'Tươi, mới', N'N3', NULL, NULL, 618, GETDATE()),
  (N'豊か（な）', N'ゆたか', N'Phong', N'Giàu có', N'N3', NULL, NULL, 619, GETDATE()),
  (N'立派（な）', N'りっぱい', N'Lập phái', N'Siêu', N'N3', NULL, NULL, 620, GETDATE()),
  (N'正確（な）', N'せいかく', N'Chính xác', N'Chính xác', N'N3', NULL, NULL, 621, GETDATE()),
  (N'確か（な）', N'たしか', N'Xác', N'Xác thực', N'N3', NULL, NULL, 622, GETDATE()),
  (N'重要（な）', N'じゅうよう', N'Trọng yếu', N'Trọng yếu', N'N3', NULL, NULL, 623, GETDATE()),
  (N'必要（な）', N'ひつよう', N'Tất yếu', N'Cần thiết', N'N3', NULL, NULL, 624, GETDATE()),
  (N'勿体無い（な）', N'もったいない', N'Vật thể vô', N'Lãng phí, hoang phí', N'N3', NULL, NULL, 625, GETDATE()),
  (N'凄い', N'すごい', N'Thê', N'Giỏi, xuất sắc', N'N3', NULL, NULL, 626, GETDATE()),
  (N'酷い', N'ひどい', N'Khốc', N'Kinh khủng, khủng khiếp', N'N3', NULL, NULL, 627, GETDATE()),
  (N'激しい', N'はげしい', N'Kích', N'Mãnh liệt', N'N3', NULL, NULL, 628, GETDATE()),
  (N'そっくり（な）', N'そっくり（な）', NULL, N'Giống', N'N3', NULL, NULL, 629, GETDATE()),
  (N'急（な）', N'きゅう', NULL, N'Gấp', N'N3', NULL, NULL, 630, GETDATE()),
  (N'適当（な）', N'てきとう', N'Thích đương', N'Thích hợp, vừa phải', N'N3', NULL, NULL, 631, GETDATE()),
  (N'特別（な）', N'とくべつ', N'Đặc biệt', N'Đặc biệt', N'N3', NULL, NULL, 632, GETDATE()),
  (N'完全（な）', N'かんぜん', N'Hoàn toàn', N'Hoàn toàn', N'N3', NULL, NULL, 633, GETDATE()),
  (N'盛ん（な）', N'さかん', N'Thịnh', N'Thịnh vượng', N'N3', NULL, NULL, 634, GETDATE()),
  (N'様々（な）', N'さまざま', N'Dạng', N'Nhiều loại', N'N3', NULL, NULL, 635, GETDATE()),
  (N'可能（な）', N'かのう', N'Khả năng', N'Khả năng', N'N3', NULL, NULL, 636, GETDATE()),
  (N'不可能（な）', N'ふかのう', N'Bất khả năng', N'Không khả thi', N'N3', NULL, NULL, 637, GETDATE()),
  (N'基本的（な）', N'きほんてき', N'Cơ bản đích', N'Tính cơ bản', N'N3', NULL, NULL, 638, GETDATE()),
  (N'国際的（な）', N'こくさいてき', N'Quốc tế đích', N'Tính quốc tế', N'N3', NULL, NULL, 639, GETDATE()),
  (N'ばらばら（な）', N'ばらばら（な）', NULL, N'Bừa bộn, lung tung', N'N3', NULL, NULL, 640, GETDATE()),
  (N'ぼろぼろ（な）', N'ぼろぼろ（な）', NULL, N'Rách nát', N'N3', NULL, NULL, 641, GETDATE()),
  (N'読書する', N'どくしょ', N'Độc thư', N'Đọc sách', N'N3', NULL, NULL, 642, GETDATE()),
  (N'演奏', N'えんそう', N'Diễn tẫu', N'Trình diễn, biểu diễn', N'N3', NULL, NULL, 643, GETDATE()),
  (N'芸術', N'げいじゅつ', N'Nghệ thuật', N'Nghệ thuật', N'N3', NULL, NULL, 644, GETDATE()),
  (N'検査する', N'ちょうさする', N'Kiểm tra', N'Kiểm tra', N'N3', NULL, NULL, 645, GETDATE()),
  (N'胃', N'い', N'Vị', N'Dạ dày', N'N3', NULL, NULL, 646, GETDATE()),
  (N'血液', N'けつえき', N'Huyết dịch', N'Máu', N'N3', NULL, NULL, 647, GETDATE()),
  (N'流れる', N'ながれる', N'Lưu', N'Chảy, trôi đi', N'N3', NULL, NULL, 648, GETDATE()),
  (N'治療する', N'ちりょうする', N'Trị liệu', N'Trị liệu', N'N3', NULL, NULL, 649, GETDATE()),
  (N'症状', N'しょうじょう', N'Chứng trạng', N'Triệu chứng', N'N3', NULL, NULL, 650, GETDATE()),
  (N'鼻水', N'はなみず', N'Tị thủy', N'Nước mũi', N'N3', NULL, NULL, 651, GETDATE()),
  (N'予防する', N'よぼうする', N'Dự phòng', N'Dự phòng', N'N3', NULL, NULL, 652, GETDATE()),
  (N'栄養', N'えいよう', N'Vinh dưỡng', N'Dinh dưỡng', N'N3', NULL, NULL, 653, GETDATE()),
  (N'手術', N'しゅじゅつ', N'Thủ thuật', N'Phẫu thuật', N'N3', NULL, NULL, 654, GETDATE()),
  (N'死亡する', N'しぼうする', N'Tử vong', N'Tử vong', N'N3', NULL, NULL, 655, GETDATE()),
  (N'命', N'いのち', N'Mệnh', N'Cuộc sống', N'N3', NULL, NULL, 656, GETDATE()),
  (N'一生', N'いっしょう', N'Sinh', N'Cuộc đời, suốt đời', N'N3', NULL, NULL, 657, GETDATE()),
  (N'誤解する', N'ごかいする', N'Ngộ giải', N'Hiểu nhầm', N'N3', NULL, NULL, 658, GETDATE()),
  (N'後悔', N'こうかい', N'Hậu hối', N'Hối hận', N'N3', NULL, NULL, 659, GETDATE()),
  (N'訳', N'わけ', N'Dịch', N'Lý do', N'N3', NULL, NULL, 660, GETDATE()),
  (N'態度', N'たいど', N'Thái độ', N'Thái độ', N'N3', NULL, NULL, 661, GETDATE()),
  (N'癖', N'くせ', N'Phích', N'Thói quen', N'N3', NULL, NULL, 662, GETDATE()),
  (N'礼儀', N'れいぎ', N'Lễ nghi', N'Lễ nghi', N'N3', NULL, NULL, 663, GETDATE()),
  (N'文句', N'もんく', N'Văn cú', N'Kêu ca, phàn nàn', N'N3', NULL, NULL, 664, GETDATE()),
  (N'表情', N'ひょうじょう', N'Biểu tình', N'Biểu tình', N'N3', NULL, NULL, 665, GETDATE()),
  (N'表面', N'ひょうめん', N'Biểu diện', N'Bề ngoài, bề mặt', N'N3', NULL, NULL, 666, GETDATE()),
  (N'禁煙する', N'きんえんする', N'Cấm yên', N'Cấm hút thuốc', N'N3', NULL, NULL, 667, GETDATE()),
  (N'禁止する', N'きんしする', N'Cấm chỉ', N'Cấm', N'N3', NULL, NULL, 668, GETDATE()),
  (N'完成する', N'かんせいする', N'Hoàn thành', N'Hoàn thành', N'N3', NULL, NULL, 669, GETDATE()),
  (N'課題', N'かだい', N'Khóa đề', N'Chủ đề', N'N3', NULL, NULL, 670, GETDATE()),
  (N'例外', N'れいがい', N'Lệ ngoại', N'Ngoại lệ', N'N3', NULL, NULL, 671, GETDATE()),
  (N'基本', N'きほん', N'Cơ bản', N'Cơ bản', N'N3', NULL, NULL, 672, GETDATE()),
  (N'記録する', N'きろくする', N'Kí lục', N'Ghi chép, ghi lại', N'N3', NULL, NULL, 673, GETDATE()),
  (N'状態', N'じょうたい', N'Trạng thái', N'Trạng thái', N'N3', NULL, NULL, 674, GETDATE()),
  (N'出来事', N'できごと', N'Xuất lai sự', N'Việc đã xảy ra', N'N3', NULL, NULL, 675, GETDATE()),
  (N'場面', N'ばめん', N'Trường diện', N'Hiện trường, bối cảnh', N'N3', NULL, NULL, 676, GETDATE()),
  (N'機会', N'きかい', N'Cơ hội', N'Cơ hội', N'N3', NULL, NULL, 677, GETDATE()),
  (N'距離', N'きょり', N'Cự ly', N'Cư ly', N'N3', NULL, NULL, 678, GETDATE()),
  (N'提案する', N'ていあんする', N'Đề án', N'Đề xuất', N'N3', NULL, NULL, 679, GETDATE()),
  (N'やり取りする', N'やりとりする', N'Thủ', N'Trao đổi', N'N3', NULL, NULL, 680, GETDATE()),
  (N'知識', N'ちしき', N'Tri thức', N'Tri thức', N'N3', NULL, NULL, 681, GETDATE()),
  (N'実力', N'じつりょく', N'Thực lực', N'Thực lực', N'N3', NULL, NULL, 682, GETDATE()),
  (N'手段', N'しゅだん', N'Thủ đoạn', N'Phương pháp, thủ đoạn', N'N3', NULL, NULL, 683, GETDATE()),
  (N'代表する', N'だいひょうする', N'Đại biểu', N'Đại biểu', N'N3', NULL, NULL, 684, GETDATE()),
  (N'影響する', N'えいきょうする', N'Ảnh hưởng', N'Ảnh hưởng', N'N3', NULL, NULL, 685, GETDATE()),
  (N'効果', N'こうか', N'Hiệu quả', N'Hiệu quả', N'N3', NULL, NULL, 686, GETDATE()),
  (N'印象', N'いんしょう', N'Ấn tượng', N'Ấn tượng', N'N3', NULL, NULL, 687, GETDATE()),
  (N'印', N'しるし', N'Ấn', N'Dấu hiệu', N'N3', NULL, NULL, 688, GETDATE()),
  (N'合図', N'あいず', N'Hợp đồ', N'Dấu hiệu', N'N3', NULL, NULL, 689, GETDATE()),
  (N'共通する', N'きょうつうする', N'Cộng thông', N'Điểm chung', N'N3', NULL, NULL, 690, GETDATE()),
  (N'強調する', N'きょうちょうする', N'Cường điều', N'Nhấn mạnh', N'N3', NULL, NULL, 691, GETDATE()),
  (N'大事', N'だいじ', N'Đại sự', N'Quan trọng', N'N3', NULL, NULL, 692, GETDATE()),
  (N'説明する', N'せつめいする', N'Thuyết minh', N'Thuyết minh', N'N3', NULL, NULL, 693, GETDATE()),
  (N'省略する', N'しょうりゃくする', N'Tỉnh lược', N'Lược bỏ', N'N3', NULL, NULL, 694, GETDATE()),
  (N'詳しい', N'くわしい', N'Tường', N'Tường tận, cụ thể', N'N3', NULL, NULL, 695, GETDATE()),
  (N'挑戦する', N'ちょうせんする', N'Thiêu chiến', N'Khiêu chiến, thách thức', N'N3', NULL, NULL, 696, GETDATE()),
  (N'やる気', N'やるき', N'Khí', N'Có hứng thú làm', N'N3', NULL, NULL, 697, GETDATE()),
  (N'勇気', N'ゆうき', N'Dũng khí', N'Dũng khí', N'N3', NULL, NULL, 698, GETDATE()),
  (N'資格', N'しかく', N'Tư cách', N'Tư cách', N'N3', NULL, NULL, 699, GETDATE()),
  (N'弁護士', N'べんごし', N'Biện hộ sĩ', N'Luật sư', N'N3', NULL, NULL, 700, GETDATE()),
  (N'申請する', N'しんせいする', N'Thân thỉnh', N'Yêu cầu, thỉnh cầu', N'N3', NULL, NULL, 701, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'通帳', N'つうちょう', N'Thông trướng', N'Sổ tiết kiệm', N'N3', NULL, NULL, 702, GETDATE()),
  (N'貯金する', N'ちょきんする', N'Trữ kim', N'Tiết kiệm, dành dụm', N'N3', NULL, NULL, 703, GETDATE()),
  (N'本人', N'ほんにん', N'Bản nhân', N'Người chính', N'N3', NULL, NULL, 704, GETDATE()),
  (N'契約する', N'けいやくする', N'Khế ước', N'Hợp đồng', N'N3', NULL, NULL, 705, GETDATE()),
  (N'証明する', N'しょうめいする', N'Chứng minh', N'Chứng minh', N'N3', NULL, NULL, 706, GETDATE()),
  (N'変更する', N'へんこうする', N'Biến canh', N'Sửa đổi', N'N3', NULL, NULL, 707, GETDATE()),
  (N'保存する', N'ほぞんする', N'Bảo tồn', N'Bảo tồn', N'N3', NULL, NULL, 708, GETDATE()),
  (N'保護する', N'ほごする', N'Bảo hộ', N'Bảo hộ', N'N3', NULL, NULL, 709, GETDATE()),
  (N'郊外', N'こうがい', N'Giao ngoại', N'Ngoại ô', N'N3', NULL, NULL, 710, GETDATE()),
  (N'都心', N'としん', N'Đô tâm', N'Trung tâm', N'N3', NULL, NULL, 711, GETDATE()),
  (N'資源', N'しげん', N'Tư nguyên', N'Tài nguyên', N'N3', NULL, NULL, 712, GETDATE()),
  (N'有効', N'ゆうこう', N'Hữu hiệu', N'Hữu hiệu', N'N3', NULL, NULL, 713, GETDATE()),
  (N'不足する', N'ふそくする', N'Bất túc', N'Không đủ', N'N3', NULL, NULL, 714, GETDATE()),
  (N'平均する', N'へいきんする', N'Bình quân', N'Trung bình', N'N3', NULL, NULL, 715, GETDATE()),
  (N'割合', N'わりあい', N'Cát hợp', N'Tỉ lệ', N'N3', NULL, NULL, 716, GETDATE()),
  (N'商売する', N'しょうばいする', N'Thương mại', N'Thương mại', N'N3', NULL, NULL, 717, GETDATE()),
  (N'商品', N'しょうひん', N'Thương phẩm', N'Sản phẩm', N'N3', NULL, NULL, 718, GETDATE()),
  (N'質', N'しつ', N'Chất', N'Chất', N'N3', NULL, NULL, 719, GETDATE()),
  (N'型', N'かた', N'Hình', N'Mẫu, khuôn', N'N3', NULL, NULL, 720, GETDATE()),
  (N'生産する', N'せいさんする', N'Sinh sản', N'Sản xuất', N'N3', NULL, NULL, 721, GETDATE()),
  (N'農業', N'のうぎょう', N'Nông nghiệp', N'Nông nghiệp', N'N3', NULL, NULL, 722, GETDATE()),
  (N'消費する', N'しょうひする', N'Tiêu phí', N'Tiêu phí', N'N3', NULL, NULL, 723, GETDATE()),
  (N'物価', N'ぶっか', N'Vật giá', N'Giá cả', N'N3', NULL, NULL, 724, GETDATE()),
  (N'倒産する', N'とうさんする', N'Đảo sản', N'Phá sản', N'N3', NULL, NULL, 725, GETDATE()),
  (N'携帯', N'けいたい', N'Huề đới', N'Cầm tay', N'N3', NULL, NULL, 726, GETDATE()),
  (N'現代', N'げんだい', N'Hiện đại', N'Hiện đại', N'N3', NULL, NULL, 727, GETDATE()),
  (N'情報', N'じょうほう', N'Tình báo', N'Thông tin', N'N3', NULL, NULL, 728, GETDATE()),
  (N'世紀', N'せいき', N'Thế kỉ', N'Thế kỉ', N'N3', NULL, NULL, 729, GETDATE()),
  (N'文化', N'ぶんか', N'Văn hóa', N'Văn hóa', N'N3', NULL, NULL, 730, GETDATE()),
  (N'都市', N'とし', N'Đô thị', N'Thành phố', N'N3', NULL, NULL, 731, GETDATE()),
  (N'地方', N'ちほう', N'Địa phương', N'Địa phương', N'N3', NULL, NULL, 732, GETDATE()),
  (N'戦争する', N'せんそうする', N'Chiến tranh', N'Chiến tranh', N'N3', NULL, NULL, 733, GETDATE()),
  (N'平和', N'へいわ', N'Bình hòa', N'Hòa bình', N'N3', NULL, NULL, 734, GETDATE()),
  (N'が　上る', N'のぼる', N'Thượng', N'Leo lên', N'N3', NULL, NULL, 735, GETDATE()),
  (N'階段', N'かいだん', N'Giai đoạn', N'Cầu thang', N'N3', NULL, NULL, 736, GETDATE()),
  (N'坂', N'さか', N'Phản', N'Dốc', N'N3', NULL, NULL, 737, GETDATE()),
  (N'下る', N'くだる', N'Hạ', N'Đi xuống', N'N3', NULL, NULL, 738, GETDATE()),
  (N'が　進む', N'すすむ', N'Tiến', N'Tiến lên', N'N3', NULL, NULL, 739, GETDATE()),
  (N'進める', N'すすめる', NULL, N'Đi tiến lên', N'N3', NULL, NULL, 740, GETDATE()),
  (N'が　通る', N'とおる', N'Thông', N'Đi qua', N'N3', NULL, NULL, 741, GETDATE()),
  (N'通す', N'とおす', NULL, N'Xuyên qua', N'N3', NULL, NULL, 742, GETDATE()),
  (N'光', N'ひかり', N'Quang', N'Ánh sáng', N'N3', NULL, NULL, 743, GETDATE()),
  (N'布', N'ぬの', N'Bố', N'Vải', N'N3', NULL, NULL, 744, GETDATE()),
  (N'空気', N'くうき', N'Không khí', N'Không khí', N'N3', NULL, NULL, 745, GETDATE()),
  (N'が　越える/超える', N'こえる', N'Việt/Triệu', N'Vượt qua', N'N3', NULL, NULL, 746, GETDATE()),
  (N'が　過ぎる', N'すぎる', N'Quá', N'Quá', N'N3', NULL, NULL, 747, GETDATE()),
  (N'過ごす', N'すごす', N'Quá', N'Trải qua', N'N3', NULL, NULL, 748, GETDATE()),
  (N'が　移る', N'うつる', N'Di', N'Di chuyển', N'N3', NULL, NULL, 749, GETDATE()),
  (N'移す', N'うつす', N'Di', N'Chuyển', N'N3', NULL, NULL, 750, GETDATE()),
  (N'本社', N'ほんしゃ', N'Bản xã', N'Trụ sở chính', N'N3', NULL, NULL, 751, GETDATE()),
  (N'連れる', N'つれる', N'Liên', N'Dẫn, dắt', N'N3', NULL, NULL, 752, GETDATE()),
  (N'が　寄る', N'よる', N'Kỳ', N'Ghé thăm', N'N3', NULL, NULL, 753, GETDATE()),
  (N'寄せる', N'よせる', N'Kỳ', N'Ghé vào', N'N3', NULL, NULL, 754, GETDATE()),
  (N'奨学金', N'しょうがくきん', N'Tưởng học kim', N'Học bổng', N'N3', NULL, NULL, 755, GETDATE()),
  (N'成績', N'せいせき', N'Thành tích', N'Thành tích', N'N3', NULL, NULL, 756, GETDATE()),
  (N'与える', N'あたえる', N'Dữ', N'Cung cấp, đưa', N'N3', NULL, NULL, 757, GETDATE()),
  (N'得る', N'える', N'Đắc', N'Đạt được', N'N3', NULL, NULL, 758, GETDATE()),
  (N'が　向く', N'むく', N'Hướng', N'Đối diện', N'N3', NULL, NULL, 759, GETDATE()),
  (N'向ける', N'むける', N'Hướng', N'Quay, hướng đến', N'N3', NULL, NULL, 760, GETDATE()),
  (N'勧める', N'すすめる', N'Khuyến', N'Mời, rủ, gợi ý', N'N3', NULL, NULL, 761, GETDATE()),
  (N'薦める', N'すすめる', N'Tiến', N'Gợi ý, giới thiệu', N'N3', NULL, NULL, 762, GETDATE()),
  (N'任せる', N'まかせる', N'Nhiệm', N'Để cho ai làm gì', N'N3', NULL, NULL, 763, GETDATE()),
  (N'守る', N'まもる', N'Thủ', N'Giữ, tuân thủ', N'N3', NULL, NULL, 764, GETDATE()),
  (N'争う', N'あらそう', N'Tranh', N'Gây gổ, tranh nhau', N'N3', NULL, NULL, 765, GETDATE()),
  (N'望む', N'のぞむ', N'Vọng', N'Ước', N'N3', NULL, NULL, 766, GETDATE()),
  (N'信じる', N'しんじる', N'Tín', N'Tin tưởng', N'N3', NULL, NULL, 767, GETDATE()),
  (N'が　通じる', N'つうじる', N'Thông', N'Thông qua', N'N3', NULL, NULL, 768, GETDATE()),
  (N'飽く', N'あく', N'Bão', N'Chán', N'N3', NULL, NULL, 769, GETDATE()),
  (N'思いつく', N'おもいつく', N'Tư', N'Nghĩ', N'N3', NULL, NULL, 770, GETDATE()),
  (N'思いやる', N'おもいやる', N'Tư', N'Quan tâm, thông cảm', N'N3', NULL, NULL, 771, GETDATE()),
  (N'熱中する', N'ねっちゅうする', N'Nhiệt trung', N'Nghiện (karaoke)', N'N3', NULL, NULL, 772, GETDATE()),
  (N'暮らす', N'くらす', N'Mộ', N'Sinh sống', N'N3', NULL, NULL, 773, GETDATE()),
  (N'巻く', N'まく', N'Quyển', N'Quấn', N'N3', NULL, NULL, 774, GETDATE()),
  (N'結ぶ', N'むすぶ', N'Kết', N'Buộc', N'N3', NULL, NULL, 775, GETDATE()),
  (N'紐', N'ひも', N'Nữu', N'Dây', N'N3', NULL, NULL, 776, GETDATE()),
  (N'が　済む', N'すむ', N'Tế', N'Kết thúc', N'N3', NULL, NULL, 777, GETDATE()),
  (N'済ます', N'すます', N'Tế', N'Kết thúc', N'N3', NULL, NULL, 778, GETDATE()),
  (N'出来る', N'できる', N'Xuất lai', N'Hoàn thành, có thể', N'N3', NULL, NULL, 779, GETDATE()),
  (N'切れる', N'きれる', N'Thiết', N'Cắt, hết', N'N3', NULL, NULL, 780, GETDATE()),
  (N'切らす', N'きらす', N'Thiết', N'Hết mất tiêu', N'N3', NULL, NULL, 781, GETDATE()),
  (N'が　伝わる', N'つたわる', N'Truyền', N'Truyền đi', N'N3', NULL, NULL, 782, GETDATE()),
  (N'伝える', N'つたえる', N'Truyền', N'Truyền đi', N'N3', NULL, NULL, 783, GETDATE()),
  (N'が　続く', N'つづく', N'Tục', N'Tiếp tục', N'N3', NULL, NULL, 784, GETDATE()),
  (N'続ける', N'つづける', N'Tục', N'Tiếp tục', N'N3', NULL, NULL, 785, GETDATE()),
  (N'が　繋がる', N'つながる', N'Hệ', N'Kết nối', N'N3', NULL, NULL, 786, GETDATE()),
  (N'繋ぐ', N'つなぐ', N'Hệ', N'Kết nối', N'N3', NULL, NULL, 787, GETDATE()),
  (N'繋げる', N'つなげる', N'Hệ', N'Làm chặt thêm', N'N3', NULL, NULL, 788, GETDATE()),
  (N'伸びる', N'のびる', N'Thân', N'Cao lên, phát triển lên', N'N3', NULL, NULL, 789, GETDATE()),
  (N'伸ばす', N'のばす', N'Thân', N'Làm cao/phát triển lên', N'N3', NULL, NULL, 790, GETDATE()),
  (N'延びる', N'のびる', N'Duyên', N'Trì hoãn', N'N3', NULL, NULL, 791, GETDATE()),
  (N'延ばす', N'のばす', N'Duyên', N'Hoãn', N'N3', NULL, NULL, 792, GETDATE()),
  (N'が　重なる', N'かさなる', N'Trọng', N'Chồng lên', N'N3', NULL, NULL, 793, GETDATE()),
  (N'重ねる', N'かさねる', N'Trọng', N'Chồng', N'N3', NULL, NULL, 794, GETDATE()),
  (N'が　広がる', N'ひろがる', N'Quảng', N'Rộng', N'N3', NULL, NULL, 795, GETDATE()),
  (N'広げる', N'ひろげる', N'Quảng', N'Mở rộng', N'N3', NULL, NULL, 796, GETDATE()),
  (N'が　載る', N'のる', N'Tải', N'Lên, vừa', N'N3', NULL, NULL, 797, GETDATE()),
  (N'載せる', N'のせる', N'Tải', N'Cho lên, cho vào', N'N3', NULL, NULL, 798, GETDATE()),
  (N'が　揃う', N'そろう', N'Tiễn', N'Thu thập', N'N3', NULL, NULL, 799, GETDATE()),
  (N'揃える', N'そろえる', N'Tiễn', N'Tập hợp', N'N3', NULL, NULL, 800, GETDATE()),
  (N'が　纏まる', N'まとまる', N'Triền', N'Tập hợp, thống nhất', N'N3', NULL, NULL, 801, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'纏める', N'まとめる', N'Triền', N'Tập hợp', N'N3', NULL, NULL, 802, GETDATE()),
  (N'が　付く', N'つく', N'Phó', N'Dính, gắn, có', N'N3', NULL, NULL, 803, GETDATE()),
  (N'付ける', N'つける', N'Phó', N'Gắn, thêm vào', N'N3', NULL, NULL, 804, GETDATE()),
  (N'が　貯まる', N'たまる', N'Trữ', N'Tiết kiệm', N'N3', NULL, NULL, 805, GETDATE()),
  (N'貯める', N'ためる', N'Trữ', N'Tiết kiệm', N'N3', NULL, NULL, 806, GETDATE()),
  (N'が　交じる/混じる', N'まじる', N'Giao/Hỗn', N'Giao vào, lẫn vào', N'N3', NULL, NULL, 807, GETDATE()),
  (N'が　交ざる/混ざる', N'まざる', N'Giao/Hỗn', N'Lẫn vào', N'N3', NULL, NULL, 808, GETDATE()),
  (N'交ぜる/混ぜる', N'まぜる', N'Giao/Hỗn', N'Trộn vào', N'N3', NULL, NULL, 809, GETDATE()),
  (N'が　溶ける/解ける', N'とける', N'Dong/Giải', N'Giải quyết, giải đông', N'N3', NULL, NULL, 810, GETDATE()),
  (N'解く/溶く/溶かす', N'とく/とかす', N'Dong/Giải', N'Giải quyết, giải đông', N'N3', NULL, NULL, 811, GETDATE()),
  (N'含む', N'ふくむ', N'Hàm', N'Bao gồm', N'N3', NULL, NULL, 812, GETDATE()),
  (N'含める', N'ふくめる', N'Hàm', N'Bao gồm', N'N3', NULL, NULL, 813, GETDATE()),
  (N'が　抜ける', N'ぬける', N'Bạt', N'Tháo, tuột', N'N3', NULL, NULL, 814, GETDATE()),
  (N'抜く', N'ぬく', N'Bạt', N'Lấy ra', N'N3', NULL, NULL, 815, GETDATE()),
  (N'が　現れる', N'あらわれる', N'Hiện', N'Xuất hiện, hiện ra', N'N3', NULL, NULL, 816, GETDATE()),
  (N'現す', N'あらわす', N'Hiện', N'Đã xuất hiện', N'N3', NULL, NULL, 817, GETDATE()),
  (N'が　表れる', N'あらわれる', N'Biểu', N'Hiện ra', N'N3', NULL, NULL, 818, GETDATE()),
  (N'表す', N'あらわす', N'Biểu', N'Biểu thị, biểu lộ', N'N3', NULL, NULL, 819, GETDATE()),
  (N'が　散る', N'ちる', N'Tàn', N'Tàn', N'N3', NULL, NULL, 820, GETDATE()),
  (N'散らす', N'ちらす', N'Tàn', N'Tàn', N'N3', NULL, NULL, 821, GETDATE()),
  (N'差す', N'さす', N'Sai', N'Giương, giơ', N'N3', NULL, NULL, 822, GETDATE());

PRINT 'Seeded 821 JLPT N3 records.';
GO
