-- ============================================================
-- JLPT Vocabulary Seed: JLPT N4
-- Records: 968
-- Generated: 2026-07-01T16:37:00.248Z
-- ============================================================

USE JapaneseAI;
GO

SET NOCOUNT ON;

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'診る', N'みる', N'Chẩn', N'Xem, khám bệnh', N'N4', N'V', NULL, 1, GETDATE()),
  (N'探す、捜す', N'さがす', N'Thám, sưu', N'Tìm, tìm kiếm', N'N4', N'V', NULL, 2, GETDATE()),
  (N'に　遅れる', N'おくれる', N'Trì', N'Chậm, muộn', N'N4', N'V', NULL, 3, GETDATE()),
  (N'に　間に合う', N'まにあう', N'Gian hợp', N'Kịp', N'N4', N'V', NULL, 4, GETDATE()),
  (N'やる', N'やる', NULL, N'Làm', N'N4', N'V', NULL, 5, GETDATE()),
  (N'参加する', N'さんかする', N'Tham gia', N'Tham gia, dự', N'N4', N'V', NULL, 6, GETDATE()),
  (N'申し込む', N'もうしこむ', N'Thân nhập', N'Đăng kí', N'N4', N'A', NULL, 7, GETDATE()),
  (N'都合が良い', N'つごうがいい', N'Đô hợp lương', N'Có time', N'N4', N'A', NULL, 8, GETDATE()),
  (N'都合が悪い', N'つごうがわるい', N'Đô hợp ác', N'Không có time', N'N4', N'A', NULL, 9, GETDATE()),
  (N'気分が良い', N'きぶんがいい', N'Khí phân lương', N'Cảm thấy không tốt', N'N4', N'A', NULL, 10, GETDATE()),
  (N'気分が悪い', N'きぶんがわるい', N'Khí phân ác', N'Cảm thấy không tốt', N'N4', N'A', NULL, 11, GETDATE()),
  (N'新聞社', N'しんぶんしゃ', N'Tân văn xã', N'Tòa soạn báo', N'N4', N'N', NULL, 12, GETDATE()),
  (N'柔道', N'じゅうどう', N'Nhu đạo', N'Môn nhu đạo', N'N4', N'N', NULL, 13, GETDATE()),
  (N'運動会', N'うんどうかい', N'Chuyển động hội', N'Hội thi thể thao', N'N4', N'N', NULL, 14, GETDATE()),
  (N'場所', N'ばしょ', N'Trường sở', N'Địa điểm', N'N4', N'N', NULL, 15, GETDATE()),
  (N'～弁', N'べん', N'Biện, biền', N'Giọng, tiếng ~', N'N4', N'N', NULL, 16, GETDATE()),
  (N'今度', N'こんど', N'Kim độ', N'Lần tới', N'N4', N'N', NULL, 17, GETDATE()),
  (N'ずいぶん', N'ずいぶん', NULL, N'Khá, tương đối', N'N4', N'N', NULL, 18, GETDATE()),
  (N'直接', N'ちょくせつ', N'Trực tiếp', N'Trực tiếp', N'N4', N'N', NULL, 19, GETDATE()),
  (N'片付く', N'かたづく', N'Phiến phó', N'Được dọn dẹp', N'N4', N'V', NULL, 20, GETDATE()),
  (N'ごみ', N'ごみ', NULL, N'Rác', N'N4', N'N', NULL, 21, GETDATE()),
  (N'出す', N'だす', N'Xuất', N'Đổ, để (rác)', N'N4', N'V', NULL, 22, GETDATE()),
  (N'が　燃える', N'もえる', N'Nhiên', N'Cháy được', N'N4', N'V', NULL, 23, GETDATE()),
  (N'置き場', N'おきば', N'Trí trường', N'Nơi để', N'N4', N'N', NULL, 25, GETDATE()),
  (N'横', N'よこ', N'Hoành', N'Bên cạnh', N'N4', N'N', NULL, 26, GETDATE()),
  (N'瓶', N'びん', N'Bình', N'Cái chai', N'N4', N'N', NULL, 27, GETDATE()),
  (N'缶', N'かん', N'Hẫu/phữu', N'Cái lon', N'N4', N'N', NULL, 28, GETDATE()),
  (N'「お」湯', N'おゆ', N'Thang', N'Nước nóng', N'N4', N'N', NULL, 29, GETDATE()),
  (N'連絡する', N'れんらくする', N'Liên lạc', N'Liên lạc', N'N4', N'V', NULL, 30, GETDATE()),
  (N'困ったなあ', N'こまったなあ', N'Khốn', N'Làm thế nào đây!', N'N4', N'N', NULL, 31, GETDATE()),
  (N'電子メール', N'でんしメール', N'Điện', N'Thư điện tử', N'N4', N'N', NULL, 32, GETDATE()),
  (N'宇宙', N'うちゅう', N'Vũ trụ', N'Vũ trụ', N'N4', N'N', NULL, 33, GETDATE()),
  (N'怖い', N'こわい', N'Bố', N'Đáng sợ', N'N4', N'N', NULL, 34, GETDATE()),
  (N'宇宙船', N'うちゅうせん', N'Vũ trụ thuyền', N'Tàu vũ trụ', N'N4', N'N', NULL, 35, GETDATE()),
  (N'別の', N'べつの', N'Biệt', N'Khác', N'N4', N'N', NULL, 36, GETDATE()),
  (N'宇宙飛行士', N'うちゅうひこうし', N'Vũ trụ cơ hành sĩ', N'Nhà du hành vũ trụ', N'N4', N'N', NULL, 37, GETDATE()),
  (N'飼う', N'かう', N'Tự', N'Nuôi (động vật)', N'N4', N'V', NULL, 38, GETDATE()),
  (N'建てる', N'たてる', N'Kiến', N'Xây dựng, xây', N'N4', N'V', NULL, 39, GETDATE()),
  (N'走る', N'はしる', N'Tẩu', N'Chạy (trên đường)', N'N4', N'V', NULL, 40, GETDATE()),
  (N'取る', N'とる', N'Thủ', N'Xin (nghỉ)', N'N4', N'V', NULL, 41, GETDATE()),
  (N'見える', N'みえる', N'Kiến', N'Nhìn thấy', N'N4', N'V', NULL, 42, GETDATE()),
  (N'聞こえる', N'きこえる', N'Văn', N'Nghe thấy', N'N4', N'V', NULL, 43, GETDATE()),
  (N'できます', N'できます', NULL, N'Được xây dựng', N'N4', N'V', NULL, 44, GETDATE()),
  (N'開く', N'ひらく', N'Khai', N'Mở (lớp học)', N'N4', N'V', NULL, 45, GETDATE()),
  (N'鳥', N'とり', N'Điểu', N'Chim', N'N4', N'N', NULL, 46, GETDATE()),
  (N'声', N'こえ', N'Thanh', N'Tiếng, giọng (人)', N'N4', NULL, NULL, 47, GETDATE()),
  (N'波', N'なみ', N'Ba', N'Sóng biển', N'N4', NULL, NULL, 48, GETDATE()),
  (N'花火', N'はなび', N'Hoa hỏa', N'Pháo hoa', N'N4', NULL, NULL, 49, GETDATE()),
  (N'景色', N'けしき', N'Cảnh sắc', N'Phong cảnh', N'N4', NULL, NULL, 50, GETDATE()),
  (N'昼間', N'ひるま', N'Trú gian', N'Time ban ngày', N'N4', NULL, NULL, 51, GETDATE()),
  (N'昔', N'むかし', N'Tích', N'Ngày xưa', N'N4', NULL, NULL, 52, GETDATE()),
  (N'道具', N'どうぐ', N'Đạo cụ', N'Dụng cụ, công cụ', N'N4', NULL, NULL, 53, GETDATE()),
  (N'自動販売機', N'じどうはんばいき', N'Tự động phiến mại cơ', N'Máy bán hàng tự động', N'N4', NULL, NULL, 54, GETDATE()),
  (N'通信販売', N'つうしんはんばい', N'Thông tín phiến mại', N'Thương mại viễn thông', N'N4', NULL, NULL, 55, GETDATE()),
  (N'台所', N'だいどころ', N'Đài sở', N'Bếp', N'N4', NULL, NULL, 56, GETDATE()),
  (N'～教室', N'きょうしつ', N'Giáo thất', N'Lớp học', N'N4', NULL, NULL, 57, GETDATE()),
  (N'～後', N'ご', N'Hậu', N'Sau ~', N'N4', NULL, NULL, 58, GETDATE()),
  (N'～しか', N'～しか', NULL, N'Chỉ ~ (phủ định)', N'N4', NULL, NULL, 59, GETDATE()),
  (N'他の', N'ほかの', N'Tha', N'Khác', N'N4', NULL, NULL, 60, GETDATE()),
  (N'はっきり', N'はっきり', NULL, N'Rõ, rõ ràng', N'N4', NULL, NULL, 61, GETDATE()),
  (N'殆ど', N'ほとんど', N'Đãi', N'Hầu như, hầu hết', N'N4', NULL, NULL, 62, GETDATE()),
  (N'日曜大工', N'にちようだいく', N'Nhật diệu', N'Thợ mộc chủ nhật', N'N4', NULL, NULL, 63, GETDATE()),
  (N'本棚', N'ほんだな', N'Bản/bổn bằng', N'Giá sách', N'N4', NULL, NULL, 64, GETDATE()),
  (N'夢', N'ゆめ', N'Mộng', N'Giấc mơ', N'N4', NULL, NULL, 65, GETDATE()),
  (N'家', N'うち', N'Gia', N'Nhà', N'N4', NULL, NULL, 66, GETDATE()),
  (N'素晴らしい', N'すばらしい', N'Tố tình', N'Tuyệt vời', N'N4', NULL, NULL, 67, GETDATE()),
  (N'子供達', N'こどもたち', N'Tử cung đạt', N'Trẻ con', N'N4', NULL, NULL, 68, GETDATE()),
  (N'大好き（な）', N'だいすき', N'Đại hảo', N'Rất thích', N'N4', NULL, NULL, 69, GETDATE()),
  (N'漫画', N'まんが', N'Man/mạn họa/hoạch', N'Truyện tranh', N'N4', NULL, NULL, 70, GETDATE()),
  (N'主人公', N'しゅじんこう', N'Chủ nhân công', N'Nhân vật chính', N'N4', NULL, NULL, 71, GETDATE()),
  (N'形', N'かたち', N'Hình', N'Hình dạng', N'N4', NULL, NULL, 72, GETDATE()),
  (N'不思議（な）', N'ふしぎ', N'Bất tư nghị', N'Bí ẩn, kì thú', N'N4', NULL, NULL, 73, GETDATE()),
  (N'例えば', N'たとえば', N'Liệt', N'Ví dụ như', N'N4', NULL, NULL, 74, GETDATE()),
  (N'付ける', N'つける', N'Phó', N'Lắp, ghép thêm', N'N4', NULL, NULL, 75, GETDATE()),
  (N'自由に', N'じゆうに', N'Tự do', N'Tự do', N'N4', NULL, NULL, 76, GETDATE()),
  (N'空', N'そら', N'Không/khống', N'Bầu trời', N'N4', NULL, NULL, 77, GETDATE()),
  (N'飛ぶ', N'とぶ', N'Cơ', N'Bay được', N'N4', NULL, NULL, 78, GETDATE()),
  (N'自分', N'じぶん', N'Tự phân', N'Tự mình', N'N4', NULL, NULL, 79, GETDATE()),
  (N'将来', N'しょうらい', N'Tương lai', N'Tương lai', N'N4', NULL, NULL, 80, GETDATE()),
  (N'が　売れる', N'うれる', N'Mại', N'Được bán', N'N4', NULL, NULL, 81, GETDATE()),
  (N'踊る', N'おどる', N'Dược', N'Khiêu vũ, nhảy', N'N4', NULL, NULL, 82, GETDATE()),
  (N'噛む', N'かむ', N'Giảo', N'Nhai, cắn', N'N4', NULL, NULL, 83, GETDATE()),
  (N'選ぶ', N'えらぶ', N'Tuyển', N'Chọn', N'N4', NULL, NULL, 84, GETDATE()),
  (N'違う', N'ちがう', N'Vi', N'Khác', N'N4', NULL, NULL, 85, GETDATE()),
  (N'に　通う', N'かよう', N'Thông', N'Đi đi lại lại', N'N4', NULL, NULL, 86, GETDATE()),
  (N'メモします', N'メモします', NULL, N'Ghi chép', N'N4', NULL, NULL, 87, GETDATE()),
  (N'真面目', N'まじめ', N'Chân diện mục', N'Nghiêm túc', N'N4', NULL, NULL, 88, GETDATE()),
  (N'熱心', N'ねっしん', N'Nhiệt tâm', N'Nhiệt tình', N'N4', NULL, NULL, 89, GETDATE()),
  (N'優しい', N'やさしい', N'Ưu', N'Hiền lành', N'N4', NULL, NULL, 90, GETDATE()),
  (N'偉い', N'えらい', N'Vĩ', N'Vĩ đại', N'N4', NULL, NULL, 91, GETDATE()),
  (N'丁度いい', N'ちょうどいい', N'Đinh độ', N'Vừa đủ, vừa đúng', N'N4', NULL, NULL, 92, GETDATE()),
  (N'習慣', N'しゅうかん', N'Tập quán', N'Tập quán', N'N4', NULL, NULL, 93, GETDATE()),
  (N'経験', N'けいけん', N'Kinh nghiệm', N'Kinh nghiệm', N'N4', NULL, NULL, 94, GETDATE()),
  (N'力', N'ちから', N'Lực', N'Sức lực', N'N4', NULL, NULL, 95, GETDATE()),
  (N'に　人気', N'にんき', N'Nhân khí', N'Được hâm mộ', N'N4', NULL, NULL, 96, GETDATE()),
  (N'形', N'ちから', N'Hình', N'Hình dáng', N'N4', NULL, NULL, 97, GETDATE()),
  (N'色', N'いろ', N'Sắc', N'Màu sắc', N'N4', NULL, NULL, 98, GETDATE()),
  (N'味', N'あじ', N'Vị', N'Vị', N'N4', NULL, NULL, 99, GETDATE()),
  (N'品物', N'しなもの', N'Phẩm vật', N'Hàng hóa', N'N4', NULL, NULL, 100, GETDATE()),
  (N'値段', N'ねだん', N'Trị đoạn', N'Giá cả', N'N4', NULL, NULL, 101, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'給料', N'きゅうりょう', N'Cấp liệu', N'Lương', N'N4', NULL, NULL, 102, GETDATE()),
  (N'番組', N'ばんぐみ', N'Phiên tổ', N'Chương trình', N'N4', NULL, NULL, 103, GETDATE()),
  (N'小説', N'しょうせつ', N'Tiểu thuyết', N'Tiểu thuyết', N'N4', NULL, NULL, 104, GETDATE()),
  (N'小説家', N'しょうせつか', N'Tiểu thuyết gia', N'Tiểu thuyết gia', N'N4', NULL, NULL, 105, GETDATE()),
  (N'歌手', N'かしゅ', N'Ca thủ', N'Ca sĩ', N'N4', NULL, NULL, 106, GETDATE()),
  (N'管理人', N'かんりにん', N'Quản lý nhân', N'Người quản lý', N'N4', NULL, NULL, 107, GETDATE()),
  (N'息子', N'むすこ', N'Tức tử', N'Con trai (mình)', N'N4', NULL, NULL, 108, GETDATE()),
  (N'息子さん', N'むすこさん', NULL, N'Con trai (khác)', N'N4', NULL, NULL, 109, GETDATE()),
  (N'娘', N'むすめ', N'Nương', N'Con gái (mình)', N'N4', NULL, NULL, 110, GETDATE()),
  (N'娘さん', N'むすめさん', NULL, N'Con gái (khác)', N'N4', NULL, NULL, 111, GETDATE()),
  (N'自分', N'じぶん', N'Tự phân', N'Tự mình', N'N4', NULL, NULL, 112, GETDATE()),
  (N'将来', N'しょうらい', N'Tương lai', N'Tương lai', N'N4', NULL, NULL, 113, GETDATE()),
  (N'暫く', N'しばらく', N'Tạm', N'Một lúc, một lát', N'N4', NULL, NULL, 114, GETDATE()),
  (N'大抵', N'たいてい', N'Đại để', N'Thông thường', N'N4', NULL, NULL, 115, GETDATE()),
  (N'それに', N'それに', NULL, N'Thêm nữa', N'N4', NULL, NULL, 116, GETDATE()),
  (N'それで', N'それで', NULL, N'Thế nên', N'N4', NULL, NULL, 117, GETDATE()),
  (N'会話', N'かいわ', N'Hội thoại', N'Hội thoại', N'N4', NULL, NULL, 118, GETDATE()),
  (N'おしゃべりする', N'おしゃべりする', NULL, N'Nói chuyện', N'N4', NULL, NULL, 119, GETDATE()),
  (N'お知らせ', N'おしらせ', N'Tri', N'Bản thông báo', N'N4', NULL, NULL, 120, GETDATE()),
  (N'日にち', N'ひにち', N'Nhật', N'Ngày', N'N4', NULL, NULL, 121, GETDATE()),
  (N'土', N'ど', N'Thổ', N'Thứ bảy', N'N4', NULL, NULL, 122, GETDATE()),
  (N'体育館', N'たいいくかん', N'Thể dục quán', N'Nhà tập thể dục', N'N4', NULL, NULL, 123, GETDATE()),
  (N'無料', N'むりょう', N'Vô liệu', N'Miễn phí', N'N4', NULL, NULL, 124, GETDATE()),
  (N'が　開く', N'あく', N'Khai', N'Mở', N'N4', NULL, NULL, 125, GETDATE()),
  (N'が　閉まる', N'しまる', N'Bế', N'Đóng', N'N4', NULL, NULL, 126, GETDATE()),
  (N'が　つく', N'が　つく', NULL, N'Sáng', N'N4', NULL, NULL, 127, GETDATE()),
  (N'が　消える', N'きえる', N'Tiêu', N'Tắt', N'N4', NULL, NULL, 128, GETDATE()),
  (N'が　込む', N'こむ', N'Nhập', N'Đông, tắc', N'N4', NULL, NULL, 129, GETDATE()),
  (N'が　すく', N'が　すく', NULL, N'Vắng, thoáng', N'N4', NULL, NULL, 130, GETDATE()),
  (N'が　壊れる', N'こわれる', N'Hoại', N'Hỏng', N'N4', NULL, NULL, 131, GETDATE()),
  (N'が　割れる', N'われる', N'Cát', N'Vỡ', N'N4', NULL, NULL, 132, GETDATE()),
  (N'が　折れる', N'おれる', N'Triết', N'Gãy, gập', N'N4', NULL, NULL, 133, GETDATE()),
  (N'が　破れる', N'やぶれる', N'Phá', N'Rách', N'N4', NULL, NULL, 134, GETDATE()),
  (N'が　汚れる', N'よごれる', N'Ô', N'Bẩn', N'N4', NULL, NULL, 135, GETDATE()),
  (N'が　付く', N'つく', N'Phó', N'Có gắn', N'N4', NULL, NULL, 136, GETDATE()),
  (N'が　外れる', N'はずれる', N'Ngoại', N'Tuột, bung', N'N4', NULL, NULL, 137, GETDATE()),
  (N'が　止まる', N'とまる', N'Chỉ', N'Dừng', N'N4', NULL, NULL, 138, GETDATE()),
  (N'間違える', N'まちがえる', N'Gian vi', N'Nhầm, sai', N'N4', NULL, NULL, 139, GETDATE()),
  (N'落とす', N'おとす', N'Lạc', N'Đánh rơi', N'N4', NULL, NULL, 140, GETDATE()),
  (N'が　掛かる', N'かかる', N'Quải', N'Khóa', N'N4', NULL, NULL, 141, GETDATE()),
  (N'皿', N'さら', N'Mãnh', N'Đĩa', N'N4', NULL, NULL, 142, GETDATE()),
  (N'茶碗', N'ちゃわん', N'Trà', N'Bát', N'N4', NULL, NULL, 143, GETDATE()),
  (N'袋', N'ふくろ', N'Đại', N'Túi', N'N4', NULL, NULL, 144, GETDATE()),
  (N'財布', N'さいふ', N'Tài bố', N'Ví', N'N4', NULL, NULL, 145, GETDATE()),
  (N'枝', N'えだ', N'Chi', N'Cành cây', N'N4', NULL, NULL, 146, GETDATE()),
  (N'駅員', N'えきいん', N'Dịch viên', N'Nhân viên nhà ga', N'N4', NULL, NULL, 147, GETDATE()),
  (N'この辺', N'このへん', N'Biên', N'Xung quanh đây', N'N4', NULL, NULL, 148, GETDATE()),
  (N'～辺', N'へん', NULL, N'~ xung quanh', N'N4', NULL, NULL, 149, GETDATE()),
  (N'このくらい', N'このくらい', NULL, N'Khoảng ngần này', N'N4', NULL, NULL, 150, GETDATE()),
  (N'お先に　どうぞ', N'おさきにどうぞ', N'Tiên', N'Xin mời đi trước', N'N4', NULL, NULL, 151, GETDATE()),
  (N'今の電車', N'いまのでんしゃ', NULL, N'Đoàn tàu vừa rồi', N'N4', NULL, NULL, 152, GETDATE()),
  (N'忘れ物', N'わすれもの', N'Vong', N'Đồ để quên', N'N4', NULL, NULL, 153, GETDATE()),
  (N'～側', N'がわ', N'Trắc', N'Phía~, bên~', N'N4', NULL, NULL, 154, GETDATE()),
  (N'覚えていない', N'おぼえていない', N'Giác', N'Tôi không nhớ', N'N4', NULL, NULL, 155, GETDATE()),
  (N'網棚', N'あみだな', N'Võng bằng', N'Giá lưới/hành lý', N'N4', NULL, NULL, 156, GETDATE()),
  (N'確か', N'たしか', N'Xác', N'Nếu không nhầm thì', N'N4', NULL, NULL, 157, GETDATE()),
  (N'地震', N'じしん', N'Địa chấn', N'Động đất', N'N4', NULL, NULL, 158, GETDATE()),
  (N'壁', N'かべ', N'Bích', N'Bức tường', N'N4', NULL, NULL, 159, GETDATE()),
  (N'針', N'はり', N'Châm', N'Kim đồng hồ', N'N4', NULL, NULL, 160, GETDATE()),
  (N'指す', N'さす', N'Chỉ', N'Chỉ', N'N4', NULL, NULL, 161, GETDATE()),
  (N'倒れる', N'たおれる', N'Đảo', N'Đổ (cây)', N'N4', NULL, NULL, 162, GETDATE()),
  (N'西', N'にし', N'Tây', N'Phía tây', N'N4', NULL, NULL, 163, GETDATE()),
  (N'方', N'ほう', N'Phương', N'Hướng', N'N4', NULL, NULL, 164, GETDATE()),
  (N'貼る', N'はる', N'Thiếp', N'Dán, dán lên', N'N4', NULL, NULL, 165, GETDATE()),
  (N'掛ける', N'かける', N'Quải', N'Treo', N'N4', NULL, NULL, 166, GETDATE()),
  (N'飾る', N'かざる', N'Sức', N'Trang trí', N'N4', NULL, NULL, 167, GETDATE()),
  (N'並べる', N'ならべる', N'Tịnh', N'Xếp hàng', N'N4', NULL, NULL, 168, GETDATE()),
  (N'植える', N'うえる', N'Thực/trĩ', N'Trồng (cây)', N'N4', NULL, NULL, 169, GETDATE()),
  (N'戻す', N'もどす', N'Lệ', N'Đưa về, trả về', N'N4', NULL, NULL, 170, GETDATE()),
  (N'纏め', N'まとめ', N'Triền', N'Tóm lại, nhóm lại', N'N4', NULL, NULL, 171, GETDATE()),
  (N'片付ける', N'かたづける', N'Phiến phó', N'Dọn dẹp', N'N4', NULL, NULL, 172, GETDATE()),
  (N'しまう', N'しまう', NULL, N'Cất vào, để vào', N'N4', NULL, NULL, 173, GETDATE()),
  (N'決める', N'きめる', N'Quyết', N'Quyết định', N'N4', NULL, NULL, 174, GETDATE()),
  (N'知らせる', N'しらせる', N'Tri', N'Thông báo', N'N4', NULL, NULL, 175, GETDATE()),
  (N'相談する', N'そうだんする', N'Tương/tướng đàm', N'Trao đổi, bàn bạc', N'N4', NULL, NULL, 176, GETDATE()),
  (N'予習する', N'よしゅうする', N'Dự tập', N'Chuẩn bị bài mới', N'N4', NULL, NULL, 177, GETDATE()),
  (N'復習する', N'ふくしゅうする', N'Phục tập', N'Ôn tập', N'N4', NULL, NULL, 178, GETDATE()),
  (N'そのままにする', N'そのままにする', NULL, N'Giữ nguyên vị trí', N'N4', NULL, NULL, 179, GETDATE()),
  (N'授業', N'じゅぎょう', N'Thụ nghiệp', N'Giờ học', N'N4', NULL, NULL, 180, GETDATE()),
  (N'講義', N'こうぎ', N'Giảng nghĩa', N'Bài giảng', N'N4', NULL, NULL, 181, GETDATE()),
  (N'予定', N'よてい', N'Dự định', N'Kế hoạch, dự định', N'N4', NULL, NULL, 182, GETDATE()),
  (N'お知らせ', N'お知らせ', NULL, N'Tờ thông báo', N'N4', NULL, NULL, 183, GETDATE()),
  (N'案内書', N'あんないしょ', N'Án nội thư', N'Sách hướng dẫn', N'N4', NULL, NULL, 184, GETDATE()),
  (N'ゴミ箱', N'ゴミばこ', N'Tương/sương', N'Thùng rác', N'N4', NULL, NULL, 185, GETDATE()),
  (N'人形', N'にんぎょう', N'Nhân hình', N'Búp bê', N'N4', NULL, NULL, 186, GETDATE()),
  (N'花瓶', N'かびん', N'Hoa bình', N'Lọ hoa', N'N4', NULL, NULL, 187, GETDATE()),
  (N'鏡', N'かがみ', N'Kính', N'Cái gương', N'N4', NULL, NULL, 188, GETDATE()),
  (N'引き出し', N'ひきだし', N'Dẫn xuất', N'Ngăn kéo', N'N4', NULL, NULL, 189, GETDATE()),
  (N'玄関', N'げんかん', N'Huyền quan', N'Cửa vào', N'N4', NULL, NULL, 190, GETDATE()),
  (N'廊下', N'ろうか', N'Lang hạ', N'Hành lang', N'N4', NULL, NULL, 191, GETDATE()),
  (N'壁', N'かべ', N'Bích', N'Bức tường', N'N4', NULL, NULL, 192, GETDATE()),
  (N'池', N'いけ', N'Trì', N'Cái ao', N'N4', NULL, NULL, 193, GETDATE()),
  (N'交番', N'こうばん', N'Giao phiên', N'Trạm/bốt cảnh sát', N'N4', NULL, NULL, 194, GETDATE()),
  (N'元の所', N'もとのところ', N'Nguyên sở', N'Vị trí ban đầu', N'N4', NULL, NULL, 195, GETDATE()),
  (N'周り', N'まわり', N'Chu', N'Xung quanh', N'N4', NULL, NULL, 196, GETDATE()),
  (N'真ん中', N'まんなか', N'Chân trung', N'Ở giữa', N'N4', NULL, NULL, 197, GETDATE()),
  (N'隅', N'すみ', N'Ôi', N'Góc', N'N4', NULL, NULL, 198, GETDATE()),
  (N'～ほど', N'～ほど', NULL, N'Khoảng ~', N'N4', NULL, NULL, 199, GETDATE()),
  (N'予定表', N'よていひょう', N'Dự định biểu', N'Lịch, TKB', N'N4', NULL, NULL, 200, GETDATE()),
  (N'ご苦労様', N'ごくろうさま', N'Khổ lao/lạo dạng', N'A/c đã làm việc vất vả', N'N4', NULL, NULL, 201, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'希望', N'きぼう', N'Hi vọng', N'Hi vọng', N'N4', NULL, NULL, 202, GETDATE()),
  (N'丸い', N'まるい', N'Hoàn', N'Tròn', N'N4', NULL, NULL, 203, GETDATE()),
  (N'月', N'つき', N'Nguyệt', N'Mặt trăng', N'N4', NULL, NULL, 204, GETDATE()),
  (N'～ある', N'～ある', NULL, N'Có ~, một ~', N'N4', NULL, NULL, 205, GETDATE()),
  (N'地球', N'ちきゅう', N'Địa cầu', N'Trái đất', N'N4', NULL, NULL, 206, GETDATE()),
  (N'嬉しい', N'うれしい', N'Hi', N'Vui mừng', N'N4', NULL, NULL, 207, GETDATE()),
  (N'嫌（な）', N'いや', N'Hiềm', N'Không chấp nhận được, chán, ghét', N'N4', NULL, NULL, 208, GETDATE()),
  (N'すると', N'すると', NULL, N'Sau đó, tiếp đó', N'N4', NULL, NULL, 209, GETDATE()),
  (N'目が　覚める', N'めがさめる', N'Mục giác', N'Tỉnh giấc', N'N4', NULL, NULL, 210, GETDATE()),
  (N'が　始まる', N'はじまる', N'Thủy', N'Được bắt đầu', N'N4', NULL, NULL, 211, GETDATE()),
  (N'続ける', N'つづける', N'Tục', N'Tiếp tục', N'N4', NULL, NULL, 212, GETDATE()),
  (N'見つける', N'みつける', NULL, N'Tìm thấy', N'N4', NULL, NULL, 213, GETDATE()),
  (N'受ける', N'うける', N'Thụ/thọ', N'Thi, tham gia', N'N4', NULL, NULL, 214, GETDATE()),
  (N'に　入学する', N'にゅうがくする', N'Nhập học', N'Nhập học', N'N4', NULL, NULL, 215, GETDATE()),
  (N'卒業する', N'そつぎょうする', N'Tốt nghiệp', N'Tốt nghiệp', N'N4', NULL, NULL, 216, GETDATE()),
  (N'に　出席する', N'しゅっせきする', N'Xuất tịch', N'Tham dự', N'N4', NULL, NULL, 217, GETDATE()),
  (N'休憩する', N'きゅうけいする', N'Hưu khế', N'Nghỉ giải lao', N'N4', NULL, NULL, 218, GETDATE()),
  (N'連休', N'れんきゅう', N'Liên hưu', N'Ngày nghỉ dài', N'N4', NULL, NULL, 219, GETDATE()),
  (N'作文', N'さくぶん', N'Tác văn', N'Bài văn', N'N4', NULL, NULL, 220, GETDATE()),
  (N'展覧会', N'てんらんかい', N'Triển lãm hội', N'Triển lãm', N'N4', NULL, NULL, 221, GETDATE()),
  (N'結婚式', N'けっこんしき', N'Kết hôn thức', N'Lễ cưới', N'N4', NULL, NULL, 222, GETDATE()),
  (N'「お」葬式', N'おそうしき', N'Táng thức', N'Lễ tang', N'N4', NULL, NULL, 223, GETDATE()),
  (N'本社', N'ほんしゃ', N'Bản xã', N'Trụ sở chính', N'N4', NULL, NULL, 224, GETDATE()),
  (N'支店/　支社', N'してん/ししゃ', N'Chi điếm, chi xã', N'Chi nhánh', N'N4', NULL, NULL, 225, GETDATE()),
  (N'教会', N'きょうかい', N'Giáo hội', N'Nhà thờ', N'N4', NULL, NULL, 226, GETDATE()),
  (N'大学院', N'だいがくいん', N'Đại học viện', N'Cao học', N'N4', NULL, NULL, 227, GETDATE()),
  (N'動物園', N'どうぶつえん', N'Động vật viên', N'Vườn bách thú', N'N4', NULL, NULL, 228, GETDATE()),
  (N'温泉', N'おんせん', N'Ôn tuyền', N'Suối nước nóng', N'N4', NULL, NULL, 229, GETDATE()),
  (N'お客「さん」', N'おきゃく', N'Khách', N'Khách hàng', N'N4', NULL, NULL, 230, GETDATE()),
  (N'誰か', N'だれか', N'Thùy', N'Ai đó', N'N4', NULL, NULL, 231, GETDATE()),
  (N'～の方', N'のほう', N'Phương', N'Phía ~, hướng ~', N'N4', NULL, NULL, 232, GETDATE()),
  (N'ずっと', N'ずっと', NULL, N'Suốt, liền', N'N4', NULL, NULL, 233, GETDATE()),
  (N'残る', N'のこる', N'Tàn', N'ở lại, còn thiếu', N'N4', NULL, NULL, 234, GETDATE()),
  (N'月に', N'つきに', NULL, N'Một tháng', N'N4', NULL, NULL, 235, GETDATE()),
  (N'普通の', N'ふつうの', N'Phổ thông', N'Thông thường', N'N4', NULL, NULL, 236, GETDATE()),
  (N'村', N'むら', N'Thôn', N'Làng', N'N4', NULL, NULL, 237, GETDATE()),
  (N'映画館', N'えいがかん', N'Ánh họa quán', N'Rạp chiếu phim', N'N4', NULL, NULL, 238, GETDATE()),
  (N'嫌（な）', N'いや', N'Hiềm', N'Chán, ghét', N'N4', NULL, NULL, 239, GETDATE()),
  (N'空', N'そら', N'Không', N'Bầu trời', N'N4', NULL, NULL, 240, GETDATE()),
  (N'閉じる', N'とじる', N'Bế', N'Nhắm mắt', N'N4', NULL, NULL, 241, GETDATE()),
  (N'都会', N'とかい', N'Đô hội', N'Thành phố', N'N4', NULL, NULL, 242, GETDATE()),
  (N'自由に', N'じゆうに', N'Tự do', N'Tự do', N'N4', NULL, NULL, 243, GETDATE()),
  (N'世界中', N'せかいじゅう', N'Thế giới trung', N'Khắp thế giới', N'N4', NULL, NULL, 244, GETDATE()),
  (N'集まる', N'あつまる', N'Tập', N'Tập trung', N'N4', NULL, NULL, 245, GETDATE()),
  (N'美しい', N'うつくしい', N'Mĩ', N'Đẹp', N'N4', NULL, NULL, 246, GETDATE()),
  (N'自然', N'しぜん', N'Tự nhiên', N'Tự nhiên', N'N4', NULL, NULL, 247, GETDATE()),
  (N'素晴らしさ', N'すばらしさ', N'Tố tình', N'Tuyệt vời', N'N4', NULL, NULL, 248, GETDATE()),
  (N'気が　付く', N'きがつく', N'Khí phó', N'Để ý, nhận ra', N'N4', NULL, NULL, 249, GETDATE()),
  (N'運動する', N'えんどうする', N'Vận động', N'Vận động', N'N4', NULL, NULL, 250, GETDATE()),
  (N'成功する', N'せいこうする', N'Thành công', N'Thành công', N'N4', NULL, NULL, 251, GETDATE()),
  (N'に　失敗する', N'しっぱいする', N'Thất bại', N'Thất bại', N'N4', NULL, NULL, 252, GETDATE()),
  (N'に　合格する', N'ごうかくする', N'Hợp cách', N'Đỗ', N'N4', NULL, NULL, 253, GETDATE()),
  (N'戻る', N'もどる', N'Lệ', N'Quay lại', N'N4', NULL, NULL, 254, GETDATE()),
  (N'が　やむ', N'が　やむ', NULL, N'Tạnh (mưa)', N'N4', NULL, NULL, 255, GETDATE()),
  (N'晴れる', N'はれる', N'Tình', N'Nắng', N'N4', NULL, NULL, 256, GETDATE()),
  (N'曇る', N'くもる', N'Đàm', N'Mây mù, có mây', N'N4', NULL, NULL, 257, GETDATE()),
  (N'が　吹く', N'ふく', N'Xuy/xúy', N'Thổi (gió)', N'N4', NULL, NULL, 258, GETDATE()),
  (N'が　直る、治る', N'なおる', N'Trực, trị', N'Sửa, khỏi', N'N4', NULL, NULL, 259, GETDATE()),
  (N'が　続く', N'つづく', N'Tục', N'Tiếp tục (sốt)', N'N4', NULL, NULL, 260, GETDATE()),
  (N'引く', N'ひく', N'Dẫn', N'Bị (cảm)', N'N4', NULL, NULL, 261, GETDATE()),
  (N'冷やす', N'ひやす', N'Lãnh', N'Làm lạnh', N'N4', NULL, NULL, 262, GETDATE()),
  (N'心配（な）', N'しんぱい', N'Tâm phối', N'Lo lắng', N'N4', NULL, NULL, 263, GETDATE()),
  (N'十分（な）', N'じゅうぶん', N'Thập phân', N'Đầy đủ, đủ', N'N4', NULL, NULL, 264, GETDATE()),
  (N'可笑しい', N'おかしい', N'Khả tiếu', N'Buồn cười', N'N4', NULL, NULL, 265, GETDATE()),
  (N'煩い', N'うるさい', N'Phiền', N'Ồn ào', N'N4', NULL, NULL, 266, GETDATE()),
  (N'やけど', N'やけど', NULL, N'Bỏng', N'N4', NULL, NULL, 267, GETDATE()),
  (N'けが', N'けが', NULL, N'Thương', N'N4', NULL, NULL, 268, GETDATE()),
  (N'せき', N'せき', NULL, N'Ho', N'N4', NULL, NULL, 269, GETDATE()),
  (N'空', N'そら', N'Không', N'Bầu trời', N'N4', NULL, NULL, 270, GETDATE()),
  (N'太陽', N'たいよう', N'Thái dương', N'Mặt trời', N'N4', NULL, NULL, 271, GETDATE()),
  (N'星', N'ほし', N'Tinh', N'Ngôi sao', N'N4', NULL, NULL, 272, GETDATE()),
  (N'月', N'つき', N'Nguyệt', N'Mặt trăng', N'N4', NULL, NULL, 273, GETDATE()),
  (N'風', N'かぜ', N'Phong', N'Gió', N'N4', NULL, NULL, 274, GETDATE()),
  (N'北', N'きた', N'Bắc', N'Bắc', N'N4', NULL, NULL, 275, GETDATE()),
  (N'南', N'みなみ', N'Nam', N'Nam', N'N4', NULL, NULL, 276, GETDATE()),
  (N'西', N'にし', N'Tây', N'Tây', N'N4', NULL, NULL, 277, GETDATE()),
  (N'東', N'ひがし', N'Đông', N'Đông', N'N4', NULL, NULL, 278, GETDATE()),
  (N'水道', N'すいどう', N'Thủy đạo', N'Nước máy', N'N4', NULL, NULL, 279, GETDATE()),
  (N'今夜', N'こんや', N'Kim dạ', N'Đêm nay', N'N4', NULL, NULL, 280, GETDATE()),
  (N'夕方', N'ゆうがた', N'Tịch phương', N'Chiều tối', N'N4', NULL, NULL, 281, GETDATE()),
  (N'前', N'まえ', N'Trước', N'Trước', N'N4', NULL, NULL, 282, GETDATE()),
  (N'遅く', N'おそく', N'Trì', N'Muộn, khuya', N'N4', NULL, NULL, 283, GETDATE()),
  (N'もしかしたら', N'もしかしたら', NULL, N'Có khả năng', N'N4', NULL, NULL, 284, GETDATE()),
  (N'それは　いけない', N'それは　いけない', NULL, N'Thế thì thật không tốt', N'N4', NULL, NULL, 285, GETDATE()),
  (N'元気', N'げんき', N'Nguyên khí', N'Khỏe mạnh', N'N4', NULL, NULL, 286, GETDATE()),
  (N'胃', N'い', N'Vị', N'Dạ dày', N'N4', NULL, NULL, 287, GETDATE()),
  (N'働きすぎ', N'はたらきすぎ', N'Động', N'Làm việc quá sức', N'N4', NULL, NULL, 288, GETDATE()),
  (N'無理　をする', N'むりをする', N'Vô lý', N'Làm việc quá sức', N'N4', NULL, NULL, 289, GETDATE()),
  (N'ゆっくりする', N'ゆっくりする', NULL, N'Nghỉ ngơi', N'N4', NULL, NULL, 290, GETDATE()),
  (N'星占い', N'ほしうらない', N'Tinh chiêm', N'Bói sao', N'N4', NULL, NULL, 291, GETDATE()),
  (N'牡牛座', N'おうしざ', N'Mẫu ngưu tọa', N'sao Kim Ngưu', N'N4', NULL, NULL, 292, GETDATE()),
  (N'困る', N'こまる', N'Khốn', N'Khó xử, rắc rối', N'N4', NULL, NULL, 293, GETDATE()),
  (N'宝くじ', N'たからくじ', N'Bảo', N'Xổ số', N'N4', NULL, NULL, 294, GETDATE()),
  (N'が　当たる', N'あたる', N'Đương', N'Trúng ( xổ số)', N'N4', NULL, NULL, 295, GETDATE()),
  (N'健康', N'けんこう', N'Kiện khang', N'Sức khỏe', N'N4', NULL, NULL, 296, GETDATE()),
  (N'恋愛', N'れんあい', N'Luyến ái', N'Tình yêu', N'N4', NULL, NULL, 297, GETDATE()),
  (N'恋人', N'こいびと', N'Luyến', N'Người yêu', N'N4', NULL, NULL, 298, GETDATE()),
  (N'お金持ち', N'おかねもち', N'Kim trì', N'Người giàu có', N'N4', NULL, NULL, 299, GETDATE()),
  (N'逃げる', N'にげる', N'Đào', N'Bỏ chạy', N'N4', NULL, NULL, 300, GETDATE()),
  (N'騒ぐ', N'さわぐ', N'Tao', N'Làm ồn', N'N4', NULL, NULL, 301, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'諦める', N'あきらめる', N'Đế', N'Đầu hàng, từ bỏ', N'N4', NULL, NULL, 302, GETDATE()),
  (N'投げる', N'なげる', N'Đầu', N'Ném', N'N4', NULL, NULL, 303, GETDATE()),
  (N'守る', N'まもる', N'Thủ', N'Tuân thủ', N'N4', NULL, NULL, 304, GETDATE()),
  (N'上げる', N'あげる', N'Thượng', N'Nâng lên, tăng lên', N'N4', NULL, NULL, 305, GETDATE()),
  (N'下げる', N'さげる', N'Hạ', N'Giảm xuống', N'N4', NULL, NULL, 306, GETDATE()),
  (N'伝える', N'つたえる', N'Truyền', N'Truyền đạt', N'N4', NULL, NULL, 307, GETDATE()),
  (N'に　注意する', N'ちゅういする', N'Chú ý', N'Chú ý', N'N4', NULL, NULL, 308, GETDATE()),
  (N'外す', N'はずす', N'Ngoại', N'Rời, không có ở', N'N4', NULL, NULL, 309, GETDATE()),
  (N'駄目（な）', N'だめ', N'Đả mục', N'Không được', N'N4', NULL, NULL, 310, GETDATE()),
  (N'席', N'せき', N'Tịch', N'Cái ghế', N'N4', NULL, NULL, 311, GETDATE()),
  (N'洗濯機', N'せんたくき', N'Tẩy trạc cơ', N'Máy giặt', N'N4', NULL, NULL, 312, GETDATE()),
  (N'規則', N'きそく', N'Quy tắc', N'Quy tắc, kỉ luật', N'N4', NULL, NULL, 313, GETDATE()),
  (N'使用禁止', N'しようきんし', N'Sử dụng cấm chỉ', N'Cấm sử dụng', N'N4', NULL, NULL, 314, GETDATE()),
  (N'立入禁止', N'たちいりきんし', N'Lập nhập cấm chỉ', N'Cấm vào', N'N4', NULL, NULL, 315, GETDATE()),
  (N'入り口', N'いりぐち', N'Nhập khẩu', N'Cửa vào', N'N4', NULL, NULL, 316, GETDATE()),
  (N'出口', N'でぐち', N'Xuất khẩu', N'Cửa ra', N'N4', NULL, NULL, 317, GETDATE()),
  (N'非常口', N'ひじょうぐち', N'Phi thường khẩu', N'Cửa thoát hiểm', N'N4', NULL, NULL, 318, GETDATE()),
  (N'無料', N'むりょう', N'Vô liệu', N'Miễn phí', N'N4', NULL, NULL, 319, GETDATE()),
  (N'本日休業', N'ほんじつきゅうぎょう', N'Bản nhật hưu nghiệp', N'Hôm nay cửa hàng đóng cửa', N'N4', NULL, NULL, 320, GETDATE()),
  (N'営業中', N'えいぎょうちゅう', N'Doanh nghiệp', N'Đang mở cửa', N'N4', NULL, NULL, 321, GETDATE()),
  (N'使用中', N'しようちゅう', N'Sử dụng', N'Đang sử dụng', N'N4', NULL, NULL, 322, GETDATE()),
  (N'駐車違反', N'ちゅうしゃいはん', N'Trú xa vi phản', N'Đỗ xe trái phép', N'N4', NULL, NULL, 323, GETDATE()),
  (N'～以内', N'いない', N'Dĩ nội', N'Trong khoảng ~', N'N4', NULL, NULL, 324, GETDATE()),
  (N'警察', N'けいさつ', N'Cảnh sát', N'Cảnh sát', N'N4', NULL, NULL, 325, GETDATE()),
  (N'罰金', N'ばっきん', N'Phạt kim', N'Tiền phạt', N'N4', NULL, NULL, 326, GETDATE()),
  (N'電報', N'でんぽう', N'Điện báo', N'Điện báo', N'N4', NULL, NULL, 327, GETDATE()),
  (N'人々', N'ひとびと', NULL, N'Những người', N'N4', NULL, NULL, 328, GETDATE()),
  (N'急用', N'きゅうよう', N'Cấp dụng', N'Việc gấp', N'N4', NULL, NULL, 329, GETDATE()),
  (N'打つ', N'うつ', N'Đả', N'Đánh, gửi', N'N4', NULL, NULL, 330, GETDATE()),
  (N'電報代', N'でんぽうだい', N'Điện báo đại', N'Tiền điện báo', N'N4', NULL, NULL, 331, GETDATE()),
  (N'できるだけ', N'できるだけ', NULL, N'Cố gắng', N'N4', NULL, NULL, 332, GETDATE()),
  (N'短く', N'みじかく', N'Đoản', N'Ngắn gọn', N'N4', NULL, NULL, 333, GETDATE()),
  (N'例えば', N'たとえば', N'Liệt', N'Ví dụ như', N'N4', NULL, NULL, 334, GETDATE()),
  (N'危篤', N'キトク', N'Nguy đốc', N'Nguy kịch (bệnh)', N'N4', NULL, NULL, 335, GETDATE()),
  (N'重い病気', N'おもいびょうき', N'Trọng bệnh khí', N'Bệnh nặng', N'N4', NULL, NULL, 336, GETDATE()),
  (N'明日', N'あす', N'Minh nhật', N'Ngày mai', N'N4', NULL, NULL, 337, GETDATE()),
  (N'留守', N'るす', N'Lưu thủ', N'Vắng nhà', N'N4', NULL, NULL, 338, GETDATE()),
  (N'留守番', N'るすばん', N'Lưu thủ phiên', N'Trông nhà, giữ nhà', N'N4', NULL, NULL, 339, GETDATE()),
  (N'「お」祝い', N'おいわい', N'Chúc', N'Việc/vật mừng', N'N4', NULL, NULL, 340, GETDATE()),
  (N'亡くなる', N'なくなる', N'Vong', N'Chết', N'N4', NULL, NULL, 341, GETDATE()),
  (N'悲しみ', N'かなしみ', N'Bi', N'Đau buồn', N'N4', NULL, NULL, 342, GETDATE()),
  (N'利用する', N'りようする', N'Tiện dụng', N'Sử dụng, tận dụng', N'N4', NULL, NULL, 343, GETDATE()),
  (N'磨く', N'みがく', N'Ma', N'Mài, đánh (răng)', N'N4', NULL, NULL, 344, GETDATE()),
  (N'組み立てる', N'くみたてる', N'Tổ lập', N'Lắp đặt', N'N4', NULL, NULL, 345, GETDATE()),
  (N'折る', N'おる', N'Triết', N'Gấp, gập, bẻ gãy', N'N4', NULL, NULL, 346, GETDATE()),
  (N'つける', N'つける', NULL, N'Chấm (xì dầu)', N'N4', NULL, NULL, 347, GETDATE()),
  (N'が　見つかる', N'みつかる', NULL, N'Được tìm thấy', N'N4', NULL, NULL, 348, GETDATE()),
  (N'質問する', N'しつもんする', N'Chất vấn', N'Hỏi', N'N4', NULL, NULL, 349, GETDATE()),
  (N'細い', N'ほそい', N'Tế', N'Gầy', N'N4', NULL, NULL, 350, GETDATE()),
  (N'太い', N'ふとい', N'Thái', N'Béo', N'N4', NULL, NULL, 351, GETDATE()),
  (N'盆踊り', N'ぼんおどり', N'Bồn dược', N'Múa trong hội Bon', N'N4', NULL, NULL, 352, GETDATE()),
  (N'家具', N'かぐ', N'Gia cụ', N'Đồ dùng nội thất', N'N4', NULL, NULL, 353, GETDATE()),
  (N'説明書', N'せつめいしょ', N'Thuyết minh thư', N'Sách giải thích', N'N4', NULL, NULL, 354, GETDATE()),
  (N'図', N'ず', N'Đồ', N'Sơ đồ, hình vẽ', N'N4', NULL, NULL, 355, GETDATE()),
  (N'線', N'せん', N'Tuyến', N'Đường (kẻ)', N'N4', NULL, NULL, 356, GETDATE()),
  (N'矢印', N'やじるし', N'Thỉ ấn', N'Dấu mũi tên', N'N4', NULL, NULL, 357, GETDATE()),
  (N'黒', N'くろ', N'Hắc', N'Đen', N'N4', NULL, NULL, 358, GETDATE()),
  (N'白', N'しろ', N'Bạch', N'Trắng', N'N4', NULL, NULL, 359, GETDATE()),
  (N'赤', N'あか', N'Xích', N'Đỏ', N'N4', NULL, NULL, 360, GETDATE()),
  (N'青', N'あお', N'Thanh', N'Xanh da trời', N'N4', NULL, NULL, 361, GETDATE()),
  (N'紺', N'こん', N'Cám', N'Xanh lam', N'N4', NULL, NULL, 362, GETDATE()),
  (N'黄色', N'きいろ', N'Hoàng sắc', N'Vàng', N'N4', NULL, NULL, 363, GETDATE()),
  (N'茶色', N'ちゃいろ', N'Trà sắc', N'Nâu', N'N4', NULL, NULL, 364, GETDATE()),
  (N'昨夜', N'ゆうべ', N'Tác dạ', N'Đêm qua', N'N4', NULL, NULL, 365, GETDATE()),
  (N'さっき', N'さっき', NULL, N'Vừa rồi', N'N4', NULL, NULL, 366, GETDATE()),
  (N'茶道', N'さどう', N'Trà đạo', N'Trà đạo', N'N4', NULL, NULL, 367, GETDATE()),
  (N'お茶を　点てる', N'おちゃをたてる', N'Trà điểm', N'Pha/khuấy trà', N'N4', NULL, NULL, 368, GETDATE()),
  (N'先に', N'おさきに', NULL, N'Trước', N'N4', NULL, NULL, 369, GETDATE()),
  (N'載せる', N'のせる', N'Tải/tái', N'Để lên, đặt lên', N'N4', NULL, NULL, 370, GETDATE()),
  (N'苦い', N'にがい', N'Khổ', N'Đắng', N'N4', NULL, NULL, 371, GETDATE()),
  (N'おやこどんぶり', N'おやこどんぶり', NULL, N'Món oyako-don', N'N4', NULL, NULL, 372, GETDATE()),
  (N'材料', N'ざいりょう', N'Tài liệu', N'Nguyên liệu', N'N4', NULL, NULL, 373, GETDATE()),
  (N'―分', N'ぶん', NULL, N'-suất, -người', N'N4', NULL, NULL, 374, GETDATE()),
  (N'鳥肉', N'とりにく', N'Điểu nhục', N'Thịt gà', N'N4', NULL, NULL, 375, GETDATE()),
  (N'―個', N'こ', N'Cá', N'-cái, -quả (nhỏ)', N'N4', NULL, NULL, 376, GETDATE()),
  (N'たまねぎ', N'たまねぎ', NULL, N'Hành củ', N'N4', NULL, NULL, 377, GETDATE()),
  (N'調味料', N'ちょうみりょう', N'Điều vị liệu', N'Gia vị', N'N4', NULL, NULL, 378, GETDATE()),
  (N'鍋', N'なべ', N'Oa', N'Cái chảo, nồi', N'N4', NULL, NULL, 379, GETDATE()),
  (N'火に　かける', N'ひにかける', NULL, N'Đun', N'N4', NULL, NULL, 380, GETDATE()),
  (N'煮る', N'にる', N'Chử', N'Nấu', N'N4', NULL, NULL, 381, GETDATE()),
  (N'煮える', N'にえる', NULL, N'Đươc nấu', N'N4', NULL, NULL, 382, GETDATE()),
  (N'丼', N'どんぶり', NULL, N'Cái bát tô', N'N4', NULL, NULL, 383, GETDATE()),
  (N'が　咲く', N'さく', N'Tiếu', N'Nở (hoa)', N'N4', NULL, NULL, 384, GETDATE()),
  (N'が　変わる', N'かわる', N'Biến', N'Đổi (màu)', N'N4', NULL, NULL, 385, GETDATE()),
  (N'困る', N'こまる', N'Khốn', N'Rắc rối, khó xử', N'N4', NULL, NULL, 386, GETDATE()),
  (N'付ける', N'つける', NULL, N'Vẽ, đánh dấu', N'N4', NULL, NULL, 387, GETDATE()),
  (N'拾う', N'ひろう', N'Thập', N'Nhặt', N'N4', NULL, NULL, 388, GETDATE()),
  (N'が　かかる', N'が　かかる', NULL, N'Có (điện thoại)', N'N4', NULL, NULL, 389, GETDATE()),
  (N'楽（な）', N'らく', N'Lạc', N'Thoải mái', N'N4', NULL, NULL, 390, GETDATE()),
  (N'正しい', N'ただしい', N'Chính', N'Chính xác', N'N4', NULL, NULL, 391, GETDATE()),
  (N'珍しい', N'めずらしい', N'Trân', N'Hiếm', N'N4', NULL, NULL, 392, GETDATE()),
  (N'向こう', N'むこう', N'Hướng', N'Bên kia', N'N4', NULL, NULL, 393, GETDATE()),
  (N'島', N'しま', N'Đảo', N'Đảo', N'N4', NULL, NULL, 394, GETDATE()),
  (N'村', N'むら', N'Thôn', N'Làng', N'N4', NULL, NULL, 395, GETDATE()),
  (N'港', N'みなと', N'Cảng', N'Cảng, bến cảng', N'N4', NULL, NULL, 396, GETDATE()),
  (N'近所', N'きんじょ', N'Cận sở', N'Hàng xóm', N'N4', NULL, NULL, 397, GETDATE()),
  (N'屋上', N'おくじょう', N'Ốc thượng', N'Mái nhà, nóc nhà', N'N4', NULL, NULL, 398, GETDATE()),
  (N'海外', N'かいがい', N'Hải ngoại', N'Nước ngoài', N'N4', NULL, NULL, 399, GETDATE()),
  (N'山登り', N'やまのぼり', N'Sơn đăng', N'Leo núi', N'N4', NULL, NULL, 400, GETDATE()),
  (N'機会', N'きかい', N'Cơ hội', N'Cơ hội', N'N4', NULL, NULL, 401, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'許可', N'きょか', N'Hứa khả', N'Giấy phép', N'N4', NULL, NULL, 402, GETDATE()),
  (N'丸', N'まる', N'Hoàn', N'Tròn, vòng tròn', N'N4', NULL, NULL, 403, GETDATE()),
  (N'操作', N'そうさ', N'Thao tác', N'Thao tác', N'N4', NULL, NULL, 404, GETDATE()),
  (N'方法', N'ほうほう', N'Phương pháp', N'Phương pháp', N'N4', NULL, NULL, 405, GETDATE()),
  (N'設備', N'せつび', N'Thiết bị', N'Thiết bị', N'N4', NULL, NULL, 406, GETDATE()),
  (N'紐', N'ひも', N'Nữu', N'Sợi dây', N'N4', NULL, NULL, 407, GETDATE()),
  (N'蓋', N'ふた', N'Cái', N'Cái nắp', N'N4', NULL, NULL, 408, GETDATE()),
  (N'葉', N'は', N'Diệp', N'Lá', N'N4', NULL, NULL, 409, GETDATE()),
  (N'曲', N'きょく', N'Khúc', N'Bản nhạc', N'N4', NULL, NULL, 410, GETDATE()),
  (N'楽しみ', N'たのしみ', NULL, N'Niềm vui', N'N4', NULL, NULL, 411, GETDATE()),
  (N'もっと', N'もっと', NULL, N'Hơn, nữa', N'N4', NULL, NULL, 412, GETDATE()),
  (N'初めに', N'はじめに', N'Sơ', N'Đầu tiên, trước hết', N'N4', NULL, NULL, 413, GETDATE()),
  (N'それなら', N'それなら', NULL, N'Vậy thì ~', N'N4', NULL, NULL, 414, GETDATE()),
  (N'夜行バス', N'やこうバス', N'Dạ hành', N'Xe bus chạy đêm', N'N4', NULL, NULL, 415, GETDATE()),
  (N'旅行社', N'りょこうしゃ', N'Lữ hành xã', N'Công ty du lịch', N'N4', NULL, NULL, 416, GETDATE()),
  (N'詳しい', N'くわしい', N'Tường', N'Cụ thể, chi tiết', N'N4', NULL, NULL, 417, GETDATE()),
  (N'スキー場', N'スキーじょう', NULL, N'Bãi trượt tuyết', N'N4', NULL, NULL, 418, GETDATE()),
  (N'朱', N'しゅ', N'Chu/châu', N'Đỏ, màu đỏ', N'N4', NULL, NULL, 419, GETDATE()),
  (N'交わる', N'まじわる', N'Giao', N'Giao lưu với, quan hệ với', N'N4', NULL, NULL, 420, GETDATE()),
  (N'諺', N'ことわざ', N'Ngạn', N'Tục ngữ, ngạn ngữ', N'N4', NULL, NULL, 421, GETDATE()),
  (N'仲良くする', N'なかよくする', N'Trọng lương', N'Quan hệ tốt với, chơi thân với', N'N4', NULL, NULL, 422, GETDATE()),
  (N'必要（な）', N'ひつよう', N'Tất yếu', N'Cần thiết', N'N4', NULL, NULL, 423, GETDATE()),
  (N'が　届く', N'とどく', N'Giới', N'Được gửi đến', N'N4', NULL, NULL, 424, GETDATE()),
  (N'に　出る', N'でる', NULL, N'Tham gia, tham dự', N'N4', NULL, NULL, 425, GETDATE()),
  (N'打つ', N'うつ', N'Đả', N'Đánh (máy chữ)', N'N4', NULL, NULL, 426, GETDATE()),
  (N'貯金する', N'ちょきんする', N'Trữ kim', N'Tiền tiết kiệm', N'N4', NULL, NULL, 427, GETDATE()),
  (N'太る', N'ふとる', N'Thái', N'Béo lên', N'N4', NULL, NULL, 428, GETDATE()),
  (N'痩せる', N'やせる', N'Sấu', N'Gầy đi', N'N4', NULL, NULL, 429, GETDATE()),
  (N'過ぎる', N'すぎる', N'Quá', N'Quá, qua', N'N4', NULL, NULL, 430, GETDATE()),
  (N'に　慣れる', N'なれる', N'Quán', N'Quen', N'N4', NULL, NULL, 431, GETDATE()),
  (N'硬い', N'かたい', N'Ngạnh', N'Cứng', N'N4', NULL, NULL, 432, GETDATE()),
  (N'軟らかい', N'やわらかい', N'Nhuyễn', N'Mềm', N'N4', NULL, NULL, 433, GETDATE()),
  (N'電子～', N'でんし', NULL, N'~ điện tử', N'N4', NULL, NULL, 434, GETDATE()),
  (N'携帯～', N'けいたい', N'Huề đới/đái', N'~ cầm tay', N'N4', NULL, NULL, 435, GETDATE()),
  (N'工場', N'こうじょう', N'Công trường', N'Nhà máy', N'N4', NULL, NULL, 436, GETDATE()),
  (N'健康', N'けんこう', N'Kiện khang', N'Sức khỏe', N'N4', NULL, NULL, 437, GETDATE()),
  (N'剣道', N'けんどう', N'Kiếm đạo', N'Kiếm đạo', N'N4', NULL, NULL, 438, GETDATE()),
  (N'毎週', N'まいしゅう', N'Mỗi chu', N'Hàng tuần', N'N4', NULL, NULL, 439, GETDATE()),
  (N'毎月', N'まいつき', N'Mỗi nguyệt', N'Hàng tháng', N'N4', NULL, NULL, 440, GETDATE()),
  (N'毎年', N'まいとし', N'Mỗi niên', N'Hàng năm', N'N4', NULL, NULL, 441, GETDATE()),
  (N'やっと', N'やっと', NULL, N'Cuối cùng thì ~', N'N4', NULL, NULL, 442, GETDATE()),
  (N'かなり', N'かなり', NULL, N'Khá, tương đối', N'N4', NULL, NULL, 443, GETDATE()),
  (N'必ず', N'かならず', N'Tất', N'Nhất định', N'N4', NULL, NULL, 444, GETDATE()),
  (N'絶対に', N'ぜったいに', N'Tuyệt đối', N'Tuyệt đối', N'N4', NULL, NULL, 445, GETDATE()),
  (N'上手に', N'じょうずに', N'Thượng thủ', N'Giỏi, khéo', N'N4', NULL, NULL, 446, GETDATE()),
  (N'できるだけ', N'できるだけ', NULL, N'Cố gắng', N'N4', NULL, NULL, 447, GETDATE()),
  (N'この頃', N'このごろ', N'Khoảnh', N'Gần dây', N'N4', NULL, NULL, 448, GETDATE()),
  (N'～ずつ', N'～ずつ', NULL, N'Từng ~, một ~', N'N4', NULL, NULL, 449, GETDATE()),
  (N'そのほうが～', N'そのほうが～', NULL, N'Như thế ~ hơn', N'N4', NULL, NULL, 450, GETDATE()),
  (N'お客様', N'おきゃくさま', N'Khách dạng', N'Quý khách', N'N4', NULL, NULL, 451, GETDATE()),
  (N'特別（な）', N'とくべつ', N'Đặc biệt', N'Đặc biệt', N'N4', NULL, NULL, 452, GETDATE()),
  (N'していらっしゃいます', N'していらっしゃいます', NULL, N'Đang làm ( kính ngữ)', N'N4', NULL, NULL, 453, GETDATE()),
  (N'水泳', N'すいえい', N'Thủy vịnh', N'Bơi, môn bơi', N'N4', NULL, NULL, 454, GETDATE()),
  (N'～とか、～とか', N'～とか、～とか', NULL, N'~, ~, v.v.', N'N4', NULL, NULL, 455, GETDATE()),
  (N'気持ち', N'きもち', N'Khí trì', N'Cảm giác', N'N4', NULL, NULL, 456, GETDATE()),
  (N'乗り物', N'のりもの', N'Thừa vật', N'Phương tiện đi lại', N'N4', NULL, NULL, 457, GETDATE()),
  (N'歴史', N'れきし', N'Lịch sử', N'Lịch sử', N'N4', NULL, NULL, 458, GETDATE()),
  (N'―世紀', N'せいき', N'Thế kỷ', N'Thế kỷ -', N'N4', NULL, NULL, 459, GETDATE()),
  (N'遠く', N'はやく', N'Viễn', N'Xa, ở xa', N'N4', NULL, NULL, 460, GETDATE()),
  (N'汽車', N'きしゃ', N'Khí xa', N'Tàu hỏa chạy bằng hơi nước', N'N4', NULL, NULL, 461, GETDATE()),
  (N'汽船', N'きせん', N'Khí thuyền', N'Thuyền chạy bằng hơi nước', N'N4', NULL, NULL, 462, GETDATE()),
  (N'大勢の', N'おおぜいの', N'Đại thế', N'Nhiều (người)', N'N4', NULL, NULL, 463, GETDATE()),
  (N'運ぶ', N'はきぶ', N'Vận', N'Vận chuyển', N'N4', NULL, NULL, 464, GETDATE()),
  (N'飛ぶ', N'とぶ', N'Cơ', N'Bay', N'N4', NULL, NULL, 465, GETDATE()),
  (N'安全（な）', N'あんぜん', N'An toàn', N'An toàn', N'N4', NULL, NULL, 466, GETDATE()),
  (N'宇宙', N'うちゅう', N'Vũ trụ', N'Vũ trụ', N'N4', NULL, NULL, 467, GETDATE()),
  (N'地球', N'ちきゅう', N'Địa cầu', N'Trái đất', N'N4', NULL, NULL, 468, GETDATE()),
  (N'褒める', N'ほめる', N'Bao', N'Khen', N'N4', NULL, NULL, 469, GETDATE()),
  (N'しかる', N'しかる', NULL, N'Mắng', N'N4', NULL, NULL, 470, GETDATE()),
  (N'誘う', N'さそう', N'Dụ', N'Mời, rủ', N'N4', NULL, NULL, 471, GETDATE()),
  (N'起こす', N'おこす', N'Khởi', N'Đánh thức', N'N4', NULL, NULL, 472, GETDATE()),
  (N'招待する', N'しょうたいする', N'Chiêu đãi', N'Chiêu đãi, mời', N'N4', NULL, NULL, 473, GETDATE()),
  (N'頼む', N'たのむ', N'Lại', N'Nhờ vả', N'N4', NULL, NULL, 474, GETDATE()),
  (N'に　注意する', N'ちゅういする', N'Chú ý', N'Chú ý', N'N4', NULL, NULL, 475, GETDATE()),
  (N'盗る', N'とる', N'Đạo', N'Ăn trộm', N'N4', NULL, NULL, 476, GETDATE()),
  (N'踏む', N'ふむ', N'Đạp', N'Giẫm lên/vào', N'N4', NULL, NULL, 477, GETDATE()),
  (N'壊す', N'こわす', N'Hoại', N'Làm hỏng', N'N4', NULL, NULL, 478, GETDATE()),
  (N'汚す', N'よごす', N'Ô', N'Làm bẩn', N'N4', NULL, NULL, 479, GETDATE()),
  (N'行う', N'おこなう', N'Hành', N'Tiến hành, tổ chức', N'N4', NULL, NULL, 480, GETDATE()),
  (N'輸出する', N'ゆしゅつする', N'Thâu xuất', N'Xuất khẩu', N'N4', NULL, NULL, 481, GETDATE()),
  (N'輸入する', N'ゆにゅうする', N'Thâu nhập', N'Nhập khẩu', N'N4', NULL, NULL, 482, GETDATE()),
  (N'翻訳する', N'ほんやくする', N'Phiên dịch', N'Biên dịch', N'N4', NULL, NULL, 483, GETDATE()),
  (N'発明する', N'はつめいする', N'Phát minh', N'Phát minh', N'N4', NULL, NULL, 484, GETDATE()),
  (N'発見する', N'はっけんする', N'Phát kiến', N'Phát kiến', N'N4', NULL, NULL, 485, GETDATE()),
  (N'設計する', N'せっけいする', N'Thiết kế', N'Thiết kế', N'N4', NULL, NULL, 486, GETDATE()),
  (N'米', N'こめ', N'Mễ', N'Gạo', N'N4', NULL, NULL, 487, GETDATE()),
  (N'麦', N'むぎ', N'Mạch', N'Lúa mạch', N'N4', NULL, NULL, 488, GETDATE()),
  (N'石油', N'せきゆ', N'Thạch du', N'Dầu mỏ', N'N4', NULL, NULL, 489, GETDATE()),
  (N'原料', N'げんりょう', N'Nguyên liệu', N'Nguyên liệu', N'N4', NULL, NULL, 490, GETDATE()),
  (N'泥棒', N'どろぼう', N'Nê bổng', N'Kẻ trộm', N'N4', NULL, NULL, 491, GETDATE()),
  (N'警官', N'けいかん', N'Cảnh quan', N'Cảnh sát', N'N4', NULL, NULL, 492, GETDATE()),
  (N'建築家', N'けんちくか', N'Kiến trúc gia', N'Kiến trúc sư', N'N4', NULL, NULL, 493, GETDATE()),
  (N'科学者', N'かがくしゃ', N'Khoa học giả', N'Nhà khoa học', N'N4', NULL, NULL, 494, GETDATE()),
  (N'漫画', N'まんが', N'Man họa', N'Truyện tranh', N'N4', NULL, NULL, 495, GETDATE()),
  (N'世界中', N'せかいじゅう', N'Thế giới trung', N'Khắp thế giới', N'N4', NULL, NULL, 496, GETDATE()),
  (N'～に　よって', N'～に　よって', NULL, N'Do ~', N'N4', NULL, NULL, 497, GETDATE()),
  (N'埋め立てる', N'うめたてる', N'Mai lập', N'Lấp (biển)', N'N4', NULL, NULL, 498, GETDATE()),
  (N'技術', N'ぎじゅつ', N'Kỹ thuật', N'Kỹ thuật', N'N4', NULL, NULL, 499, GETDATE()),
  (N'土地', N'とち', N'Thổ địa', N'Đất, diện tích đất', N'N4', NULL, NULL, 500, GETDATE()),
  (N'騒音', N'そうおん', N'Tao âm', N'Tiếng ồn', N'N4', NULL, NULL, 501, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'利用する', N'りようする', N'Tiện dụng', N'Sử dụng, tận dụng', N'N4', NULL, NULL, 502, GETDATE()),
  (N'―世紀', N'せいき', N'Thế kỉ', N'Thế kỉ -', N'N4', NULL, NULL, 503, GETDATE()),
  (N'豪華（な）', N'ごうか', N'Hào hoa', N'Hào hoa, sang trọng', N'N4', NULL, NULL, 504, GETDATE()),
  (N'彫刻', N'ちょうこく', N'Điêu khắc', N'Điêu khắc', N'N4', NULL, NULL, 505, GETDATE()),
  (N'眠る', N'ねむる', N'Miên', N'Ngủ', N'N4', NULL, NULL, 506, GETDATE()),
  (N'彫る', N'ほる', N'Điêu', N'Khắc', N'N4', NULL, NULL, 507, GETDATE()),
  (N'仲間', N'なかま', N'Trọng gian', N'Bạn bè, đồng nghiệp', N'N4', NULL, NULL, 508, GETDATE()),
  (N'そのあと～', N'そのあと～', NULL, N'Sau đó ~', N'N4', NULL, NULL, 509, GETDATE()),
  (N'一生懸命', N'いっしょうけんめい', N'Sinh huyền mệnh', N'Chăm chỉ, miệt mài', N'N4', NULL, NULL, 510, GETDATE()),
  (N'鼠', N'ねずみ', N'ねずみ', N'Con chuột', N'N4', NULL, NULL, 511, GETDATE()),
  (N'一匹も　いない', N'いっぴきもいない', N'Thất', N'Không có con nào cả', N'N4', NULL, NULL, 512, GETDATE()),
  (N'育てる', N'そだてる', N'Dục', N'Nuôi, trồng', N'N4', NULL, NULL, 513, GETDATE()),
  (N'運ぶ', N'はこぶ', N'Vận', N'Vận chuyển', N'N4', NULL, NULL, 514, GETDATE()),
  (N'亡くなる', N'なくなる', N'Vong', N'Chết', N'N4', NULL, NULL, 515, GETDATE()),
  (N'入院する', N'にゅういんする', N'Nhập viện', N'Nhập viện', N'N4', NULL, NULL, 516, GETDATE()),
  (N'退院する', N'たいいんする', N'Thoái viện', N'Xuất viện', N'N4', NULL, NULL, 517, GETDATE()),
  (N'入れる', N'いれる', NULL, N'Bật', N'N4', NULL, NULL, 518, GETDATE()),
  (N'切る', N'きる', N'Thiết', N'Tắt', N'N4', NULL, NULL, 519, GETDATE()),
  (N'掛ける', N'かける', N'Quải', N'Khóa', N'N4', NULL, NULL, 520, GETDATE()),
  (N'気持ちが　良い', N'きもちがいい', N'Khí trì lương', N'Dễ chịu', N'N4', NULL, NULL, 521, GETDATE()),
  (N'気持ちが　悪い', N'きもちがわるい', N'Khí trì ác', N'Khó chịu', N'N4', NULL, NULL, 522, GETDATE()),
  (N'大きな～', N'おおきな', NULL, N'~ to, ~ lớn', N'N4', NULL, NULL, 523, GETDATE()),
  (N'小さな～', N'ちいさな', N'Tiểu', N'~ nhỏ, ~ bé', N'N4', NULL, NULL, 524, GETDATE()),
  (N'赤ちゃん', N'あかちゃん', N'Xích', N'Em bé', N'N4', NULL, NULL, 525, GETDATE()),
  (N'小学校', N'しょうがっこう', NULL, N'Trường cấp 1', N'N4', NULL, NULL, 526, GETDATE()),
  (N'中学校', N'ちゅうがっこう', NULL, N'Trường cấp 2', N'N4', NULL, NULL, 527, GETDATE()),
  (N'駅前', N'えきまえ', N'Dịch trước', N'Khu vực trước ga', N'N4', NULL, NULL, 528, GETDATE()),
  (N'海岸', N'かいがん', N'Hải ngạn', N'Bờ biển', N'N4', NULL, NULL, 529, GETDATE()),
  (N'嘘', N'うそ', N'Hư', N'Nói dối', N'N4', NULL, NULL, 530, GETDATE()),
  (N'書類', N'しょるい', N'Thư loại', N'Giấy tờ, tài liệu', N'N4', NULL, NULL, 531, GETDATE()),
  (N'電源', N'でんげん', N'Điện nguyên', N'Công tắc điện', N'N4', NULL, NULL, 532, GETDATE()),
  (N'～製', N'せい', N'Chế', N'Sản xuất tại ~', N'N4', NULL, NULL, 533, GETDATE()),
  (N'回覧', N'かいらん', N'Hồi lãm', N'Tập thông báo', N'N4', NULL, NULL, 534, GETDATE()),
  (N'研究室', N'けんきゅうしつ', N'Nghiên cứu thất', N'Phòng nghiên cứu', N'N4', NULL, NULL, 535, GETDATE()),
  (N'きちんと', N'きちんと', NULL, N'Nghiêm chỉnh', N'N4', NULL, NULL, 536, GETDATE()),
  (N'整理する', N'せいりする', N'Chỉnh lý', N'Sắp xếp', N'N4', NULL, NULL, 537, GETDATE()),
  (N'―冊', N'さつ', N'Sách', N'Đơn vị đếm sách', N'N4', NULL, NULL, 538, GETDATE()),
  (N'判子', N'はんこ', N'Phán tử/tý', N'Con dấu', N'N4', NULL, NULL, 539, GETDATE()),
  (N'押す', N'おす', N'Áp', N'Đóng (dấu)', N'N4', NULL, NULL, 540, GETDATE()),
  (N'双子', N'ふたご', N'Song tử', N'Cặp sinh đôi', N'N4', NULL, NULL, 541, GETDATE()),
  (N'姉妹', N'しまい', N'Tỷ muội', N'Chị em gái', N'N4', NULL, NULL, 542, GETDATE()),
  (N'似ている', N'にている', N'Tự', N'Giống', N'N4', NULL, NULL, 543, GETDATE()),
  (N'性格', N'せいかく', N'Tính cách', N'Tính cách', N'N4', NULL, NULL, 544, GETDATE()),
  (N'大人しい', N'おとなしい', N'Đại nhân', N'Hiền lành, trầm', N'N4', NULL, NULL, 545, GETDATE()),
  (N'世話を　する', N'せわをする', N'Thế thoại', N'Giúp đỡ', N'N4', NULL, NULL, 546, GETDATE()),
  (N'時間が　経つ', N'じかんがたつ', N'Thời gian kinh', N'Thời gian trôi qua', N'N4', NULL, NULL, 547, GETDATE()),
  (N'大好き（な）', N'だいすき', N'Đại hảo', N'Rất thích', N'N4', NULL, NULL, 548, GETDATE()),
  (N'―点', N'てん', N'Điểm', N'-điểm', N'N4', NULL, NULL, 549, GETDATE()),
  (N'喧嘩する', N'けんかする', N'Huyên hoa', N'Cãi nhau', N'N4', NULL, NULL, 550, GETDATE()),
  (N'不思議（な）', N'ふしぎ', N'Bất tư nghị', N'Bí ẩn, kì thú', N'N4', NULL, NULL, 551, GETDATE()),
  (N'に　答える', N'こたえる', N'Đáp', N'Trả lời (câu hỏi)', N'N4', NULL, NULL, 552, GETDATE()),
  (N'が　倒れる', N'たおれる', N'Đảo', N'Đổ (cây)', N'N4', NULL, NULL, 553, GETDATE()),
  (N'が　焼ける', N'やける', N'Thiêu', N'Cháy, nướng', N'N4', NULL, NULL, 554, GETDATE()),
  (N'通る', N'とおる', N'Thông', N'Đi qua, thông qua', N'N4', NULL, NULL, 555, GETDATE()),
  (N'死ぬ', N'しぬ', N'Tử', N'Chết', N'N4', NULL, NULL, 556, GETDATE()),
  (N'びっくりする', N'びっくりする', NULL, N'Ngạc nhiên', N'N4', NULL, NULL, 557, GETDATE()),
  (N'がっかりする', N'がっかりする', NULL, N'Thất vọng', N'N4', NULL, NULL, 558, GETDATE()),
  (N'安心する', N'あんしんする', N'An tâm', N'Yên tâm', N'N4', NULL, NULL, 559, GETDATE()),
  (N'遅刻する', N'ちこくする', N'Trì khắc', N'Đến muộn', N'N4', NULL, NULL, 560, GETDATE()),
  (N'早退する', N'そうたいする', N'Tảo thoái', N'Về sớm', N'N4', NULL, NULL, 561, GETDATE()),
  (N'喧嘩する', N'けんかする', N'Huyên hoa', N'Cãi nhau', N'N4', NULL, NULL, 562, GETDATE()),
  (N'離婚する', N'りこんする', N'Ly hôn', N'Ly hôn', N'N4', NULL, NULL, 563, GETDATE()),
  (N'複雑（な）', N'ふくざつ', N'Phức tạp', N'Phức tạp', N'N4', NULL, NULL, 564, GETDATE()),
  (N'邪魔（な）', N'じゃま', N'Tà ma', N'Chiếm diện tích', N'N4', NULL, NULL, 565, GETDATE()),
  (N'汚い', N'きたない', N'Ô', N'Bẩn', N'N4', NULL, NULL, 566, GETDATE()),
  (N'嬉しい', N'うれしい', N'Hi', N'Vui sướng', N'N4', NULL, NULL, 567, GETDATE()),
  (N'悲しい', N'かなしい', N'Bi', N'Đau buồn', N'N4', NULL, NULL, 568, GETDATE()),
  (N'恥ずかしい', N'はずかしい', N'Sỉ', N'Xấu hổ', N'N4', NULL, NULL, 569, GETDATE()),
  (N'地震', N'じしん', N'Địa chấn', N'Động đất', N'N4', NULL, NULL, 570, GETDATE()),
  (N'台風', N'たいふう', N'Đài phong', N'Bão', N'N4', NULL, NULL, 571, GETDATE()),
  (N'火事', N'かじ', N'Hỏa sự', N'Hỏa hoạn', N'N4', NULL, NULL, 572, GETDATE()),
  (N'事故', N'じこ', N'Sự cố', N'Sự cố, tai nạn', N'N4', NULL, NULL, 573, GETDATE()),
  (N'「お」見合い', N'おみあい', N'Kiến hợp', N'Làm mối', N'N4', NULL, NULL, 574, GETDATE()),
  (N'電話代', N'でんわだい', N'Điện thoại đại', N'Tiền điện thoại', N'N4', NULL, NULL, 575, GETDATE()),
  (N'―号室', N'ごうしつ', N'Hiệu thất', N'Phòng số -', N'N4', NULL, NULL, 576, GETDATE()),
  (N'汗', N'あせ', N'Hãn', N'Mồ hôi', N'N4', NULL, NULL, 577, GETDATE()),
  (N'石鹸', N'せっけん', NULL, N'Xà phòng', N'N4', NULL, NULL, 578, GETDATE()),
  (N'大勢', N'おおぜい', N'Đại thế', N'Nhiều người', N'N4', NULL, NULL, 579, GETDATE()),
  (N'お疲れ様でした', N'おつかれさまでした', N'Bí dạng', N'Chắc a/c đã mệt vì làm việc', N'N4', NULL, NULL, 580, GETDATE()),
  (N'伺います', N'うかがいます', N'Tỷ/tứ', N'Đến thăm ( khiêm nhường いきます)', N'N4', NULL, NULL, 581, GETDATE()),
  (N'途中で', N'とちゅうで', N'Đồ trung', N'Giữa đường', N'N4', NULL, NULL, 582, GETDATE()),
  (N'ぶつかる', N'ぶつかる', NULL, N'Đâm, va chạm', N'N4', NULL, NULL, 583, GETDATE()),
  (N'並ぶ', N'ならぶ', N'Tịnh', N'Xếp hàng', N'N4', NULL, NULL, 584, GETDATE()),
  (N'大人', N'おとな', NULL, N'Người lớn', N'N4', NULL, NULL, 585, GETDATE()),
  (N'洋服', N'ようふく', N'Dương phục', N'Quần áo kiểu Tây Âu', N'N4', NULL, NULL, 586, GETDATE()),
  (N'西洋化する', N'せいようかする', N'Tây dương hóa', N'Tây Âu hóa', N'N4', NULL, NULL, 587, GETDATE()),
  (N'が 合う', N'あう', N'Hợp', N'Vừa, hợp', N'N4', NULL, NULL, 588, GETDATE()),
  (N'今では', N'いまでは', N'Kim', N'Bây giờ thì', N'N4', NULL, NULL, 589, GETDATE()),
  (N'成人式', N'せいじんだい', N'Thành nhân thức', N'Lễ trưởng thành', N'N4', NULL, NULL, 590, GETDATE()),
  (N'数える', N'かぞえる', N'Số', N'Đếm', N'N4', NULL, NULL, 591, GETDATE()),
  (N'測る、量る', N'はかる', NULL, N'Đo, cân', N'N4', NULL, NULL, 592, GETDATE()),
  (N'確かめる', N'たしかめる', N'Xác', N'Xác nhận, kiểm tra', N'N4', NULL, NULL, 593, GETDATE()),
  (N'が　合う', N'あう', N'Hợp', N'Vừa, hợp', N'N4', NULL, NULL, 594, GETDATE()),
  (N'出発する', N'しゅっぱつする', N'Xuất phát', N'Xuất phát', N'N4', NULL, NULL, 595, GETDATE()),
  (N'到着する', N'とうちゃくする', N'Đáo trước', N'Đến nơi', N'N4', NULL, NULL, 596, GETDATE()),
  (N'酔う', N'よう', N'Túy', N'Say', N'N4', NULL, NULL, 597, GETDATE()),
  (N'危険（な）', N'きけん', N'Nguy hiểm', N'Nguy hiểm', N'N4', NULL, NULL, 598, GETDATE()),
  (N'必要（な）', N'ひつよう', N'Tất yếu', N'Cần thiết', N'N4', NULL, NULL, 599, GETDATE()),
  (N'宇宙', N'うちゅう', N'Vũ trụ', N'Vũ trụ', N'N4', NULL, NULL, 600, GETDATE()),
  (N'地球', N'ちきゅう', N'Địa cầu', N'Trái đất', N'N4', NULL, NULL, 601, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'忘年会', N'ぼうねんかい', N'Vong niên hội', N'Tiệc tất niên', N'N4', NULL, NULL, 602, GETDATE()),
  (N'新年会', N'しんねんかい', N'Tân niên hội', N'Tiệc tân niên', N'N4', NULL, NULL, 603, GETDATE()),
  (N'二次会', N'にじかい', N'Nhị thứ hội', N'Tăng hai', N'N4', NULL, NULL, 604, GETDATE()),
  (N'大会', N'たいかい', N'Đại hội', N'Đại hội, cuộc thi', N'N4', NULL, NULL, 605, GETDATE()),
  (N'表', N'おもて', N'Biểu', N'Mặt trước', N'N4', NULL, NULL, 606, GETDATE()),
  (N'裏', N'うら', N'Lý', N'Mặt sau', N'N4', NULL, NULL, 607, GETDATE()),
  (N'返事', N'へんじ', N'Phản sự', N'Hồi âm, trả lời', N'N4', NULL, NULL, 608, GETDATE()),
  (N'本当', N'ほんとう', N'Bản đương', N'Thật', N'N4', NULL, NULL, 609, GETDATE()),
  (N'間違い', N'まちがい', N'Gian vi', N'Sai, lỗi', N'N4', NULL, NULL, 610, GETDATE()),
  (N'傷', N'きず', N'Thương', N'Vết thương', N'N4', NULL, NULL, 611, GETDATE()),
  (N'長さ', N'ながさ', N'Trường', N'Chiều dài', N'N4', NULL, NULL, 612, GETDATE()),
  (N'重さ', N'おもさ', N'Trọng', N'Cân nặng', N'N4', NULL, NULL, 613, GETDATE()),
  (N'高さ', N'たかさ', N'Cao', N'Chiều cao', N'N4', NULL, NULL, 614, GETDATE()),
  (N'大きさ', N'おおきさ', N'Đại', N'Kích thước', N'N4', NULL, NULL, 615, GETDATE()),
  (N'―便', N'びん', N'Tiện', N'Chuyến bay -', N'N4', NULL, NULL, 616, GETDATE()),
  (N'―号', N'ごう', N'Hiệu', N'Số - (tàu, cơn bão)', N'N4', NULL, NULL, 617, GETDATE()),
  (N'―個', N'こ', N'Cá', N'-cái (vật nhỏ)', N'N4', NULL, NULL, 618, GETDATE()),
  (N'―本', N'ほん', N'Bản', N'-cái (thon dài)', N'N4', NULL, NULL, 619, GETDATE()),
  (N'―杯', N'はい', N'Bôi', N'-chén, cốc', N'N4', NULL, NULL, 620, GETDATE()),
  (N'―キロ', N'―キロ', NULL, N'Kilo', N'N4', NULL, NULL, 621, GETDATE()),
  (N'―グラム', N'―グラム', NULL, N'Gam', N'N4', NULL, NULL, 622, GETDATE()),
  (N'―センチ', N'―センチ', NULL, N'Cm', N'N4', NULL, NULL, 623, GETDATE()),
  (N'―ミリ', N'―ミリ', NULL, N'Mm', N'N4', NULL, NULL, 624, GETDATE()),
  (N'～以上', N'いじょう', N'Dĩ thượng', N'~ trở lên', N'N4', NULL, NULL, 625, GETDATE()),
  (N'～以下', N'いか', N'Dĩ hạ', N'~ trở xuống', N'N4', NULL, NULL, 626, GETDATE()),
  (N'どうでしょうか', N'どうでしょうか', NULL, N'Thế nào (lịch sự)', N'N4', NULL, NULL, 627, GETDATE()),
  (N'成績', N'せいせき', N'Thành tích', N'Thành tích', N'N4', NULL, NULL, 628, GETDATE()),
  (N'所で', N'ところで', N'Sở', N'Nhân tiện đây', N'N4', NULL, NULL, 629, GETDATE()),
  (N'いらっしゃいます', N'いらっしゃいます', NULL, N'Đến (tôn kính ngữ)', N'N4', NULL, NULL, 630, GETDATE()),
  (N'様子', N'ようす', N'Dạng tử', N'Vẻ, tình hình', N'N4', NULL, NULL, 631, GETDATE()),
  (N'事件', N'じけん', N'Sự kiện', N'Vụ án, sự kiện', N'N4', NULL, NULL, 632, GETDATE()),
  (N'爆弾', N'ばくだん', N'Bộc đạn/đàn', N'Bom', N'N4', NULL, NULL, 633, GETDATE()),
  (N'積む', N'つむ', N'Tích', N'Chuyển lên', N'N4', NULL, NULL, 634, GETDATE()),
  (N'運転者', N'うんてんしゃ', N'Vận động giả', N'Lái xe', N'N4', NULL, NULL, 635, GETDATE()),
  (N'離れた', N'はなれた', N'Ly', N'Xa cách, xa', N'N4', NULL, NULL, 636, GETDATE()),
  (N'急に', N'きゅうに', N'Cấp', N'Gấp, đột nhiên', N'N4', NULL, NULL, 637, GETDATE()),
  (N'動かす', N'うごかす', N'Động', N'Khởi động, chạy', N'N4', NULL, NULL, 638, GETDATE()),
  (N'一生懸命', N'いっしょうけんめい', N'Sinh huyền mệnh', N'Hết sức, chăm chỉ', N'N4', NULL, NULL, 639, GETDATE()),
  (N'犯人', N'はんにん', N'Phạm nhân', N'Phạm nhân', N'N4', NULL, NULL, 640, GETDATE()),
  (N'手に入れる', N'てにいれる', NULL, N'Có được, lấy được', N'N4', NULL, NULL, 641, GETDATE()),
  (N'今でも', N'いまでも', NULL, N'Ngay cả bây giờ', N'N4', NULL, NULL, 642, GETDATE()),
  (N'噂', N'うわさ', N'Đồn', N'Đồn đại', N'N4', NULL, NULL, 643, GETDATE()),
  (N'頂きます', N'いただきます', N'Đỉnh/đinh', N'Nhận (khiêm)', N'N4', NULL, NULL, 644, GETDATE()),
  (N'くださいます', N'くださいます', NULL, N'Cho, tặng (khiêm)', N'N4', NULL, NULL, 645, GETDATE()),
  (N'やります', N'やります', NULL, N'Cho, tặng (=,<)', N'N4', NULL, NULL, 646, GETDATE()),
  (N'呼ぶ', N'よぶ', N'Hô', N'Mời', N'N4', NULL, NULL, 647, GETDATE()),
  (N'取り替える', N'とりかえる', N'Thủ thế', N'Đổi, thay', N'N4', NULL, NULL, 648, GETDATE()),
  (N'親切に　する', N'しんせつにする', N'Thân thiết', N'Đối xử thân thiện', N'N4', NULL, NULL, 649, GETDATE()),
  (N'可愛い', N'かわいい', N'Khả ái', N'Xinh, đáng yêu', N'N4', NULL, NULL, 650, GETDATE()),
  (N'「お」祝い', N'おいわい', N'Chúc', N'Mừng, quà mừng', N'N4', NULL, NULL, 651, GETDATE()),
  (N'お年玉', N'おとしだま', N'Niên ngọc', N'Tiền mừng tuổi', N'N4', NULL, NULL, 652, GETDATE()),
  (N'「お」見舞い', N'おみまい', N'Kiến vũ', N'Thăm người ốm', N'N4', NULL, NULL, 653, GETDATE()),
  (N'に　興味がある', N'きょうみ', N'Hưng vị', N'Quan tâm về', N'N4', NULL, NULL, 654, GETDATE()),
  (N'情報', N'じょうほう', N'Tình báo', N'Thông tin', N'N4', NULL, NULL, 655, GETDATE()),
  (N'文法', N'ぶんぽう', N'Văn pháp', N'Ngữ pháp', N'N4', NULL, NULL, 656, GETDATE()),
  (N'発音', N'はつおん', N'Phát âm', N'Phát âm', N'N4', NULL, NULL, 657, GETDATE()),
  (N'猿', N'さる', N'Viên', N'Con khỉ', N'N4', NULL, NULL, 658, GETDATE()),
  (N'絵本', N'えほん', N'Hội bản', N'Quyển tr/tranh', N'N4', NULL, NULL, 659, GETDATE()),
  (N'絵はがき', N'えはがき', NULL, N'Bưu ảnh', N'N4', NULL, NULL, 660, GETDATE()),
  (N'靴下', N'くつした', N'Ngoa hạ', N'Cái tất', N'N4', NULL, NULL, 661, GETDATE()),
  (N'手袋', N'てぶくろ', N'Thủ đại', N'Găng tay', N'N4', NULL, NULL, 662, GETDATE()),
  (N'指輪', N'ゆびわ', N'Chỉ luân', N'Nhẫn', N'N4', NULL, NULL, 663, GETDATE()),
  (N'祖父', N'そふ', N'Tổ phụ', N'Ông (mình)', N'N4', NULL, NULL, 664, GETDATE()),
  (N'祖母', N'そぼ', N'Tổ mẫu', N'Bà (mình)', N'N4', NULL, NULL, 665, GETDATE()),
  (N'孫', N'まご', N'Tôn', N'Cháu', N'N4', NULL, NULL, 666, GETDATE()),
  (N'叔父', N'おじ', N'Thúc phụ', N'Chú, cậu, bác(m)', N'N4', NULL, NULL, 667, GETDATE()),
  (N'叔父さん', N'おじさん', NULL, N'Chú, cậu, bác(k)', N'N4', NULL, NULL, 668, GETDATE()),
  (N'叔母', N'おば', N'Thúc mẫu', N'Cô, dì, bác (mình)', N'N4', NULL, NULL, 669, GETDATE()),
  (N'叔母さん', N'おばさん', NULL, N'Cô, dì, bác (khác)', N'N4', NULL, NULL, 670, GETDATE()),
  (N'一昨年', N'おととし', NULL, N'Năm kia', N'N4', NULL, NULL, 671, GETDATE()),
  (N'申し訳ない', N'もうしわけない', N'Thân dịch', N'Xin lỗi', N'N4', NULL, NULL, 672, GETDATE()),
  (N'預かる', N'あずかる', N'Dự', N'Chăm sóc, trông nom', N'N4', NULL, NULL, 673, GETDATE()),
  (N'先日', N'せんじつ', NULL, N'Mấy ngày trước', N'N4', NULL, NULL, 674, GETDATE()),
  (N'助かる', N'たすかる', N'Trợ', N'May có a/c giúp', N'N4', NULL, NULL, 675, GETDATE()),
  (N'昔話', N'むかしばなし', N'Tích thoại', N'Truyện cổ tích', N'N4', NULL, NULL, 676, GETDATE()),
  (N'ある～', N'ある～', NULL, N'Có ~, một ~', N'N4', NULL, NULL, 677, GETDATE()),
  (N'男', N'おとこ', N'Nam', N'Người đàn ông', N'N4', NULL, NULL, 678, GETDATE()),
  (N'虐める', N'いじめる', N'Ngược', N'Bắt nạt', N'N4', NULL, NULL, 679, GETDATE()),
  (N'亀', N'かめ', N'Quy', N'Con rùa', N'N4', NULL, NULL, 680, GETDATE()),
  (N'助ける', N'たすける', N'Trợ', N'Giúp đỡ', N'N4', NULL, NULL, 681, GETDATE()),
  (N'「お」城', N'おしろ', N'Thành', N'Lâu đài', N'N4', NULL, NULL, 682, GETDATE()),
  (N'お姫様', N'おひめさま', N'Cơ dạng', N'Công chúa', N'N4', NULL, NULL, 683, GETDATE()),
  (N'楽しく', N'たのしく', NULL, N'Vui', N'N4', NULL, NULL, 684, GETDATE()),
  (N'暮らす', N'くらす', N'Mộ', N'Sống, sinh hoạt', N'N4', NULL, NULL, 685, GETDATE()),
  (N'陸', N'りく', N'Lục', N'Lục địa, đất liền', N'N4', NULL, NULL, 686, GETDATE()),
  (N'すると', N'すると', NULL, N'Sau đó, thế rồi', N'N4', NULL, NULL, 687, GETDATE()),
  (N'煙', N'けむり', N'Yên', N'Khói', N'N4', NULL, NULL, 688, GETDATE()),
  (N'真っ白（な）', N'まっしろ', N'Chân bạch', N'Trắng toát/ngần', N'N4', NULL, NULL, 689, GETDATE()),
  (N'中身', N'中身', N'Trung thân', N'Nội dung, đồ ở bên trong', N'N4', NULL, NULL, 690, GETDATE()),
  (N'包む', N'つつむ', N'Bao', N'Bọc, gói', N'N4', NULL, NULL, 691, GETDATE()),
  (N'沸かす', N'わかす', N'Phí/phất', N'Đun sôi', N'N4', NULL, NULL, 692, GETDATE()),
  (N'混ぜる', N'まぜる', N'Hỗn', N'Trộn, khuấy', N'N4', NULL, NULL, 693, GETDATE()),
  (N'計算する', N'けいさんする', N'Kế toán', N'Tính toán', N'N4', NULL, NULL, 694, GETDATE()),
  (N'厚い', N'あつい', N'Hậu', N'Dày', N'N4', NULL, NULL, 695, GETDATE()),
  (N'薄い', N'うすい', N'Bạc', N'Mỏng, nhạt', N'N4', NULL, NULL, 696, GETDATE()),
  (N'弁護士', N'べんごし', N'Biện hộ sĩ', N'Luật sư', N'N4', NULL, NULL, 697, GETDATE()),
  (N'音楽家', N'おんがくか', N'Âm nhạc gia', N'Nhạc sĩ', N'N4', NULL, NULL, 698, GETDATE()),
  (N'教育', N'きょういく', N'Giáo dục', N'Giáo dục', N'N4', NULL, NULL, 699, GETDATE()),
  (N'歴史', N'れきし', N'Lịch sử', N'Lịch sử', N'N4', NULL, NULL, 700, GETDATE()),
  (N'文化', N'ぶんか', N'Văn hóa', N'Văn hóa', N'N4', NULL, NULL, 701, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'社会', N'しゃかい', N'Xã hội', N'Xã hội', N'N4', NULL, NULL, 702, GETDATE()),
  (N'法律', N'ほうりつ', N'Pháp luật', N'Pháp luật', N'N4', NULL, NULL, 703, GETDATE()),
  (N'戦争', N'せんそう', N'Chiến tranh', N'Chiến tranh', N'N4', NULL, NULL, 704, GETDATE()),
  (N'平和', N'へいわ', N'Bình hòa', N'Hòa bình', N'N4', NULL, NULL, 705, GETDATE()),
  (N'目的', N'もくてき', N'Mục đích', N'Mục đích', N'N4', NULL, NULL, 706, GETDATE()),
  (N'安全', N'あんぜん', N'An toàn', N'An toàn', N'N4', NULL, NULL, 707, GETDATE()),
  (N'関係', N'かんけい', N'Quan hệ', N'Quan hệ', N'N4', NULL, NULL, 708, GETDATE()),
  (N'薬缶', N'やかん', N'Dược hẫu/phữu', N'Ấm nước', N'N4', NULL, NULL, 709, GETDATE()),
  (N'栓抜き', N'せんぬき', N'Xuyên/then bạt', N'Cái mở nắp chai', N'N4', NULL, NULL, 710, GETDATE()),
  (N'缶切り', N'かんきり', N'Hẫu/phữu thiết', N'Cái mở đồ hộp', N'N4', NULL, NULL, 711, GETDATE()),
  (N'缶詰', N'かんづめ', N'Hẫu/phữu cật', N'Đồ hộp', N'N4', NULL, NULL, 712, GETDATE()),
  (N'算盤', N'そろばん', N'Toán bàn', N'Bàn tính', N'N4', NULL, NULL, 713, GETDATE()),
  (N'体温計', N'たいおんけい', N'Thể ôn kế', N'Máy đo nhiệt độ', N'N4', NULL, NULL, 714, GETDATE()),
  (N'材料', N'ざいりょう', N'Tài liệu', N'Nguyên liệu', N'N4', NULL, NULL, 715, GETDATE()),
  (N'石', N'いし', N'Thạch', N'Hòn đá', N'N4', NULL, NULL, 716, GETDATE()),
  (N'なぜ', N'なぜ', NULL, N'Tại sao', N'N4', NULL, NULL, 717, GETDATE()),
  (N'鍋', N'なべ', N'Oa', N'Cái chảo, nồi', N'N4', NULL, NULL, 718, GETDATE()),
  (N'丼', N'どんぶり', NULL, N'Cái bát tô', N'N4', NULL, NULL, 719, GETDATE()),
  (N'食品', N'しょくひん', N'Thực phẩm', N'Thực phẩm', N'N4', NULL, NULL, 720, GETDATE()),
  (N'調査', N'ちょうさ', N'Điều tra', N'Điều tra', N'N4', NULL, NULL, 721, GETDATE()),
  (N'～の　代わりに', N'のかわりに', N'Đại', N'Thay ~, thay thế ~', N'N4', NULL, NULL, 722, GETDATE()),
  (N'どこででも', N'どこででも', NULL, N'Ở đâu cũng', N'N4', NULL, NULL, 723, GETDATE()),
  (N'今では', N'いまでは', NULL, N'Bây giờ thì', N'N4', NULL, NULL, 724, GETDATE()),
  (N'が　増える', N'ふえる', N'Tang', N'Tăng, tăng lên', N'N4', NULL, NULL, 725, GETDATE()),
  (N'が　減る', N'へる', N'Giảm', N'Giảm, giảm xuống', N'N4', NULL, NULL, 726, GETDATE()),
  (N'が　上がる', N'あがる', NULL, N'Bị tăng lên', N'N4', NULL, NULL, 727, GETDATE()),
  (N'が　下がる', N'さがる', NULL, N'Bị giảm xuống', N'N4', NULL, NULL, 728, GETDATE()),
  (N'が　切れる', N'きれる', N'Thiết', N'Bị đứt', N'N4', NULL, NULL, 729, GETDATE()),
  (N'が　とれる', N'が　とれる', NULL, N'Bị tuột', N'N4', NULL, NULL, 730, GETDATE()),
  (N'が　落つ', N'おつ', N'Lạc', N'Bị rơi', N'N4', NULL, NULL, 731, GETDATE()),
  (N'が　無くなる', N'なくなる', N'Vô', N'Bị mất', N'N4', NULL, NULL, 732, GETDATE()),
  (N'丈夫（な）', N'じょうぶ', N'Trượng phu', N'Chắc, bền', N'N4', NULL, NULL, 733, GETDATE()),
  (N'変　（な）', N'へん', N'Biến', N'Lạ, kỳ quặc', N'N4', NULL, NULL, 734, GETDATE()),
  (N'幸せ（な）', N'しあわせ', N'Hạnh', N'Hạnh phúc', N'N4', NULL, NULL, 735, GETDATE()),
  (N'うまい', N'うまい', N'Chỉ', N'Ngon', N'N4', NULL, NULL, 736, GETDATE()),
  (N'不味い', N'まずい', N'Bất vị', N'Dở', N'N4', NULL, NULL, 737, GETDATE()),
  (N'詰まらない', N'つまらない', N'Cật', N'Buồn tẻ', N'N4', NULL, NULL, 738, GETDATE()),
  (N'暖房', N'だんぼう', N'Noãn phòng', N'Thiết bị làm ấm', N'N4', NULL, NULL, 739, GETDATE()),
  (N'冷房', N'れいぼう', N'Lãnh phòng', N'Thiết bị làm mát', N'N4', NULL, NULL, 740, GETDATE()),
  (N'服のセンスがある', N'服のセンスがある', N'Phục', N'Có khiếu, có gu (ăn mặc)', N'N4', NULL, NULL, 741, GETDATE()),
  (N'今にも', N'いまにも', NULL, N'(sắp)~ đến nơi', N'N4', NULL, NULL, 742, GETDATE()),
  (N'会員', N'かいいん', N'Hội viên', N'Thành viên', N'N4', NULL, NULL, 743, GETDATE()),
  (N'適当', N'てきとう', N'Thích đương', N'Thích hợp, vừa phải', N'N4', NULL, NULL, 744, GETDATE()),
  (N'年齢', N'ねんれい', N'Niên linh', N'Tuổi', N'N4', NULL, NULL, 745, GETDATE()),
  (N'収入', N'しゅうにゅう', N'Thu nhập', N'Thu nhập', N'N4', NULL, NULL, 746, GETDATE()),
  (N'ぴったり', N'ぴったり', NULL, N'Vừa vặn, đúng', N'N4', NULL, NULL, 747, GETDATE()),
  (N'そのうえ', N'そのうえ', NULL, N'Thêm vào đó', N'N4', NULL, NULL, 748, GETDATE()),
  (N'～と　いう', N'～と　いう', NULL, N'Là ~, gọi là ~', N'N4', NULL, NULL, 749, GETDATE()),
  (N'ばら', N'ばら', NULL, N'Hoa hồng', N'N4', NULL, NULL, 750, GETDATE()),
  (N'泣く', N'なく', N'Khấp', N'Khóc', N'N4', NULL, NULL, 751, GETDATE()),
  (N'笑う', N'わらい', N'Tiếu', N'Cười', N'N4', NULL, NULL, 752, GETDATE()),
  (N'乾く', N'かわく', N'Can', N'Khô', N'N4', NULL, NULL, 753, GETDATE()),
  (N'濡れる', N'ぬれる', N'Nhu', N'Ướt', N'N4', NULL, NULL, 754, GETDATE()),
  (N'滑る', N'すべる', N'Hoạt', N'Trượt', N'N4', NULL, NULL, 755, GETDATE()),
  (N'が　起きる', N'おきる', NULL, N'Xảy ra (tai nạn)', N'N4', NULL, NULL, 756, GETDATE()),
  (N'調節する', N'ちょうせつする', N'Điều tiết', N'Điều chỉnh', N'N4', NULL, NULL, 757, GETDATE()),
  (N'安全（な）', N'あんぜん', N'An toàn', N'An toàn', N'N4', NULL, NULL, 758, GETDATE()),
  (N'丁寧（な）', N'ていねい', N'Đinh ninh', N'Lịch sự', N'N4', NULL, NULL, 759, GETDATE()),
  (N'細かい', N'こまかい', N'Tế', N'Tỉ mỉ', N'N4', NULL, NULL, 760, GETDATE()),
  (N'濃い', N'こい', N'Nồng', N'Đậm, nồng', N'N4', NULL, NULL, 761, GETDATE()),
  (N'薄い', N'うすい', N'Bạc', N'Nhạt', N'N4', NULL, NULL, 762, GETDATE()),
  (N'空気', N'くうき', N'Không khí', N'Không khí', N'N4', NULL, NULL, 763, GETDATE()),
  (N'涙', N'なみだ', N'Lệ', N'Nước mắt', N'N4', NULL, NULL, 764, GETDATE()),
  (N'和食', N'わしょく', N'Hòa thực', N'Món ăn Nhật', N'N4', NULL, NULL, 765, GETDATE()),
  (N'洋食', N'ようしょく', N'Dương thực', N'Món ăn Âu Mỹ', N'N4', NULL, NULL, 766, GETDATE()),
  (N'おかず', N'おかず', NULL, N'Thức ăn', N'N4', NULL, NULL, 767, GETDATE()),
  (N'量', N'りょう', N'Lượng', N'Lượng', N'N4', NULL, NULL, 768, GETDATE()),
  (N'―倍', N'ばい', N'Bội', N'-lần, gấp đôi', N'N4', NULL, NULL, 769, GETDATE()),
  (N'半分', N'はんぶん', N'Bán phân', N'Một nửa', N'N4', NULL, NULL, 770, GETDATE()),
  (N'たんす', N'箪笥', NULL, N'Tủ đựng quần áo', N'N4', NULL, NULL, 771, GETDATE()),
  (N'洗濯物', N'せんたくもの', N'Tẩy trạc vật', N'Quần áo giặt', N'N4', NULL, NULL, 772, GETDATE()),
  (N'理由', N'りゆう', N'Lý do', N'Lý do', N'N4', NULL, NULL, 773, GETDATE()),
  (N'嫌がる', N'いやがる', N'Hiềm', N'Tỏ thái độ không thích', N'N4', NULL, NULL, 774, GETDATE()),
  (N'順序', N'じゅんじょ', N'Thuận tự', N'Thứ tự', N'N4', NULL, NULL, 775, GETDATE()),
  (N'表現', N'ひょうげん', N'Biểu hiện', N'Cách diễn đạt', N'N4', NULL, NULL, 776, GETDATE()),
  (N'例えば', N'たとえば', N'Liệt', N'Ví dụ', N'N4', NULL, NULL, 777, GETDATE()),
  (N'別れる', N'わかれる', N'Biệt', N'Chia tay, từ biệt', N'N4', NULL, NULL, 778, GETDATE()),
  (N'これら', N'これら', NULL, N'Những cái này', N'N4', NULL, NULL, 779, GETDATE()),
  (N'縁起が　悪い', N'えんぎがわるい', N'Duyên khởi ác', N'Không may, không lành', N'N4', NULL, NULL, 780, GETDATE()),
  (N'謝る', N'あやまる', N'Tạ', N'Xin lỗi, tạ tội', N'N4', NULL, NULL, 781, GETDATE()),
  (N'に　合う', N'あう', N'Hợp', N'Gặp (tai nạn)', N'N4', NULL, NULL, 782, GETDATE()),
  (N'信じる', N'しんじる', N'Tín', N'Tin, tin tưởng', N'N4', NULL, NULL, 783, GETDATE()),
  (N'用意する', N'よういする', N'Dụng ý', N'Chuẩn bị', N'N4', NULL, NULL, 784, GETDATE()),
  (N'保証書', N'ほしょうしょ', N'Bảo chứng thư', N'Giấy bảo hành', N'N4', NULL, NULL, 785, GETDATE()),
  (N'領収書', N'りょうしょうしょ', N'Lãnh thu thư', N'Hóa đơn', N'N4', NULL, NULL, 786, GETDATE()),
  (N'贈り物', N'おくりもの', N'Tặng vật', N'Quà tặng', N'N4', NULL, NULL, 787, GETDATE()),
  (N'係', N'かかり', N'Hệ', N'Người phụ trách', N'N4', NULL, NULL, 788, GETDATE()),
  (N'中止', N'ちゅうし', N'Trung chỉ', N'Dừng, đình chỉ', N'N4', NULL, NULL, 789, GETDATE()),
  (N'点', N'てん', N'Điểm', N'Điểm', N'N4', NULL, NULL, 790, GETDATE()),
  (N'札', N'さつ', N'Trát', N'Tờ tiền giấy', N'N4', NULL, NULL, 791, GETDATE()),
  (N'ちゃんと', N'ちゃんと', NULL, N'Đúng, hẳn hoi', N'N4', NULL, NULL, 792, GETDATE()),
  (N'急に', N'きゅうに', N'Cấp', N'Gấp', N'N4', NULL, NULL, 793, GETDATE()),
  (N'以上です', N'いじょうです', N'Dĩ', N'Xin hết', N'N4', NULL, NULL, 794, GETDATE()),
  (N'係員', N'かかりいん', N'Hệ viên', N'Nhân viên', N'N4', NULL, NULL, 795, GETDATE()),
  (N'―位', N'い', N'Vị', N'Vị trị thứ-, giải-', N'N4', NULL, NULL, 796, GETDATE()),
  (N'優勝する', N'ゆうしょうする', N'Ưu thắng', N'Vô địch', N'N4', NULL, NULL, 797, GETDATE()),
  (N'悩み', N'なやみ', N'Não', N'Lo nghĩ', N'N4', NULL, NULL, 798, GETDATE()),
  (N'目覚まし', N'めざまし', N'Mục giác', N'Báo thức', N'N4', NULL, NULL, 799, GETDATE()),
  (N'眠る', N'ねむる', N'Miên', N'Ngủ', N'N4', NULL, NULL, 800, GETDATE()),
  (N'目が　覚める', N'めがさめる', NULL, N'Tỉnh giấc', N'N4', NULL, NULL, 801, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'大学生', N'だいがくせい', NULL, N'Sinh viên đại học', N'N4', NULL, NULL, 802, GETDATE()),
  (N'回答', N'かいとう', N'Hồi đáp', N'Câu trả lời', N'N4', NULL, NULL, 803, GETDATE()),
  (N'鳴る', N'なる', N'Minh', N'Reo, kêu', N'N4', NULL, NULL, 804, GETDATE()),
  (N'それでも', N'それでも', NULL, N'Tuy thế, mặc dù thế', N'N4', NULL, NULL, 805, GETDATE()),
  (N'焼く', N'やく', N'Thiêu', N'Nướng, rán', N'N4', NULL, NULL, 806, GETDATE()),
  (N'渡す', N'わたす', N'Độ', N'Đưa cho, giao cho', N'N4', NULL, NULL, 807, GETDATE()),
  (N'帰って　来る', N'かえってくる', N'Quy', N'Về, trở lại', N'N4', NULL, NULL, 808, GETDATE()),
  (N'が　出る', N'でる', NULL, N'Xuất phát, chạy', N'N4', NULL, NULL, 809, GETDATE()),
  (N'留守', N'るす', N'Lưu thủ', N'Đi vắng', N'N4', NULL, NULL, 810, GETDATE()),
  (N'宅配便', N'たくはいびん', N'Trạch phối tiện', N'Dịch vụ chuyển đồ', N'N4', NULL, NULL, 811, GETDATE()),
  (N'原因', N'げんいん', N'Nguyên nhân', N'Nguyên nhân', N'N4', NULL, NULL, 812, GETDATE()),
  (N'注射', N'ちゅうしゃ', N'Chú xạ', N'Tiêm', N'N4', NULL, NULL, 813, GETDATE()),
  (N'食欲', N'しょくよく', N'Thực dục', N'Cảm giác thèm ăn', N'N4', NULL, NULL, 814, GETDATE()),
  (N'～の所', N'のところ', NULL, N'Xung quanh ~', N'N4', NULL, NULL, 815, GETDATE()),
  (N'丁度', N'ちょうど', N'Đinh độ', N'Vừa đúng', N'N4', NULL, NULL, 816, GETDATE()),
  (N'たった今', N'たったいま', NULL, N'Vừa mới rồi', N'N4', NULL, NULL, 817, GETDATE()),
  (N'今いいでしょうか', N'いまいいでしょか', NULL, N'Bây giờ tôi làm phiền anh được không', N'N4', NULL, NULL, 818, GETDATE()),
  (N'具合', N'ぐあい', N'Cụ hợp', N'Trạng thái', N'N4', NULL, NULL, 819, GETDATE()),
  (N'向かう', N'むかう', N'Hướng', N'Trên đường đến', N'N4', NULL, NULL, 820, GETDATE()),
  (N'お待たせしました', N'おまたせしました', N'Đãi', N'Xin lỗi vì để a/c phải đợi', N'N4', NULL, NULL, 821, GETDATE()),
  (N'知識', N'ちしき', N'Tri thức', N'Tri thức', N'N4', NULL, NULL, 822, GETDATE()),
  (N'宝庫', N'ほうこ', N'Bảo khố', N'Kho báu', N'N4', NULL, NULL, 823, GETDATE()),
  (N'が　手に入る', N'てにはいる', NULL, N'Thu nhập được', N'N4', NULL, NULL, 824, GETDATE()),
  (N'一部分', N'いちぶぶん', N'Nhất bộ phân', N'Một bộ phận', N'N4', NULL, NULL, 825, GETDATE()),
  (N'入力する', N'にゅうりょくする', N'Nhập lực', N'Nhập (hàng)', N'N4', NULL, NULL, 826, GETDATE()),
  (N'秒', N'びょう', N'Miểu', N'Giây', N'N4', NULL, NULL, 827, GETDATE()),
  (N'が　出る', N'でる', NULL, N'Được xuất bản', N'N4', NULL, NULL, 828, GETDATE()),
  (N'が　集まる', N'あつまる', N'Tập', N'Tập trung (人)', N'N4', NULL, NULL, 829, GETDATE()),
  (N'が　別れる', N'わかれる', N'Biệt', N'Chia ra (人)', N'N4', NULL, NULL, 830, GETDATE()),
  (N'長生きします', N'ながいきします', N'Trường sinh', N'Sống lâu', N'N4', NULL, NULL, 831, GETDATE()),
  (N'差す', N'さす', N'Soa', N'Che (ô)', N'N4', NULL, NULL, 832, GETDATE()),
  (N'酷い', N'ひどい', N'Khốc', N'Tồi tệ, xấu', N'N4', NULL, NULL, 833, GETDATE()),
  (N'怖い', N'こわい', N'Bố', N'Sợ, khiếp', N'N4', NULL, NULL, 834, GETDATE()),
  (N'天気予報', N'てんきよほう', N'Thiên khí dự báo', N'Dự báo thời tiết', N'N4', NULL, NULL, 835, GETDATE()),
  (N'発表', N'はっぴょう', N'Phát biểu', N'Phát biểu, báo cáo', N'N4', NULL, NULL, 836, GETDATE()),
  (N'実験', N'じっけん', N'Thực nghiệm', N'Thực/thí nghiệm', N'N4', NULL, NULL, 837, GETDATE()),
  (N'人口', N'じんこう', N'Nhân khẩu', N'Dân số', N'N4', NULL, NULL, 838, GETDATE()),
  (N'におい', N'におい', NULL, N'Mùi', N'N4', NULL, NULL, 839, GETDATE()),
  (N'科学', N'かがく', N'Khoa học', N'Khoa học', N'N4', NULL, NULL, 840, GETDATE()),
  (N'医学', N'いがく', N'Y học', N'Y học', N'N4', NULL, NULL, 841, GETDATE()),
  (N'文学', N'ぶんがく', N'Văn học', N'Văn học', N'N4', NULL, NULL, 842, GETDATE()),
  (N'救急車', N'きゅうきゅうしゃ', N'Cứu cấp xa', N'Xe cấp cứu', N'N4', NULL, NULL, 843, GETDATE()),
  (N'賛成', N'さんせい', N'Tán thành', N'Tán thành', N'N4', NULL, NULL, 844, GETDATE()),
  (N'反対', N'はんたい', N'Phản đối', N'Phản đối', N'N4', NULL, NULL, 845, GETDATE()),
  (N'男性', N'だんせい', N'Nam tính', N'Nam giới', N'N4', NULL, NULL, 846, GETDATE()),
  (N'女性', N'じょせい', N'Nữ tính', N'Nữ giới', N'N4', NULL, NULL, 847, GETDATE()),
  (N'～に　よると', N'～に　よると', NULL, N'Theo ~ thì', N'N4', NULL, NULL, 848, GETDATE()),
  (N'恋人', N'こいびと', N'Luyến nhân', N'Người yêu', N'N4', NULL, NULL, 849, GETDATE()),
  (N'婚約する', N'こんやくする', N'Hôn ước', N'Đính hôn', N'N4', NULL, NULL, 850, GETDATE()),
  (N'相手', N'あいて', N'Tương thủ', N'Đối tác', N'N4', NULL, NULL, 851, GETDATE()),
  (N'知り合う', N'しりあう', N'Tri hợp', N'Gặp gỡ làm quen', N'N4', NULL, NULL, 852, GETDATE()),
  (N'平均寿命', N'へいきんじゅみょう', N'Bình quân thọ mệnh', N'Tuổi thọ trung bình', N'N4', NULL, NULL, 853, GETDATE()),
  (N'と　比べる', N'くらべる', N'Tỉ', N'So sánh', N'N4', NULL, NULL, 854, GETDATE()),
  (N'博士', N'はかせ', N'Bác sĩ', N'Tiến sĩ', N'N4', NULL, NULL, 855, GETDATE()),
  (N'脳', N'のう', N'Não', N'Não', N'N4', NULL, NULL, 856, GETDATE()),
  (N'化粧品', N'けしょうひん', N'Hóa trang phẩm', N'Mỹ phẩm', N'N4', NULL, NULL, 857, GETDATE()),
  (N'調べ', N'しらべる', N'Điều', N'Điều tra, tìm hiểu', N'N4', NULL, NULL, 858, GETDATE()),
  (N'化粧', N'けしょう', NULL, N'Trang điểm', N'N4', NULL, NULL, 859, GETDATE()),
  (N'下ろす、降ろす', N'おろす', N'Giáng/hàng', N'Cho/hạ xuống', N'N4', NULL, NULL, 860, GETDATE()),
  (N'届ける', N'とどける', N'Giới', N'Gửi/chuyển đến', N'N4', NULL, NULL, 861, GETDATE()),
  (N'世話を　する', N'せわをする', NULL, N'Chăm sóc', N'N4', NULL, NULL, 862, GETDATE()),
  (N'嫌（な）', N'いや', N'Hiềm', N'Ngán, không thích', N'N4', NULL, NULL, 863, GETDATE()),
  (N'厳しい', N'きびしい', N'Nghiêm', N'Nghiêm khắc', N'N4', NULL, NULL, 864, GETDATE()),
  (N'塾', N'じゅく', N'Thục', N'Cơ sở học them', N'N4', NULL, NULL, 865, GETDATE()),
  (N'生徒', N'せいと', N'Sinh đồ', N'Học sinh/trò', N'N4', NULL, NULL, 866, GETDATE()),
  (N'者', N'もの', N'Giả', N'Người thân, cấp dưới', N'N4', NULL, NULL, 867, GETDATE()),
  (N'入管', N'にゅうかん', N'Nhập quản', N'Cục quản lý nhập cảnh', N'N4', NULL, NULL, 868, GETDATE()),
  (N'再入国ビザ', N'さいにゅうこく', N'Tái nhập quốc', N'Thị thực tái nhập cảnh', N'N4', NULL, NULL, 869, GETDATE()),
  (N'自由に', N'じゆうに', N'Tự do', N'Tự do', N'N4', NULL, NULL, 870, GETDATE()),
  (N'～間', N'かん', NULL, N'Trong ~ (time)', N'N4', NULL, NULL, 871, GETDATE()),
  (N'お忙しいですか', N'おいそがしいですね', N'Mang', N'A/c có bận không (kính ngữ)', N'N4', NULL, NULL, 872, GETDATE()),
  (N'久しぶり', N'ひさしぶり', N'Cửu', N'Lâu', N'N4', NULL, NULL, 873, GETDATE()),
  (N'営業', N'えいぎょう', N'Doanh nghiệp', N'Kinh doanh', N'N4', NULL, NULL, 874, GETDATE()),
  (N'それまでに', N'それまでに', NULL, N'Trước thời điểm đó', N'N4', NULL, NULL, 875, GETDATE()),
  (N'構いません', N'かまいません', N'Cấu', N'Không vấn đề/sao', N'N4', NULL, NULL, 876, GETDATE()),
  (N'楽しむ', N'たのしむ', NULL, N'Vui, vui thích', N'N4', NULL, NULL, 877, GETDATE()),
  (N'元々', N'もともと', NULL, N'Vốn dĩ là ~', N'N4', NULL, NULL, 878, GETDATE()),
  (N'―世紀', N'せいき', N'Thế kỉ', N'Thế kỷ -', N'N4', NULL, NULL, 879, GETDATE()),
  (N'代わりを　する', N'かわりをする', NULL, N'Thay thế', N'N4', NULL, NULL, 880, GETDATE()),
  (N'競走する', N'きょうそうする', N'Cạnh tẩu', N'Chạy đua, thi chạy', N'N4', NULL, NULL, 881, GETDATE()),
  (N'芸', N'げい', N'Nghệ', N'Trò diễn, tiết mục', N'N4', NULL, NULL, 882, GETDATE()),
  (N'美しい', N'うつくしい', N'Mỹ', N'Đẹp', N'N4', NULL, NULL, 883, GETDATE()),
  (N'姿', N'すがた', N'Tư', N'Dáng điệu, tư thế', N'N4', NULL, NULL, 884, GETDATE()),
  (N'心', N'こころ', N'Tâm', N'Trái tim, tấm lòng, cảm tình', N'N4', NULL, NULL, 885, GETDATE()),
  (N'～に　とって', N'～に　とって', NULL, N'Đối với ~', N'N4', NULL, NULL, 886, GETDATE()),
  (N'に　勤める', N'つとめる', N'Cần', N'Làm việc ở ~', N'N4', NULL, NULL, 887, GETDATE()),
  (N'休む', N'やすむ', N'Hưu', N'Ngủ', N'N4', NULL, NULL, 888, GETDATE()),
  (N'に　掛ける', N'かける', N'Quải', N'Ngồi (ghế)', N'N4', NULL, NULL, 889, GETDATE()),
  (N'過ごす', N'すごす', N'Quá', N'Trải qua, tiêu time', N'N4', NULL, NULL, 890, GETDATE()),
  (N'に　寄る', N'よる', N'Kỳ', N'Ghé qua', N'N4', NULL, NULL, 891, GETDATE()),
  (N'いらっしゃいます', N'いらっしゃいます', NULL, N'ở, có, đi, đến (tkn)', N'N4', NULL, NULL, 892, GETDATE()),
  (N'召し上がります', N'めしあがります', N'Triệu thượng', N'Ăn, uống (tkn)', N'N4', NULL, NULL, 893, GETDATE()),
  (N'おっしゃいます', N'おっしゃいます', NULL, N'Nói (tkn)', N'N4', NULL, NULL, 894, GETDATE()),
  (N'なさいます', N'なさいます', NULL, N'Làm (tkn)', N'N4', NULL, NULL, 895, GETDATE()),
  (N'ご覧になります', N'ごらんいなります', N'Lãm', N'Xem, nhìn (tkn)', N'N4', NULL, NULL, 896, GETDATE()),
  (N'ご存じます', N'おぞんじます', N'Tồn', N'Biết (tkn)', N'N4', NULL, NULL, 897, GETDATE()),
  (N'挨拶', N'あいさつ', NULL, N'Chào hỏi', N'N4', NULL, NULL, 898, GETDATE()),
  (N'灰皿', N'はいざら', N'Hôi mãnh', N'Gạt tàn', N'N4', NULL, NULL, 899, GETDATE()),
  (N'旅館', N'りょかん', N'Lữ quán', N'Khách sạn kiểu Nhật', N'N4', NULL, NULL, 900, GETDATE()),
  (N'会場', N'かいじょう', N'Hội trường', N'Hội trường', N'N4', NULL, NULL, 901, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'バス停', N'バスてい', N'Đình', N'Bến xe bus', N'N4', NULL, NULL, 902, GETDATE()),
  (N'貿易', N'ぼうえき', N'Mậu dịch', N'Thương mại', N'N4', NULL, NULL, 903, GETDATE()),
  (N'～様', N'さま', NULL, N'Ngài/Ông/Bà ~', N'N4', NULL, NULL, 904, GETDATE()),
  (N'帰りに', N'かえりに', N'Quy', N'Trên đường về', N'N4', NULL, NULL, 905, GETDATE()),
  (N'偶に', N'たまに', N'Ngẫu', N'Thỉnh thoảng', N'N4', NULL, NULL, 906, GETDATE()),
  (N'ちっとも', N'ちっとも', NULL, N'Chẳng ~ tí nào, chẳng hề', N'N4', NULL, NULL, 907, GETDATE()),
  (N'遠慮なく', N'えんりょなく', N'Viễn lự', N'Không giữ ý, không làm khách', N'N4', NULL, NULL, 908, GETDATE()),
  (N'―年―組み', N'ーねんーくみ', N'Niên tổ', N'Lớp - năm thứ -', N'N4', NULL, NULL, 909, GETDATE()),
  (N'では', N'では', NULL, N'Thế thì (lịch sự của じゃ)', N'N4', NULL, NULL, 910, GETDATE()),
  (N'出す', N'だす', NULL, N'Bị (sốt)', N'N4', NULL, NULL, 911, GETDATE()),
  (N'よろしく　お伝えください', N'よろしく　おつたえください', N'Truyền', N'Cho tôi gửi lời hỏi thăm', N'N4', NULL, NULL, 912, GETDATE()),
  (N'失礼いたします', N'失礼いたします', NULL, N'Xin phép a/c (knn)', N'N4', NULL, NULL, 913, GETDATE()),
  (N'講師', N'こうし', N'Giảng sư', N'Giảng/giáo viên', N'N4', NULL, NULL, 914, GETDATE()),
  (N'多くの～', N'おおくの', N'Đa', N'Nhiều ~', N'N4', NULL, NULL, 915, GETDATE()),
  (N'作品', N'さくひん', N'Tác phẩm', N'Tác phẩm', N'N4', NULL, NULL, 916, GETDATE()),
  (N'受賞する', N'じゅしょうする', N'Thụ thưởng', N'Nhận, được giải thưởng', N'N4', NULL, NULL, 917, GETDATE()),
  (N'世界的に', N'せかいてきに', NULL, N'Tầm cỡ thế giới', N'N4', NULL, NULL, 918, GETDATE()),
  (N'作家', N'さっか', NULL, N'Nhà văn', N'N4', NULL, NULL, 919, GETDATE()),
  (N'～で　いらっしゃいます', N'～で　いらっしゃいます', NULL, N'Là (tkn của です)', N'N4', NULL, NULL, 920, GETDATE()),
  (N'長男', N'ちょうなん', NULL, N'Trưởng nam', N'N4', NULL, NULL, 921, GETDATE()),
  (N'障害', N'しょうがい', N'Chướng hại', N'Khuyết/tàn tật', N'N4', NULL, NULL, 922, GETDATE()),
  (N'お持ちです', N'おまちです', N'Trì', N'Có (tknもっています)', N'N4', NULL, NULL, 923, GETDATE()),
  (N'作曲', N'さっきょく', N'Tác khúc', N'Sáng tác nhạc', N'N4', NULL, NULL, 924, GETDATE()),
  (N'活動', N'かつどう', N'Hoạt động', N'Hoạt động', N'N4', NULL, NULL, 925, GETDATE()),
  (N'それでは', N'それでは', NULL, N'Bây giờ thì ~', N'N4', NULL, NULL, 926, GETDATE()),
  (N'参ります', N'まいります', N'Tham', N'Đi, đến (knn)', N'N4', NULL, NULL, 927, GETDATE()),
  (N'おります', N'おります', NULL, N'Ở, có (knn)', N'N4', NULL, NULL, 928, GETDATE()),
  (N'頂きます', N'いただきます', N'Đỉnh/đinh', N'Ăn, uống, nhận (knn)', N'N4', NULL, NULL, 929, GETDATE()),
  (N'申します', N'もうします', N'thân', N'Nói (knn)', N'N4', NULL, NULL, 930, GETDATE()),
  (N'いたします', N'いたします', NULL, N'Làm (knn)', N'N4', NULL, NULL, 931, GETDATE()),
  (N'拝見します', N'はいけんする', N'Bái kiến', N'Xem, nhìn (knn)', N'N4', NULL, NULL, 932, GETDATE()),
  (N'存じます', N'ぞんじます', N'Tồn', N'Biết (knn)', N'N4', NULL, NULL, 933, GETDATE()),
  (N'伺います', N'うかがいます', N'Tỷ/tứ', N'Hỏi, nghe, đến thăm (knn)', N'N4', NULL, NULL, 934, GETDATE()),
  (N'お目にかかります', N'おめにかかります', NULL, N'Gặp (knn)', N'N4', NULL, NULL, 935, GETDATE()),
  (N'ございます', N'ございます', NULL, N'Có (lịch sự あり)', N'N4', NULL, NULL, 936, GETDATE()),
  (N'～で　ございます', N'～で　ございます', NULL, N'Là (lịch sự です)', N'N4', NULL, NULL, 937, GETDATE()),
  (N'私', N'わたくし', NULL, N'Tôi (knn)', N'N4', NULL, NULL, 938, GETDATE()),
  (N'ガイド', N'ガイド', NULL, N'Hướng dẫn viên', N'N4', NULL, NULL, 939, GETDATE()),
  (N'お宅', N'おたく', N'Trạch', N'Nhà (khác)', N'N4', NULL, NULL, 940, GETDATE()),
  (N'郊外', N'こうがい', N'Giao ngoại', N'Ngoại ô', N'N4', NULL, NULL, 941, GETDATE()),
  (N'アルバム', N'アルバム', NULL, N'Album', N'N4', NULL, NULL, 942, GETDATE()),
  (N'再来週', N'さらいしゅう', N'Tái lai chu', N'Tuần sau nữa', N'N4', NULL, NULL, 943, GETDATE()),
  (N'再来月', N'さらいげつ', N'Tái lai nguyệt', N'Tháng sau nữa', N'N4', NULL, NULL, 944, GETDATE()),
  (N'再来年', N'さらいねん', N'Tái lai niên', N'Năm sau nữa', N'N4', NULL, NULL, 945, GETDATE()),
  (N'半年', N'はんとし', N'Bán niên', N'Nửa năm', N'N4', NULL, NULL, 946, GETDATE()),
  (N'最初に', N'さいしょに', N'Tối sơ', N'Đầu tiên, trước hết', N'N4', NULL, NULL, 947, GETDATE()),
  (N'最後に', N'さいごに', N'Tối hậu', N'Cuối cùng', N'N4', NULL, NULL, 948, GETDATE()),
  (N'ただ今', N'ただいま', NULL, N'Bây giờ (lịch sự)', N'N4', NULL, NULL, 949, GETDATE()),
  (N'緊張する', N'きんちょうする', N'Khẩn trương', N'Căng thẳng', N'N4', NULL, NULL, 950, GETDATE()),
  (N'放送する', N'ほうそうする', N'Phóng tống', N'Phát thanh', N'N4', NULL, NULL, 951, GETDATE()),
  (N'に　撮る', N'とる', N'Toát', N'Thu, quay (video)', N'N4', NULL, NULL, 952, GETDATE()),
  (N'賞金', N'しょうきん', N'Thưởng kim', N'Tiền thưởng', N'N4', NULL, NULL, 953, GETDATE()),
  (N'自然', N'しぜん', N'Tự nhiên', N'Tự/thiên nhiên', N'N4', NULL, NULL, 954, GETDATE()),
  (N'象', N'ぞう', N'Tượng', N'Voi', N'N4', NULL, NULL, 955, GETDATE()),
  (N'頃', N'ころ', N'Khoảnh', N'Hồi, thời', N'N4', NULL, NULL, 956, GETDATE()),
  (N'が　かなう', N'が　かなう', NULL, N'~ thành hiện thực', N'N4', NULL, NULL, 957, GETDATE()),
  (N'一言　よろしいでしょうか', N'ひとこと。。。', NULL, N'Tôi xin phép nói vài lời được không', N'N4', NULL, NULL, 958, GETDATE()),
  (N'協力する', N'きょうりょくする', N'Hiệp lực', N'Hợp tác', N'N4', NULL, NULL, 959, GETDATE()),
  (N'心から', N'こころから', NULL, N'Từ trái tim/đáy lòng', N'N4', NULL, NULL, 960, GETDATE()),
  (N'感謝する', N'かんしゃする', N'Cảm tạ', N'Cảm ơn, cảm tạ', N'N4', NULL, NULL, 961, GETDATE()),
  (N'お礼', N'おれい', N'Lễ', N'Lời/sự cảm ơn', N'N4', NULL, NULL, 962, GETDATE()),
  (N'拝啓', N'はいけい', N'Bái khải', N'Kính gửi ~', N'N4', NULL, NULL, 963, GETDATE()),
  (N'美しい', N'うつくしい', NULL, N'Đẹp', N'N4', NULL, NULL, 964, GETDATE()),
  (N'お元気で　いらっしゃいますか', N'おげんきで。。', NULL, N'A/c có khỏe không (tkn)', N'N4', NULL, NULL, 965, GETDATE()),
  (N'迷惑を　かける', N'めいわくをかける', N'Mê hoặc', N'Làm phiền', N'N4', NULL, NULL, 966, GETDATE()),
  (N'生かす', N'いかす', NULL, N'Tận dụng, phát huy', N'N4', NULL, NULL, 967, GETDATE()),
  (N'お城', N'お城', NULL, N'Lâu đài', N'N4', NULL, NULL, 968, GETDATE()),
  (N'敬具', N'けいぐ', N'Kính cụ', N'Kính thư', N'N4', NULL, NULL, 969, GETDATE());

PRINT 'Seeded 968 JLPT N4 records.';
GO
