-- ============================================================
-- JLPT Vocabulary Seed: JLPT N5
-- Records: 728
-- Generated: 2026-07-04T05:53:39.986Z
-- ============================================================

USE JapaneseAI;
GO

SET NOCOUNT ON;

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'私', N'わたし', N'Tư', N'Tôi', N'N5', N'N', NULL, 1, GETDATE()),
  (N'私達', N'わたしたち', N'Tư đạt', N'Chúng tôi', N'N5', N'N', NULL, 2, GETDATE()),
  (N'貴方', N'あなた', N'Quý phương', N'Bạn', N'N5', N'N', NULL, 3, GETDATE()),
  (N'先生', N'せんせい', N'Tiên sinh', N'Cô, thầy giáo', N'N5', N'N', NULL, 4, GETDATE()),
  (N'教師', N'きょうし', N'Giáo sư', N'Giáo viên', N'N5', N'N', NULL, 5, GETDATE()),
  (N'実習生', N'じっしゅうせい', N'Thực tập sinh', N'Thực tập sinh', N'N5', N'N', NULL, 6, GETDATE()),
  (N'研究者', N'けんきゅうしゃ', N'Nghiên cứu giả', N'Nhà nghiên cứu', N'N5', N'N', NULL, 7, GETDATE()),
  (N'技術者', N'ぎじゅつしゃ', N'Kỹ thuật giả', N'Kỹ thuật viên', N'N5', N'N', NULL, 8, GETDATE()),
  (N'留学生', N'りゅうがくせい', N'Lưu học sinh', N'Du học sinh', N'N5', N'N', NULL, 9, GETDATE()),
  (N'学生', N'がくせい', N'Học sinh', N'Học sinh', N'N5', N'N', NULL, 10, GETDATE()),
  (N'会社員/社員', N'かいしゃいん', N'Hội xã viên', N'Nhân viên công ty', N'N5', N'N', NULL, 11, GETDATE()),
  (N'銀行員', N'ぎんこういん', N'Ngân hàng viên', N'Nhân viên ngân hàng', N'N5', N'N', NULL, 12, GETDATE()),
  (N'医者', N'いしゃ', N'Y giả', N'Bác sĩ', N'N5', N'N', NULL, 13, GETDATE()),
  (N'大学', N'だいがく', N'Đại học', N'Trường đại học', N'N5', N'N', NULL, 14, GETDATE()),
  (N'機械', N'きかい', N'Cơ giới', N'Máy móc, cơ khí', N'N5', N'N', NULL, 15, GETDATE()),
  (N'自動車/車', N'じどうしゃ', N'Tự động xa', N'Ô tô', N'N5', N'N', NULL, 16, GETDATE()),
  (N'専門', N'せんもん', N'Chuyên môn', N'Chuyên môn', N'N5', N'N', NULL, 17, GETDATE()),
  (N'何歳/おいくつ', N'なんさい', N'Hà tuế', N'Bao nhiêu tuổi', N'N5', N'N', NULL, 18, GETDATE()),
  (N'失礼ですが', N'しつれい', N'Thất lễ', N'Xin lỗi (nhờ vả, hỏi thăm)', N'N5', N'N', NULL, 19, GETDATE()),
  (N'お名前は', N'おなまえは？', N'Danh tiền', N'Tên bạn là gì?', N'N5', N'N', NULL, 20, GETDATE()),
  (N'初めまして', N'はじめまして', N'Sơ', N'Xin chào (lần đầu gặp)', N'N5', N'N', NULL, 21, GETDATE()),
  (N'中国', N'ちゅうごく', N'Trung quốc', N'Trung Quốc', N'N5', N'N', NULL, 22, GETDATE()),
  (N'韓国', N'かんこく', N'Hàn quốc', N'Hàn Quốc', N'N5', N'N', NULL, 23, GETDATE()),
  (N'ベトナム', N'ベトナム', NULL, N'Việt Nam', N'N5', N'N', NULL, 24, GETDATE()),
  (N'日本　/にっぽん', N'にほん', N'Nhật bản', N'Nhật Bản', N'N5', N'N', NULL, 25, GETDATE()),
  (N'誰', N'だれ', N'Thùy', N'Ai', N'N5', N'N', NULL, 26, GETDATE()),
  (N'本', N'ほん', N'Bản', N'Quyển sách', N'N5', N'N', NULL, 27, GETDATE()),
  (N'辞書', N'じしょ', N'Từ thư', N'Từ điển', N'N5', N'N', NULL, 28, GETDATE()),
  (N'雑誌', N'ざっし', N'Tạp chí', N'Tạp chí', N'N5', N'N', NULL, 29, GETDATE()),
  (N'新聞', N'しんぶん', N'Tân văn', N'Báo', N'N5', N'N', NULL, 30, GETDATE()),
  (N'紙', N'かみ', N'Chỉ', N'Giấy', N'N5', N'N', NULL, 31, GETDATE()),
  (N'煙草', N'たばこ', N'Yên thảo', N'Thuốc lá', N'N5', N'N', NULL, 32, GETDATE()),
  (N'灰皿', N'はいざら', N'Hôi mãnh', N'Gạt tàn thuốc lá', N'N5', N'N', NULL, 33, GETDATE()),
  (N'箱', N'はこ', N'Tương', N'Hộp', N'N5', N'N', NULL, 34, GETDATE()),
  (N'手紙', N'てがみ', N'Thủ chỉ', N'Thư', N'N5', N'N', NULL, 35, GETDATE()),
  (N'手帳', N'てちょう', N'Thủ trướng', N'Sổ tay', N'N5', N'N', NULL, 36, GETDATE()),
  (N'名刺', N'めいし', N'Danh thích', N'Danh thiếp', N'N5', N'N', NULL, 37, GETDATE()),
  (N'鉛筆', N'えんぴつ', N'Duyên bút', N'Bút chì', N'N5', N'N', NULL, 38, GETDATE()),
  (N'鍵', N'かぎ', N'Kiện', N'Chìa khóa', N'N5', N'N', NULL, 39, GETDATE()),
  (N'時計', N'とけい', N'Thời kế', N'Đồng hồ', N'N5', N'N', NULL, 40, GETDATE()),
  (N'傘', N'かさ', N'Tán', N'Cái ô', N'N5', N'N', NULL, 41, GETDATE()),
  (N'鞄', N'かばん', N'Bạc', N'Cặp sách', N'N5', N'N', NULL, 42, GETDATE()),
  (N'電話', N'でんわ', N'Điện thoại', N'Điện thoại', N'N5', N'N', NULL, 43, GETDATE()),
  (N'携帯電話', N'けいたいでんわ', N'Huề đới', N'Điện thoại cầm tay', N'N5', N'N', NULL, 44, GETDATE()),
  (N'机', N'つくえ', N'Kỷ', N'Bàn', N'N5', N'N', NULL, 45, GETDATE()),
  (N'椅子', N'いす', N'Kỷ tử', N'Ghế', N'N5', N'N', NULL, 46, GETDATE()),
  (N'窓', N'まど', N'Song', N'Cửa sổ', N'N5', N'N', NULL, 47, GETDATE()),
  (N'英語', N'えいご', N'Anh ngữ', N'Tiếng Anh', N'N5', N'N', NULL, 48, GETDATE()),
  (N'日本語', N'にほんご', N'Nhật bản ngữ', N'Tiếng Nhật', N'N5', N'N', NULL, 49, GETDATE()),
  (N'違う', N'ちがう', N'Vi', N'Không phải', N'N5', N'N', NULL, 50, GETDATE()),
  (N'お土産', N'おみやげ', N'Thổ sản', N'Quà (chơi xa)', N'N5', N'N', NULL, 51, GETDATE()),
  (N'教室', N'きょうしつ', N'Giáo thất', N'Phòng học', N'N5', N'N', NULL, 52, GETDATE()),
  (N'食堂', N'しょくどう', N'Thực đường', N'Nhà ăn', N'N5', N'N', NULL, 53, GETDATE()),
  (N'事務所/　事務室', N'じむしょ', N'Sự vụ sở', N'Văn phòng', N'N5', N'N', NULL, 54, GETDATE()),
  (N'会議室', N'かいぎしつ', N'Hội nghị thất', N'Phòng họp', N'N5', N'N', NULL, 55, GETDATE()),
  (N'受付', N'うけつけ', N'Thụ phó', N'Phòng lễ tân', N'N5', N'N', NULL, 56, GETDATE()),
  (N'部屋', N'へや', N'Bộ ốc', N'Phòng', N'N5', N'N', NULL, 57, GETDATE()),
  (N'庭', N'にわ', N'Đình', N'Sân vườn', N'N5', N'N', NULL, 58, GETDATE()),
  (N'階段', N'かいだん', N'Giai đoạn', N'Cầu thang', N'N5', N'N', NULL, 59, GETDATE()),
  (N'「お」国', N'くに', N'Quốc', N'Đất nước', N'N5', N'N', NULL, 60, GETDATE()),
  (N'会社', N'かいしゃ', N'Hội xã', N'Công ty', N'N5', N'N', NULL, 61, GETDATE()),
  (N'家', N'うち', N'Gia', N'Nhà', N'N5', N'N', NULL, 62, GETDATE()),
  (N'靴', N'くつ', N'Ngoa', N'Giày', N'N5', N'N', NULL, 63, GETDATE()),
  (N'煙草', N'たばこ', N'Yên thảo', N'Thuốc lá', N'N5', N'N', NULL, 64, GETDATE()),
  (N'売り場', N'うりば', N'Mại trường', N'Nơi bán', N'N5', N'N', NULL, 65, GETDATE()),
  (N'自動販売機', N'じどうはんばいき', N'Tự động phiến mại cơ', N'Máy bán hàng tự động', N'N5', N'N', NULL, 66, GETDATE()),
  (N'地下', N'ちか', N'Địa hạ', N'Tầng hầm', N'N5', N'N', NULL, 67, GETDATE()),
  (N'―階', N'ーかい/がい', N'Giai', N'Tầng -', N'N5', N'N', NULL, 68, GETDATE()),
  (N'何階', N'なんがい', N'Hà giai', N'Tầng mấy', N'N5', N'N', NULL, 69, GETDATE()),
  (N'―円', N'えん', N'Viên', N'- yên', N'N5', N'N', NULL, 70, GETDATE()),
  (N'幾ら', N'いくら', N'Kỉ', N'Bao nhiêu tiền', N'N5', N'N', NULL, 71, GETDATE()),
  (N'百', N'ひゃく', N'Bách', N'Trăm', N'N5', N'N', NULL, 72, GETDATE()),
  (N'千', N'せん', N'Thiên', N'Nghìn', N'N5', N'N', NULL, 73, GETDATE()),
  (N'万', N'まん', N'Vạn', N'Vạn', N'N5', N'N', NULL, 74, GETDATE()),
  (N'起きる', N'おきる', N'Khởi', N'Thức dậy', N'N5', N'V', NULL, 75, GETDATE()),
  (N'寝る', N'ねる', N'Tẩm', N'Ngủ', N'N5', N'V', NULL, 76, GETDATE()),
  (N'働く', N'はたらく', N'Động', N'Làm việc', N'N5', N'V', NULL, 77, GETDATE()),
  (N'休む', N'やすむ', N'Hưu', N'Nghỉ', N'N5', N'V', NULL, 78, GETDATE()),
  (N'勉強する', N'べんきょうする', N'Miễn cường', N'Học', N'N5', N'V', NULL, 79, GETDATE()),
  (N'見学する', N'けんがくする', N'Kiến học', N'Kiến học', N'N5', N'V', NULL, 80, GETDATE()),
  (N'終わる', N'おわる', N'Chung', N'Kết thúc', N'N5', N'V', NULL, 81, GETDATE()),
  (N'銀行', N'ぎんこう', N'Ngân hàng', N'Ngân hàng', N'N5', N'N', NULL, 82, GETDATE()),
  (N'郵便局', N'ゆうびんきょく', N'Bưu tiện cục', N'Bưu điện', N'N5', N'N', NULL, 83, GETDATE()),
  (N'図書館', N'としょかん', N'Đồ thư quán', N'Thư viện', N'N5', N'N', NULL, 84, GETDATE()),
  (N'美術館', N'びじゅつかん', N'Mỹ thuật quán', N'Bảo tàng mỹ thuật', N'N5', N'N', NULL, 85, GETDATE()),
  (N'今', N'いま', N'Kim', N'Bây giờ', N'N5', N'N', NULL, 86, GETDATE()),
  (N'―時', N'じ', N'Thời', N'-giờ', N'N5', N'N', NULL, 87, GETDATE()),
  (N'―分', N'ふん/ぶん', N'Phân', N'-phút', N'N5', N'N', NULL, 88, GETDATE()),
  (N'何時', N'なんじ', N'Hà thời', N'Mấy giờ', N'N5', N'N', NULL, 89, GETDATE()),
  (N'何分', N'なんぶん', N'Hà phân', N'Mấy phút', N'N5', N'N', NULL, 90, GETDATE()),
  (N'午前', N'ごぜん', N'Ngọ tiền', N'Buổi sáng', N'N5', N'N', NULL, 91, GETDATE()),
  (N'午後', N'ごご', N'Ngọ hậu', N'Buổi chiều', N'N5', N'N', NULL, 92, GETDATE()),
  (N'朝', N'あさ', N'Triều', N'Sáng', N'N5', N'N', NULL, 93, GETDATE()),
  (N'昼', N'ひる', N'Trú', N'Trưa', N'N5', N'N', NULL, 94, GETDATE()),
  (N'晩　/　夜', N'ばん/よる', N'Vãn / dạ', N'Tối / đêm', N'N5', N'N', NULL, 95, GETDATE()),
  (N'毎朝', N'まいあさ', N'Mỗi triều', N'Hàng sáng', N'N5', N'N', NULL, 96, GETDATE()),
  (N'毎晩', N'まいばん', N'Mỗi vãn', N'Hàng tối', N'N5', N'N', NULL, 97, GETDATE()),
  (N'毎日', N'まいにち', N'Mỗi nhật', N'Hàng ngày', N'N5', N'N', NULL, 98, GETDATE()),
  (N'一昨日', N'おととい', N'Nhất tác minh', N'Hôm kia', N'N5', N'N', NULL, 99, GETDATE()),
  (N'昨日', N'きのう', NULL, N'Hôm qua', N'N5', N'N', NULL, 100, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'今日', N'きょう', NULL, N'Hôm nay', N'N5', N'N', NULL, 101, GETDATE()),
  (N'明日', N'あした', N'Minh', N'Ngày mai', N'N5', N'N', NULL, 102, GETDATE()),
  (N'明後日', N'あっさて', N'Minh hậu nhật', N'Ngày kia', N'N5', N'N', NULL, 103, GETDATE()),
  (N'今朝', N'けさ', N'Kim triều', N'Sáng nay', N'N5', N'N', NULL, 104, GETDATE()),
  (N'今晩', N'こんばん', N'Kim vãn', N'Tối nay', N'N5', N'N', NULL, 105, GETDATE()),
  (N'昼休み', N'ひるやすみ', N'Trú hưu', N'Nghỉ trưa', N'N5', N'N', NULL, 106, GETDATE()),
  (N'講義', N'こうぎ', N'Giảng nghĩa', N'Bài giảng', N'N5', N'N', NULL, 107, GETDATE()),
  (N'日曜日', N'にちようび', N'Nhật diệu', N'Chủ nhật', N'N5', N'N', NULL, 108, GETDATE()),
  (N'月曜日', N'けつようび', N'Nguyệt', N'Thứ 2', N'N5', N'N', NULL, 109, GETDATE()),
  (N'火曜日', N'かようび', N'Hỏa', N'Thứ 3', N'N5', N'N', NULL, 110, GETDATE()),
  (N'水曜日', N'すいようび', N'Thủy', N'Thứ 4', N'N5', N'N', NULL, 111, GETDATE()),
  (N'木曜日', N'もくようび', N'Mộc', N'Thứ 5', N'N5', N'N', NULL, 112, GETDATE()),
  (N'金曜日', N'きんようび', N'Kim', N'Thứ 6', N'N5', N'N', NULL, 113, GETDATE()),
  (N'土曜日', N'どようび', N'Thổ', N'Thứ 7', N'N5', N'N', NULL, 114, GETDATE()),
  (N'何曜日', N'なんようび', NULL, N'Thứ mấy', N'N5', N'N', NULL, 115, GETDATE()),
  (N'番号', N'ばんごう', N'Phiên hiệu', N'Số', N'N5', N'N', NULL, 116, GETDATE()),
  (N'何番', N'なんばん', NULL, N'Số mấy', N'N5', N'N', NULL, 117, GETDATE()),
  (N'大変ですね', N'たいへんですね', N'Đại biến', N'Vất vả quá nhỉ.', N'N5', N'N', NULL, 118, GETDATE()),
  (N'お願いします', N'おねがいします', N'Nguyện', N'Làm ơn...', N'N5', N'N', NULL, 119, GETDATE()),
  (N'行く', N'いく', N'Hành', N'Đi', N'N5', N'V', NULL, 120, GETDATE()),
  (N'来る', N'くる', N'Lai', N'Đến', N'N5', N'V', NULL, 121, GETDATE()),
  (N'帰る', N'かえる', N'Quy', N'Về', N'N5', N'V', NULL, 122, GETDATE()),
  (N'学校', N'がっこう', N'Học hiệu', N'Trường học', N'N5', N'N', NULL, 123, GETDATE()),
  (N'小学校', N'しょうがっこう', N'Tiểu học hiệu', N'Trường cấp 1', N'N5', N'N', NULL, 124, GETDATE()),
  (N'中学校', N'ちゅうがっこう', N'Trung học hiệu', N'Trường cấp 2', N'N5', N'N', NULL, 125, GETDATE()),
  (N'高校', N'こうこう', N'Cao hiệu', N'Trường cấp 3', N'N5', N'N', NULL, 126, GETDATE()),
  (N'市場', N'いちば', N'Thị trường', N'Chợ', N'N5', N'N', NULL, 127, GETDATE()),
  (N'駅', N'えき', N'Dịch', N'Nhà ga', N'N5', N'N', NULL, 128, GETDATE()),
  (N'工場', N'こうじょう', N'Công trường', N'Công trường', N'N5', N'N', NULL, 129, GETDATE()),
  (N'企業', N'きぎょう', N'Xí nghiệp', N'Xí nghiệp', N'N5', N'N', NULL, 130, GETDATE()),
  (N'～屋', N'～や', N'ốc', N'Hiệu, cửa hàng', N'N5', N'N', NULL, 131, GETDATE()),
  (N'故郷', N'ふるさと/こきょう', N'Cố hương', N'Quê hương', N'N5', N'N', NULL, 132, GETDATE()),
  (N'公園', N'こうえん', N'Công viên', N'Công viên', N'N5', N'N', NULL, 133, GETDATE()),
  (N'空港', N'くうこう', N'Không cảng', N'Sân bay', N'N5', N'N', NULL, 134, GETDATE()),
  (N'飛行機', N'ひこうき', N'Phi hành cơ', N'Máy bay', N'N5', N'N', NULL, 135, GETDATE()),
  (N'船', N'ふね', N'Thuyền', N'Thuyền', N'N5', N'N', NULL, 136, GETDATE()),
  (N'電車', N'でんしゃ', N'Điện xa', N'Tàu điện', N'N5', N'N', NULL, 137, GETDATE()),
  (N'新幹線', N'しんかんせん', N'Tân cán tuyến', N'Tàu siêu tốc', N'N5', N'N', NULL, 138, GETDATE()),
  (N'地下鉄', N'ちかてつ', N'Địa hạ thiết', N'Tàu điện ngầm', N'N5', N'N', NULL, 139, GETDATE()),
  (N'普通', N'ふつう', N'Phổ thông', N'Tàu thường', N'N5', N'N', NULL, 140, GETDATE()),
  (N'急行', N'きゅうこう', N'Cấp hành', N'Tàu nhanh', N'N5', N'N', NULL, 141, GETDATE()),
  (N'特急', N'とっきゅう', N'Đặc cấp', N'Tàu tốc hành', N'N5', N'N', NULL, 142, GETDATE()),
  (N'自転車', N'じてんしゃ', N'Tự chuyển xa', N'Xe đạp', N'N5', N'N', NULL, 143, GETDATE()),
  (N'歩いて', N'あるいて', N'Bộ', N'Đi bộ', N'N5', N'N', NULL, 144, GETDATE()),
  (N'人', N'ひと', N'Nhân', N'Người', N'N5', N'N', NULL, 145, GETDATE()),
  (N'友達', N'ともだち', N'Hữu đạt', N'Bạn bè', N'N5', N'N', NULL, 146, GETDATE()),
  (N'恋人', N'こいびと', N'Luyến', N'Người yêu', N'N5', N'N', NULL, 147, GETDATE()),
  (N'彼', N'かれ', N'Bỉ', N'Anh ấy', N'N5', N'N', NULL, 148, GETDATE()),
  (N'彼女', N'かのじょ', N'Bỉ nữ', N'Cô ấy', N'N5', N'N', NULL, 149, GETDATE()),
  (N'家族', N'かぞく', N'Gia tộc', N'Gia đình', N'N5', N'N', NULL, 150, GETDATE()),
  (N'一人で', N'ひとりで', NULL, N'Một mình', N'N5', N'N', NULL, 151, GETDATE()),
  (N'先週/先月/去年', N'先週/先月/去年', N'Chu, nguyệt, niên', N'Tuần/Tháng/Năm trước', N'N5', N'N', NULL, 152, GETDATE()),
  (N'今週/今月/今年', N'今週/今月/今年', NULL, N'Tuần/Tháng/Năm nay', N'N5', N'N', NULL, 153, GETDATE()),
  (N'来週/来月/来年', N'来週/来月/来年', NULL, N'Tuần/Tháng/Năm sau', N'N5', N'N', NULL, 154, GETDATE()),
  (N'週末', N'しゅうまつ', N'Chu mạt', N'Cuối tuần', N'N5', N'N', NULL, 155, GETDATE()),
  (N'誕生日', N'たんじょうび', N'Đản sinh nhật', N'Ngày sinh nhật', N'N5', N'N', NULL, 156, GETDATE()),
  (N'～番線', N'～ばんせん', N'Phiên tuyến', N'Chuyến số -', N'N5', N'N', NULL, 157, GETDATE()),
  (N'次の', N'つぎの', N'Thứ', N'Tiếp theo', N'N5', N'N', NULL, 158, GETDATE()),
  (N'食べる', N'たべる', N'Thực', N'Ăn', N'N5', N'V', NULL, 159, GETDATE()),
  (N'飲む', N'のむ', N'Ẩm', N'Uống', N'N5', N'V', NULL, 160, GETDATE()),
  (N'吸う', N'すう', N'Hấp', N'Hút', N'N5', N'V', NULL, 161, GETDATE()),
  (N'見る', N'みる', N'Kiến', N'Xem, nhìn', N'N5', N'V', NULL, 162, GETDATE()),
  (N'聞く', N'きく', N'Văn', N'Nghe, hỏi', N'N5', N'V', NULL, 163, GETDATE()),
  (N'書く', N'かく', N'Thư', N'Viết, vẽ', N'N5', N'V', NULL, 164, GETDATE()),
  (N'読む', N'よむ', N'Độc', N'Đọc', N'N5', N'V', NULL, 165, GETDATE()),
  (N'買う', N'かう', N'Mãi', N'Mua', N'N5', N'V', NULL, 166, GETDATE()),
  (N'撮る', N'とる', N'Toát', N'Chụp', N'N5', N'V', NULL, 167, GETDATE()),
  (N'会う', N'かう', N'Hội', N'Gặp', N'N5', N'V', NULL, 168, GETDATE()),
  (N'実習する', N'じっしゅうする', N'Thực tập', N'Thực hành', N'N5', N'V', NULL, 169, GETDATE()),
  (N'ご飯', N'ごはん', N'Phãn', N'Cơm, bữa ăn', N'N5', N'N', NULL, 170, GETDATE()),
  (N'朝ご飯', N'あさごはん', NULL, N'Cơm sáng', N'N5', N'N', NULL, 171, GETDATE()),
  (N'昼ご飯', N'ひるごはん', NULL, N'Cơm trưa', N'N5', N'N', NULL, 172, GETDATE()),
  (N'晩ご飯', N'ばんごはん', NULL, N'Cơm tối', N'N5', N'N', NULL, 173, GETDATE()),
  (N'卵', N'たまご', N'Noãn', N'Trứng', N'N5', N'N', NULL, 174, GETDATE()),
  (N'煙草', N'たばこ', N'Yên thảo', N'Thuốc lá', N'N5', N'N', NULL, 175, GETDATE()),
  (N'肉', N'にく', N'Nhục', N'Thịt', N'N5', N'N', NULL, 176, GETDATE()),
  (N'魚', N'さかな', N'Ngư', N'Cá', N'N5', N'N', NULL, 177, GETDATE()),
  (N'果物', N'くだもの', N'Quả vật', N'Hoa quả', N'N5', N'N', NULL, 178, GETDATE()),
  (N'水', N'みず', N'Thủy', N'Nước', N'N5', N'N', NULL, 179, GETDATE()),
  (N'お茶', N'おちゃ', N'Trà', N'Trà', N'N5', N'N', NULL, 180, GETDATE()),
  (N'紅茶', N'こうちゃ', N'Hồng trà', N'Trà đen', N'N5', N'N', NULL, 181, GETDATE()),
  (N'牛乳　/　ミルク', N'ぎゅうにゅう', N'Ngưu nhũ', N'Sữa bò', N'N5', N'N', NULL, 182, GETDATE()),
  (N'「お」酒', N'おさけ', N'Tửu', N'Rượu sake', N'N5', N'N', NULL, 183, GETDATE()),
  (N'映画', N'えいが', N'Ánh họa', N'phim', N'N5', N'N', NULL, 184, GETDATE()),
  (N'写真', N'しゃしん', N'Tả chân', N'Ảnh', N'N5', N'N', NULL, 185, GETDATE()),
  (N'店', N'みせ', N'Điếm', N'Cửa hàng', N'N5', N'N', NULL, 186, GETDATE()),
  (N'宿題', N'しゅくだい', N'Túc đề', N'Bài tập', N'N5', N'N', NULL, 187, GETDATE()),
  (N'一緒に', N'いっしょに', N'Tự', N'Cùng nhau', N'N5', N'N', NULL, 188, GETDATE()),
  (N'時々', N'ときどき', NULL, N'Thỉnh thoảng', N'N5', N'N', NULL, 189, GETDATE()),
  (N'分かった', N'わかった', NULL, N'Tôi hiểu rồi, được rồi', N'N5', N'N', NULL, 190, GETDATE()),
  (N'何ですか', N'なんですか', NULL, N'Gì vậy, cái gì vậy', N'N5', N'N', NULL, 191, GETDATE()),
  (N'じゃ、また明日', N'じゃ、またあした', NULL, N'Hẹn gặp lại ngày mai', N'N5', N'N', NULL, 192, GETDATE()),
  (N'切る', N'きる', N'Thiết', N'Cắt', N'N5', N'V', NULL, 193, GETDATE()),
  (N'送る', N'おくる', N'Tống', N'Gửi', N'N5', N'V', NULL, 194, GETDATE()),
  (N'上げる', N'あげる', N'Thượng', N'Cho, biếu, tặng', N'N5', N'V', NULL, 195, GETDATE()),
  (N'貰う', N'もらう', N'Thế', N'Nhận', N'N5', N'V', NULL, 196, GETDATE()),
  (N'貸す', N'かす', N'Thải', N'Cho mượn/thuê', N'N5', N'V', NULL, 197, GETDATE()),
  (N'借りる', N'かりる', N'Tá', N'Mượn, thuê', N'N5', N'V', NULL, 198, GETDATE()),
  (N'教える', N'おしえる', N'Giáo', N'Dạy, chỉ bảo', N'N5', N'V', NULL, 199, GETDATE()),
  (N'習う', N'ならう', N'Tập', N'Học (từ ai)', N'N5', N'V', NULL, 200, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'修理する', N'しゅうりする', N'Tu lý', N'Sửa chữa', N'N5', N'V', NULL, 201, GETDATE()),
  (N'手', N'て', N'Thủ', N'Tay', N'N5', N'N', NULL, 202, GETDATE()),
  (N'箸', N'はし', N'Trứ', N'Đũa', N'N5', N'N', NULL, 203, GETDATE()),
  (N'鋏', N'はさみ', N'Kiệp', N'Cái kéo', N'N5', N'N', NULL, 204, GETDATE()),
  (N'消しゴム', N'けしゴム', N'Tiêu', N'Cục tẩy', N'N5', N'N', NULL, 205, GETDATE()),
  (N'お金', N'おかね', N'Kim', N'Tiền', N'N5', N'N', NULL, 206, GETDATE()),
  (N'花', N'はな', N'Hoa', N'Hoa', N'N5', N'N', NULL, 207, GETDATE()),
  (N'荷物', N'にもつ', N'Hạ vật', N'Hành lý', N'N5', N'N', NULL, 208, GETDATE()),
  (N'切符', N'きっぷ', N'Thiết phù', N'Vé (tàu xe)', N'N5', N'N', NULL, 209, GETDATE()),
  (N'切手', N'きって', N'Thiết thủ', N'Tem', N'N5', N'N', NULL, 210, GETDATE()),
  (N'家族', N'かぞく', N'Gia tộc', N'Gia đình', N'N5', N'N', NULL, 211, GETDATE()),
  (N'父', N'ちち', N'Phụ', N'Bố (m)', N'N5', N'N', NULL, 212, GETDATE()),
  (N'お父さん', N'おとうさん', NULL, N'Bố (k)', N'N5', N'N', NULL, 213, GETDATE()),
  (N'母', N'はは', N'Mẫu', N'Mẹ (m)', N'N5', N'N', NULL, 214, GETDATE()),
  (N'お母さん', N'おかあさん', NULL, N'Mẹ (k)', N'N5', N'N', NULL, 215, GETDATE()),
  (N'兄', N'あに', N'Huynh', N'Anh trai (m)', N'N5', N'N', NULL, 216, GETDATE()),
  (N'お兄さん', N'おにいさん', NULL, N'Anh trai (k)', N'N5', N'N', NULL, 217, GETDATE()),
  (N'姉', N'あね', N'Tỉ', N'Chị gái (m)', N'N5', N'N', NULL, 218, GETDATE()),
  (N'お姉さん', N'おねえさん', NULL, N'Chị gái (k)', N'N5', N'N', NULL, 219, GETDATE()),
  (N'弟', N'おとうと', N'Đệ', N'Em trai (m)', N'N5', N'N', NULL, 220, GETDATE()),
  (N'弟さん', N'おとうとさん', NULL, N'Em trai (k)', N'N5', N'N', NULL, 221, GETDATE()),
  (N'妹', N'いもうと', N'Muội', N'Em gái (m)', N'N5', N'N', NULL, 222, GETDATE()),
  (N'妹さん', N'いもうとさん', NULL, N'Em gái (k)', N'N5', N'N', NULL, 223, GETDATE()),
  (N'家内　/　妻', N'かない/つま', N'Gia nội / Thê', N'Vợ (m)', N'N5', N'N', NULL, 224, GETDATE()),
  (N'奥さん', N'おくさん', N'Áo', N'Vợ (k)', N'N5', N'N', NULL, 225, GETDATE()),
  (N'主人　/　夫', N'しゅじん/おっと', N'Chủ nhân', N'Chồng (m)', N'N5', N'N', NULL, 226, GETDATE()),
  (N'ご主人', N'ごしゅじん', NULL, N'Chồng (k)', N'N5', N'N', NULL, 227, GETDATE()),
  (N'子供', N'こども', N'Tử cung', N'Con', N'N5', N'N', NULL, 228, GETDATE()),
  (N'～素敵ですね', N'すてきですね', N'Tố địch', N'Đẹp/tuyệt nhỉ', N'N5', N'N', NULL, 229, GETDATE()),
  (N'旅行', N'りょこう', N'Lữ hành', N'Du lịch', N'N5', N'A', NULL, 230, GETDATE()),
  (N'奇麗　（な）', N'きれい', N'Kì lệ', N'Xinh đẹp, sạch', N'N5', N'A', NULL, 231, GETDATE()),
  (N'静か　（な）', N'しずか', N'Tĩnh', N'Yên tĩnh', N'N5', N'A', NULL, 232, GETDATE()),
  (N'賑やか（な）', N'にぎやか', N'Chẩn', N'Náo nhiệt', N'N5', N'A', NULL, 233, GETDATE()),
  (N'有名　（な）', N'ゆうめい', N'Hữu danh', N'Nổi tiếng', N'N5', N'A', NULL, 234, GETDATE()),
  (N'親切　（な）', N'しんせつ', N'Thân thiết', N'Thân thiện', N'N5', N'A', NULL, 235, GETDATE()),
  (N'元気　（な）', N'げんき', N'Nguyên khí', N'Khỏe mạnh', N'N5', N'A', NULL, 236, GETDATE()),
  (N'暇　　（な）', N'ひま', N'Hạ', N'Rảnh rỗi', N'N5', N'A', NULL, 237, GETDATE()),
  (N'便利　（な）', N'べんり', N'Tiện lợi', N'Tiện lợi', N'N5', N'A', NULL, 238, GETDATE()),
  (N'素敵　（な）', N'すてき', N'Tố địch', N'Tuyệt vời', N'N5', N'A', NULL, 239, GETDATE()),
  (N'大きい/大きな', N'おおきい', N'Đại', N'To', N'N5', N'A', NULL, 240, GETDATE()),
  (N'小さい/小さな', N'ちいさい', N'Tiểu', N'Nhỏ', N'N5', N'A', NULL, 241, GETDATE()),
  (N'新しい', N'あたらしい', N'Tân', N'Mới', N'N5', N'A', NULL, 242, GETDATE()),
  (N'古い', N'ふるい', N'Cổ', N'Cũ', N'N5', N'A', NULL, 243, GETDATE()),
  (N'良い', N'いい', N'Lương', N'Tốt', N'N5', N'A', NULL, 244, GETDATE()),
  (N'悪い', N'わるい', N'Ác', N'Xấu', N'N5', N'A', NULL, 245, GETDATE()),
  (N'暑い', N'あつい', N'Thử', N'Nóng (thời tiết)', N'N5', N'A', NULL, 246, GETDATE()),
  (N'寒い', N'さむい', N'Hàn', N'Lạnh (thời tiết)', N'N5', N'A', NULL, 247, GETDATE()),
  (N'冷たい', N'つめたい', N'Lãnh', N'Lạnh (người)', N'N5', N'A', NULL, 248, GETDATE()),
  (N'難しい', N'むずかしい', N'Nan', N'Khó', N'N5', N'A', NULL, 249, GETDATE()),
  (N'易しい', N'やさしい', N'Dị', N'Dễ', N'N5', N'A', NULL, 250, GETDATE()),
  (N'高い', N'たかい', N'Cao', N'Cao, đắt', N'N5', N'A', NULL, 251, GETDATE()),
  (N'安い', N'やすい', N'An', N'Rẻ', N'N5', N'A', NULL, 252, GETDATE()),
  (N'低い', N'ひくい', N'Đê', N'Thấp (người)', N'N5', N'A', NULL, 253, GETDATE()),
  (N'面白い', N'おもしろい', N'Diện bạch', N'Thú vị, hay', N'N5', N'A', NULL, 254, GETDATE()),
  (N'美味しい', N'おいしい', N'Mĩ vị', N'Ngon', N'N5', N'A', NULL, 255, GETDATE()),
  (N'忙しい', N'いそがしい', N'Mang', N'Bận rộn', N'N5', N'A', NULL, 256, GETDATE()),
  (N'楽しい', N'たのしい', N'Lạc', N'Vui (bữa tiệc)', N'N5', N'A', NULL, 257, GETDATE()),
  (N'白い', N'しろい', N'Bạch', N'Màu trắng', N'N5', N'A', NULL, 258, GETDATE()),
  (N'黒い', N'くろい', N'Hắc', N'Màu đen', N'N5', N'A', NULL, 259, GETDATE()),
  (N'赤い', N'あかい', N'Xích', N'Màu đỏ', N'N5', N'A', NULL, 260, GETDATE()),
  (N'青い', N'あおい', N'Thanh', N'Màu xanh', N'N5', N'A', NULL, 261, GETDATE()),
  (N'桜', N'さくら', N'Anh', N'Hoa anh đào', N'N5', N'N', NULL, 262, GETDATE()),
  (N'富士山', N'ふじさん', N'Phú sĩ sơn', N'Núi Phú Sĩ', N'N5', N'N', NULL, 263, GETDATE()),
  (N'山', N'やま', N'Sơn', N'Núi', N'N5', N'N', NULL, 264, GETDATE()),
  (N'町', N'まち', N'Đinh', N'Phố, thị trấn', N'N5', N'N', NULL, 265, GETDATE()),
  (N'食べ物', N'たべもの', N'Thực vật', N'Đồ ăn', N'N5', N'N', NULL, 266, GETDATE()),
  (N'飲み物', N'のみもの', N'Ẩm vật', N'Đồ uống', N'N5', N'N', NULL, 267, GETDATE()),
  (N'所', N'ところ', N'Sở', N'Nơi, chỗ', N'N5', N'N', NULL, 268, GETDATE()),
  (N'寮', N'りょう', N'Liêu', N'Ký túc xá', N'N5', N'N', NULL, 269, GETDATE()),
  (N'生活', N'せいかつ', N'Sinh hoạt', N'Cuộc sống', N'N5', N'N', NULL, 270, GETDATE()),
  (N'「お」仕事', N'おしごと', N'Sĩ sự', N'Công việc', N'N5', N'N', NULL, 271, GETDATE()),
  (N'大変', N'たいへん', N'Đại biến', N'Vô cùng, vất vả', N'N5', N'N', NULL, 272, GETDATE()),
  (N'暫くですね', N'しばらくですね', N'Tạm', N'Lâu rồi mới gặp nhỉ', N'N5', N'N', NULL, 273, GETDATE()),
  (N'お久しぶりですね', N'おひさしぶりですね', N'Cửu', N'Lâu lắm rồi mới gặp nhỉ', N'N5', N'N', NULL, 274, GETDATE()),
  (N'いいえ、結構です', N'いいえ、けっこうです', N'Kết cấu', N'Không, tôi dùng đủ rồi', N'N5', N'N', NULL, 275, GETDATE()),
  (N'分かる', N'わかる', N'Phân', N'Hiểu', N'N5', N'V', NULL, 276, GETDATE()),
  (N'好き　（な）', N'すき', N'Hảo', N'Thích', N'N5', N'A', NULL, 277, GETDATE()),
  (N'嫌い　（な）', N'きらい', N'Hiềm', N'Ghét', N'N5', N'A', NULL, 278, GETDATE()),
  (N'上手　（な）', N'じょうず', N'Thượng thủ', N'Giỏi', N'N5', N'A', NULL, 279, GETDATE()),
  (N'下手　（な）', N'へた', N'Hạ thủ', N'Kém', N'N5', N'A', NULL, 280, GETDATE()),
  (N'料理', N'りょうり', N'Liệu lý', N'Món ăn', N'N5', N'N', NULL, 281, GETDATE()),
  (N'豚肉', N'ぶたにく', N'Độn nhục', N'Thịt lợn', N'N5', N'N', NULL, 282, GETDATE()),
  (N'鳥肉', N'とりにく', N'Điểu nhục', N'Thịt gà', N'N5', N'N', NULL, 283, GETDATE()),
  (N'牛肉', N'ぎゅうにく', N'Ngưu nhục', N'Thịt bò', N'N5', N'N', NULL, 284, GETDATE()),
  (N'野球', N'やきゅう', N'Dã cầu', N'Bóng chày', N'N5', N'N', NULL, 285, GETDATE()),
  (N'音楽', N'おんがく', N'Âm nhạc', N'Âm nhạc', N'N5', N'N', NULL, 286, GETDATE()),
  (N'歌', N'うた', N'Ca', N'Bài hát', N'N5', N'N', NULL, 287, GETDATE()),
  (N'歌舞伎', N'かぶき', N'Ca vũ kĩ', N'Kịch Kabuki', N'N5', N'N', NULL, 288, GETDATE()),
  (N'絵', N'え', N'Hội', N'Tranh', N'N5', N'N', NULL, 289, GETDATE()),
  (N'字', N'じ', N'Tự', N'Chữ', N'N5', N'N', NULL, 290, GETDATE()),
  (N'平仮名', N'ひらがな', N'Bình giả danh', N'Chữ mềm', N'N5', N'N', NULL, 292, GETDATE()),
  (N'細かいお金', N'こまかいおかね', N'Tế', N'Tiền lẻ', N'N5', N'N', NULL, 293, GETDATE()),
  (N'時間', N'じかん', N'Thời gian', N'Thời gian', N'N5', N'N', NULL, 294, GETDATE()),
  (N'用事', N'ようじ', N'Dụng sự', N'Việc bận', N'N5', N'N', NULL, 295, GETDATE()),
  (N'約束', N'やくそく', N'Ước thúc', N'Có hẹn, lời hứa', N'N5', N'N', NULL, 296, GETDATE()),
  (N'よく', N'よく', NULL, N'Hay, thường', N'N5', N'N', NULL, 297, GETDATE()),
  (N'大体', N'だいたい', N'Đại thể', N'Đại khái', N'N5', N'N', NULL, 298, GETDATE()),
  (N'沢山', N'たくさん', N'Trạch sơn', N'Nhiều', N'N5', N'N', NULL, 299, GETDATE()),
  (N'少し', N'すこし', N'Thiểu', N'Một chút, một ít', N'N5', N'N', NULL, 300, GETDATE()),
  (N'全然', N'ぜんぜん', N'Toàn nhiên', N'Hoàn toàn..không', N'N5', N'N', NULL, 301, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'勿論', N'もちろん', N'Vật luận', N'Tất nhiên', N'N5', N'N', NULL, 302, GETDATE()),
  (N'速く　/　早く', N'はやく', N'Tốc / Tảo', N'Nhanh, sớm', N'N5', N'N', NULL, 303, GETDATE()),
  (N'病気', N'びょうき', N'Bệnh khí', N'Bị bệnh', N'N5', N'N', NULL, 304, GETDATE()),
  (N'薬', N'くすり', N'Dược', N'Thuốc', N'N5', N'N', NULL, 305, GETDATE()),
  (N'頭', N'あたま', N'Đầu', N'Đầu', N'N5', N'N', NULL, 306, GETDATE()),
  (N'お腹', N'おなか', N'Phúc', N'Bụng', N'N5', N'N', NULL, 307, GETDATE()),
  (N'痛い', N'いたい', N'Thống', N'Bị đau', N'N5', N'N', NULL, 308, GETDATE()),
  (N'熱がある', N'ねつがある', N'Nhiệt', N'Bị sốt', N'N5', N'N', NULL, 309, GETDATE()),
  (N'風邪を引く', N'かぜをひく', N'Phong tà', N'Bị cảm', N'N5', N'N', NULL, 310, GETDATE()),
  (N'残念ですね', N'ざんねんですね', N'Tàn niệm', N'Tiếc nhỉ', N'N5', N'N', NULL, 311, GETDATE()),
  (N'駄目ですか', N'だめですか', N'Đả mục', N'Không được à', N'N5', N'N', NULL, 312, GETDATE()),
  (N'色々　（な）', N'いろいろ', N'Sắc', N'Nhiều loại', N'N5', N'N', NULL, 313, GETDATE()),
  (N'男の人', N'おとこのひと', N'Nam', N'Người con trai', N'N5', N'N', NULL, 314, GETDATE()),
  (N'女の人', N'おんなのひと', N'Nữ', N'Người con gái', N'N5', N'N', NULL, 315, GETDATE()),
  (N'男の子', N'おとこのこ', NULL, N'Bé trai', N'N5', N'N', NULL, 316, GETDATE()),
  (N'女の子', N'おんなのこ', NULL, N'Bé gái', N'N5', N'N', NULL, 317, GETDATE()),
  (N'犬', N'いぬ', N'Khuyển', N'Con chó', N'N5', N'N', NULL, 318, GETDATE()),
  (N'猫', N'ねこ', N'Miêu', N'Con mèo', N'N5', N'N', NULL, 319, GETDATE()),
  (N'象', N'ぞう', N'Tượng', N'Con voi', N'N5', N'N', NULL, 320, GETDATE()),
  (N'木', N'き', N'Mộc', N'Cây', N'N5', N'N', NULL, 321, GETDATE()),
  (N'物', N'もの', N'Vật', N'Đồ vật', N'N5', N'N', NULL, 322, GETDATE()),
  (N'電池', N'でんち', N'Điện trì', N'Pin', N'N5', N'N', NULL, 323, GETDATE()),
  (N'冷蔵庫', N'れいぞうこ', N'Lãnh tàng khố', N'Tủ lạnh', N'N5', N'N', NULL, 324, GETDATE()),
  (N'机', N'つくえ', N'Kỷ', N'Bàn làm việc', N'N5', N'N', NULL, 325, GETDATE()),
  (N'棚', N'たな', N'Bằng', N'Ngăn, kệ', N'N5', N'N', NULL, 326, GETDATE()),
  (N'公園', N'こうえん', N'Công viên', N'Công viên', N'N5', N'N', NULL, 327, GETDATE()),
  (N'喫茶店', N'きっさてん', N'Khiết trà điếm', N'Quán nước giải khát', N'N5', N'N', NULL, 328, GETDATE()),
  (N'乗り場', N'のりば', N'Thừa trường', N'Điểm lên xe', N'N5', N'N', NULL, 329, GETDATE()),
  (N'県', N'けん', N'Huyện', N'Huyện', N'N5', N'N', NULL, 330, GETDATE()),
  (N'上', N'うえ', N'Thượng', N'Trên', N'N5', N'N', NULL, 331, GETDATE()),
  (N'下', N'した', N'Hạ', N'Dưới', N'N5', N'N', NULL, 332, GETDATE()),
  (N'前', N'まえ', N'Tiền', N'Trước', N'N5', N'N', NULL, 333, GETDATE()),
  (N'後ろ', N'後ろ', N'Hậu', N'Sau', N'N5', N'N', NULL, 334, GETDATE()),
  (N'右', N'みぎ', N'Hữu', N'Phải', N'N5', N'N', NULL, 335, GETDATE()),
  (N'左', N'ひだり', N'Tả', N'Trái', N'N5', N'N', NULL, 336, GETDATE()),
  (N'中', N'なか', N'Trung', N'Trong', N'N5', N'N', NULL, 337, GETDATE()),
  (N'外', N'そと', N'Ngoại', N'Ngoài', N'N5', N'N', NULL, 338, GETDATE()),
  (N'隣', N'となり', N'Lân', N'Bên cạnh', N'N5', N'N', NULL, 339, GETDATE()),
  (N'側', N'そば', N'Trắc', N'Bên cạnh', N'N5', N'N', NULL, 340, GETDATE()),
  (N'横', N'よこ', N'Hoành', N'Bên cạnh', N'N5', N'N', NULL, 341, GETDATE()),
  (N'近く', N'ちかく', N'Cận', N'Gần', N'N5', N'N', NULL, 342, GETDATE()),
  (N'間', N'あいだ', N'Gian', N'Giữa', N'N5', N'N', NULL, 343, GETDATE()),
  (N'真ん中', N'まんなか', N'Chân trung', N'Chính giữa', N'N5', N'N', NULL, 344, GETDATE()),
  (N'向こう', N'むこう', N'Hướng', N'Đối diện, bên kia', N'N5', N'N', NULL, 345, GETDATE()),
  (N'周り', N'まわり', N'Chu', N'Xung quanh', N'N5', N'N', NULL, 346, GETDATE()),
  (N'一番', N'いちばん', N'Phiên', N'Nhất', N'N5', N'N', NULL, 347, GETDATE()),
  (N'段目', N'だんめ', N'Đoạn mục', N'Ngăn thứ -', N'N5', N'N', NULL, 348, GETDATE()),
  (N'地図', N'ちず', N'Địa đồ', N'Bản đồ', N'N5', N'N', NULL, 349, GETDATE()),
  (N'大使館', N'たいしかん', N'Đại sứ quán', N'Đại sự quán', N'N5', N'N', NULL, 350, GETDATE()),
  (N'奥', N'おく', N'Áo', N'Phía trong cùng', N'N5', N'N', NULL, 351, GETDATE()),
  (N'葉書', N'はがき', N'Diệp thư', N'Bưu thiếp', N'N5', N'N', NULL, 352, GETDATE()),
  (N'封筒', N'ふうとう', N'Phong đồng', N'Phong bì', N'N5', N'N', NULL, 353, GETDATE()),
  (N'速達', N'そくたつ', N'Tốc đạt', N'Chuyển phát nhanh', N'N5', N'N', NULL, 354, GETDATE()),
  (N'書留', N'かきとめ', N'Thư lưu', N'Gửi bảo đảm', N'N5', N'N', NULL, 355, GETDATE()),
  (N'航空便', N'こうくうびん', N'Hàng không tiện', N'Đường bưu điện hàng không', N'N5', N'N', NULL, 356, GETDATE()),
  (N'船便', N'ふなびん', N'Thuyền tiện', N'Bưu điện đường thủy', N'N5', N'N', NULL, 357, GETDATE()),
  (N'両親', N'りょうしん', N'Lưỡng thân', N'Bố mẹ', N'N5', N'N', NULL, 358, GETDATE()),
  (N'兄弟', N'きょうだい', N'Huynh đệ', N'Anh em', N'N5', N'N', NULL, 359, GETDATE()),
  (N'外国', N'がいこく', N'Ngoại quốc', N'Nước ngoài', N'N5', N'N', NULL, 360, GETDATE()),
  (N'一日', N'いちにち', NULL, N'1 ngày', N'N5', N'N', NULL, 361, GETDATE()),
  (N'～時間', N'じかん', N'Thời gian', N'~ tiếng', N'N5', N'N', NULL, 362, GETDATE()),
  (N'～週間', N'しゅうかん', N'Chu gian', N'~ tuần', N'N5', N'N', NULL, 363, GETDATE()),
  (N'～ヶ月', N'かげつ', N'Nguyệt', N'~ tháng', N'N5', N'N', NULL, 364, GETDATE()),
  (N'～年', N'ねん', N'Niên', N'~ năm', N'N5', N'N', NULL, 365, GETDATE()),
  (N'全部で', N'ぜんぶで', N'Toàn bộ', N'Tổng cộng', N'N5', N'N', NULL, 366, GETDATE()),
  (N'全部', N'ぜんぶ', NULL, N'Toàn bộ, tất cả', N'N5', N'N', NULL, 367, GETDATE()),
  (N'皆', N'みんな', N'Giai', N'Tất cả mọi người', N'N5', N'N', NULL, 368, GETDATE()),
  (N'簡単　（な）', N'かんたん', N'Giản đơn', N'Đơn giản', N'N5', N'A', NULL, 369, GETDATE()),
  (N'近い', N'ちかい', N'Cận', N'Gần', N'N5', N'A', NULL, 370, GETDATE()),
  (N'遠い', N'とおい', N'Viễn', N'Xa', N'N5', N'A', NULL, 371, GETDATE()),
  (N'早い　/　速い', N'はやい', N'Tảo / tốc', N'Sớm, nhanh', N'N5', N'A', NULL, 372, GETDATE()),
  (N'遅い', N'おそい', N'Trì', N'Chậm, muộn', N'N5', N'A', NULL, 373, GETDATE()),
  (N'多い', N'おおい', N'Đa', N'Nhiều, đông', N'N5', N'A', NULL, 374, GETDATE()),
  (N'少ない', N'すくない', N'Thiểu', N'Ít, vắng', N'N5', N'A', NULL, 375, GETDATE()),
  (N'暖かい', N'あたたかい', N'Noãn', N'Ấm áp', N'N5', N'A', NULL, 376, GETDATE()),
  (N'涼しい', N'すずしい', N'Lượng', N'Mát mẻ', N'N5', N'A', NULL, 377, GETDATE()),
  (N'甘い', N'あまい', N'Cam', N'Ngọt', N'N5', N'A', NULL, 378, GETDATE()),
  (N'辛い', N'からい', N'Tân', N'Cay', N'N5', N'A', NULL, 379, GETDATE()),
  (N'重い', N'おもい', N'Trọng', N'Nặng', N'N5', N'A', NULL, 380, GETDATE()),
  (N'軽い', N'かるい', N'Khinh', N'Nhẹ', N'N5', N'A', NULL, 381, GETDATE()),
  (N'若い', N'わかい', N'Nhược, nhã', N'Trẻ', N'N5', N'A', NULL, 382, GETDATE()),
  (N'季節', N'きせつ', N'Quý tiết', N'Mùa', N'N5', N'N', NULL, 383, GETDATE()),
  (N'春', N'はる', N'Xuân', N'Xuân', N'N5', N'N', NULL, 384, GETDATE()),
  (N'夏', N'なつ', N'Hạ', N'Hạ', N'N5', N'N', NULL, 385, GETDATE()),
  (N'秋', N'あき', N'Thu', N'Thu', N'N5', N'N', NULL, 386, GETDATE()),
  (N'冬', N'ふゆ', N'Đông', N'Đông', N'N5', N'N', NULL, 387, GETDATE()),
  (N'天気', N'てんき', N'Thiên khí', N'Thời tiết', N'N5', N'N', NULL, 388, GETDATE()),
  (N'雨', N'あめ', N'Vũ', N'Mưa', N'N5', N'N', NULL, 389, GETDATE()),
  (N'曇り', N'くもり', N'Đàm', N'Mây mù', N'N5', N'N', NULL, 390, GETDATE()),
  (N'空港', N'くうこう', N'Không cảng', N'Sân bay', N'N5', N'N', NULL, 391, GETDATE()),
  (N'海', N'うみ', N'Hải', N'Biển', N'N5', N'N', NULL, 392, GETDATE()),
  (N'世界', N'せかい', N'Thế giới', N'Thế giới', N'N5', N'N', NULL, 393, GETDATE()),
  (N'「お」祭り', N'おまつり', N'Tế', N'Lễ hội', N'N5', N'N', NULL, 394, GETDATE()),
  (N'試験', N'しけん', N'Thí nghiệm', N'Kỳ thi', N'N5', N'N', NULL, 395, GETDATE()),
  (N'遊ぶ', N'あそぶ', N'Du', N'Chơi', N'N5', N'V', NULL, 396, GETDATE()),
  (N'泳ぐ', N'およぐ', N'Vịnh', N'Bơi', N'N5', N'V', NULL, 397, GETDATE()),
  (N'迎える', N'むかえる', N'Nghênh', N'Đón', N'N5', N'V', NULL, 398, GETDATE()),
  (N'変える', N'かえる', N'Biến', N'Đổi', N'N5', N'V', NULL, 399, GETDATE()),
  (N'疲れる', N'つかれる', N'Bì', N'Mệt', N'N5', N'V', NULL, 400, GETDATE()),
  (N'出す', N'だす', N'Xuất', N'Lấy ra, cho ra', N'N5', N'V', NULL, 401, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'入る', N'はいる', N'Nhập', N'Vào, đi vào', N'N5', N'V', NULL, 402, GETDATE()),
  (N'出る', N'でる', NULL, N'Ra, đi ra', N'N5', N'V', NULL, 403, GETDATE()),
  (N'見物する', N'けんぶつする', N'Kiến vật', N'Thăm quan', N'N5', N'V', NULL, 404, GETDATE()),
  (N'見学する', N'けんがくする', N'Kiến học', N'Kiến học, dự giờ', N'N5', N'V', NULL, 405, GETDATE()),
  (N'結婚する', N'けっこんする', N'Kết hôn', N'Kết hôn', N'N5', N'V', NULL, 406, GETDATE()),
  (N'買い物する', N'かいものする', N'Mãi vật', N'Mua sắm', N'N5', N'V', NULL, 407, GETDATE()),
  (N'食事する', N'しょくじする', N'Thực sự', N'Dùng bữa', N'N5', N'V', NULL, 408, GETDATE()),
  (N'散歩する', N'さんぽする', N'Tản bộ', N'Đi dạo', N'N5', N'V', NULL, 409, GETDATE()),
  (N'欲しい', N'ほしい', N'Dục', N'Muốn', N'N5', N'A', NULL, 410, GETDATE()),
  (N'寂しい', N'さびしい', N'Tịch', N'Buồn', N'N5', N'A', NULL, 411, GETDATE()),
  (N'広い', N'ひろい', N'Quảng', N'Rộng', N'N5', N'A', NULL, 412, GETDATE()),
  (N'狭い', N'せまい', N'Hiệp', N'Hẹp', N'N5', N'A', NULL, 413, GETDATE()),
  (N'市役所', N'しやくしょ', N'Thị dịch sở', N'Chính quyền thành phố', N'N5', N'N', NULL, 414, GETDATE()),
  (N'川', N'かわ', N'Xuyên', N'Sông', N'N5', N'N', NULL, 415, GETDATE()),
  (N'経済', N'けいざい', N'Kinh tế', N'Kinh tế', N'N5', N'N', NULL, 416, GETDATE()),
  (N'美術', N'びじゅつ', N'Mĩ thuật', N'Mỹ thuật', N'N5', N'N', NULL, 417, GETDATE()),
  (N'釣りをする', N'つりをする', N'Điếu', N'Câu cá', N'N5', N'V', NULL, 418, GETDATE()),
  (N'会議をする', N'かいぎをする', N'Hội nghị', N'Họp', N'N5', N'V', NULL, 419, GETDATE()),
  (N'登録をする', N'とうろくをする', N'Đăng lục', N'Đăng kí', N'N5', N'V', NULL, 420, GETDATE()),
  (N'何か', N'なにか', NULL, N'Cái gì đó', N'N5', N'N', NULL, 421, GETDATE()),
  (N'お腹が空いた', N'おなかがすいた', N'Phúc, không', N'Tôi đói', N'N5', N'N', NULL, 422, GETDATE()),
  (N'お腹が一杯だ', N'おなかがいっぱい', N'Phúc, bôi', N'Tôi no rồi', N'N5', N'N', NULL, 423, GETDATE()),
  (N'喉が乾いた', N'のどがかわいた', N'Hầu, can', N'Tôi khát nước', N'N5', N'N', NULL, 424, GETDATE()),
  (N'ご注文は', N'ごちゅうもんは', N'Chú văn', N'Quý khách gọi món gì', N'N5', N'N', NULL, 425, GETDATE()),
  (N'定食', N'ていしょく', N'Định thực', N'Cơm suất', N'N5', N'N', NULL, 426, GETDATE()),
  (N'少々お待ち下さい', N'しょうしょうおまちください', N'Thiểu, đãi', N'Xin chờ một chút', N'N5', N'N', NULL, 427, GETDATE()),
  (N'別々に', N'べつべつに', N'Biệt', N'Tính/làm riêng ra', N'N5', N'N', NULL, 428, GETDATE()),
  (N'付ける', N'つける', N'Phó', N'Bật', N'N5', N'V', NULL, 429, GETDATE()),
  (N'消す', N'けす', N'Tiêu', N'Tắt, xóa', N'N5', N'V', NULL, 430, GETDATE()),
  (N'開ける', N'あける', N'Khai', N'Mở', N'N5', N'V', NULL, 431, GETDATE()),
  (N'閉める', N'しめる', N'Bế', N'Đóng, đậy', N'N5', N'V', NULL, 432, GETDATE()),
  (N'急ぐ', N'いそぐ', N'Cấp', N'Vội vàng', N'N5', N'V', NULL, 433, GETDATE()),
  (N'持つ', N'もつ', N'Trì', N'Cầm, mang', N'N5', N'V', NULL, 434, GETDATE()),
  (N'待つ', N'まつ', N'Đãi', N'Chờ, đợi', N'N5', N'V', NULL, 435, GETDATE()),
  (N'止める', N'とめる', N'Chỉ', N'Dừng, đỗ', N'N5', N'V', NULL, 436, GETDATE()),
  (N'曲がる', N'まがる', N'Khúc', N'Rẽ', N'N5', N'V', NULL, 437, GETDATE()),
  (N'信号を右へ曲がる', N'しんごうをみぎへまがる', N'Tín hiệu', N'Rẽ sang phải ở chỗ có đèn giao thông', N'N5', N'V', NULL, 438, GETDATE()),
  (N'覚える', N'おぼえる', N'Giác', N'Nhớ, thuộc lòng', N'N5', N'V', NULL, 439, GETDATE()),
  (N'思い出す', N'おもいだす', N'Tư', N'Nhớ nhung', N'N5', N'V', NULL, 440, GETDATE()),
  (N'取る', N'とる', N'Thủ', N'Lấy', N'N5', N'V', NULL, 441, GETDATE()),
  (N'手伝う', N'てつだう', N'Thủ truyền', N'Giúp đỡ', N'N5', N'V', NULL, 442, GETDATE()),
  (N'呼ぶ', N'よぶ', N'Hô', N'Gọi', N'N5', N'V', NULL, 443, GETDATE()),
  (N'話す', N'はなす', N'Thoại', N'Nói chuyện', N'N5', N'V', NULL, 444, GETDATE()),
  (N'見せる', N'みせる', N'Kiến', N'Cho xem/nhìn', N'N5', N'V', NULL, 445, GETDATE()),
  (N'住所を教える', N'じゅうしょをおしえる', N'Trú sở', N'Cho địa chỉ', N'N5', N'V', NULL, 446, GETDATE()),
  (N'始める', N'はじめる', N'Thủy', N'Bắt đầu', N'N5', N'V', NULL, 447, GETDATE()),
  (N'降る', N'ふる', N'Hàng(giáng)', N'Rơi', N'N5', N'V', NULL, 448, GETDATE()),
  (N'名前', N'なまえ', N'Danh tiền', N'Tên', N'N5', N'N', NULL, 449, GETDATE()),
  (N'住所', N'じゅうしょ', N'Trú sở', N'Địa chỉ', N'N5', N'N', NULL, 450, GETDATE()),
  (N'塩', N'しお', N'Diêm', N'Muối', N'N5', N'N', NULL, 451, GETDATE()),
  (N'砂糖', N'さとう', N'Sa đường', N'Đường', N'N5', N'N', NULL, 452, GETDATE()),
  (N'読み方', N'よみかた', N'Độc phương', N'Cách đọc', N'N5', N'N', NULL, 453, GETDATE()),
  (N'ゆゅくり', N'ゆゅくり', NULL, N'Chậm, từ từ', N'N5', N'N', NULL, 454, GETDATE()),
  (N'すぐ', N'すぐ', NULL, N'Ngay lập tức, ngay', N'N5', N'N', NULL, 455, GETDATE()),
  (N'また', N'また', NULL, N'Lại, nữa', N'N5', N'N', NULL, 456, GETDATE()),
  (N'後で', N'あとで', N'Hậu', N'Sau, để sau', N'N5', N'N', NULL, 457, GETDATE()),
  (N'もう少し', N'もうすこし', NULL, N'Thêm một chút nữa', N'N5', N'N', NULL, 458, GETDATE()),
  (N'お釣', N'おつり', N'Điếu', N'Tiền thừa trả lại', N'N5', N'N', NULL, 459, GETDATE()),
  (N'真っ直ぐ', N'まっすぐ', N'Chân trực', N'(đi) Thẳng', N'N5', N'N', NULL, 460, GETDATE()),
  (N'言葉', N'ことば', N'Ngôn diệp', N'Từ vựng', N'N5', N'N', NULL, 461, GETDATE()),
  (N'立つ', N'たつ', N'Lập', N'Đứng', N'N5', N'V', NULL, 462, GETDATE()),
  (N'座る', N'すわる', N'Tọa', N'Ngồi', N'N5', N'V', NULL, 463, GETDATE()),
  (N'使う', N'つかう', N'Sử', N'Sử dụng', N'N5', N'V', NULL, 464, GETDATE()),
  (N'作る', N'つくる', N'Tác', N'Chế tạo, chế biến', N'N5', N'V', NULL, 465, GETDATE()),
  (N'置く', N'おく', N'Trí', N'Đặt, để', N'N5', N'V', NULL, 466, GETDATE()),
  (N'起きる', N'おきる', N'Khởi', N'Thức dậy', N'N5', N'V', NULL, 467, GETDATE()),
  (N'売る', N'うる', N'Mại', N'Bán', N'N5', N'V', NULL, 468, GETDATE()),
  (N'研究する', N'けんきゅうする', N'Nghiên cứu', N'Nghiên cứu', N'N5', N'V', NULL, 469, GETDATE()),
  (N'知る', N'しる', N'Tri(trí)', N'Biết', N'N5', N'V', NULL, 470, GETDATE()),
  (N'住む', N'すむ', N'Trú', N'Sống', N'N5', N'V', NULL, 471, GETDATE()),
  (N'住んでいる', N'すんでいる', NULL, N'Đang sống ở', N'N5', N'V', NULL, 472, GETDATE()),
  (N'持っている', N'しっている', N'Trì', N'Có, sở hữu', N'N5', N'V', NULL, 473, GETDATE()),
  (N'禁煙', N'きんえん', N'Cấm yên', N'Cấm hút thuốc', N'N5', N'N', NULL, 474, GETDATE()),
  (N'石鹸', N'せっけん', NULL, N'Xà phòng', N'N5', N'N', NULL, 475, GETDATE()),
  (N'独身', N'どくしん', N'Độc thân', N'Độc thân', N'N5', N'N', NULL, 476, GETDATE()),
  (N'資料', N'しりょう', N'Tư liệu', N'Tài liệu', N'N5', N'N', NULL, 477, GETDATE()),
  (N'時刻表', N'じこくひょう', N'Thời khắc biểu', N'Thời gian tàu chạy', N'N5', N'N', NULL, 478, GETDATE()),
  (N'服', N'ふく', N'Phục', N'Quần áo', N'N5', N'N', NULL, 479, GETDATE()),
  (N'製品', N'せいひん', N'Chế phẩm', N'Sản phẩm', N'N5', N'N', NULL, 480, GETDATE()),
  (N'歯医者', N'はいしゃ', N'Xỉ y giả', N'Bác sĩ nha khoa', N'N5', N'N', NULL, 481, GETDATE()),
  (N'床屋', N'とこや', N'Sàng ốc', N'Hiệu cắt tóc nam', N'N5', N'N', NULL, 482, GETDATE()),
  (N'特に', N'とくに', N'Đặc', N'Đặc biệt là', N'N5', N'N', NULL, 483, GETDATE()),
  (N'思い出す', N'おもいだす', N'Tư', N'Nhớ nhung', N'N5', N'N', NULL, 484, GETDATE()),
  (N'ご家族', N'ごかぞく', N'Gia tộc', N'Gia đình (k)', N'N5', N'N', NULL, 485, GETDATE()),
  (N'高校', N'こうこう', N'Cao hiệu', N'Trường cấp 3', N'N5', N'V', NULL, 486, GETDATE()),
  (N'歩く', N'あるく', N'Bộ', N'Đi bộ', N'N5', N'V', NULL, 487, GETDATE()),
  (N'乗る', N'のる', N'Thừa', N'Lên', N'N5', N'V', NULL, 488, GETDATE()),
  (N'降りる', N'おりる', N'Hàng(giáng)', N'Xuống', N'N5', N'V', NULL, 489, GETDATE()),
  (N'乗り換える', N'のりかえる', N'Thừa hoán', N'Chuyển xe', N'N5', N'V', NULL, 490, GETDATE()),
  (N'浴びる', N'あびる', N'Dục', N'Tắm', N'N5', N'V', NULL, 491, GETDATE()),
  (N'入れる', N'いれる', N'Nhập', N'Cho vào', N'N5', N'V', NULL, 492, GETDATE()),
  (N'出す', N'だす', NULL, N'Lấy ra', N'N5', N'V', NULL, 493, GETDATE()),
  (N'辞める', N'やめる', N'Từ', N'Bỏ, thôi', N'N5', N'V', NULL, 494, GETDATE()),
  (N'押す', N'おす', N'Áp', N'ấn, đẩy, ép', N'N5', N'V', NULL, 495, GETDATE()),
  (N'払う', N'はらう', N'Phất', N'Trả (tiền)', N'N5', N'V', NULL, 496, GETDATE()),
  (N'お金を下ろす', N'おかねをおろす', NULL, N'Rút tiền', N'N5', N'V', NULL, 497, GETDATE()),
  (N'長い', N'ながい', N'Trường', N'Dài', N'N5', N'A', NULL, 498, GETDATE()),
  (N'短い', N'みじかい', N'Đoản', N'Ngắn', N'N5', N'A', NULL, 499, GETDATE()),
  (N'明るい', N'あかるい', N'Minh', N'Sáng sủa', N'N5', N'A', NULL, 500, GETDATE()),
  (N'暗い', N'くらい', N'Ám', N'Tối', N'N5', N'A', NULL, 501, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'背が高い', N'せがたかい', N'Bối', N'Người cao', N'N5', N'A', NULL, 502, GETDATE()),
  (N'背が低い', N'せがひくい', N'Đê', N'Người thấp', N'N5', N'A', NULL, 503, GETDATE()),
  (N'頭が良い', N'あたまがいい', N'Đầu', N'Thông minh', N'N5', N'A', NULL, 504, GETDATE()),
  (N'体', N'からだ', N'Thể', N'Cơ thể', N'N5', N'N', NULL, 505, GETDATE()),
  (N'鼻', N'はな', N'Tị', N'Mũi', N'N5', N'N', NULL, 506, GETDATE()),
  (N'髪', N'かみ', N'Phát', N'Tóc', N'N5', N'N', NULL, 507, GETDATE()),
  (N'顔', N'かお', N'Nhan', N'Khuôn mặt', N'N5', N'N', NULL, 508, GETDATE()),
  (N'目', N'め', N'Mục', N'Mắt', N'N5', N'N', NULL, 509, GETDATE()),
  (N'耳', N'みみ', N'Nhĩ', N'Tai', N'N5', N'N', NULL, 510, GETDATE()),
  (N'口', N'くち', N'Khẩu', N'Miệng', N'N5', N'N', NULL, 511, GETDATE()),
  (N'歯', N'は', N'Xỉ', N'Răng', N'N5', N'N', NULL, 512, GETDATE()),
  (N'お腹', N'おなか', N'Phúc', N'Bụng', N'N5', N'N', NULL, 513, GETDATE()),
  (N'足', N'あし', N'Túc', N'Chân', N'N5', N'N', NULL, 514, GETDATE()),
  (N'緑', N'みどり', N'Lục', N'Màu xanh lá cây, cây cỏ', N'N5', N'N', NULL, 515, GETDATE()),
  (N'「お」寺', N'おてら', N'Tự', N'Chùa', N'N5', N'N', NULL, 516, GETDATE()),
  (N'神社', N'じんじゃ', N'Thần xã', N'Đền', N'N5', N'N', NULL, 517, GETDATE()),
  (N'～番', N'ばん', NULL, N'Số ~', N'N5', N'N', NULL, 518, GETDATE()),
  (N'お引き出しますか', N'おひきだしますか', N'Dẫn', N'Bạn rút tiền có phải không', N'N5', N'N', NULL, 519, GETDATE()),
  (N'まず', N'まず', NULL, N'Trước tiên', N'N5', N'N', NULL, 520, GETDATE()),
  (N'暗証番号', N'あんしょうばんごう', N'Ám chứng phiên hiệu', N'Mã số cá nhân', N'N5', N'N', NULL, 521, GETDATE()),
  (N'次に', N'つぎに', N'Thứ', N'Tiếp theo, sau đó', N'N5', N'N', NULL, 522, GETDATE()),
  (N'金額', N'きんがく', N'Kim ngạch', N'Số tiền', N'N5', N'N', NULL, 523, GETDATE()),
  (N'確認', N'かくにん', N'Xác nhận', N'Xác nhận, kiểm tra', N'N5', N'N', NULL, 524, GETDATE()),
  (N'忘れる', N'わすれる', N'Vong', N'Quên', N'N5', N'V', NULL, 525, GETDATE()),
  (N'無くす', N'なくす', N'Vô', N'Làm mất', N'N5', N'V', NULL, 526, GETDATE()),
  (N'返す', N'かえす', N'Phản', N'Trả lại', N'N5', N'V', NULL, 527, GETDATE()),
  (N'出かける', N'でかける', NULL, N'Đi ra ngoài', N'N5', N'V', NULL, 528, GETDATE()),
  (N'脱ぐ', N'ぬぐ', N'Thoát', N'Cởi ra', N'N5', N'V', NULL, 529, GETDATE()),
  (N'持って行く', N'もっていく', N'Trì hành', N'Mang đi', N'N5', N'V', NULL, 530, GETDATE()),
  (N'持って来る', N'もってくる', N'Trì lai', N'Mang đến', N'N5', N'V', NULL, 531, GETDATE()),
  (N'心配する', N'しんぱいする', N'Tâm phối', N'Lo lắng', N'N5', N'V', NULL, 532, GETDATE()),
  (N'残業する', N'ざんぎょうする', N'Tàn nghiệp', N'Làm thêm giờ', N'N5', N'V', NULL, 533, GETDATE()),
  (N'出張する', N'しゅっちょうする', N'Xuất trường', N'Đi công tác', N'N5', N'V', NULL, 534, GETDATE()),
  (N'飲む', N'のむ', N'Ẩm', N'Uống', N'N5', N'V', NULL, 535, GETDATE()),
  (N'お風呂に入る', N'おふろにはいる', N'Phong lữ', N'Đi tắm', N'N5', N'V', NULL, 536, GETDATE()),
  (N'気を付ける', N'きをつける', N'Khí', N'Chú ý, cẩn thận', N'N5', N'V', NULL, 537, GETDATE()),
  (N'入れる', N'いれる', N'Nhập', N'Cho vào', N'N5', N'V', NULL, 538, GETDATE()),
  (N'出す', N'だす', NULL, N'Lấy ra', N'N5', N'V', NULL, 539, GETDATE()),
  (N'触る', N'さわる', N'Xúc', N'Sờ, chạm', N'N5', N'V', NULL, 540, GETDATE()),
  (N'食事を作る', N'しょくじをつくる', N'Thực sự tác', N'Nấu ăn', N'N5', N'V', NULL, 541, GETDATE()),
  (N'大切　（な）', N'たいせつ', N'Đại thiết', N'Quan trọng', N'N5', N'A', NULL, 542, GETDATE()),
  (N'大丈夫（な）', N'だいじょうぶ', N'Đại trượng phu', N'Không vấn đề gì', N'N5', N'A', NULL, 543, GETDATE()),
  (N'危ない', N'あぶない', N'Nguy', N'Nguy hiểm', N'N5', N'A', NULL, 544, GETDATE()),
  (N'凄い', N'すごい', N'Thê', N'Xuất sắc, khủng khiếp', N'N5', N'A', NULL, 545, GETDATE()),
  (N'問題', N'もんだい', N'Vấn đề', N'Vấn đề', N'N5', N'N', NULL, 546, GETDATE()),
  (N'答え', N'こたえ', N'Đáp', N'Câu trả lời', N'N5', N'N', NULL, 547, GETDATE()),
  (N'「健康」保険証', N'けんこう', N'Kiện khang', N'Thẻ bảo hiểm (sức khỏe)', N'N5', N'N', NULL, 548, GETDATE()),
  (N'薬', N'くすり', N'Dược', N'Thuốc', N'N5', N'N', NULL, 550, GETDATE()),
  (N'お風呂', N'おふろ', N'Phong lữ', N'Nhà tắm', N'N5', N'N', NULL, 551, GETDATE()),
  (N'上着', N'うわぎ', N'Thượng trước', N'Áo khoác', N'N5', N'N', NULL, 552, GETDATE()),
  (N'下着', N'したぎ', N'Hạ trước', N'Quần áo lót', N'N5', N'N', NULL, 553, GETDATE()),
  (N'先生', N'せんせい', N'Tiên sinh', N'Bác sĩ, giáo viên', N'N5', N'N', NULL, 554, GETDATE()),
  (N'許可', N'きょか', N'Hứa khả', N'Sự cho phép', N'N5', N'N', NULL, 555, GETDATE()),
  (N'評価', N'ひょうか', N'Bình giá', N'Đánh giá', N'N5', N'N', NULL, 556, GETDATE()),
  (N'喉が痛いだ', N'のどがいたいだ', N'Hầu thống', N'Tôi bị đau họng', N'N5', N'N', NULL, 557, GETDATE()),
  (N'お大事に', N'おだいじに', N'Đại sự', N'Anh giữ gìn sức khỏe nhé (ốm)', N'N5', N'N', NULL, 558, GETDATE()),
  (N'出来る', N'できる', N'Xuất lai', N'Có thể', N'N5', N'V', NULL, 559, GETDATE()),
  (N'洗う', N'あらう', N'Tẩy', N'Rửa, giặt', N'N5', N'V', NULL, 560, GETDATE()),
  (N'引く', N'ひく', N'Dẫn', N'Chơi (nhạc cụ)', N'N5', N'V', NULL, 561, GETDATE()),
  (N'歌う', N'うたう', N'Ca', N'Hát', N'N5', N'V', NULL, 562, GETDATE()),
  (N'集める', N'あつめる', N'Tập', N'Tập trung lại', N'N5', N'V', NULL, 563, GETDATE()),
  (N'捨てる', N'すてる', N'Xả', N'Vứt đi', N'N5', N'V', NULL, 564, GETDATE()),
  (N'運転する', N'うんてんする', N'Vận chuyển', N'Lái xe', N'N5', N'V', NULL, 565, GETDATE()),
  (N'予約する', N'よやくする', N'Dự ước', N'Đặt trước', N'N5', N'V', NULL, 566, GETDATE()),
  (N'直す', N'なおす', N'Trực', N'Sửa', N'N5', N'V', NULL, 567, GETDATE()),
  (N'練習する', N'れんしゅうする', N'Luyện tập', N'Luyện tập', N'N5', N'V', NULL, 568, GETDATE()),
  (N'始める', N'はじめる', N'Thủy', N'Bắt đầu', N'N5', N'V', NULL, 569, GETDATE()),
  (N'故障', N'こしょう', N'Cố chướng', N'Hỏng', N'N5', N'N', NULL, 570, GETDATE()),
  (N'趣味', N'しゅみ', N'Thú vị', N'Sở thích', N'N5', N'N', NULL, 571, GETDATE()),
  (N'もっと 練習しないと', N'もっとれんしゅうしないと', NULL, N'Tôi còn phải luyện tập nhiều hơn nữa', N'N5', N'N', NULL, 572, GETDATE()),
  (N'国際', N'こくさい', N'Quốc tế', N'Quốc tế', N'N5', N'N', NULL, 573, GETDATE()),
  (N'現金', N'げんきん', N'Hiện kim', N'Tiền mặt', N'N5', N'N', NULL, 574, GETDATE()),
  (N'日記', N'にっき', N'Nhật kí', N'Nhật kí', N'N5', N'N', NULL, 575, GETDATE()),
  (N'「お」祈り', N'おいのり', N'Kì', N'Lời cầu nguyện', N'N5', N'N', NULL, 576, GETDATE()),
  (N'課長', N'かちょう', N'Khóa trường', N'Trưởng nhóm', N'N5', N'N', NULL, 577, GETDATE()),
  (N'部長', N'ぶちょう', N'Bộ trường', N'Trưởng phòng', N'N5', N'N', NULL, 578, GETDATE()),
  (N'社長', N'しゃちょう', N'Xã trường', N'Giám đốc', N'N5', N'N', NULL, 579, GETDATE()),
  (N'動物', N'どうぶつ', N'Động vật', N'Động vật', N'N5', N'N', NULL, 580, GETDATE()),
  (N'馬', N'うま', N'Mã', N'Con ngựa', N'N5', N'N', NULL, 581, GETDATE()),
  (N'なかなか', N'なかなか', NULL, N'Mãi mà…không', N'N5', N'N', NULL, 582, GETDATE()),
  (N'牧場', N'ぼくじょ', N'Mục trường', N'Đồng cỏ, trại chăn nuôi', N'N5', N'N', NULL, 583, GETDATE()),
  (N'本当ですか', N'ほんとうですか', N'Bản đương', N'Thật thế à', N'N5', N'N', NULL, 584, GETDATE()),
  (N'是非', N'ぜひ', N'Thị phi', N'Nhất định', N'N5', N'N', NULL, 585, GETDATE()),
  (N'自分で', N'じぶんで', N'Tự phân', N'Tự mình', N'N5', N'N', NULL, 586, GETDATE()),
  (N'登る', N'のぼる', N'Đăng', N'Leo', N'N5', N'V', NULL, 587, GETDATE()),
  (N'泊まる', N'とまる', N'Bạc', N'Trọ, nghỉ lại', N'N5', N'V', NULL, 588, GETDATE()),
  (N'掃除する', N'そうじする', N'Tảo trừ', N'Dọn dẹp, lau chùi', N'N5', N'V', NULL, 589, GETDATE()),
  (N'洗濯する', N'せんたくする', N'Tẩy trạc', N'Giặt giũ', N'N5', N'V', NULL, 590, GETDATE()),
  (N'なる', N'なる', NULL, N'Trở nên, trở thành', N'N5', N'V', NULL, 591, GETDATE()),
  (N'眠い', N'ねむい', N'Miên', N'Buồn ngủ', N'N5', N'A', NULL, 592, GETDATE()),
  (N'強い', N'つよい', N'Cường', N'Mạnh mẽ', N'N5', N'A', NULL, 593, GETDATE()),
  (N'弱い', N'よわい', N'Nhược', N'Yếu', N'N5', N'A', NULL, 594, GETDATE()),
  (N'調子が良い', N'ちょうしがいい', N'Điều tử', N'Tình trạng tốt', N'N5', N'A', NULL, 595, GETDATE()),
  (N'調子が悪い', N'ちょうしがわるい', NULL, N'Tình trạng xấu', N'N5', N'A', NULL, 596, GETDATE()),
  (N'相撲', N'すもう', N'Tướng bạc', N'Môn võ Sumo', N'N5', N'N', NULL, 597, GETDATE()),
  (N'一度', N'いちど', N'Độ', N'Một lần', N'N5', N'N', NULL, 598, GETDATE()),
  (N'一度も', N'いちども', NULL, N'Một lần cũng chưa', N'N5', N'N', NULL, 599, GETDATE()),
  (N'段々', N'だんだん', N'Đoạn', N'Dần dần', N'N5', N'N', NULL, 600, GETDATE()),
  (N'もう直ぐ', N'もうすぐ', NULL, N'Chuẩn bị', N'N5', N'N', NULL, 601, GETDATE()),
  (N'お陰様で', N'おかげさまで', N'Âm dạng', N'Nhờ trời, cảm ơn', N'N5', N'N', NULL, 602, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'乾杯', N'かんぱい', N'Can bôi', N'Cạn chén, cạn ly', N'N5', N'N', NULL, 603, GETDATE()),
  (N'実は', N'じつは', N'Thực', N'Thực ra thì', N'N5', N'N', NULL, 604, GETDATE()),
  (N'何回も', N'なんかいも', N'Hồi', N'Nhiều lần', N'N5', N'N', NULL, 605, GETDATE()),
  (N'しかし', N'しかし', NULL, N'Nhưng mà', N'N5', N'N', NULL, 606, GETDATE()),
  (N'無理　（な）', N'むり', N'Vô lý', N'Vô lý', N'N5', N'A', NULL, 607, GETDATE()),
  (N'体に良い', N'からだにいい', N'Thể lương', N'Tốt cho cơ thể', N'N5', N'A', NULL, 608, GETDATE()),
  (N'要る', N'いる', N'Yếu', N'Cần thiết', N'N5', N'V', NULL, 609, GETDATE()),
  (N'調べる', N'しらべる', N'Điều', N'Điều tra, kiểm tra', N'N5', N'V', NULL, 610, GETDATE()),
  (N'電話する', N'でんわする', N'Điện thoại', N'Gọi điện thoại', N'N5', N'V', NULL, 611, GETDATE()),
  (N'僕', N'ぼく', N'Phó', N'Tôi, tớ (khiêm tốn)', N'N5', N'N', NULL, 612, GETDATE()),
  (N'君', N'きみ', N'Quân', N'Bạn (thân mật)', N'N5', N'N', NULL, 613, GETDATE()),
  (N'物価　/　値段', N'ぶっか/ねだん', N'Vật giá / Trị đoạn', N'Giá cả', N'N5', N'N', NULL, 614, GETDATE()),
  (N'着物', N'きもの', N'Trước vật', N'Áo Kimono', N'N5', N'N', NULL, 615, GETDATE()),
  (N'始め', N'はじめ', N'Thủy', N'Sự bắt đầu', N'N5', N'N', NULL, 616, GETDATE()),
  (N'終わり', N'おわり', N'Chung', N'Sự kết thúc', N'N5', N'N', NULL, 617, GETDATE()),
  (N'この間', N'このあいだ', N'Gian', N'Hôm nọ', N'N5', N'N', NULL, 618, GETDATE()),
  (N'皆で', N'みなで', N'Giai', N'Tất cả mọi người', N'N5', N'N', NULL, 619, GETDATE()),
  (N'～けど', N'～けど', NULL, N'Nhưng ~', N'N5', N'N', NULL, 620, GETDATE()),
  (N'場所', N'ばしょ', N'Trường sở', N'Địa điểm', N'N5', N'N', NULL, 621, GETDATE()),
  (N'よかったら', N'よかったら', NULL, N'Nếu mà được thì', N'N5', N'N', NULL, 622, GETDATE()),
  (N'思う', N'おもう', N'Tư', N'Nghĩ rằng', N'N5', N'V', NULL, 623, GETDATE()),
  (N'言う', N'いう', N'Ngôn', N'Nói', N'N5', N'V', NULL, 624, GETDATE()),
  (N'足りる', N'たりる', N'Túc', N'Đủ', N'N5', N'V', NULL, 625, GETDATE()),
  (N'勝つ', N'かつ', N'Thắng', N'Thắng', N'N5', N'V', NULL, 626, GETDATE()),
  (N'負ける', N'まける', N'Phụ', N'Thua', N'N5', N'V', NULL, 627, GETDATE()),
  (N'役に立つ', N'やくにたつ', N'Dịch lập', N'Có ích', N'N5', N'V', NULL, 628, GETDATE()),
  (N'動く', N'うごく', N'Động', N'Chuyển động', N'N5', N'V', NULL, 629, GETDATE()),
  (N'無駄　（な）', N'むだ', N'Vô đả', N'Lãng phí, vô ích', N'N5', N'N', NULL, 630, GETDATE()),
  (N'不便', N'ふべん', N'Bất tiện', N'Bất tiện', N'N5', N'N', NULL, 631, GETDATE()),
  (N'同じ', N'おなじ', N'Đồng', N'Giống nhau', N'N5', N'N', NULL, 632, GETDATE()),
  (N'首相', N'しゅしょう', N'Thủ tướng', N'Thủ tướng', N'N5', N'N', NULL, 633, GETDATE()),
  (N'大統領', N'だいとうりょう', N'Đại thống lãnh', N'Tổng thống', N'N5', N'N', NULL, 634, GETDATE()),
  (N'政治', N'せいじ', N'Chính trị', N'Chính trị', N'N5', N'N', NULL, 635, GETDATE()),
  (N'試合', N'しあい', N'Thí hợp', N'Trận đấu', N'N5', N'N', NULL, 636, GETDATE()),
  (N'意見', N'いけん', N'Ý kiến', N'Ý kiến', N'N5', N'N', NULL, 637, GETDATE()),
  (N'お話', N'おはなし', N'Thoại', N'Câu chuyện', N'N5', N'N', NULL, 638, GETDATE()),
  (N'交通', N'こうつう', N'Giao thông', N'Giao thong', N'N5', N'N', NULL, 639, GETDATE()),
  (N'最近', N'さいきん', N'Tối cận', N'Gần đây', N'N5', N'N', NULL, 640, GETDATE()),
  (N'多分', N'たぶん', N'Đa phân', N'Có lẽ', N'N5', N'N', NULL, 641, GETDATE()),
  (N'きっと', N'きっと', NULL, N'Chắc là', N'N5', N'N', NULL, 642, GETDATE()),
  (N'本当に', N'ほんとうに', N'Bản đương', N'Quả đúng là', N'N5', N'N', NULL, 643, GETDATE()),
  (N'そんなに～', N'そんなに～', NULL, N'Không…đến như thế', N'N5', N'N', NULL, 644, GETDATE()),
  (N'～に　ついて', N'～に　ついて', NULL, N'Về ~', N'N5', N'N', NULL, 645, GETDATE()),
  (N'仕方がない', N'しかたがない', N'Sĩ phương', N'Không có cách nào khác, đành vậy', N'N5', N'N', NULL, 646, GETDATE()),
  (N'研修旅行', N'けんしゅうりょこう', N'Nghiên tu lữ hành', N'Du lịch tu nghiệp', N'N5', N'N', NULL, 647, GETDATE()),
  (N'質問', N'しつもん', N'Chất vấn', N'Câu hỏi', N'N5', N'N', NULL, 648, GETDATE()),
  (N'技術', N'ぎじゅつ', N'Kĩ thuật', N'Kỹ thuật', N'N5', N'N', NULL, 649, GETDATE()),
  (N'他の', N'ほかの', N'Tha', N'Ngoài ra', N'N5', N'N', NULL, 650, GETDATE()),
  (N'けれども', N'Lịch sự của が', NULL, N'Nhưng mà ~', N'N5', N'N', NULL, 651, GETDATE()),
  (N'見ないと', N'みないと', NULL, N'Nếu mà không xem thì ~', N'N5', N'N', NULL, 652, GETDATE()),
  (N'かぐや姫', N'かぐやひめ', N'Cơ', N'Công chúa Kaguya', N'N5', N'N', NULL, 653, GETDATE()),
  (N'夢', N'ゆめ', N'Mộng', N'Giấc mơ', N'N5', N'N', NULL, 654, GETDATE()),
  (N'地球', N'ちきゅう', N'Địa cầu', N'Trái đất', N'N5', N'N', NULL, 655, GETDATE()),
  (N'天才', N'てんさい', N'Thiên tài', N'Thiên tài', N'N5', N'N', NULL, 656, GETDATE()),
  (N'放送', N'ほうそう', N'Phỏng tống', N'Phát sóng', N'N5', N'N', NULL, 657, GETDATE()),
  (N'天神祭', N'てんじんまつり', N'Thiên thần tế', N'Lễ hội Tenjin', N'N5', N'N', NULL, 658, GETDATE()),
  (N'着る', N'きる', N'Trước', N'Mặc', N'N5', N'V', NULL, 659, GETDATE()),
  (N'履く', N'はく', N'Lí', N'Đi, mặc (dưới)', N'N5', N'V', NULL, 660, GETDATE()),
  (N'被る', N'かぶる', N'Bị', N'Đội', N'N5', N'V', NULL, 661, GETDATE()),
  (N'帽子を被る', N'ぼうしをかぶる', N'Mạo tử', N'Đội mũ', N'N5', N'V', NULL, 662, GETDATE()),
  (N'掛ける', N'かける', N'Quải', N'Đeo', N'N5', N'V', NULL, 663, GETDATE()),
  (N'眼鏡を掛ける', N'めがねをかける', N'Nhãn kính', N'Đeo kính', N'N5', N'V', NULL, 664, GETDATE()),
  (N'生まれる', N'うまれる', NULL, N'Được sinh ra', N'N5', N'V', NULL, 665, GETDATE()),
  (N'部品', N'ぶひん', N'Bộ phẩm', N'Linh kiện', N'N5', N'N', NULL, 666, GETDATE()),
  (N'家賃', N'やちん', N'Gia nhẫm', N'Tiền thuê nhà', N'N5', N'N', NULL, 667, GETDATE()),
  (N'和室', N'わしつ', N'Hòa thất', N'Phòng kiểu Nhật', N'N5', N'N', NULL, 668, GETDATE()),
  (N'押入れ', N'おしいれ', N'Áp nhập', N'Nơi để chăn gối', N'N5', N'N', NULL, 669, GETDATE()),
  (N'布団', N'ふとん', N'Bố đoàn', N'Chăn, đệm', N'N5', N'N', NULL, 670, GETDATE()),
  (N'聞く', N'きく', N'Văn', N'Hỏi', N'N5', N'V', NULL, 671, GETDATE()),
  (N'回す', N'まわす', N'Hồi', N'Xoay, vặn', N'N5', N'V', NULL, 672, GETDATE()),
  (N'引く', N'ひく', N'Dẫn', N'Kéo', N'N5', N'V', NULL, 673, GETDATE()),
  (N'お釣が出る', N'おつりがでる', N'Điều', N'Tiền thừa chạy ra', N'N5', N'V', NULL, 674, GETDATE()),
  (N'動く', N'うごく', N'Động', N'Chuyển động,chạy', N'N5', N'V', NULL, 675, GETDATE()),
  (N'道を歩く', N'みちをあるく', N'Đạo bộ', N'Đi bộ trên đường', N'N5', N'V', NULL, 676, GETDATE()),
  (N'渡る', N'わたる', N'Độ', N'Đi qua', N'N5', N'V', NULL, 677, GETDATE()),
  (N'橋を渡る', N'はしをわたる', N'Kiều', N'Đi qua cầu', N'N5', N'V', NULL, 678, GETDATE()),
  (N'引っ越しする', N'ひっこしする', N'Dẫn việt', N'Chuyển nhà', N'N5', N'V', NULL, 679, GETDATE()),
  (N'調節する', N'ちょうせつする', N'Điều tiết', N'Điều chỉnh', N'N5', N'V', NULL, 680, GETDATE()),
  (N'困る', N'こまる', N'Khốn', N'Khó khan', N'N5', N'V', NULL, 681, GETDATE()),
  (N'頑張る', N'がんばる', N'Ngoan trương', N'Cố gắng', N'N5', N'V', NULL, 682, GETDATE()),
  (N'悲しい', N'かなしい', N'Bi', N'Đau buồn', N'N5', N'A', NULL, 683, GETDATE()),
  (N'寂しい', N'さびしい', N'Tịch', N'Buồn', N'N5', N'A', NULL, 684, GETDATE()),
  (N'嬉しい', N'うれしい', N'Hi', N'Vui mừng', N'N5', N'A', NULL, 685, GETDATE()),
  (N'意味', N'いみ', N'Ý vị', N'Ý nghĩa', N'N5', N'N', NULL, 686, GETDATE()),
  (N'困ったな', N'こまったな', NULL, N'Khó khăn rồi đây', N'N5', N'b', NULL, 687, GETDATE()),
  (N'音', N'おと', N'Âm', N'Tiếng, âm thanh', N'N5', N'N', NULL, 688, GETDATE()),
  (N'抓み', N'つまみ', N'Trảo', N'Núm xoay', N'N5', N'N', NULL, 689, GETDATE()),
  (N'角', N'かど', N'Giác', N'Góc phố', N'N5', N'N', NULL, 690, GETDATE()),
  (N'交差点', N'こうさてん', N'Giao soa điểm', N'Ngã tư', N'N5', N'N', NULL, 691, GETDATE()),
  (N'駐車場', N'ちゅうしゃじょう', N'Trú xa trường', N'Bãi đỗ xe', N'N5', N'N', NULL, 692, GETDATE()),
  (N'～目', N'め', N'Mục', N'Thứ ~ (số thứ tự)', N'N5', N'N', NULL, 693, GETDATE()),
  (N'お正月', N'おしょうがつ', N'Chính nguyệt', N'Tết', N'N5', N'N', NULL, 694, GETDATE()),
  (N'建物', N'たてもの', N'Kiến vật', N'Tòa nhà cao tầng', N'N5', N'N', NULL, 695, GETDATE()),
  (N'呉れる', N'くれる', N'Ngô', N'Cho', N'N5', N'V', NULL, 696, GETDATE()),
  (N'連れて行く', N'つれていく', N'Liên', N'Dẫn đi', N'N5', N'V', NULL, 697, GETDATE()),
  (N'連れて来る', N'つれてくる', NULL, N'Dẫn đến', N'N5', N'V', NULL, 698, GETDATE()),
  (N'送る', N'おくる', N'Tống', N'Tiến, đưa, gửi', N'N5', N'V', NULL, 699, GETDATE()),
  (N'人を送る', N'ひとをおくる', NULL, N'Tiễn ai, đưa ai', N'N5', N'V', NULL, 700, GETDATE()),
  (N'紹介する', N'しょうかいする', N'Thiệu giới', N'Giới thiệu', N'N5', N'V', NULL, 701, GETDATE()),
  (N'案内する', N'あんないする', N'Án nội', N'Hướng dẫn', N'N5', N'V', NULL, 702, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'説明する', N'せつめいする', N'Thuyết minh', N'Giải thích', N'N5', N'V', NULL, 703, GETDATE()),
  (N'入れる', N'いれる', N'Nhập', N'Cho vào, pha', N'N5', N'V', NULL, 704, GETDATE()),
  (N'お祖父さん', N'おじいさん', N'Tổ phụ', N'Ông', N'N5', N'N', NULL, 705, GETDATE()),
  (N'お祖母さん', N'おばあさん', N'Tổ mẫu', N'Bà', N'N5', N'N', NULL, 706, GETDATE()),
  (N'準備', N'じゅんび', N'Chuẩn bị', N'Chuẩn bị', N'N5', N'N', NULL, 707, GETDATE()),
  (N'お菓子', N'おかし', N'Quả tử', N'Kẹo, bánh kẹo', N'N5', N'N', NULL, 708, GETDATE()),
  (N'人形', N'にんぎょう', N'Nhân hình', N'Búp bê', N'N5', N'N', NULL, 709, GETDATE()),
  (N'大阪城', N'おおさかじょう', N'Đại phản thành', N'Thành Osaka', N'N5', N'N', NULL, 710, GETDATE()),
  (N'他に', N'ほかに', N'Tha', N'Ngoài ra, khác', N'N5', N'N', NULL, 711, GETDATE()),
  (N'お弁当', N'おべんとう', N'Biện đương', N'Cơm hộp', N'N5', N'N', NULL, 712, GETDATE()),
  (N'考える', N'かんがえる', N'Khảo', N'Nghĩ', N'N5', N'V', NULL, 713, GETDATE()),
  (N'着く', N'つく', N'Trước', N'Đến nơi, tơi nơi', N'N5', N'V', NULL, 714, GETDATE()),
  (N'駅に着く', N'えきにつく', N'Dịch', N'Đến nhà ga', N'N5', N'V', NULL, 715, GETDATE()),
  (N'留学する', N'りゅうがくする', N'Lưu học', N'Du học', N'N5', N'V', NULL, 716, GETDATE()),
  (N'年を取る', N'としをとる', N'Niên thủ', N'Già, có tuổi', N'N5', N'V', NULL, 717, GETDATE()),
  (N'続ける', N'つづける', N'Tục', N'Tiếp tục', N'N5', N'V', NULL, 718, GETDATE()),
  (N'片付ける', N'かたづける', N'Phiến phó', N'Dọn dẹp', N'N5', N'V', NULL, 719, GETDATE()),
  (N'間違い', N'まちがい', N'Gian vi', N'Nhầm, sai', N'N5', N'A', NULL, 720, GETDATE()),
  (N'道具', N'どうぐ', N'Đạo cụ', N'Dụng cụ', N'N5', N'N', NULL, 721, GETDATE()),
  (N'一般研修', N'いっぱんけんしゅう', N'Nhất ban nghiên tu', N'Tu nghiệp phổ thông', N'N5', N'N', NULL, 722, GETDATE()),
  (N'世界', N'せかい', N'Thế giới', N'Thế giới', N'N5', N'N', NULL, 723, GETDATE()),
  (N'困ったこと', N'こまったこと', N'Khốn', N'Việc khó khăn', N'N5', N'N', NULL, 724, GETDATE()),
  (N'田舎', N'いなか', N'Điền xá', N'Quê hương, nông thôn', N'N5', N'N', NULL, 725, GETDATE()),
  (N'億', N'おく', N'Ức', N'Một trăm triệu', N'N5', N'N', NULL, 726, GETDATE()),
  (N'転勤する', N'てんきんする', N'Chuyển cần', N'Chuyển chỗ làm', N'N5', N'N', NULL, 727, GETDATE()),
  (N'～のこと', N'～のこと', NULL, N'Những chuyện về', N'N5', N'N', NULL, 728, GETDATE()),
  (N'色々お世話になりました', N'いろいろおせわになりました', N'Sắc thế thoại', N'Cảm ơn..đã giúp trong thời gian qua', N'N5', N'N', NULL, 729, GETDATE()),
  (N'どうぞお元気で', N'どうぞおげんきで', N'Nguyên khí', N'Xin bảo trọng, giữ gìn sức khỏe nhé', N'N5', N'N', NULL, 730, GETDATE());

PRINT 'Seeded 728 JLPT N5 records.';
GO
