-- ============================================================
-- JLPT Vocabulary Seed: Special (N2 BS + Từ Láy + Lượng Từ)
-- Records: 709
-- Generated: 2026-07-04T05:53:40.020Z
-- ============================================================

USE JapaneseAI;
GO

SET NOCOUNT ON;

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'一生', N'いっせい', N'NHẤT SINH', N'Một đời', N'N2', NULL, N'special', 1, GETDATE()),
  (N'生涯', N'しょうがい', N'SINH NHAI', N'Sinh nhai, sự nghiệp', N'N2', NULL, N'special', 2, GETDATE()),
  (N'平等', N'へいとう', N'BÌNH ĐẲNG', N'Bình đẳng', N'N2', NULL, N'special', 3, GETDATE()),
  (N'人類', N'じんるい', N'NHÂN LOẠI', N'Nhân loại', N'N2', NULL, N'special', 4, GETDATE()),
  (N'親類', N'しんるい', N'THÂN LOẠI', N'Họ hàng', N'N2', NULL, N'special', 5, GETDATE()),
  (N'親族', N'しんぞく', N'THÂN TỘC', N'Họ hàng', N'N2', NULL, N'special', 6, GETDATE()),
  (N'仲', N'なか', N'TRỌNG', N'Quan hệ', N'N2', NULL, N'special', 7, GETDATE()),
  (N'長女', N'ちょうじょ', N'TRƯỞNG NỮ', N'Trưởng nữ', N'N2', NULL, N'special', 8, GETDATE()),
  (N'三男', N'さんなん', N'TAM NAM', N'Con trai thứ 3', N'N2', NULL, N'special', 9, GETDATE()),
  (N'三女', N'さんじょ', N'TAM NỮ', N'Con gái thứ 3', N'N2', NULL, N'special', 10, GETDATE()),
  (N'次男', N'じなん', N'THỨ NAM', N'Con trai thứ', N'N2', NULL, N'special', 11, GETDATE()),
  (N'次女', N'じじょ', N'THỨ NỮ', N'Con gái thứ', N'N2', NULL, N'special', 12, GETDATE()),
  (N'末っ子', N'すえっこ', N'MẠT TỬ', N'Con út', N'N2', NULL, N'special', 13, GETDATE()),
  (N'大事', N'だいじ', N'ĐẠI SỰ', N'Việc đại sự, quan trọng', N'N2', NULL, N'special', 14, GETDATE()),
  (N'従業員', N'じゅうぎょういん', N'TÒNG NGHIỆP VIÊN', N'Công nhân, người làm thuê', N'N2', NULL, N'special', 15, GETDATE()),
  (N'腕がいい', N'うでがいい', N'OẢN', N'Tay nghề tốt', N'N2', NULL, N'special', 16, GETDATE()),
  (N'双生児', N'そうせいじ', N'SONG SINH NHI', N'Sinh đôi', N'N2', NULL, N'special', 17, GETDATE()),
  (N'兄弟', N'きょうだい', N'HUYNH ĐỆ', N'Anh em', N'N2', NULL, N'special', 18, GETDATE()),
  (N'分かれる', N'わかれる', N'PHÂN', N'Phân chia', N'N2', NULL, N'special', 19, GETDATE()),
  (N'進歩', N'しんぽ', N'TIẾN BỘ', N'Tiến bộ', N'N2', NULL, N'special', 20, GETDATE()),
  (N'伸びる', N'のびる', N'THÂN', N'Cao hơn, phát triển hơn', N'N2', NULL, N'special', 21, GETDATE()),
  (N'未来', N'みらい', N'VI LAI', N'Tương lai (xa)', N'N2', NULL, N'special', 22, GETDATE()),
  (N'希望', N'きぼう', N'HY VỌNG', N'Hi vọng', N'N2', NULL, N'special', 23, GETDATE()),
  (N'解決', N'かいけつ', N'GIẢI QUYẾT', N'Giải quyết', N'N2', NULL, N'special', 24, GETDATE()),
  (N'問題', N'もんだい', N'VẤN ĐỀ', N'Vấn đề', N'N2', NULL, N'special', 25, GETDATE()),
  (N'短所', N'たんしょ', N'ĐOẠN SỞ', N'Sở đoạn, điểm yếu', N'N2', NULL, N'special', 26, GETDATE()),
  (N'性格', N'せいかく', N'TÍNH CÁCH', N'Tính cách', N'N2', NULL, N'special', 27, GETDATE()),
  (N'教育', N'きょういく', N'GIÁO DỤC', N'Giáo dục', N'N2', NULL, N'special', 28, GETDATE()),
  (N'伸ばす', N'のばす', N'THÂN', N'Làm cao lên, phát triển lên', N'N2', NULL, N'special', 29, GETDATE()),
  (N'左利き', N'ひだりきき', N'TẢ LỢI', N'Thuận tay trái', N'N2', NULL, N'special', 30, GETDATE()),
  (N'優雅', N'ゆうが', N'ƯU NHÃ', N'Dịu dàng', N'N2', NULL, N'special', 31, GETDATE()),
  (N'模倣', N'もほう', N'MÔ PHỎNG', N'Sự mô phỏng', N'N2', NULL, N'special', 32, GETDATE()),
  (N'平均', N'へいきん', N'BÌNH QUÂN', N'Trung bình', N'N2', NULL, N'special', 33, GETDATE()),
  (N'一人暮らし', N'ひとりぐらし', N'NHẤT SINH MỘ', N'Sống một mình', N'N2', NULL, N'special', 34, GETDATE()),
  (N'最近', N'さいきん', N'CẬN SỞ', N'Gần đây', N'N2', NULL, N'special', 35, GETDATE()),
  (N'育児', N'いくじ', N'DỤC NHI', N'Chăm sóc trẻ', N'N2', NULL, N'special', 36, GETDATE()),
  (N'お年寄り', N'おとしより', N'NIÊN KÝ', N'Người cao tuổi', N'N2', NULL, N'special', 37, GETDATE()),
  (N'共稼ぎ', N'ともかせぎ', N'CỘNG ĐỘNG', N'Cùng nhau kiếm tiền', N'N2', NULL, N'special', 38, GETDATE()),
  (N'欠勤', N'けっきん', N'KHUYẾT CẦN', N'Nghỉ phép', N'N2', NULL, N'special', 39, GETDATE()),
  (N'退勤', N'たいきん', N'THOÁI CẦN', N'Ra về = checkout', N'N2', NULL, N'special', 40, GETDATE()),
  (N'経済', N'けいざい', N'KINH TẾ', N'Kinh tế', N'N2', NULL, N'special', 41, GETDATE()),
  (N'玄関', N'げんかん', N'HUYỀN QUAN', N'Cửa ra vào', N'N2', NULL, N'special', 42, GETDATE()),
  (N'しわ', N'しわ', NULL, N'Nếp Nhăn', N'N2', NULL, N'special', 43, GETDATE()),
  (N'お年を取る', N'おとしをとる', N'NIÊN THỦ', N'Về già, tuổi già', N'N2', NULL, N'special', 44, GETDATE()),
  (N'面接', N'めんせつ', N'DIỆN TIẾP', N'Phỏng vấn', N'N2', NULL, N'special', 45, GETDATE()),
  (N'お礼', N'おれい', N'LỄ', N'Lễ, cảm ơn', N'N2', NULL, N'special', 46, GETDATE()),
  (N'お辞儀', N'おじぎ', N'TỪ NGHI', N'Cúi chào', N'N2', NULL, N'special', 47, GETDATE()),
  (N'認め', N'みとめ', N'XÁC', N'Thừa nhận', N'N2', NULL, N'special', 48, GETDATE()),
  (N'豊富', N'ほうふ', N'PHONG PHÚ', N'Phong phú', N'N2', NULL, N'special', 49, GETDATE()),
  (N'信用する', N'しんようする', N'TÍN DỤNG', N'Tin tưởng', N'N2', NULL, N'special', 50, GETDATE()),
  (N'褒める', N'ほめる', N'BAO', N'Khen', N'N2', NULL, N'special', 51, GETDATE()),
  (N'叱る', N'しかる', N'SẤT', N'Mắng', N'N2', NULL, N'special', 52, GETDATE()),
  (N'意思/意志', N'いし', N'Ý TƯ/Ý CHÍ', N'Ý chí', N'N2', NULL, N'special', 53, GETDATE()),
  (N'理性', N'りせい', N'LÝ TÍNH', N'Lý tính, lý trí', N'N2', NULL, N'special', 54, GETDATE()),
  (N'拾う', N'ひろう', N'THẬP', N'Nhặt', N'N2', NULL, N'special', 55, GETDATE()),
  (N'結ぶ', N'むすぶ', N'KẾT', N'Buộc', N'N2', NULL, N'special', 56, GETDATE()),
  (N'縛り', N'しばる', N'PHƯỢC', N'Buộc', N'N2', NULL, N'special', 57, GETDATE()),
  (N'通す', N'とうす', N'THÔNG', N'Xuyên qua', N'N2', NULL, N'special', 58, GETDATE()),
  (N'糸', N'いと', N'MỊCH', N'Sợi chỉ', N'N2', NULL, N'special', 59, GETDATE()),
  (N'蓋', N'ふた', N'CÁI', N'Cái nắp', N'N2', NULL, N'special', 60, GETDATE()),
  (N'抜く', N'ぬく', N'BẠT', N'Cậy, tháo', N'N2', NULL, N'special', 61, GETDATE()),
  (N'日当たりが良い', N'ひあたりがいい', N'NHẬT ĐƯƠNG LƯƠNG', N'Có ánh sáng mặt trời chiếu vào', N'N2', NULL, N'special', 62, GETDATE()),
  (N'日当たりが悪い', N'ひあたりがわるい', N'NHẬT ĐƯƠNG ÁC', N'Không có ánh sáng mặt trời chiếu vào', N'N2', NULL, N'special', 63, GETDATE()),
  (N'昨夜', N'さくや', N'TẠC DẠ', N'Đêm qua', N'N2', NULL, N'special', 64, GETDATE()),
  (N'応募', N'おうぼ', N'ỨNG MỘ', N'Ứng tuyển', N'N2', NULL, N'special', 65, GETDATE()),
  (N'釣りをする', N'つりをする', N'ĐIẾU', N'Câu cá', N'N2', NULL, N'special', 66, GETDATE()),
  (N'営業', N'えいぎょう', N'DOANH NGHIỆP', N'Doanh nghiệp, kinh doanh', N'N2', NULL, N'special', 67, GETDATE()),
  (N'週末', N'しゅうまつ', N'CHU MẠT', N'Cuối tuần', N'N2', NULL, N'special', 68, GETDATE()),
  (N'土日', N'どにち', N'THỔ NHẬT', N'Thứ 7, cuối tuần', N'N2', NULL, N'special', 69, GETDATE()),
  (N'休日', N'きゅうじつ', N'HƯU NHẬT', N'Ngày nghỉ', N'N2', NULL, N'special', 70, GETDATE()),
  (N'祭日', N'さいじつ', N'TẾ NHẬT', N'Ngày lễ', N'N2', NULL, N'special', 71, GETDATE()),
  (N'祝日', N'しゅくじつ', N'CHÚC NHẬT', N'Ngày lễ', N'N2', NULL, N'special', 72, GETDATE()),
  (N'順番', N'じゅんばん', N'THUẬN PHIÊN', N'Thứ tự', N'N2', NULL, N'special', 73, GETDATE()),
  (N'過去', N'かこ', N'QUÁ KHỨ', N'Quá khứ', N'N2', NULL, N'special', 74, GETDATE()),
  (N'病人', N'びょうにん', N'BỆNH NHÂN', N'Người ốm', N'N2', NULL, N'special', 75, GETDATE()),
  (N'列車', N'れっしゃ', N'LIỆT XA', N'Xe điện', N'N2', NULL, N'special', 76, GETDATE()),
  (N'貯める', N'ためる', N'TRỮ', N'Để dành tiền', N'N2', NULL, N'special', 77, GETDATE()),
  (N'景品', N'けいひん', N'CẢNH PHẨM', N'Quà kèm giảm giá、Phần thưởng', N'N2', NULL, N'special', 78, GETDATE()),
  (N'有料', N'ゆうりょう', N'HỮU LIỆU', N'Sự trả phí', N'N2', NULL, N'special', 79, GETDATE()),
  (N'試供品', N'しきょうひん', N'THÍ CUNG PHẨM', N'Hàng dùng thử, sản phẩm dùng thử', N'N2', NULL, N'special', 80, GETDATE()),
  (N'経営', N'けいえい', N'KINH DOANH', N'Kinh doanh', N'N2', NULL, N'special', 81, GETDATE()),
  (N'喫茶店', N'きっさてん', N'KHIẾT TRÀ ĐIẾM', N'Quán giải khát, cửa hàng cafe', N'N2', NULL, N'special', 82, GETDATE()),
  (N'追求', N'ついきゅう', N'TRUY CẦU', N'Theo đuổi', N'N2', NULL, N'special', 83, GETDATE()),
  (N'損失', N'そんしつ', N'TỔN THẤT', N'Tổn thất、lỗ', N'N2', NULL, N'special', 84, GETDATE()),
  (N'損害', N'そんがい', N'TỔN HẠI', N'Tổn hại', N'N2', NULL, N'special', 85, GETDATE()),
  (N'不利益', N'ふりえき', N'BẤT LỢI ÍCH', N'Không có lợi ích', N'N2', NULL, N'special', 86, GETDATE()),
  (N'黒字', N'くろじ', N'HẮC TỰ', N'Lãi', N'N2', NULL, N'special', 87, GETDATE()),
  (N'宣伝', N'せんでん', N'TUYÊN TRUYỀN', N'Tuyên truyền', N'N2', NULL, N'special', 88, GETDATE()),
  (N'計算', N'けいさん', N'KẾ TOÁN', N'Tính toán', N'N2', NULL, N'special', 89, GETDATE()),
  (N'会計', N'かいけい', N'HỘI KẾ', N'Tính toán', N'N2', NULL, N'special', 90, GETDATE()),
  (N'補償', N'ほしょう', N'BỔ THƯỜNG', N'Bồi thường、Bồi hoàn', N'N2', NULL, N'special', 91, GETDATE()),
  (N'賠償', N'ばいしょう', N'BỒI THƯỜNG', N'Bồi thường', N'N2', NULL, N'special', 92, GETDATE()),
  (N'倒産', N'とうさん', N'ĐẢO SẢN', N'Phá sản', N'N2', NULL, N'special', 93, GETDATE()),
  (N'被災者', N'ひさいしゃ', N'BỊ TAI GIẢ', N'Nạn nhân', N'N2', NULL, N'special', 94, GETDATE()),
  (N'平和', N'へいわ', N'BÌNH HÒA', N'Hòa bình', N'N2', NULL, N'special', 95, GETDATE()),
  (N'甘やか', N'あまやか', N'CAM', N'Ngọt ngào', N'N2', NULL, N'special', 96, GETDATE()),
  (N'虐める', N'いじめる', N'NGƯỢC', N'Bị bắt nặt', N'N2', NULL, N'special', 97, GETDATE()),
  (N'泣く', N'なく', N'KHẤP', N'Khóc', N'N2', NULL, N'special', 98, GETDATE()),
  (N'床', N'ゆか', N'SÀNG', N'Nền nhà', N'N2', NULL, N'special', 99, GETDATE()),
  (N'種', N'たね', N'CHỦNG', N'Giống', N'N2', NULL, N'special', 100, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'畑', N'はたけ', N'ĐIỀN', N'Ruộng', N'N2', NULL, N'special', 101, GETDATE()),
  (N'測る/量る/計る', N'はかる', N'TRẮC/LƯỢNG/KẾ', N'Đo', N'N2', NULL, N'special', 102, GETDATE()),
  (N'測定する', N'そくていする', N'TRẮC ĐỊNH', N'Đo lường', N'N2', NULL, N'special', 103, GETDATE()),
  (N'測量する', N'そくりょうする', N'TRẮC LƯỢNG', N'Đo lường, thăm dò, khảo sát', N'N2', NULL, N'special', 104, GETDATE()),
  (N'計測する', N'けそくする', N'KẾ TRẮC', N'Đo lường', N'N2', NULL, N'special', 105, GETDATE()),
  (N'運勢', N'うんせい', N'VẬN THẾ', N'Vận may', N'N2', NULL, N'special', 106, GETDATE()),
  (N'胸', N'むね', N'HUNG', N'Ngực', N'N2', NULL, N'special', 107, GETDATE()),
  (N'骨折', N'こっせつ', N'CỐT CHIẾT', N'Gãy xương', N'N2', NULL, N'special', 108, GETDATE()),
  (N'骨', N'ほね', N'CỐT', N'Xương cốt, xương xẩu', N'N2', NULL, N'special', 109, GETDATE()),
  (N'死亡', N'しぼう', N'TỬ VONG', N'Tử vong, chết', N'N2', NULL, N'special', 110, GETDATE()),
  (N'診察する', N'しさつする', N'CHẨN SÁT', N'Chẩn đoán, khám bệnh', N'N2', NULL, N'special', 111, GETDATE()),
  (N'勤務する', N'きんむする', N'CẦN VỤ', N'Làm việc', N'N2', NULL, N'special', 112, GETDATE()),
  (N'学費', N'がくひ', N'HỌC PHÍ', N'Học phí', N'N2', NULL, N'special', 113, GETDATE()),
  (N'失業率', N'しつぎょうりつ', N'THẤT NGHIỆP SUẤT', N'Tỉ lệ thất nghiệp', N'N2', NULL, N'special', 114, GETDATE()),
  (N'磁石', N'じしゃく', N'TỪ THẠCH', N'Nam châm', N'N2', NULL, N'special', 115, GETDATE()),
  (N'離れる', N'はなれる', N'LY', N'Tách ra', N'N2', NULL, N'special', 116, GETDATE()),
  (N'沈没', N'ちんぼつ', N'TRẦM MỘT', N'Sự chìm xuống', N'N2', NULL, N'special', 117, GETDATE()),
  (N'電灯', N'でんとう', N'ĐIỆN ĐĂNG', N'Điện quang, đèn điện', N'N2', NULL, N'special', 118, GETDATE()),
  (N'下げる/提げる', N'さげる', N'HẠ/ĐÊ', N'Giảm bớt, hạ', N'N2', NULL, N'special', 119, GETDATE()),
  (N'転げる', N'ころげる', N'CHUYỂN', N'Lăn', N'N2', NULL, N'special', 120, GETDATE()),
  (N'塀', N'へい', N'BIÊN', N'Tường, rào', N'N2', NULL, N'special', 121, GETDATE()),
  (N'散乱', N'さんらん', N'TÁN LOẠN', N'Vứt lung tung', N'N2', NULL, N'special', 122, GETDATE()),
  (N'解ける/とける', N'ほどける', N'GIẢI', N'Mở ra,　có thể giải quyết', N'N2', NULL, N'special', 123, GETDATE()),
  (N'解く/とく', N'ほどく', N'GIẢI', N'Cởi、giải quyết', N'N2', NULL, N'special', 124, GETDATE()),
  (N'散る', N'ちる', N'TẢN', N'Tàn, rụng', N'N2', NULL, N'special', 125, GETDATE()),
  (N'手足', N'てあし', N'THỦ TÚC', N'Tay chân', N'N2', NULL, N'special', 126, GETDATE()),
  (N'争う', N'あらそう', N'TRANH', N'Đánh nhau, tranh chấp', N'N2', NULL, N'special', 127, GETDATE()),
  (N'戦争する', N'せんそうする', N'CHIẾN TRANH', N'Chiến tranh', N'N2', NULL, N'special', 128, GETDATE()),
  (N'闘争する', N'とうそうする', N'ĐẤU TRANH', N'Đấu tranh', N'N2', NULL, N'special', 129, GETDATE()),
  (N'領土', N'りょうど', N'LÃNH THỔ', N'Lãnh thổ', N'N2', NULL, N'special', 130, GETDATE()),
  (N'取り扱う', N'とりつかう', N'THỦ TRÁP', N'Thao tác, bán', N'N2', NULL, N'special', 131, GETDATE()),
  (N'関係する', N'かんけいする', N'QUAN HỆ', N'Quan hệ', N'N2', NULL, N'special', 132, GETDATE()),
  (N'立つ/発つ', N'たつ', N'LẬP/PHÁT', N'Khởi hành', N'N2', NULL, N'special', 133, GETDATE()),
  (N'出発する', N'しゅっぱつする', N'XUẤT PHÁT', N'Khởi hành', N'N2', NULL, N'special', 134, GETDATE()),
  (N'議長', N'ぎちょう', N'NGHỊ TRƯỜNG', N'Chủ tịch', N'N2', NULL, N'special', 135, GETDATE()),
  (N'不明', N'ふめい', N'BẤT MINH', N'Bất tỉnh, bất minh', N'N2', NULL, N'special', 136, GETDATE()),
  (N'寄付金', N'きふきん', N'KÝ PHÓ KIM', N'Đóng góp', N'N2', NULL, N'special', 137, GETDATE()),
  (N'幸い', N'さいわい', N'HẠNH', N'Hạnh phúc', N'N2', NULL, N'special', 138, GETDATE()),
  (N'幸福', N'こうふく', N'HẠNH PHÚC', N'Hạnh phúc', N'N2', NULL, N'special', 139, GETDATE()),
  (N'幼稚', N'ようち', N'ẤU TRĨ', N'Ấu trĩ, non nớt', N'N2', NULL, N'special', 140, GETDATE()),
  (N'未熟', N'みじゅく', N'VI THỤC', N'Chưa có kinh nghiệm, chưa chín chắn', N'N2', NULL, N'special', 141, GETDATE()),
  (N'心強い', N'こころづよい', N'TÂM CƯỜNG', N'Vững tâm, khích lệ', N'N2', NULL, N'special', 142, GETDATE()),
  (N'哀れ', N'あわれ', N'AI', N'Tội nghiệp', N'N2', NULL, N'special', 143, GETDATE()),
  (N'可愛らしい', N'かわいらしい', N'KHẢ ÁI', N'Đáng yêu, dễ thương', N'N2', NULL, N'special', 144, GETDATE()),
  (N'気の毒', N'きのどく', N'KHÍ ĐỘC', N'Đáng tiếc, chia buồn, đáng thương', N'N2', NULL, N'special', 145, GETDATE()),
  (N'豊か', N'ゆたか', N'PHONG', N'Giàu có, phong phú', N'N2', NULL, N'special', 146, GETDATE()),
  (N'借金', N'しゃっきん', N'TÁ KIM', N'Món nợ, khoản nợ', N'N2', NULL, N'special', 147, GETDATE()),
  (N'仕方ない', N'しかたない', N'SĨ PHƯƠNG', N'Không có cách nào khác', N'N2', NULL, N'special', 148, GETDATE()),
  (N'嵐', N'あらし', N'LAM', N'Dông bão', N'N2', NULL, N'special', 149, GETDATE()),
  (N'煩わしい', N'わずらわしい', N'PHIỀN', N'Phiền phức', N'N2', NULL, N'special', 150, GETDATE()),
  (N'諄い', N'くどい', N'TRUÂN', N'Dài dòng, lắm lời', N'N2', NULL, N'special', 151, GETDATE()),
  (N'あっさりした', N'あっさりした', NULL, N'Đơn giản, cởi mở', N'N2', NULL, N'special', 152, GETDATE()),
  (N'煙たい', N'けむたい', N'YÊN', N'Ngột ngạt', N'N2', NULL, N'special', 153, GETDATE()),
  (N'邪魔', N'じゃま', N'TÀ MA', N'Vướng víu', N'N2', NULL, N'special', 154, GETDATE()),
  (N'煩い', N'うるさい', N'PHIỀN', N'Ồn ào', N'N2', NULL, N'special', 155, GETDATE()),
  (N'平穏', N'へいおん', N'BÌNH ỔN', N'Bình yên, bình tĩnh, yên bình', N'N2', NULL, N'special', 156, GETDATE()),
  (N'穏やか', N'おだやか', N'ỔN', N'Điềm đảm, yên ả, ôn hòa', N'N2', NULL, N'special', 157, GETDATE()),
  (N'怒る', N'おこる', N'NỘ', N'Tức giận', N'N2', NULL, N'special', 158, GETDATE()),
  (N'慌しい', N'あわただしい', N'HOẢNG', N'Vội vã, cuống cuồng', N'N2', NULL, N'special', 159, GETDATE()),
  (N'傷つけ', N'きずつけ', N'THƯƠNG', N'Tổn thương', N'N2', NULL, N'special', 160, GETDATE()),
  (N'馬鹿馬鹿しい', N'ばかばかしい', N'MÃ LỘC', N'Buồn cười, ngu ngốc', N'N2', NULL, N'special', 161, GETDATE()),
  (N'出鱈目', N'でたらめ', N'XUẤT TUYẾT MỤC', N'Bừa, linh tinh', N'N2', NULL, N'special', 162, GETDATE()),
  (N'いい加減', N'いいかげん', N'GIA GIẢM', N'Vô trách nhiệm, quá đáng', N'N2', NULL, N'special', 163, GETDATE()),
  (N'格好', N'かっこう', N'CÁCH HẢO', N'Ngoại hình, vẻ bề ngoài', N'N2', NULL, N'special', 164, GETDATE()),
  (N'きちんとした', N'きちんとした', NULL, N'Gọn gàng, ngăn nắp', N'N2', NULL, N'special', 165, GETDATE()),
  (N'図々しい', N'ずうずうしい', N'ĐỒ', N'Vô liêm sỉ, trơ trẽn', N'N2', NULL, N'special', 166, GETDATE()),
  (N'殺す', N'ころす', N'SÁT', N'Giết', N'N2', NULL, N'special', 167, GETDATE()),
  (N'緩やか', N'ゆるやか', N'HOÃN', N'Lỏng lẻo, nhẹ nhàng, chậm rãi, thoải mái', N'N2', NULL, N'special', 168, GETDATE()),
  (N'乗り越える', N'のりこえる', N'THỪA VIỆT', N'Vuợt qua', N'N2', NULL, N'special', 169, GETDATE()),
  (N'窮屈', N'きゅうくつ', N'CÙNG KHUẤT', N'Khó khăn, gò bó, không linh hoạt', N'N2', NULL, N'special', 170, GETDATE()),
  (N'粗い/荒い', N'あらい', N'THÔ/HOANG', N'Bạo lực, cục cằn', N'N2', NULL, N'special', 171, GETDATE()),
  (N'激しい', N'はげしい', N'KÍCH', N'Mãnh liệt', N'N2', NULL, N'special', 172, GETDATE()),
  (N'強引', N'ごういん', N'CƯỜNG DẪN', N'Cưỡng bức', N'N2', NULL, N'special', 173, GETDATE()),
  (N'勝手', N'かって', N'THẮNG THỦ', N'Tự do', N'N2', NULL, N'special', 174, GETDATE()),
  (N'言動', N'げんどう', N'NGÔN ĐỘNG', N'Nói và làm', N'N2', NULL, N'special', 175, GETDATE()),
  (N'強気', N'つよき', N'CƯỜNG KHÍ', N'Mạnh bạo', N'N2', NULL, N'special', 176, GETDATE()),
  (N'勝気', N'かちき', N'THẮNG KHÍ', N'Mạnh bạo', N'N2', NULL, N'special', 177, GETDATE()),
  (N'弱気/気弱', N'よわき/きよわ', N'NHƯỢC KHÍ', N'Rụt rè, nhút nhát', N'N2', NULL, N'special', 178, GETDATE()),
  (N'頑固', N'がんこ', N'NGOAN CỐ', N'Ngoan cố, bướng bỉnh, cứng đầu', N'N2', NULL, N'special', 179, GETDATE()),
  (N'強情', N'ごうじょう', N'CƯỜNG TÌNH', N'Ngoan cố, bướng bỉnh, cứng đầu', N'N2', NULL, N'special', 180, GETDATE()),
  (N'過剰', N'かじょう', N'QUÁ THẶNG', N'Vượt quá, nhiều', N'N2', NULL, N'special', 181, GETDATE()),
  (N'重大', N'じゅうだい', N'TRỌNG ĐẠI', N'Nghiêm trọng, trọng đại', N'N2', NULL, N'special', 182, GETDATE()),
  (N'深刻', N'しんこく', N'THÂM KHẮC', N'Nghiêm trọng', N'N2', NULL, N'special', 183, GETDATE()),
  (N'猛暑', N'もうしょ', N'MÃNH THỬ', N'Nóng bức dữ dội', N'N2', NULL, N'special', 184, GETDATE()),
  (N'気楽', N'きらく', N'KHÍ LẠC', N'Thoải mái, nhẹ nhõm', N'N2', NULL, N'special', 185, GETDATE()),
  (N'安易', N'あんい', N'AN DỊCH', N'Dễ dàng, dễ dãi', N'N2', NULL, N'special', 186, GETDATE()),
  (N'神経を抜いた', N'しんけいをぬいた', N'THẦN KINH BẠT', N'Ảnh hưởng đến thần kinh', N'N2', NULL, N'special', 187, GETDATE()),
  (N'関心', N'かんしん', N'QUAN TÂM', N'Quan tâm', N'N2', NULL, N'special', 188, GETDATE()),
  (N'投げる', N'なげる', N'ĐẦU', N'Ném', N'N2', NULL, N'special', 189, GETDATE()),
  (N'労働', N'ろうどう', N'LAO ĐỘNG', N'Lao động', N'N2', NULL, N'special', 190, GETDATE()),
  (N'被害', N'ひがい', N'BỊ HẠI', N'Thiệt hại', N'N2', NULL, N'special', 191, GETDATE()),
  (N'恵む', N'めぐむ', N'HUỆ', N'Thuận hòa, ban cho', N'N2', NULL, N'special', 192, GETDATE()),
  (N'草', N'くさ', N'THẢO', N'Cỏ', N'N2', NULL, N'special', 193, GETDATE()),
  (N'家畜', N'かちく', N'GIA SÚC', N'Gia súc', N'N2', NULL, N'special', 194, GETDATE()),
  (N'退場', N'たいじょう', N'THOÁI TRƯỜNG', N'Rời khỏi vũ đài', N'N2', NULL, N'special', 195, GETDATE()),
  (N'支援', N'しえん', N'CHI VIỆN', N'Chi viện', N'N2', NULL, N'special', 196, GETDATE()),
  (N'回答/解答', N'かいとう', N'HỒI ĐÁP/GIẢI ĐÁP', N'Trả lời', N'N2', NULL, N'special', 197, GETDATE()),
  (N'逆様', N'さかさま', N'NGHỊCH DẠNG', N'Ngược lại, đảo lộn', N'N2', NULL, N'special', 198, GETDATE()),
  (N'あべこべ', N'あべこべ', NULL, N'Ngược lại', N'N2', NULL, N'special', 199, GETDATE()),
  (N'左右', N'さゆう', N'TẢ HỮU', N'Trái Phải', N'N2', NULL, N'special', 200, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'余所', N'よそ', N'DƯ SỞ', N'Nơi khác', N'N2', NULL, N'special', 201, GETDATE()),
  (N'他', N'ほか', N'THA', N'(người) khác', N'N2', NULL, N'special', 202, GETDATE()),
  (N'境界', N'きょうかい', N'CẢNH GIỚI', N'Biên giới, ngăn cách', N'N2', NULL, N'special', 203, GETDATE()),
  (N'国境', N'こっきょう', N'QUỐC CẢNH', N'Biên giới, ngăn cách', N'N2', NULL, N'special', 204, GETDATE()),
  (N'特殊', N'とくしゅ', N'ĐẶC THÙ', N'Đặc biệt, đặc thù', N'N2', NULL, N'special', 205, GETDATE()),
  (N'責任', N'せきにん', N'TRÁCH NHIỆM', N'Trách nhiệm', N'N2', NULL, N'special', 206, GETDATE()),
  (N'諺', N'ことわざ', N'NGẠN', N'Tục ngữ', N'N2', NULL, N'special', 207, GETDATE()),
  (N'教訓', N'きょうくん', N'GIÁO HUẤN', N'Giáo huấn', N'N2', NULL, N'special', 208, GETDATE()),
  (N'切掛', N'きっかけ', N'THIẾT QUẢI', N'Động lực', N'N2', NULL, N'special', 209, GETDATE()),
  (N'契機', N'けいき', N'THẾ CƠ', N'Nhân tiện, cơ hội, bắt đầu', N'N2', NULL, N'special', 210, GETDATE()),
  (N'立派', N'りっぱ', N'LẬP PHÁI', N'Quý báu', N'N2', NULL, N'special', 211, GETDATE()),
  (N'利用', N'りよう', N'LỢI DỤNG', N'Sử dụng', N'N2', NULL, N'special', 212, GETDATE()),
  (N'延ばす', N'のばす', N'DUYÊN', N'Gia hạn, kéo dài', N'N2', NULL, N'special', 213, GETDATE()),
  (N'電波', N'でんぱ', N'ĐIỆN BA', N'Sóng điện', N'N2', NULL, N'special', 214, GETDATE()),
  (N'選挙', N'せんきょ', N'TUYỂN CỬ', N'Bầu cử', N'N2', NULL, N'special', 215, GETDATE()),
  (N'市長', N'しちょう', N'THỊ TRƯỜNG', N'Thị trưởng', N'N2', NULL, N'special', 216, GETDATE()),
  (N'落選', N'らくせん', N'LẠC TUYỂN', N'Không được bầu', N'N2', NULL, N'special', 217, GETDATE()),
  (N'配布/配付', N'はいふ', N'PHỐI BỐ/PHỐI PHÓ', N'Phân phát', N'N2', NULL, N'special', 218, GETDATE()),
  (N'反則', N'はんそく', N'PHẢN TẮC', N'Phạm lỗi', N'N2', NULL, N'special', 219, GETDATE()),
  (N'長年', N'ながねん', N'TRƯỜNG NIÊN', N'Nhiều năm', N'N2', NULL, N'special', 220, GETDATE()),
  (N'路上', N'ろじょう', N'LỘ THƯỢNG', N'Trên đường', N'N2', NULL, N'special', 221, GETDATE()),
  (N'分裂', N'ぶんれつ', N'PHÂN LIỆT', N'Sự phân liệt, rạn nứt', N'N2', NULL, N'special', 222, GETDATE()),
  (N'拡張', N'かくちょう', N'KHUẾCH TRƯƠNG', N'Sự khuếch đại, sự khuếch trương', N'N2', NULL, N'special', 223, GETDATE()),
  (N'解散', N'かいさん', N'GIẢI TÁN', N'Giải tán', N'N2', NULL, N'special', 224, GETDATE()),
  (N'分散', N'ぶんさん', N'PHÂN TÁN', N'Phân tán', N'N2', NULL, N'special', 225, GETDATE()),
  (N'停電', N'ていでん', N'ĐÌNH ĐIỆN', N'Mất điện', N'N2', NULL, N'special', 226, GETDATE()),
  (N'向上', N'こうじょう', N'HƯỚNG THƯỢNG', N'Nâng cao', N'N2', NULL, N'special', 227, GETDATE()),
  (N'規定', N'きてい', N'QUY ĐỊNH', N'Quy định', N'N2', NULL, N'special', 228, GETDATE()),
  (N'驚く', N'おどろく', N'KINH', N'Kinh ngạc', N'N2', NULL, N'special', 229, GETDATE()),
  (N'闘志', N'とうし', N'ĐẤU CHÍ', N'Ý chí chiến đấu', N'N2', NULL, N'special', 230, GETDATE()),
  (N'湧き上がる
沸き上がる', N'わきあがる', N'DŨNG THƯỢNG
PHÍ THƯỢNG', N'Sôi lên, tăng lên', N'N2', NULL, N'special', 231, GETDATE()),
  (N'筋肉', N'きんにく', N'CÂN NHỤC', N'Cơ bắp', N'N2', NULL, N'special', 232, GETDATE()),
  (N'歓声', N'かんせい', N'HOAN THANH', N'Tiếng hoan hô', N'N2', NULL, N'special', 233, GETDATE()),
  (N'出来上がる', N'できあがる', N'THƯỢNG', N'Hoàn thành (xong thức ăn)', N'N2', NULL, N'special', 234, GETDATE()),
  (N'鍛える', N'きたえる', N'ĐOÁN', N'Dạy dỗ, rèn luyện', N'N2', NULL, N'special', 235, GETDATE()),
  (N'借り出す', N'かりだす', N'TÁ XUẤT', N'Mượn', N'N2', NULL, N'special', 236, GETDATE()),
  (N'駆ける', N'かける', N'KHU', N'Chạy nhanh, phi nước đại, tiến triển nhanh', N'N2', NULL, N'special', 237, GETDATE()),
  (N'見込む', N'みこむ', N'KIẾN NHẬP', N'Dự kiến', N'N2', NULL, N'special', 238, GETDATE()),
  (N'羊', N'ひつじ', N'DƯƠNG', N'Con cừu', N'N2', NULL, N'special', 239, GETDATE()),
  (N'囲い', N'かこい', N'VI', N'Chuồng, hàng rào', N'N2', NULL, N'special', 240, GETDATE()),
  (N'師匠', N'ししょう', N'SƯ TƯỢNG', N'Sư phụ, thầy dạy nghề', N'N2', NULL, N'special', 241, GETDATE()),
  (N'根気', N'こんき', N'CĂN KHÍ', N'Kiên nhẫn', N'N2', NULL, N'special', 242, GETDATE()),
  (N'暴力', N'ぼうりょく', N'BẠO LỰC', N'Bạo lực', N'N2', NULL, N'special', 243, GETDATE()),
  (N'仲直りする', N'なかなおりする', N'TRỌNG TRỰC', N'Hòa giải', N'N2', NULL, N'special', 244, GETDATE()),
  (N'互い', N'たがい', N'HỖ', N'Lẫn nhau, song phương', N'N2', NULL, N'special', 245, GETDATE()),
  (N'人質', N'ひとじち', N'NHÂN CHẤT', N'Con tin; người tù', N'N2', NULL, N'special', 246, GETDATE()),
  (N'逃走する', N'とうそうする', N'ĐÀO TẨU', N'Đào tẩu, bỏ chạy', N'N2', NULL, N'special', 247, GETDATE()),
  (N'完了', N'かんりょう', N'HOÀN LIỄU', N'Sự hoàn thành, sự kết thúc', N'N2', NULL, N'special', 248, GETDATE()),
  (N'食糧/食料', N'しょくりょう', N'THỰC LƯƠNG/THỰC LIỆU', N'Đồ ăn, thực phẩm', N'N2', NULL, N'special', 249, GETDATE()),
  (N'自給率', N'じきゅうりつ', N'TỰ CẤP XUẤT', N'Tỷ lệ tự cung tự cấp', N'N2', NULL, N'special', 250, GETDATE()),
  (N'ぶどう', N'ぶどう', NULL, N'Quả nho', N'N2', NULL, N'special', 251, GETDATE()),
  (N'屑', N'くず', N'TIẾT', N'Vụn rác', N'N2', NULL, N'special', 252, GETDATE()),
  (N'小麦', N'こむぎ', N'TIỂU MẠCH', N'Lúa mì', N'N2', NULL, N'special', 253, GETDATE()),
  (N'所持', N'しょじ', N'SỞ TRÌ', N'Sở hữu', N'N2', NULL, N'special', 254, GETDATE()),
  (N'制作/製作', N'せいさく', N'CHẾ TÁC', N'Sản xuất', N'N2', NULL, N'special', 255, GETDATE()),
  (N'天然', N'てんねん', N'THIÊN NHIÊN', N'Thiên nhiên', N'N2', NULL, N'special', 256, GETDATE()),
  (N'役目', N'やくめ', N'DỊCH MỤC', N'Vai trò', N'N2', NULL, N'special', 257, GETDATE()),
  (N'交代/交替', N'こうたい', N'GIAO ĐẠI/GIAO THẾ', N'Thay phiên, thay đổi', N'N2', NULL, N'special', 258, GETDATE()),
  (N'笛', N'ふえ', N'ĐỊCH', N'Cái sáo, cái còi', N'N2', NULL, N'special', 259, GETDATE()),
  (N'予想', N'よそう', N'DỰ TƯỞNG', N'Dự đoán', N'N2', NULL, N'special', 260, GETDATE()),
  (N'外見', N'がいけん', N'NGOẠI KIẾN', N'Ngoại hình, vẻ bề ngoài', N'N2', NULL, N'special', 261, GETDATE()),
  (N'肩書き', N'かたがき', N'KIÊN THƯ', N'Chức vụ', N'N2', NULL, N'special', 262, GETDATE()),
  (N'推量', N'すいりょう', N'SUY LƯỢNG', N'Sự phỏng đoán, sự ước lượng', N'N2', NULL, N'special', 263, GETDATE()),
  (N'物質', N'ぶっしつ', N'VẬT CHẤT', N'Vật chất', N'N2', NULL, N'special', 264, GETDATE()),
  (N'効果', N'こうか', N'HIỆU QUẢ', N'Hiệu quả', N'N2', NULL, N'special', 265, GETDATE()),
  (N'継続', N'けいぞく', N'KẾ TỤC', N'Sự tiếp tục, sự liên tục', N'N2', NULL, N'special', 266, GETDATE()),
  (N'下降', N'かこう', N'HẠ GIÁNG', N'Rơi xuống; tụt xuống', N'N2', NULL, N'special', 267, GETDATE()),
  (N'支障', N'ししょう', N'CHI CHƯỚNG', N'Chướng ngại, khó khăn', N'N2', NULL, N'special', 268, GETDATE()),
  (N'組合', N'くみあい', N'TỔ HỢP', N'Tập đoàn', N'N2', NULL, N'special', 269, GETDATE()),
  (N'待遇', N'たいぐう', N'ĐÃI NGỘ', N'Đãi ngộ', N'N2', NULL, N'special', 270, GETDATE()),
  (N'不一致', N'ふいっち', N'BẤT NHẤT TRÍ', N'Không nhất trí', N'N2', NULL, N'special', 271, GETDATE()),
  (N'湖', N'みずうみ', N'HỒ', N'Hồ', N'N2', NULL, N'special', 272, GETDATE()),
  (N'浸かる', N'つかる', N'TẨM', N'Ngập, ngâm', N'N2', NULL, N'special', 273, GETDATE()),
  (N'浸ける', N'つける', N'TẨM', N'Làm ngập, ngâm', N'N2', NULL, N'special', 274, GETDATE()),
  (N'追求する', N'ついきゅうする', N'TRUY CẦU', N'Theo đuổi', N'N2', NULL, N'special', 275, GETDATE()),
  (N'追究する', N'ついきゅうする', N'TRUY CỨU', N'Truy cứu', N'N2', NULL, N'special', 276, GETDATE()),
  (N'振り返す', N'ふりかえす', N'CHẤN PHẢN', N'Xác nhận lại', N'N2', NULL, N'special', 277, GETDATE()),
  (N'文章', N'さくじょする', N'VĂN CHƯƠNG', N'Văn chương', N'N2', NULL, N'special', 278, GETDATE()),
  (N'削除する', N'さくげんする', N'TƯỚC TRỪ', N'Gạch bỏ, xóa bỏ', N'N2', NULL, N'special', 279, GETDATE()),
  (N'削減する', N'さくげんする', N'TƯỚC GIẢM', N'Sự cắt giảm', N'N2', NULL, N'special', 280, GETDATE()),
  (N'搾る', N'しぼる', N'TRÁ', N'Vắt, bóp', N'N2', NULL, N'special', 281, GETDATE()),
  (N'絞る', N'しぼる', N'GIẢO', N'Vắt, bóp', N'N2', NULL, N'special', 282, GETDATE()),
  (N'搾り取る', N'しぼりとる', N'TRÁ THỦ', N'Vắt, bóp, nghĩa bóng: bóc lột', N'N2', NULL, N'special', 283, GETDATE()),
  (N'通り掛かる', N'とおりかかる', N'THÔNG QUẢI', N'Tình cờ đi ngang qua', N'N2', NULL, N'special', 284, GETDATE()),
  (N'補足する', N'ほそくする', N'BỔ TÚC', N'Thêm, bổ sung', N'N2', NULL, N'special', 285, GETDATE()),
  (N'助ける', N'たすける', N'TRỢ', N'Giúp đỡ', N'N2', NULL, N'special', 286, GETDATE()),
  (N'仕舞う', N'しまう', N'SĨ VŨ', N'Cất đi, đưa vào', N'N2', NULL, N'special', 287, GETDATE()),
  (N'怠る', N'おこたる', N'ĐÃI', N'Bỏ bê; sao nhãng', N'N2', NULL, N'special', 288, GETDATE()),
  (N'失せる', N'うせる', N'THẤT', N'Biến đi, biến mất', N'N2', NULL, N'special', 289, GETDATE()),
  (N'逃す', N'のがす', N'ĐÀO', N'Bỏ lỡ 
チャンスを逃す人: Người bỏ lỡ cơ hội', N'N2', NULL, N'special', 290, GETDATE()),
  (N'掴む', N'つかむ', N'QUẶC', N'Nắm bắt
チャンスを掴む人: Người nắm bắt cơ hội', N'N2', NULL, N'special', 291, GETDATE()),
  (N'得る', N'える', N'ĐẮC', N'Thu được, lĩnh hội, lí giải', N'N2', NULL, N'special', 292, GETDATE()),
  (N'引き起こす', N'ひきおこす', N'DẪN KHỞI', N'Dẫn đến, gây ra', N'N2', NULL, N'special', 293, GETDATE()),
  (N'引っくり返る', N'ひっくりかえる', N'DẪN PHẢN', N'Đảo ngược, ngã', N'N2', NULL, N'special', 294, GETDATE()),
  (N'滑れる', N'ずれる', N'HOẠT', N'Trượt khỏi, lệch khỏi', N'N2', NULL, N'special', 295, GETDATE()),
  (N'茹でる', N'ゆでる', N'NHƯ', N'Luộc', N'N2', NULL, N'special', 296, GETDATE()),
  (N'揚げる', N'あげる', N'DƯƠNG', N'Rán', N'N2', NULL, N'special', 297, GETDATE()),
  (N'炒める', N'いためる', N'SAO', N'Xào, rán giòn', N'N2', NULL, N'special', 298, GETDATE()),
  (N'蒸す', N'むす', N'CHƯNG', N'Hấp', N'N2', NULL, N'special', 299, GETDATE()),
  (N'煮る', N'にる', N'CHỬ', N'Nấu, ninh', N'N2', NULL, N'special', 300, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'炊く', N'たく', N'XÚY', N'Thổi cơm, nấu cơm', N'N2', NULL, N'special', 301, GETDATE()),
  (N'認可する', N'にんかする', N'NHẬN KHẢ', N'Phê duyệt', N'N2', NULL, N'special', 302, GETDATE()),
  (N'許可する', N'きょかする', N'HỨA KHẢ', N'Sự cho phép', N'N2', NULL, N'special', 303, GETDATE()),
  (N'認定する', N'にんていする', N'NHẬN ĐỊNH', N'Thừa nhận, chứng nhận', N'N2', NULL, N'special', 304, GETDATE()),
  (N'再検討する', N'さいけんとう', N'TÁI KIỂM THẢO', N'Sự xem xét lại', N'N2', NULL, N'special', 305, GETDATE()),
  (N'成る', N'はんする', N'THÀNH', N'Trở thành, trở nên', N'N2', NULL, N'special', 306, GETDATE()),
  (N'蕾', N'つぼみ', N'LÔI', N'Nụ hoa', N'N2', NULL, N'special', 307, GETDATE()),
  (N'頬', N'ほお', N'GIÁP', N'Má', N'N2', NULL, N'special', 308, GETDATE()),
  (N'沿う', N'そう', N'DUYÊN', N'Men theo, dọc theo, theo đó, theo', N'N2', NULL, N'special', 309, GETDATE()),
  (N'眩しい', N'まぶしい', N'HUYỄN', N'Chói', N'N2', NULL, N'special', 310, GETDATE()),
  (N'目覚め', N'めざめ', N'MỤC GIÁC', N'Tỉnh dậy, mở mắt', N'N2', NULL, N'special', 311, GETDATE()),
  (N'偏る/片寄る', N'かたよる', N'THIÊN/PHIẾN KÝ', N'Dồn về 1 phía, không cân bằng', N'N2', NULL, N'special', 312, GETDATE()),
  (N'鎮まる/静まる', N'しずまる', N'TRẤN/TĨNH', N'Lắng xuống, dịu đi, yên tĩnh đi', N'N2', NULL, N'special', 313, GETDATE()),
  (N'鎮める/静める', N'しずめる', N'TRẤN/TĨNH', N'Yên tĩnh', N'N2', NULL, N'special', 314, GETDATE()),
  (N'長引き', N'ながびく', N'TRƯỜNG DẪN', N'Kéo dài', N'N2', NULL, N'special', 315, GETDATE()),
  (N'整える/調える', N'ととのえる', N'CHỈNH/ĐIỀU', N'Chuẩn bị sẵn sàng', N'N2', NULL, N'special', 316, GETDATE()),
  (N'覆る/覆す', N'くつがえる/くつがえす', N'PHÚC', N'bị lật ngược/Lật ngược', N'N2', NULL, N'special', 317, GETDATE()),
  (N'複雑', N'ふくざつ', N'PHỨC TẠP', N'Phức Tạp', N'N2', NULL, N'special', 318, GETDATE()),
  (N'簡単', N'かんたん', N'GIẢN ĐƠN', N'Đơn giản', N'N2', NULL, N'special', 319, GETDATE()),
  (N'純粋', N'じゅんすい', N'THUẦN TÚY', N'Thuần túy, trong sáng', N'N2', NULL, N'special', 320, GETDATE()),
  (N'不純', N'ふじゅん', N'BẤT THUẦN', N'Không thuần khiết, ko trong sáng', N'N2', NULL, N'special', 321, GETDATE()),
  (N'透明', N'とうめい', N'THẤU MINH', N'Trong suốt, trong vắt', N'N2', NULL, N'special', 322, GETDATE()),
  (N'爽やか', N'さわやか', N'SẢNG', N'Tươi, sảng khoái', N'N2', NULL, N'special', 323, GETDATE()),
  (N'爽快', N'そうかい', N'SẢNG KHOÁI', N'Sảng khoái', N'N2', NULL, N'special', 324, GETDATE()),
  (N'素直', N'すなお', N'TỐ TRỰC', N'Dễ bảo, ngoan ngoãn', N'N2', NULL, N'special', 325, GETDATE()),
  (N'頑固', N'がんこ', N'NGOAN CỐ', N'Ngoan cố, bướng bỉnh, cứng đầu', N'N2', NULL, N'special', 326, GETDATE()),
  (N'反抗的', N'はんこうてき', N'PHẢN KHÁNG ĐÍCH', N'Tính phản kháng', N'N2', NULL, N'special', 327, GETDATE()),
  (N'率直', N'そっちょく', N'SUẤT TRỰC', N'Trực tính, thẳng thắn', N'N2', NULL, N'special', 328, GETDATE()),
  (N'誠実', N'せいじつ', N'THÀNH THỰC', N'Thành thật', N'N2', NULL, N'special', 329, GETDATE()),
  (N'不誠実', N'ふせいじつ', N'BẤT THÀNH THỰC', N'Không thành thật', N'N2', NULL, N'special', 330, GETDATE()),
  (N'謙虚', N'けんきょ', N'KHIÊM HƯ', N'Khiêm tốn, khiêm nhường', N'N2', NULL, N'special', 331, GETDATE()),
  (N'賢明', N'けんめい', N'HIỀN', N'Thông minh', N'N2', NULL, N'special', 332, GETDATE()),
  (N'慎重', N'しんちょう', N'THẬN TRỌNG', N'Thận trọng', N'N2', NULL, N'special', 333, GETDATE()),
  (N'注意深い', N'ちゅういぶかい', N'CHÚ Ý THÂM', N'Cẩn thận', N'N2', NULL, N'special', 334, GETDATE()),
  (N'軽率', N'けいそつ', N'KHINH SUẤT', N'Khinh Suất', N'N2', NULL, N'special', 335, GETDATE()),
  (N'穏やか', N'おだやか', N'ỔN', N'Yên lặng, trầm', N'N2', NULL, N'special', 336, GETDATE()),
  (N'真剣', N'しんけん', N'CHÂN KIẾM', N'Nghiêm túc, nghiêm chỉnh', N'N2', NULL, N'special', 337, GETDATE()),
  (N'正式', N'せいしき', N'CHÍNH THỨC', N'Chính thức, sang trọng', N'N2', NULL, N'special', 338, GETDATE()),
  (N'略式', N'りゃくしき', N'LƯỢC THỨC', N'Đã rút gọn, đơn giản', N'N2', NULL, N'special', 339, GETDATE()),
  (N'主', N'おも', N'CHỦ', N'Chính, chủ yếu', N'N2', NULL, N'special', 340, GETDATE()),
  (N'貴重', N'きちょう', N'QUÝ TRỌNG', N'Quý giá, quý trọng', N'N2', NULL, N'special', 341, GETDATE()),
  (N'偉大', N'いだい', N'VĨ ĐẠI', N'Vĩ đại', N'N2', NULL, N'special', 342, GETDATE()),
  (N'独特', N'どくとく', N'ĐỘC ĐẶC', N'Sự đặc trưng, đặc biệt', N'N2', NULL, N'special', 343, GETDATE()),
  (N'独自', N'どくじ', N'ĐỘC TỰ', N'Độc đáo, đặc biệt', N'N2', NULL, N'special', 344, GETDATE()),
  (N'特有', N'特有', N'ĐẶC HỮU', N'Tiêu biểu, mang tính đại diện', N'N2', NULL, N'special', 345, GETDATE()),
  (N'固有', N'こゆう', N'CỐ HỮU', N'Cái vốn có, truyền thống', N'N2', NULL, N'special', 346, GETDATE()),
  (N'特殊', N'とくしゅ', N'ĐẶC THÙ', N'Đặc thù, đặc trưng', N'N2', NULL, N'special', 347, GETDATE()),
  (N'普遍', N'ふへん', N'PHỔ BIẾN', N'Phổ biến', N'N2', NULL, N'special', 348, GETDATE()),
  (N'奇妙', N'きみょう', N'KỲ DIỆU', N'Kì diệu, lạ lùng', N'N2', NULL, N'special', 349, GETDATE()),
  (N'妙', N'みょう', N'DIỆU', N'Lạ, kì, tò mò', N'N2', NULL, N'special', 350, GETDATE()),
  (N'不審', N'ふしん', N'BẤT THẨM', N'Nghi ngờ, đáng nghi', N'N2', NULL, N'special', 351, GETDATE()),
  (N'異常', N'いじょう', N'DỊ THƯỜNG', N'Bất thường', N'N2', NULL, N'special', 352, GETDATE()),
  (N'正常', N'せいじょう', N'CHÍNH THƯỜNG', N'Thông thường', N'N2', NULL, N'special', 353, GETDATE()),
  (N'高度', N'こうど', N'CAO ĐỘ', N'Độ chính xác cao', N'N2', NULL, N'special', 354, GETDATE()),
  (N'新た', N'あらた', N'TÂN', N'Sự tươi; sự mới', N'N2', NULL, N'special', 355, GETDATE()),
  (N'合理的', N'ごうりてき', N'HỢP LÝ ĐÍCH', N'Tính hợp lý', N'N2', NULL, N'special', 356, GETDATE()),
  (N'不合理', N'ふごうり', N'BẤT HỢP LÝ', N'Không hợp lý', N'N2', NULL, N'special', 357, GETDATE()),
  (N'非合理的', N'ひごうりてき', N'PHI HỢP LÝ ĐÍCH', N'Phi lý', N'N2', NULL, N'special', 358, GETDATE()),
  (N'器用', N'きよう', N'KHÍ DỤNG', N'Khéo léo', N'N2', NULL, N'special', 359, GETDATE()),
  (N'不器用', N'ふきよう', N'BẤT KHÍ DỤNG', N'Không khéo léo', N'N2', NULL, N'special', 360, GETDATE()),
  (N'手軽', N'てがる', N'THỦ KHINH', N'Nhẹ nhàng, đơn giản', N'N2', NULL, N'special', 361, GETDATE()),
  (N'手ごろ', N'てごろ', N'THỦ', N'Hợp lý, vừa tầm tay', N'N2', NULL, N'special', 362, GETDATE()),
  (N'贅沢', N'ぜいたく', N'CHUẾ TRẠCH', N'Xa hoa, lãng phí', N'N2', NULL, N'special', 363, GETDATE()),
  (N'豪華', N'ごうか', N'HÀO HOA', N'Sang trọng, cao cấp', N'N2', NULL, N'special', 364, GETDATE()),
  (N'高級', N'こうきゅう', N'CAO CẤP', N'Cao cấp', N'N2', NULL, N'special', 365, GETDATE()),
  (N'上等', N'じょうとう', N'THƯỢNG ĐẲNG', N'Thượng đẳng', N'N2', NULL, N'special', 366, GETDATE()),
  (N'上品', N'じょうひん', N'THƯỢNG PHẨM', N'Thượng phẩm', N'N2', NULL, N'special', 367, GETDATE()),
  (N'下品', N'げひん', N'HẠ PHẨM', N'Hạ Phẩm', N'N2', NULL, N'special', 368, GETDATE()),
  (N'品がある', N'ひんがある', N'PHẨM', N'Hàng hóa có phẩm chất cao', N'N2', NULL, N'special', 369, GETDATE()),
  (N'適度', N'てきど', N'THÍCH ĐỘ', N'Mức độ vừa phải, thích hợp', N'N2', NULL, N'special', 370, GETDATE()),
  (N'快適', N'かいてき', N'KHOÁI THÍCH', N'Dễ chịu, sảng khoái', N'N2', NULL, N'special', 371, GETDATE()),
  (N'気持ちいい', N'きもちいい', N'KHÍ TRÌ', N'Dễ chịu, hài lòng', N'N2', NULL, N'special', 372, GETDATE()),
  (N'順調', N'じゅんちょう', N'THUẬN ĐIỀU', N'Thuận lợi (tiến triển)', N'N2', NULL, N'special', 373, GETDATE()),
  (N'好調', N'こうちょう', N'HẢO ĐIỀU', N'Thuận lợi (tiến triển)', N'N2', NULL, N'special', 374, GETDATE()),
  (N'活発', N'かっぱつ', N'HOẠT PHÁT', N'Hoạt bát', N'N2', NULL, N'special', 375, GETDATE()),
  (N'的確', N'的確', N'ĐÍCH XÁC', N'Sự đích xác', N'N2', NULL, N'special', 376, GETDATE()),
  (N'不的確', N'不的確', N'BẤT ĐÍCH XÁC', N'Không đích xác', N'N2', NULL, N'special', 377, GETDATE()),
  (N'確実', N'確実', N'XÁC THỰC', N'Sự xác thực', N'N2', NULL, N'special', 378, GETDATE()),
  (N'不確実', N'不確実', N'BẤT XÁC THỰC', N'Không xác thực', N'N2', NULL, N'special', 379, GETDATE()),
  (N'明らか', N'明らか', N'MINH', N'Rõ ràng', N'N2', NULL, N'special', 380, GETDATE()),
  (N'明白', N'めいはく', N'MINH BẠCH', N'Minh bạch, rõ ràng', N'N2', NULL, N'special', 381, GETDATE()),
  (N'明確', N'めいかく', N'MINH XÁC', N'Rõ ràng', N'N2', NULL, N'special', 382, GETDATE()),
  (N'曖昧', N'あいまい', N'ÁI MUỘI', N'Mơ hồ, không rõ ràng', N'N2', NULL, N'special', 383, GETDATE()),
  (N'具体的', N'ぐたいてき', N'CỤ THỂ ĐÍCH', N'Cụ thể', N'N2', NULL, N'special', 384, GETDATE()),
  (N'抽象的', N'ちゅうしょうてき', N'TRỪU TƯỢNG ĐÍCH', N'Tính Trừu Tượng', N'N2', NULL, N'special', 385, GETDATE()),
  (N'平等', N'びょうどう', N'BÌNH ĐẲNG', N'Bình đẳng', N'N2', NULL, N'special', 386, GETDATE()),
  (N'不平等', N'ふびょうどう', N'BẤT BÌNH ĐẲNG', N'Không bình đẳng', N'N2', NULL, N'special', 387, GETDATE()),
  (N'公平', N'こうへい', N'CÔNG BÌNH', N'Công bằng', N'N2', NULL, N'special', 388, GETDATE()),
  (N'不公平', N'ふこうへい', N'BẤT CÔNG BÌNH', N'Không công bằng', N'N2', NULL, N'special', 389, GETDATE()),
  (N'振り', N'ふり', N'CHẤN', N'Giả vờ', N'N2', NULL, N'special', 390, GETDATE()),
  (N'標準語', N'ひょうじゅんご', N'TIÊU CHUẨN NGỮ', N'Tiếng tiêu chuẩn', N'N2', NULL, N'special', 391, GETDATE()),
  (N'共通語', N'きょうつうご', N'CỘNG THÔNG NGỮ', N'Ngôn ngữ chung', N'N2', NULL, N'special', 392, GETDATE()),
  (N'重要視', N'じゅうようし', N'TRỌNG YẾU THỊ', N'Xem trọng, coi trọng', N'N2', NULL, N'special', 393, GETDATE()),
  (N'軽視', N'けいし', N'KHINH THỊ', N'Coi thường, coi nhẹ', N'N2', NULL, N'special', 394, GETDATE()),
  (N'手直し', N'てなおし', N'THỦ TRỰC', N'Sửa', N'N2', NULL, N'special', 395, GETDATE()),
  (N'排水', N'はいすい', N'BÀI THỦY', N'Nước thải', N'N2', NULL, N'special', 396, GETDATE()),
  (N'凸凹', N'でこぼこ', N'ĐỘT AO', N'Lồi lõm, ổ gà', N'N2', NULL, N'special', 397, GETDATE()),
  (N'目撃', N'もくげき', N'MỤC KÍCH', N'Mục kích, người chứng kiến', N'N2', NULL, N'special', 398, GETDATE()),
  (N'指導', N'しどう', N'CHỈ ĐẠO', N'Chỉ đạo', N'N2', NULL, N'special', 399, GETDATE()),
  (N'領域', N'りょういき', N'LĨNH VỰC', N'Lĩnh vực', N'N2', NULL, N'special', 400, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'使い道', N'つかいみち', N'SỬ ĐẠO', N'Cách sử dụng', N'N2', NULL, N'special', 401, GETDATE()),
  (N'手当て', N'てあて', N'THỦ ĐƯƠNG', N'Điều trị. sự chuẩn bị. phụ cấp. trợ cấp', N'N2', NULL, N'special', 402, GETDATE()),
  (N'治療', N'ちりょう', N'TRỊ LIỆU', N'Trị liệu', N'N2', NULL, N'special', 403, GETDATE()),
  (N'仮面', N'かめん', N'GIẢ DIỆN', N'Mặt nạ, sự nguy trang', N'N2', NULL, N'special', 404, GETDATE()),
  (N'説 (原子説)', N'せつ（げんしせつ）', N'THUYẾT (NGUYÊN TỬ)', N'Thuyết (thuyết nguyên tử)', N'N2', NULL, N'special', 405, GETDATE()),
  (N'湯取り', N'ゆとり', N'THANG THỦ', N'Thừa, dư ra', N'N2', NULL, N'special', 406, GETDATE()),
  (N'保障', N'ほしょう', N'BẢO CHƯỚNG', N'Bảo hành, Sự bảo đảm', N'N2', NULL, N'special', 407, GETDATE()),
  (N'指名する', N'しめいする', N'CHỈ DANH', N'Sự nêu tên, sự chỉ định', N'N2', NULL, N'special', 408, GETDATE()),
  (N'濯ぐ', N'すすぐ/ゆすぐ', N'TRẠC', N'Súc, rửa, giũ', N'N2', NULL, N'special', 409, GETDATE()),
  (N'言及する', N'げんきゅうする', N'NGÔN CẬP', N'Sự nhắc đến, sự đề cập đến', N'N2', NULL, N'special', 410, GETDATE()),
  (N'肩', N'かた', N'KIÊN', N'Bờ vai', N'N2', NULL, N'special', 411, GETDATE()),
  (N'描写する', N'びょうしゃする', N'MIÊU TẢ', N'Vẽ, miêu tả', N'N2', NULL, N'special', 412, GETDATE()),
  (N'逸れる', N'それる', N'DẬT', N'Trượt, lỡ, hướng lệch đi', N'N2', NULL, N'special', 413, GETDATE()),
  (N'凝視する', N'ぎょうしする', N'NGƯNG THỊ', N'Nhìn chằm chằm, nhìn xăm xoi', N'N2', NULL, N'special', 414, GETDATE()),
  (N'直視する', N'ちょくしする', N'TRỰC THỊ', N'Nhìn thẳng, nhìn chằm chằm', N'N2', NULL, N'special', 415, GETDATE()),
  (N'訪問する', N'ほうもんする', N'PHỎNG VẤN', N'Đến, thăm', N'N2', NULL, N'special', 416, GETDATE()),
  (N'来る', N'きたる/くる', N'LAI', N'Đến', N'N2', NULL, N'special', 417, GETDATE()),
  (N'啜る', N'すする', N'XUYẾT', N'Hớp, húp', N'N2', NULL, N'special', 418, GETDATE()),
  (N'追及する', N'ついきゅうする', N'TRUY CẬP', N'Sự điều tra', N'N2', NULL, N'special', 419, GETDATE()),
  (N'重用する', N'ちょうようする', N'TRỌNG DỤNG', N'Trọng dụng', N'N2', NULL, N'special', 420, GETDATE()),
  (N'登用する', N'とうようする', N'ĐĂNG DỤNG', N'Phân công, bổ nhiệm', N'N2', NULL, N'special', 421, GETDATE()),
  (N'任用する', N'にんようする', N'NHIỆM DỤNG', N'Bổ nhiệm, chỉ định', N'N2', NULL, N'special', 422, GETDATE()),
  (N'使用する', N'しようする', N'SỬ DỤNG', N'Sử dụng', N'N2', NULL, N'special', 423, GETDATE()),
  (N'収まる', N'おさまる', N'THU', N'Bình tĩnh; bình thường; lặng (gió)', N'N2', NULL, N'special', 424, GETDATE()),
  (N'納まる', N'おさまる', N'NẠP', N'Ngừng, kiềm chế', N'N2', NULL, N'special', 425, GETDATE()),
  (N'治まる', N'おさまる', N'TRIỊ', N'Ngừng; yên', N'N2', NULL, N'special', 426, GETDATE()),
  (N'収める', N'おさめる', N'THU', N'Tiếp thu; thu vào; nhận', N'N2', NULL, N'special', 427, GETDATE()),
  (N'納める', N'おさめる', N'NẠP', N'Đóng, nộp (thuế...)', N'N2', NULL, N'special', 428, GETDATE()),
  (N'治める', N'おさめる', N'TRỊ', N'Cai quản, cai trị', N'N2', NULL, N'special', 429, GETDATE()),
  (N'納入する', N'のうにゅうする', N'NẠP NHẬP', N'Thu nạp, giao nộp', N'N2', NULL, N'special', 430, GETDATE()),
  (N'統治する', N'とうちする', N'THỐNG TRỊ', N'Thống trị', N'N2', NULL, N'special', 431, GETDATE()),
  (N'沿う', N'そう', N'DUYÊN', N'Chạy dài; dọc theo', N'N2', NULL, N'special', 432, GETDATE()),
  (N'添う', N'そう', N'THIÊM', N'Cùng với', N'N2', NULL, N'special', 433, GETDATE()),
  (N'略する', N'りゃくする', N'LƯỢC', N'Lược bớt, tóm tắt, viết tắt', N'N2', NULL, N'special', 434, GETDATE()),
  (N'侵害する', N'しんがいする', N'XÂM HẠI', N'Xâm hại, xâm chiếm', N'N2', NULL, N'special', 435, GETDATE()),
  (N'脅迫する', N'きょうはくする', N'HIẾP BÁCH', N'Bắt nạt, đe dọa', N'N2', NULL, N'special', 436, GETDATE()),
  (N'妨害する', N'ぼうがいする', N'PHƯƠNG HẠI', N'Ngăn chặn', N'N2', NULL, N'special', 437, GETDATE()),
  (N'否定する', N'ひてい', N'PHỦ ĐỊNH', N'Phủ nhận, bác bỏ', N'N2', NULL, N'special', 438, GETDATE()),
  (N'応える', N'こたえる', N'ỨNG', N'Đáp lại, đối ứng', N'N2', NULL, N'special', 439, GETDATE()),
  (N'頂く', N'いただく', N'ĐỈNH', N'Nhận; xin nhận
(Khiêm nhường ngữ của 食べる/飲む/もらう ）', N'N2', NULL, N'special', 440, GETDATE()),
  (N'到達する', N'とうたつする', N'ĐÁO ĐẠT', N'Đạt đến', N'N2', NULL, N'special', 442, GETDATE()),
  (N'遂げる', N'とげる', N'TOẠI', N'Đạt đến', N'N2', NULL, N'special', 443, GETDATE()),
  (N'勝る', N'まさる', N'THẮNG', N'Vượt trội hơn, áp đảo hơn', N'N2', NULL, N'special', 444, GETDATE()),
  (N'所属する', N'しょぞくする', N'SỞ THUỘC', N'Thuộc về', N'N2', NULL, N'special', 445, GETDATE()),
  (N'草臥れる', N'くたびれる', N'THẢO NGỌA', N'Mệt, chán', N'N2', NULL, N'special', 446, GETDATE()),
  (N'躊躇する', N'ちゅうちょうする', N'TRÙ TRỪ', N'E dè', N'N2', NULL, N'special', 447, GETDATE()),
  (N'うとうと', N'うとうと', NULL, N'ngủ gật', N'N3', NULL, N'special', 0, GETDATE()),
  (N'はらはら', N'はらはら', NULL, N'áy náy, run rẩy', N'N3', NULL, N'special', 1, GETDATE()),
  (N'ぺらぺら', N'ぺらぺら', NULL, N'lưu loát, trôi chảy', N'N3', NULL, N'special', 2, GETDATE()),
  (N'のろのろ', N'のろのろ', NULL, N'chậm chạp, lề mề', N'N3', NULL, N'special', 3, GETDATE()),
  (N'ぼろぼろ', N'ぼろぼろ', NULL, N'rách tơi tả, te tua', N'N3', NULL, N'special', 4, GETDATE()),
  (N'ますます', N'ますます', NULL, N'ngày càng, hơn nữa', N'N3', NULL, N'special', 5, GETDATE()),
  (N'するする', N'するする', NULL, N'một cách trôi chảy, nhanh chóng', N'N3', NULL, N'special', 6, GETDATE()),
  (N'とうとう', N'とうとう', NULL, N'cuối cùng, kết cục, sau cùng', N'N3', NULL, N'special', 7, GETDATE()),
  (N'そわそわ', N'そわそわ', NULL, N'không yên, hoang mang', N'N3', NULL, N'special', 8, GETDATE()),
  (N'まずまず', N'まずまず', NULL, N'kha khá, tàm tạm', N'N3', NULL, N'special', 9, GETDATE()),
  (N'すらすら', N'すらすら', NULL, N'trơn chu, trôi chảy', N'N3', NULL, N'special', 10, GETDATE()),
  (N'たびたび', N'たびたび', NULL, N'thường xuyên, lập lại nhiều lần', N'N3', NULL, N'special', 11, GETDATE()),
  (N'びしょびしょ', N'びしょびしょ', NULL, N'ướt sũng, sũng nước', N'N3', NULL, N'special', 12, GETDATE()),
  (N'ぺこぺこ', N'ぺこぺこ', NULL, N'đói', N'N3', NULL, N'special', 13, GETDATE()),
  (N'ちかちか', N'ちかちか', NULL, N'le lói', N'N3', NULL, N'special', 14, GETDATE()),
  (N'どきどき
どきりと', N'どきどき
どきりと', NULL, N'Hồi hộp, thình thịch', N'N3', NULL, N'special', 15, GETDATE()),
  (N'ごろごろ', N'ごろごろ', NULL, N'ăn không ngồi rồi, lười nhác', N'N3', NULL, N'special', 16, GETDATE()),
  (N'きらきら', N'きらきら', NULL, N'sự lấp lánh', N'N3', NULL, N'special', 17, GETDATE()),
  (N'めちゃめちゃ', N'めちゃめちゃ', NULL, N'quá mức/quá đáng, liều lĩnh/ thiếu thận trọng', N'N3', NULL, N'special', 18, GETDATE()),
  (N'ぴかぴか', N'ぴかぴか', NULL, N'lấp lánh, sáng loáng', N'N3', NULL, N'special', 19, GETDATE()),
  (N'ぽちゃぽちゃ', N'ぽちゃぽちゃ', NULL, N'nước bắn tung tóe, bì bỡm', N'N3', NULL, N'special', 20, GETDATE()),
  (N'くらくら', N'くらくら', NULL, N'hoa mắt, choáng váng, chóng mặt', N'N3', NULL, N'special', 21, GETDATE()),
  (N'ぞろぞろ', N'ぞろぞろ', NULL, N'kéo dài lê thê, ùn ùn', N'N3', NULL, N'special', 22, GETDATE()),
  (N'たらたら', N'たらたら', NULL, N'tong tong, tí tách, long tong', N'N3', NULL, N'special', 23, GETDATE()),
  (N'ひらひら', N'ひらひら', NULL, N'bay bổng, bay phấp phới', N'N3', NULL, N'special', 24, GETDATE()),
  (N'すぎすぎ', N'すぎすぎ', NULL, N'quá', N'N3', NULL, N'special', 25, GETDATE()),
  (N'ずけずけ', N'ずけずけ', NULL, N'thẳng thừng, huỳnh toẹt', N'N3', NULL, N'special', 26, GETDATE()),
  (N'おいおい', N'おいおい', NULL, N'này này', N'N3', NULL, N'special', 27, GETDATE()),
  (N'ずるずる', N'ずるずる', NULL, N'kéo dài mãi, dùng dà dùng dằng không kết thúc được', N'N3', NULL, N'special', 28, GETDATE()),
  (N'はきはき', N'はきはき', NULL, N'minh bạch, rõ ràng, sáng suốt, minh mẫn', N'N3', NULL, N'special', 29, GETDATE()),
  (N'ぐいぐい', N'ぐいぐい', NULL, N'ừng ực', N'N3', NULL, N'special', 30, GETDATE()),
  (N'たまたま', N'たまたま', NULL, N'thỉnh thoảng, đôi khi, hiếm khi', N'N3', NULL, N'special', 31, GETDATE()),
  (N'かんかん', N'かんかん', NULL, N'Ầm ầm', N'N3', NULL, N'special', 32, GETDATE()),
  (N'にこにこ
にっこり', N'にこにこ
にっこり', NULL, N'Cười sung sướng', N'N3', NULL, N'special', 33, GETDATE()),
  (N'にやにや
にやりと', N'にやにや
にやりと', NULL, N'Meo meo', N'N3', NULL, N'special', 34, GETDATE()),
  (N'びしょびしょ
びっしょり', N'びしょびしょ
びっしょり', NULL, N'Ẩm ướt', N'N3', NULL, N'special', 35, GETDATE()),
  (N'のろのろ', N'のろのろ', NULL, N'Chậm rãi', N'N3', NULL, N'special', 36, GETDATE()),
  (N'ふらふら', N'ふらふら', NULL, N'Quay cuồng', N'N3', NULL, N'special', 37, GETDATE()),
  (N'ぶらぶら', N'ぶらぶら', NULL, N'Rung động', N'N3', NULL, N'special', 38, GETDATE()),
  (N'うろうろ', N'うろうろ', NULL, N'Đi lung tung, xung quanh', N'N3', NULL, N'special', 39, GETDATE()),
  (N'べつべつ', N'べつべつ', NULL, N'Riêng biệt', N'N3', NULL, N'special', 40, GETDATE()),
  (N'それぞれ', N'それぞれ', NULL, N'Mỗi', N'N3', NULL, N'special', 41, GETDATE()),
  (N'いらいら', N'いらいら', NULL, N'Khó chịu, nóng giận', N'N3', NULL, N'special', 42, GETDATE()),
  (N'つぎつぎ', N'つぎつぎ', NULL, N'Tiếp theo', N'N3', NULL, N'special', 43, GETDATE()),
  (N'どんどん', N'どんどん', NULL, N'Dần dần', N'N3', NULL, N'special', 44, GETDATE()),
  (N'ますます', N'ますます', NULL, N'Càng ngày càng', N'N3', NULL, N'special', 45, GETDATE()),
  (N'ぎりぎり', N'ぎりぎり', NULL, N'Gần, sát nút', N'N3', NULL, N'special', 46, GETDATE()),
  (N'とうとう', N'とうとう', NULL, N'Cuối cùng', N'N3', NULL, N'special', 47, GETDATE()),
  (N'わざわざ', N'わざわざ', NULL, N'làm phiền, gây phiền', N'N3', NULL, N'special', 48, GETDATE()),
  (N'いよいよ', N'いよいよ', NULL, N'cuối cùng, đã đến lúc', N'N3', NULL, N'special', 49, GETDATE()),
  (N'せいぜい', N'せいぜい', NULL, N'tối đa, nhiều nhất có thể', N'N3', NULL, N'special', 50, GETDATE()),
  (N'ぞくぞく', N'ぞくぞく', NULL, N'liên tục, cái này sau cái kia', N'N3', NULL, N'special', 51, GETDATE()),
  (N'いきいき', N'いきいき', NULL, N'sống động, sinh động', N'N3', NULL, N'special', 52, GETDATE()),
  (N'ひとりひとり', N'ひとりひとり', NULL, N'từng người, mỗi người', N'N3', NULL, N'special', 53, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'いちいち', N'いちいち', NULL, N'từng thứ, từng việc', N'N3', NULL, N'special', 54, GETDATE()),
  (N'ところどころ', N'ところどころ', NULL, N'đây đó', N'N3', NULL, N'special', 55, GETDATE()),
  (N'たまたま', N'たまたま', NULL, N'tình cờ, thỉnh thoảng', N'N3', NULL, N'special', 56, GETDATE()),
  (N'もともと', N'もともと', NULL, N'vốn dĩ', N'N3', NULL, N'special', 57, GETDATE()),
  (N'ぶるぶる', N'ぶるぶる', NULL, N'Lập cập', N'N3', NULL, N'special', 58, GETDATE()),
  (N'たちまち', N'たちまち', NULL, N'Ngay lập tức', N'N3', NULL, N'special', 59, GETDATE()),
  (N'しばしば', N'しばしば', NULL, N'rất thường xuyên (しばしば > たびたび > しょっちゅう＝常に)', N'N3', NULL, N'special', 60, GETDATE()),
  (N'たびたび', N'たびたび', NULL, N'hay, nhiều lần', N'N3', NULL, N'special', 61, GETDATE()),
  (N'しょっちゅう', N'しょっちゅう', NULL, N'luôn luôn, thường xuyên', N'N3', NULL, N'special', 62, GETDATE()),
  (N'たまに', N'たまに', NULL, N'thỉnh thoảng', N'N3', NULL, N'special', 63, GETDATE()),
  (N'めったに…ない', N'めったに…ない', NULL, N'hầu như không', N'N3', NULL, N'special', 64, GETDATE()),
  (N'にこにこ・にっこり', N'にこにこ・にっこり', NULL, N'cười khúc khích, cười sung sướng', N'N3', NULL, N'special', 65, GETDATE()),
  (N'にやにや・にやりと', N'にやにや・にやりと', NULL, N'cười tủm', N'N3', NULL, N'special', 66, GETDATE()),
  (N'どきどき・どきりと', N'どきどき・どきりと', NULL, N'hồi hộp', N'N3', NULL, N'special', 67, GETDATE()),
  (N'はらはら', N'はらはら', NULL, N'run rẩy(người), rung rung(vật)', N'N3', NULL, N'special', 68, GETDATE()),
  (N'かんかん', N'かんかん', NULL, N'rực rỡ(ánh sáng), bực mình', N'N3', NULL, N'special', 69, GETDATE()),
  (N'びしょびしょ・びっしょり', N'びしょびしょ・びっしょり', NULL, N'ướt sũng', N'N3', NULL, N'special', 70, GETDATE()),
  (N'うろうろ', N'うろうろ', NULL, N'đi lung tung, đi xung quanh', N'N3', NULL, N'special', 71, GETDATE()),
  (N'のろのろ', N'のろのろ', NULL, N'chậm rãi, chậm như sên', N'N3', NULL, N'special', 72, GETDATE()),
  (N'ふらふら', N'ふらふら', NULL, N'chóng mặt, hay thay đổi', N'N3', NULL, N'special', 73, GETDATE()),
  (N'ぶらぶら', N'ぶらぶら', NULL, N'quanh quẩn, đung đưa (đồ vật)', N'N3', NULL, N'special', 74, GETDATE()),
  (N'大変（に）', N'たいへん', NULL, N'Cực', N'N3', NULL, N'special', 1, GETDATE()),
  (N'ほとんど', N'ほとんど', NULL, N'Gần như hoàn toàn', N'N3', NULL, N'special', 2, GETDATE()),
  (N'大体', N'だいたい', NULL, N'Đại khái', N'N3', NULL, N'special', 3, GETDATE()),
  (N'かなり', N'かなり', NULL, N'Khá', N'N3', NULL, N'special', 4, GETDATE()),
  (N'ずいぶん', N'ずいぶん', NULL, N'Khá', N'N3', NULL, N'special', 5, GETDATE()),
  (N'結構', N'けっこう', NULL, N'Khá, tốt, đủ', N'N3', NULL, N'special', 6, GETDATE()),
  (N'だいぶ
だいぶん', N'大分', NULL, N'Hầu như', N'N3', NULL, N'special', 7, GETDATE()),
  (N'もっと', N'もっと', NULL, N'Hơn nữa', N'N3', NULL, N'special', 8, GETDATE()),
  (N'すっかり', N'すっかり', NULL, N'Toàn bộ', N'N3', NULL, N'special', 9, GETDATE()),
  (N'いっぱい', N'いっぱい', NULL, N'Đầy, nhiều', N'N3', NULL, N'special', 10, GETDATE()),
  (N'ぴったり', N'ぴったり', NULL, N'Vừa vặn, đúng', N'N3', NULL, N'special', 11, GETDATE()),
  (N'たいてい', N'たいてい', NULL, N'Bình thường', N'N3', NULL, N'special', 12, GETDATE()),
  (N'同時に', N'どうじに', NULL, N'Đồng thời', N'N3', NULL, N'special', 13, GETDATE()),
  (N'前もって', N'まえもって', NULL, N'Trước', N'N3', NULL, N'special', 14, GETDATE()),
  (N'すぐ（に）', N'すぐ（に）', NULL, N'Ngay lập tức', N'N3', NULL, N'special', 15, GETDATE()),
  (N'もうすぐ', N'もうすぐ', NULL, N'Sắp, chuẩn bị', N'N3', NULL, N'special', 16, GETDATE()),
  (N'突然', N'とつぜん', NULL, N'Đột nhiên', N'N3', NULL, N'special', 17, GETDATE()),
  (N'あっという間に', N'あっというまに', NULL, N'Loáng một cái', N'N3', NULL, N'special', 18, GETDATE()),
  (N'いつの間にか', N'いつのまにか', NULL, N'Lúc nào không biết', N'N3', NULL, N'special', 19, GETDATE()),
  (N'暫く', N'しばらく', NULL, N'Một chút', N'N3', NULL, N'special', 20, GETDATE()),
  (N'ずっと', N'ずっと', NULL, N'Suốt, nhiều', N'N3', NULL, N'special', 21, GETDATE()),
  (N'相変わらず', N'あいかわらず', NULL, N'Như mọi khi', N'N3', NULL, N'special', 22, GETDATE()),
  (N'やっと', N'やっと', NULL, N'Cuối cùng', N'N3', NULL, N'special', 23, GETDATE()),
  (N'もちろん', N'もちろん', NULL, N'Tất nhiên', N'N3', NULL, N'special', 24, GETDATE()),
  (N'やはり', N'やはり', NULL, N'Cuối cùng, như dự tính', N'N3', NULL, N'special', 25, GETDATE()),
  (N'きっと', N'きっと', NULL, N'Nhất định', N'N3', NULL, N'special', 26, GETDATE()),
  (N'ぜひ', N'ぜひ', NULL, N'Rất', N'N3', NULL, N'special', 27, GETDATE()),
  (N'なるべく', N'なるべく', NULL, N'Càng…càng
nếu có thể thì', N'N3', NULL, N'special', 28, GETDATE()),
  (N'案外', N'あんがい', NULL, N'Không ngờ đến', N'N3', NULL, N'special', 29, GETDATE()),
  (N'もしかすると
もしかしたら
もしかして', N'もしかすると
もしかしたら
もしかして', NULL, N'Có lẽ', N'N3', NULL, N'special', 30, GETDATE()),
  (N'まさか', N'まさか', NULL, N'Không thể ngờ', N'N3', NULL, N'special', 31, GETDATE()),
  (N'うっかり', N'うっかり', NULL, N'Ngơ ngác, không để ý', N'N3', NULL, N'special', 32, GETDATE()),
  (N'ついに', N'ついに', NULL, N'Buột, vô ý
Cuối cùng', N'N3', NULL, N'special', 33, GETDATE()),
  (N'思わず', N'おもわず', NULL, N'Không ngờ đến', N'N3', NULL, N'special', 34, GETDATE()),
  (N'ほっと', N'ほっと', NULL, N'Yên tâm', N'N3', NULL, N'special', 35, GETDATE()),
  (N'のんびり', N'のんびり', NULL, N'Từ từ tận hưởng', N'N3', NULL, N'special', 36, GETDATE()),
  (N'実は', N'じつは', NULL, N'Thực tế là', N'N3', NULL, N'special', 37, GETDATE()),
  (N'ぐっすり', N'ぐっすり', NULL, N'Ngủ say', N'N3', NULL, N'special', 38, GETDATE()),
  (N'きちんと', N'きちんと', NULL, N'Ngay ngắn, nghiêm chỉnh', N'N3', NULL, N'special', 39, GETDATE()),
  (N'しっかり', N'しっかり', NULL, N'Chắc chắn', N'N3', NULL, N'special', 40, GETDATE()),
  (N'はっきり', N'はっきり', NULL, N'Rõ ràng', N'N3', NULL, N'special', 41, GETDATE()),
  (N'じっと', N'じっと', NULL, N'Nhìn chăm chằm', N'N3', NULL, N'special', 42, GETDATE()),
  (N'そっと', N'そっと', NULL, N'Yên lặng nhẹ nhàng', N'N3', NULL, N'special', 43, GETDATE()),
  (N'互いに', N'たがいに', NULL, N'Lẫn nhau, song phương', N'N3', NULL, N'special', 44, GETDATE()),
  (N'ちょくせつ', N'ちょくせつ', NULL, N'Trực tiếp', N'N3', NULL, N'special', 45, GETDATE()),
  (N'本当に', N'ほんとうに', NULL, N'Thực sự thì', N'N3', NULL, N'special', 46, GETDATE()),
  (N'必ず', N'かならず', NULL, N'Chắc chắn', N'N3', NULL, N'special', 47, GETDATE()),
  (N'絶対に', N'ぜったいに', NULL, N'Tuyệt đối', N'N3', NULL, N'special', 48, GETDATE()),
  (N'特に', N'とくに', NULL, N'Đặc biệt là', N'N3', NULL, N'special', 49, GETDATE()),
  (N'ただ', N'ただ', NULL, N'Chỉ
Nhưng, ngoại trừ', N'N3', NULL, N'special', 50, GETDATE()),
  (N'少なくても', N'すくなくても', NULL, N'Ít nhất', N'N3', NULL, N'special', 51, GETDATE()),
  (N'決して', N'けっして', NULL, N'Không bao giờ', N'N3', NULL, N'special', 52, GETDATE()),
  (N'少しも', N'すこしも', NULL, N'Một chút', N'N3', NULL, N'special', 53, GETDATE()),
  (N'ちっとも', N'ちっとも', NULL, N'Không…tí gì', N'N3', NULL, N'special', 54, GETDATE()),
  (N'全く', N'まったく', NULL, N'hoàn toàn …không', N'N3', NULL, N'special', 55, GETDATE()),
  (N'とても', N'とても', NULL, N'Rất', N'N3', NULL, N'special', 56, GETDATE()),
  (N'どんなに', N'どんなに', NULL, N'Thế nào cũng', N'N3', NULL, N'special', 57, GETDATE()),
  (N'どうしても', N'どうしても', NULL, N'Kiểu gì cũng', N'N3', NULL, N'special', 58, GETDATE()),
  (N'まるで', N'まるで', NULL, N'Như là', N'N3', NULL, N'special', 59, GETDATE()),
  (N'一体', N'いったい', NULL, N'Cái quái gì', N'N3', NULL, N'special', 60, GETDATE()),
  (N'別に', N'べつに', NULL, N'Không có gì', N'N3', NULL, N'special', 61, GETDATE()),
  (N'たった', N'たった', NULL, N'Chỉ', N'N3', NULL, N'special', 62, GETDATE()),
  (N'ほんの', N'ほんの', NULL, N'Một chút', N'N3', NULL, N'special', 63, GETDATE()),
  (N'それで', N'それで', NULL, N'Thế thì', N'N3', NULL, N'special', 64, GETDATE()),
  (N'そこで', N'そこで', NULL, N'Tiếp theo', N'N3', NULL, N'special', 65, GETDATE()),
  (N'そのうえ', N'そのうえ', NULL, N'Hơn nữa', N'N3', NULL, N'special', 66, GETDATE()),
  (N'また', N'また', NULL, N'Nữa', N'N3', NULL, N'special', 67, GETDATE()),
  (N'または', N'または', NULL, N'Hoặc', N'N3', NULL, N'special', 68, GETDATE()),
  (N'それとも', N'それとも', NULL, N'Hoặc', N'N3', NULL, N'special', 69, GETDATE()),
  (N'つまり', N'つまり', NULL, N'Nói cách khác', N'N3', NULL, N'special', 70, GETDATE()),
  (N'最も', N'もっとも', NULL, N'Nhất', N'N3', NULL, N'special', 71, GETDATE()),
  (N'ほぼ', N'ほぼ', NULL, N'Gần như', N'N3', NULL, N'special', 72, GETDATE()),
  (N'相当', N'そうとう', NULL, N'Đáng kể', N'N3', NULL, N'special', 73, GETDATE()),
  (N'割に
割と
割り合い（に/と）', N'わりに
わりと
わりあい', NULL, N'Tương đối', N'N3', NULL, N'special', 74, GETDATE()),
  (N'多少', N'たしょう', NULL, N'Một chút', N'N3', NULL, N'special', 75, GETDATE()),
  (N'少々', N'しょうしょう', NULL, N'Một chút', N'N3', NULL, N'special', 76, GETDATE()),
  (N'全て', N'すべて', NULL, N'Toàn bộ', N'N3', NULL, N'special', 77, GETDATE()),
  (N'何もかも', N'なにもかも', NULL, N'Toàn bộ', N'N3', NULL, N'special', 78, GETDATE()),
  (N'たっぷり', N'たっぷり', NULL, N'Đủ, nhiều', N'N3', NULL, N'special', 79, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'できるだけ', N'できるだけ', NULL, N'Càng càng', N'N3', NULL, N'special', 80, GETDATE()),
  (N'次第に', N'しだいに', NULL, N'Dần dần', N'N3', NULL, N'special', 81, GETDATE()),
  (N'徐々に', N'じょじょに', NULL, N'Chút một, chút một', N'N3', NULL, N'special', 82, GETDATE()),
  (N'さらに', N'さらに', NULL, N'Hơn nữa', N'N3', NULL, N'special', 83, GETDATE()),
  (N'一層', N'いっそう（tầng)', NULL, N'Hơn, vẫn', N'N3', NULL, N'special', 84, GETDATE()),
  (N'一段と', N'いちだんと', NULL, N'Hơn rất nhiều', N'N3', NULL, N'special', 85, GETDATE()),
  (N'より', N'より', NULL, N'Hơn', N'N3', NULL, N'special', 86, GETDATE()),
  (N'結局', N'けっきょく', NULL, N'Kết cục', N'N3', NULL, N'special', 87, GETDATE()),
  (N'ようやく', N'ようやく', NULL, N'Cuối cùng', N'N3', NULL, N'special', 88, GETDATE()),
  (N'再び', N'ふたたび', NULL, N'Lần nữa', N'N3', NULL, N'special', 89, GETDATE()),
  (N'たちまち', N'たちまち', NULL, N'Ngày lập tức', N'N3', NULL, N'special', 90, GETDATE()),
  (N'今度', N'こんど', NULL, N'Lần này', N'N3', NULL, N'special', 91, GETDATE()),
  (N'今後', N'こんご', NULL, N'Từ giờ về sau', N'N3', NULL, N'special', 92, GETDATE()),
  (N'後（に）', N'のち（に）', NULL, N'Sau đó', N'N3', NULL, N'special', 93, GETDATE()),
  (N'まもなく', N'まもなく', NULL, N'Sắp', N'N3', NULL, N'special', 94, GETDATE()),
  (N'そのうち（に）', N'そのうち（に）', NULL, N'Lúc nào đó', N'N3', NULL, N'special', 95, GETDATE()),
  (N'やがて', N'やがて', NULL, N'Cuối cùng, sắp sớm', N'N3', NULL, N'special', 96, GETDATE()),
  (N'いずれ', N'いずれ', NULL, N'Sớm hay muộn', N'N3', NULL, N'special', 97, GETDATE()),
  (N'先ほど', N'さきほど', NULL, N'Cách đây không lâu', N'N3', NULL, N'special', 98, GETDATE()),
  (N'とっくに', N'とっくに', NULL, N'Rồi, lâu rồi', N'N3', NULL, N'special', 99, GETDATE()),
  (N'すでに', N'すでに', NULL, N'Rồi', N'N3', NULL, N'special', 100, GETDATE()),
  (N'事前に', N'じぜんに', NULL, N'Trước', N'N3', NULL, N'special', 101, GETDATE()),
  (N'当日', N'とうじつ', NULL, N'Ngày đó', N'N3', NULL, N'special', 102, GETDATE()),
  (N'当時', N'とうじ', NULL, N'Thời đó', N'N3', NULL, N'special', 103, GETDATE()),
  (N'一時', N'いちじ', NULL, N'Nhất thời, có lúc', N'N3', NULL, N'special', 104, GETDATE()),
  (N'至急', N'しきゅう', NULL, N'Khẩn cấp', N'N3', NULL, N'special', 105, GETDATE()),
  (N'直ちに', N'ただちに', NULL, N'Lập tức', N'N3', NULL, N'special', 106, GETDATE()),
  (N'早速', N'さっそく', NULL, N'Nhanh chóng', N'N3', NULL, N'special', 107, GETDATE()),
  (N'いきなり', N'いきなり', NULL, N'Bất ngờ, bất thình lình', N'N3', NULL, N'special', 108, GETDATE()),
  (N'常に', N'つねに', NULL, N'Thường xuyên', N'N3', NULL, N'special', 109, GETDATE()),
  (N'絶えず', N'たえず', NULL, N'Liên tục', N'N3', NULL, N'special', 110, GETDATE()),
  (N'しばしば', N'しばしば', NULL, N'Thường xuyên', N'N3', NULL, N'special', 111, GETDATE()),
  (N'たびたび', N'たびたび', NULL, N'Hay, thường xuyên', N'N3', NULL, N'special', 112, GETDATE()),
  (N'しょっちゅう', N'しょっちゅう', NULL, N'Hay', N'N3', NULL, N'special', 113, GETDATE()),
  (N'たまに', N'たまに', NULL, N'Thỉnh thoảng', N'N3', NULL, N'special', 114, GETDATE()),
  (N'めったに', N'めったに', NULL, N'Hiếm khi', N'N3', NULL, N'special', 115, GETDATE()),
  (N'したがって', N'したがって', NULL, N'Theo đó', N'N3', NULL, N'special', 116, GETDATE()),
  (N'だが', N'だが', NULL, N'Tuy nhiên', N'N3', NULL, N'special', 117, GETDATE()),
  (N'ところが', N'ところが', NULL, N'Nhưng', N'N3', NULL, N'special', 118, GETDATE()),
  (N'しかも', N'しかも', NULL, N'Hơn nữa', N'N3', NULL, N'special', 119, GETDATE()),
  (N'すると', N'すると', NULL, N'Như vậy', N'N3', NULL, N'special', 120, GETDATE()),
  (N'なぜなら', N'なぜなら', NULL, N'Bởi vì', N'N3', NULL, N'special', 121, GETDATE()),
  (N'だって', N'だって', NULL, N'Bởi vì', N'N3', NULL, N'special', 122, GETDATE()),
  (N'要するに', N'ようするに', NULL, N'Tóm lại', N'N3', NULL, N'special', 123, GETDATE()),
  (N'すなわち', N'すなわち', NULL, N'Tóm lại, đó là', N'N3', NULL, N'special', 124, GETDATE()),
  (N'あるいは', N'あるいは', NULL, N'Hoặc', N'N3', NULL, N'special', 125, GETDATE()),
  (N'さて', N'さて', NULL, N'Thế thì, tiếp', N'N3', NULL, N'special', 126, GETDATE()),
  (N'では', N'では', NULL, N'Thế thì', N'N3', NULL, N'special', 127, GETDATE()),
  (N'ところで', N'ところで', NULL, N'Nhân tiện', N'N3', NULL, N'special', 128, GETDATE()),
  (N'そう言えば', N'そういえば', NULL, N'Nói như vậy', N'N3', NULL, N'special', 129, GETDATE()),
  (N'さっぱり', N'さっぱり', NULL, N'hoàn toàn sảng khoái, nhẹ nhõm', N'N3', NULL, N'special', 130, GETDATE()),
  (N'すっきり', N'すっきり', NULL, N'sảng khoái lại', N'N3', NULL, N'special', 131, GETDATE()),
  (N'実に', N'じつに', NULL, N'thực tế, thực ra', N'N3', NULL, N'special', 132, GETDATE()),
  (N'思い切り', N'おもいきり', NULL, N'hết sức', N'N3', NULL, N'special', 133, GETDATE()),
  (N'何となく', N'なんとなく', NULL, N'hơi hơi, một chút', N'N3', NULL, N'special', 134, GETDATE()),
  (N'何だか', N'なんだか', NULL, N'một tí, một chút, hơi hơi', N'N3', NULL, N'special', 135, GETDATE()),
  (N'どうにか', N'どうにか', NULL, N'bằng cách nào đó, như thế nào đó', N'N3', NULL, N'special', 136, GETDATE()),
  (N'どうにも', N'どうにも', NULL, N'chẳng thể làm gì', N'N3', NULL, N'special', 137, GETDATE()),
  (N'何とか', N'なんとか', NULL, N'chút nào đó, gì đó', N'N3', NULL, N'special', 138, GETDATE()),
  (N'何とも', N'なんとも', NULL, N'không...một chút nào', N'N3', NULL, N'special', 139, GETDATE()),
  (N'わざと', N'わざと', NULL, N'cố ý', N'N3', NULL, N'special', 140, GETDATE()),
  (N'せっかく', N'せっかく', NULL, N'đã mất công', N'N3', NULL, N'special', 141, GETDATE()),
  (N'あいにく', N'あいにく', NULL, N'đáng tiếc', N'N3', NULL, N'special', 142, GETDATE()),
  (N'案の定', N'あんじょう', NULL, N'quả như đã nghĩ, như mong đợi', N'N3', NULL, N'special', 143, GETDATE()),
  (N'さすが', N'さすが', NULL, N'quả là, như dự đoán, thật đúng là', N'N3', NULL, N'special', 144, GETDATE()),
  (N'とにかく', N'とにかく', NULL, N'dù sao, cách này hay cách khác', N'N3', NULL, N'special', 145, GETDATE()),
  (N'ともかく', N'ともかく', NULL, N'dù sao, cách này hay cách khác', N'N3', NULL, N'special', 146, GETDATE()),
  (N'せめて', N'せめて', NULL, N'ít nhất, tối thiểu là', N'N3', NULL, N'special', 147, GETDATE()),
  (N'どうせ', N'どうせ', NULL, N'dù cho, đằng nào thì', N'N3', NULL, N'special', 148, GETDATE()),
  (N'ぎっしり', N'ぎっしり', NULL, N'lèn chặt, đầy chặt, kín lịch', N'N3', NULL, N'special', 149, GETDATE()),
  (N'ずらりと', N'ずらりと', NULL, N'trong 1 dãy', N'N3', NULL, N'special', 150, GETDATE()),
  (N'あっさり', N'あっさり', NULL, N'đơn giản, nhẹ nhàng', N'N3', NULL, N'special', 151, GETDATE()),
  (N'しんと
しいんと', N'しんと
しいんと', NULL, N'yên lặng, lặng lẽ', N'N3', NULL, N'special', 152, GETDATE()),
  (N'ちゃんと', N'ちゃんと', NULL, N'cẩn thận, kĩ càng', N'N3', NULL, N'special', 153, GETDATE()),
  (N'どっと', N'どっと', NULL, N'tất cả, cùng lúc', N'N3', NULL, N'special', 154, GETDATE()),
  (N'ばったり', N'ばったり', NULL, N'đột nhiên, ngã', N'N3', NULL, N'special', 155, GETDATE()),
  (N'さっさと', N'さっさと', NULL, N'nhanh chóng', N'N3', NULL, N'special', 156, GETDATE()),
  (N'さっと', N'さっと', NULL, N'nhanh', N'N3', NULL, N'special', 157, GETDATE()),
  (N'すっと', N'すっと', NULL, N'vươn thẳng', N'N3', NULL, N'special', 158, GETDATE()),
  (N'せっせと', N'せっせと', NULL, N'siên năng, cần cù', N'N3', NULL, N'special', 159, GETDATE()),
  (N'ざっと', N'ざっと', NULL, N'khoảng, nháp, qua', N'N3', NULL, N'special', 160, GETDATE()),
  (N'そっそり', N'そっそり', NULL, N'bí mật, lén lút', N'N3', NULL, N'special', 161, GETDATE()),
  (N'ばんやり', N'ばんやり', NULL, N'mờ ảo', N'N3', NULL, N'special', 162, GETDATE()),
  (N'ふと', N'ふと', NULL, N'đột nhiên, tình cờ', N'N3', NULL, N'special', 163, GETDATE()),
  (N'じかに', N'じかに', NULL, N'trực tiếp', N'N3', NULL, N'special', 164, GETDATE()),
  (N'一度に', N'いちどに', NULL, N'1 lần, cùng lúc', N'N3', NULL, N'special', 165, GETDATE()),
  (N'一斉に', N'いっせいに (tế)', NULL, N'cùng lúc', N'N3', NULL, N'special', 166, GETDATE()),
  (N'共に', N'ともに', NULL, N'cùng với', N'N3', NULL, N'special', 167, GETDATE()),
  (N'相互に', N'そうごに', NULL, N'lẫn nhau, cùng nhau', N'N3', NULL, N'special', 168, GETDATE()),
  (N'どうか', N'どうか', NULL, N'どうぞ, sai', N'N3', NULL, N'special', 169, GETDATE()),
  (N'できれば
できたち', N'できれば
できたち', NULL, N'Có thể', N'N3', NULL, N'special', 170, GETDATE()),
  (N'たいして', N'たいして', NULL, N'không thú vị lắm', N'N3', NULL, N'special', 171, GETDATE()),
  (N'恐らく', N'おそらく', NULL, N'có lẽ', N'N3', NULL, N'special', 172, GETDATE()),
  (N'むしろ', N'むしろ', NULL, N'hơn', N'N3', NULL, N'special', 173, GETDATE()),
  (N'果たして', N'はたして', NULL, N'quả nhiên', N'N3', NULL, N'special', 174, GETDATE()),
  (N'かえって', N'かえって', NULL, N'ngược lại, hơn', N'N3', NULL, N'special', 175, GETDATE()),
  (N'必ずしも', N'かならずしも', NULL, N'không hẳn, không cần thiết', N'N3', NULL, N'special', 176, GETDATE()),
  (N'単に', N'たんに', NULL, N'chỉ, đơn giản', N'N3', NULL, N'special', 177, GETDATE()),
  (N'いまだに', N'いまだに', NULL, N'vẫn chưa', N'N3', NULL, N'special', 178, GETDATE()),
  (N'ついでに', N'ついでに', NULL, N'nhân tiện', N'N3', NULL, N'special', 179, GETDATE());

INSERT INTO Vocabulary (Kanji, Kana, HanViet, Vietnamese, JlptLevel, PartOfSpeech, Tags, SortOrder, CreatedAt)
VALUES
  (N'とりあえず', N'とりあえず', NULL, N'đầu tiên', N'N3', NULL, N'special', 180, GETDATE()),
  (N'万一
万が一', N'まんいち
まんがいち', NULL, N'trường hợp xấu, khẩn cấp', N'N3', NULL, N'special', 181, GETDATE()),
  (N'偶然', N'ぐうぜん', NULL, N'ngẫu nhiên', N'N3', NULL, N'special', 182, GETDATE()),
  (N'実際（に）', N'じっさい（に）', NULL, N'thực tế', N'N3', NULL, N'special', 183, GETDATE()),
  (N'同様', N'どうよう', NULL, N'giống', N'N3', NULL, N'special', 184, GETDATE()),
  (N'本来', N'ほんらい', NULL, N'từ đầu, nguyên bản', N'N3', NULL, N'special', 185, GETDATE()),
  (N'あらゆる', N'あらゆる', NULL, N'tất cả', N'N3', NULL, N'special', 186, GETDATE()),
  (N'たいした', N'たいした', NULL, N'không có gì to tát, không có gì nghiêm trọng', N'N3', NULL, N'special', 187, GETDATE()),
  (N'いわゆる', N'いわゆる', NULL, N'gọi là, thường gọi là', N'N3', NULL, N'special', 188, GETDATE());

PRINT 'Seeded 709 Special (N2 BS + Từ Láy + Lượng Từ) records.';
GO
